START TRANSACTION
;
replace special_event set description = 'BLS Academy 39 workshop (proctors only)';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 39 workshop (proctors only)'), nominal_day = '2020-07-21', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 39 workshop (proctors only)'), nominal_day = '2020-07-28', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 39 workshop (proctors only)'), nominal_day = '2020-08-04', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 39 workshop (proctors only)'), nominal_day = '2020-07-21', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 39 workshop (proctors only)'), nominal_day = '2020-07-28', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 39 workshop (proctors only)'), nominal_day = '2020-08-04', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 39 workshop (proctors only)'), nominal_day = '2020-08-11', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 39 workshop (proctors only)'), nominal_day = '2020-08-18', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 39 workshop (proctors only)'), nominal_day = '2020-08-25', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 39 workshop (proctors only)'), nominal_day = '2020-09-01', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 39 workshop (proctors only)'), nominal_day = '2020-09-08', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 39 workshop (proctors only)'), nominal_day = '2020-09-15', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 39 workshop (proctors only)'), nominal_day = '2020-09-22', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 39 workshop (proctors only)'), nominal_day = '2020-09-29', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 39 workshop (proctors only)'), nominal_day = '2020-10-06', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 39 workshop (proctors only)'), nominal_day = '2020-10-13', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 39 workshop (proctors only)'), nominal_day = '2020-10-20', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 39 workshop (proctors only)'), nominal_day = '2020-10-27', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 39 workshop (proctors only)'), nominal_day = '2020-11-03', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 39 workshop (proctors only)'), nominal_day = '2020-11-17', name = '1800-2200';
;
replace special_event set description = 'BLS Academy 40 workshop (proctors only)';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 40 workshop (proctors only)'), nominal_day = '2020-07-23', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 40 workshop (proctors only)'), nominal_day = '2020-07-30', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 40 workshop (proctors only)'), nominal_day = '2020-08-06', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 40 workshop (proctors only)'), nominal_day = '2020-08-13', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 40 workshop (proctors only)'), nominal_day = '2020-08-20', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 40 workshop (proctors only)'), nominal_day = '2020-08-27', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 40 workshop (proctors only)'), nominal_day = '2020-09-03', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 40 workshop (proctors only)'), nominal_day = '2020-09-10', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 40 workshop (proctors only)'), nominal_day = '2020-09-17', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 40 workshop (proctors only)'), nominal_day = '2020-09-24', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 40 workshop (proctors only)'), nominal_day = '2020-10-01', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 40 workshop (proctors only)'), nominal_day = '2020-10-08', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 40 workshop (proctors only)'), nominal_day = '2020-10-15', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 40 workshop (proctors only)'), nominal_day = '2020-10-22', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 40 workshop (proctors only)'), nominal_day = '2020-10-29', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 40 workshop (proctors only)'), nominal_day = '2020-11-05', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 40 workshop (proctors only)'), nominal_day = '2020-11-19', name = '1800-2200';
;
COMMIT