START TRANSACTION
;
replace special_event set description = 'BLS Academy 51 workshop (proctors only)';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 51 workshop (proctors only)'), nominal_day = '2022-01-18', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 51 workshop (proctors only)'), nominal_day = '2022-01-25', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 51 workshop (proctors only)'), nominal_day = '2022-02-01', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 51 workshop (proctors only)'), nominal_day = '2022-02-08', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 51 workshop (proctors only)'), nominal_day = '2022-02-15', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 51 workshop (proctors only)'), nominal_day = '2022-02-22', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 51 workshop (proctors only)'), nominal_day = '2022-03-01', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 51 workshop (proctors only)'), nominal_day = '2022-03-08', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 51 workshop (proctors only)'), nominal_day = '2022-03-15', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 51 workshop (proctors only)'), nominal_day = '2022-03-22', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 51 workshop (proctors only)'), nominal_day = '2022-03-29', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 51 workshop (proctors only)'), nominal_day = '2022-04-05', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 51 workshop (proctors only)'), nominal_day = '2022-04-12', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 51 workshop (proctors only)'), nominal_day = '2022-04-26', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 51 workshop (proctors only)'), nominal_day = '2022-05-03', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 51 workshop (proctors only)'), nominal_day = '2022-05-10', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 51 workshop (proctors only)'), nominal_day = '2022-05-17', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 51 workshop (proctors only)'), nominal_day = '2022-05-31', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 51 workshop (proctors only)'), nominal_day = '2022-06-07', name = '1800-2200';
;
replace special_event set description = 'BLS Academy 52 workshop (proctors only)';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 52 workshop (proctors only)'), nominal_day = '2022-01-20', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 52 workshop (proctors only)'), nominal_day = '2022-01-27', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 52 workshop (proctors only)'), nominal_day = '2022-02-03', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 52 workshop (proctors only)'), nominal_day = '2022-02-10', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 52 workshop (proctors only)'), nominal_day = '2022-02-17', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 52 workshop (proctors only)'), nominal_day = '2022-02-24', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 52 workshop (proctors only)'), nominal_day = '2022-03-03', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 52 workshop (proctors only)'), nominal_day = '2022-03-10', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 52 workshop (proctors only)'), nominal_day = '2022-03-17', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 52 workshop (proctors only)'), nominal_day = '2022-03-24', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 52 workshop (proctors only)'), nominal_day = '2022-03-31', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 52 workshop (proctors only)'), nominal_day = '2022-04-07', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 52 workshop (proctors only)'), nominal_day = '2022-04-14', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 52 workshop (proctors only)'), nominal_day = '2022-04-28', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 52 workshop (proctors only)'), nominal_day = '2022-05-05', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 52 workshop (proctors only)'), nominal_day = '2022-05-12', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 52 workshop (proctors only)'), nominal_day = '2022-05-19', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 52 workshop (proctors only)'), nominal_day = '2022-06-02', name = '1800-2200';
replace special_event_shift set special_event_id = (select id from special_event where description = 'BLS Academy 52 workshop (proctors only)'), nominal_day = '2022-06-09', name = '1800-2200';
;
COMMIT