<?
//
// $Id$
//
require_once("f_oscarhomepageurl.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
?>
<html>

<head>
<title>OSCAR - VBDEMS ALS Availability Submission Form</title>
</head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
        <table><tr><td>
           <h6 align="center">
              KVEO-IT-PROJECT<br>
              <a href="<? echo OscarHomePageUrl(); ?>">OSCAR SYSTEM</a><br>
              <a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></h6>
           <h1 align="center">Online Availability Submission Form</h1>
           <h2 align="center">for ALS Providers</h2>
        </td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>
           <? PutLibPhotoRandomPlaced("sasquatch",1); ?>
        </td></tr></table>
        <hr>
        <p>For centrally-scheduled members only.&nbsp; Starred<sup><b>*</b></sup> fields are required.</p>
        <form method="POST" action="add-avail-sheet.phtml">
          <table border="0" cellpadding="0" cellspacing="0" width="912">
            <tr>
              <td>First name:<sup><b>*</b></sup></td>
              <td><input type="text" name=first_name size="32" maxlength=32></td>
            </tr>
            <tr>
              <td>Last name:<sup><b>*</b></sup></td>
              <td><input type="text" name=last_name size="32" maxlength=32></td>
            </tr>
            <tr>
              <td>Email address:<sup><b>*</b></sup></td>
              <td><input type="text" name=email_addr size="64" maxlength=64></td>
            </tr>
            <tr>
              <td>Home squad:<sup><b>*</b></sup></td>
              <td><select size="1" name=squad>
                  <option value="">Select</option>
                  <option value="1">1 - Ocean Park</option>
                  <option value="2">2 - Davis Corner</option>
                  <option value="4">4 - Chesapeake Beach</option>
                  <option value="5">5 - Courthouse</option>
                  <option value="6">6 - Creeds</option>
                  <option value="9">9 - Kempsville</option>
                  <option value="13">13 - Blackwater</option>
                  <option value="14">14 - Virginia Beach</option>
                  <option value="15">15 - Knotts Island</option>
                  <option value="16">16 - Plaza</option>
                  <option value="17">17 - Sandbridge</option>
                  <option value="ERS">ERS - VBFD</option>
                </select></td>
            </tr>
            <tr>
               <td>Applicable month:<sup><b>*</b></sup></td>
               <td><select size=1 name=applicable_month_num>
                  <option value="">Select</option>
                  <?
                  $next_month_num = date("n") + 1;
                  echo "<option value=" . $next_month_num . ">" . date("F",mktime(12,0,0,$next_month_num,1)) . "</option>\n";
                  echo "<option value=" . ($next_month_num + 1) . ">" . date("F",mktime(12,0,0,($next_month_num + 1),1)) . "</option>\n";
                  ?>
               </select></td>
            </tr>
          </table>
  </center>
        <p>Check all that apply as of today's date:</p>
        <ul>
          <li><input type="checkbox" name=be_on_team_30 value="TRUE">I
            am on the Squad Truck Team.</li>
          <li><input type="checkbox" name=be_on_team_5 value="TRUE">I
            am an EMS-5.</li>
        </ul>
        <div align="left">
          <table border="0" cellpadding="0" cellspacing="0" width="892">
            <tr>
              <td width="890" valign="bottom" colspan="3">Check all shifts for
                which you are available for at least one type of duty:
                <p>&nbsp;</td>
            </tr>
            <tr>
              <td width="136" valign="bottom">Leave nonapplicable days blank.
                <p>&nbsp;</td>
              <td width="125" valign="bottom">
                <p align="left">Day shifts</p>
                <ul>
                  <li><input type="checkbox" name="d1" value="AVAILABLE">1st</li>
                  <li><input type="checkbox" name="d2" value="AVAILABLE">2nd</li>
                  <li><input type="checkbox" name="d3" value="AVAILABLE">3rd</li>
                  <li><input type="checkbox" name="d4" value="AVAILABLE">4th</li>
                  <li><input type="checkbox" name="d5" value="AVAILABLE">5th</li>
                  <li><input type="checkbox" name="d6" value="AVAILABLE">6th</li>
                  <li><input type="checkbox" name="d7" value="AVAILABLE">7th</li>
                  <li><input type="checkbox" name="d8" value="AVAILABLE">8th</li>
                  <li><input type="checkbox" name="d9" value="AVAILABLE">9th</li>
                  <li><input type="checkbox" name="d10" value="AVAILABLE">10th</li>
                  <li><input type="checkbox" name="d11" value="AVAILABLE">11th</li>
                  <li><input type="checkbox" name="d12" value="AVAILABLE">12th</li>
                  <li><input type="checkbox" name="d13" value="AVAILABLE">13th</li>
                  <li><input type="checkbox" name="d14" value="AVAILABLE">14th</li>
                  <li><input type="checkbox" name="d15" value="AVAILABLE">15th</li>
                  <li><input type="checkbox" name="d16" value="AVAILABLE">16th</li>
                  <li><input type="checkbox" name="d17" value="AVAILABLE">17th</li>
                  <li><input type="checkbox" name="d18" value="AVAILABLE">18th</li>
                  <li><input type="checkbox" name="d19" value="AVAILABLE">19th</li>
                  <li><input type="checkbox" name="d20" value="AVAILABLE">20th</li>
                  <li><input type="checkbox" name="d21" value="AVAILABLE">21st</li>
                  <li><input type="checkbox" name="d22" value="AVAILABLE">22nd</li>
                  <li><input type="checkbox" name="d23" value="AVAILABLE">23rd</li>
                  <li><input type="checkbox" name="d24" value="AVAILABLE">24th</li>
                  <li><input type="checkbox" name="d25" value="AVAILABLE">25th</li>
                  <li><input type="checkbox" name="d26" value="AVAILABLE">26th</li>
                  <li><input type="checkbox" name="d27" value="AVAILABLE">27th</li>
                  <li><input type="checkbox" name="d28" value="AVAILABLE">28th</li>
                  <li><input type="checkbox" name="d29" value="AVAILABLE">29th</li>
                  <li><input type="checkbox" name="d30" value="AVAILABLE">30th</li>
                  <li><input type="checkbox" name="d31" value="AVAILABLE">31st</li>
                </ul>
              </td>
              <td width="625" valign="bottom">
                <p align="left">Night shifts</p>
                <ul>
                  <li><input type="checkbox" name="n1" value="AVAILABLE">1st</li>
                  <li><input type="checkbox" name="n2" value="AVAILABLE">2nd</li>
                  <li><input type="checkbox" name="n3" value="AVAILABLE">3rd</li>
                  <li><input type="checkbox" name="n4" value="AVAILABLE">4th</li>
                  <li><input type="checkbox" name="n5" value="AVAILABLE">5th</li>
                  <li><input type="checkbox" name="n6" value="AVAILABLE">6th</li>
                  <li><input type="checkbox" name="n7" value="AVAILABLE">7th</li>
                  <li><input type="checkbox" name="n8" value="AVAILABLE">8th</li>
                  <li><input type="checkbox" name="n9" value="AVAILABLE">9th</li>
                  <li><input type="checkbox" name="n10" value="AVAILABLE">10th</li>
                  <li><input type="checkbox" name="n11" value="AVAILABLE">11th</li>
                  <li><input type="checkbox" name="n12" value="AVAILABLE">12th</li>
                  <li><input type="checkbox" name="n13" value="AVAILABLE">13th</li>
                  <li><input type="checkbox" name="n14" value="AVAILABLE">14th</li>
                  <li><input type="checkbox" name="n15" value="AVAILABLE">15th</li>
                  <li><input type="checkbox" name="n16" value="AVAILABLE">16th</li>
                  <li><input type="checkbox" name="n17" value="AVAILABLE">17th</li>
                  <li><input type="checkbox" name="n18" value="AVAILABLE">18th</li>
                  <li><input type="checkbox" name="n19" value="AVAILABLE">19th</li>
                  <li><input type="checkbox" name="n20" value="AVAILABLE">20th</li>
                  <li><input type="checkbox" name="n21" value="AVAILABLE">21st</li>
                  <li><input type="checkbox" name="n22" value="AVAILABLE">22nd</li>
                  <li><input type="checkbox" name="n23" value="AVAILABLE">23rd</li>
                  <li><input type="checkbox" name="n24" value="AVAILABLE">24th</li>
                  <li><input type="checkbox" name="n25" value="AVAILABLE">25th</li>
                  <li><input type="checkbox" name="n26" value="AVAILABLE">26th</li>
                  <li><input type="checkbox" name="n27" value="AVAILABLE">27th</li>
                  <li><input type="checkbox" name="n28" value="AVAILABLE">28th</li>
                  <li><input type="checkbox" name="n29" value="AVAILABLE">29th</li>
                  <li><input type="checkbox" name="n30" value="AVAILABLE">30th</li>
                  <li><input type="checkbox" name="n31" value="AVAILABLE">31st</li>
                </ul>
              </td>
            </tr>
          </table>
        </div>
        <p align="left">How many extra shifts are you willing to be scheduled
          for?&nbsp; <input type="text" name=num_extras size="2" value="0"></p>
          <blockquote>
            <table border="1">
               <tr>
                  <td width="100%">
                     <p align="center"><u>Survey box</u><br>
                     <small>Please take a moment to fill out the survey questions,
                     if any.</small></p>
                     <ul>
                        <li>No survey questions at this time.</li>
                     </ul>
                  </td>
               </tr>
            </table>
          </blockquote>
          <p align=left>Special requests:<br>
          <textarea rows="8" name=note cols="60"></textarea></p>
        <ul>
          <li>
            <p align=left>Availability sheets are due on the 10th day of the
            proceeding month.</li>
          <li>
            <p align=left>Fraudulent submissions are traceable and are cause for disciplinary action.</li>
          <li>
            <p align=left>OSCAR knows you are submitting from
               <?
               echo GetHostByName($REMOTE_ADDR);
               ?>
            </li>
          <li>
            <p align=left>Double check your selections before submitting this
            form.</li>
          <?
          echo "<li><p align=left>If you have feedback about this form, please send it to the <a href=mailto:" . RoleEmailAddress("") . ">OSCAR System Administrator</a>.</li>";
          ?>
          <li>
            <p align=left>If you wish to print a copy of the completed form
            for your records, do so <b>before</b> you click Submit.</li>
        </ul>
  <center>
          <p><input type="submit" value="Submit" name="B1"><input type="reset" value="Reset" name="B2"></p>
        </form>
        <p><small><small><em><pre>$Id$</pre></em></small></small></center></td>
    </tr>
  </table>
</body>

</html>

