<?
//
// $Id: approve-and-trust.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $
//
// Emulate register_globals on
if (!ini_get('register_globals'))
  {
  $superglobals = array($_SERVER,$_ENV,$_FILES,$_COOKIE,$_POST,$_GET);
  if (isset($_SESSION))
    {
    array_unshift($superglobals, $_SESSION);
    }
  foreach ($superglobals as $superglobal)
    {
    extract($superglobal, EXTR_SKIP);
    }
  }
//
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_oscarmailheaders.phtml");
require_once("f_sendapprovalnotice.phtml");
//
$ini = AppSettings();
$db_link = DbLink($ini);
$dbkalipso_link = DbkalipsoLink($ini);
//
if ($ini[app][do_report_all_errors]) error_reporting(E_ALL);
?>
<html>
<head><title>Request Approval and Trust Registration</title></head>
<? BodyOpen(); ?>
<table align=center width=80%><tr><td>
<H6 ALIGN=CENTER>KVEO-IT-PROJECT<br><a href="javascript:close();">OSCAR SYSTEM</a><br><a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></H6>
<H1 ALIGN=CENTER>Request Approval and Trust Registration</H1>
<hr>
<?
if (
      ($email_addr != "")
   and
      ($digest != "")
   and
      ($coord_agency != "")
   )
//then
   {
      $email_addr = kix\k::Safe($email_addr,kix\k::PhpValueOf_safe_hint_type("EMAIL_ADDRESS"));
      $coord_agency = kix\k::Safe($coord_agency,kix\k::PhpValueOf_safe_hint_type("ALPHANUM"));
      //
      // Insert the trusted email address into the trusted_user table.
      //
      $db_link->query
         (
         "insert into trusted_user "
         .  "set email_address='$email_addr'"
         .  ", coord_agency='$coord_agency'"
         )
         or die("Trust assertion failed with error: " . mysqli_error($db_link));
      //
      if (SendApprovalNotice($ini,$db_link,$email_addr,$digest))
         {
         PutLibPhotoRandomPlaced($ini,$dbkalipso_link,"oscarsystem",1,"right");
         echo "<p>The OSCAR system has performed the following:</p>\n"
            . "<ul>\n"
            . "   <li><p>Sent instructions to <i>$email_addr</i> on how to retrieve the requested report;</p></li>\n"
            . "   <li><p>Registered <i>$email_addr</i> as a user who is trusted by coordinating agency \"$coord_agency\".</p></li>\n"
            . "</ul>\n";
         }
      else
         {
         //
         // Fill the page out with a warning and instructions.
         //
         ?>
         <h2><i>Error!</i></h2>
         <b>
         <blockquote>
            <? echo "<p>The OSCAR system encountered an internal error while processing your request.  Please let the <a href=mailto:" . RoleEmailAddress($db_link,"") . "?subj=\"OSCAR Bug Report\">OSCAR System Administrator</a> know this error occurred.</p>"; ?>
         </blockquote>            
         </b>
         <?
         }
   }
else
   {
   //
   // Fill the page out with a warning and instructions.
   //
   ?>
   <h2><i>Error!</i></h2>
   <b>
   <blockquote>
      <p>Invalid arguments.</p>
   </blockquote>            
   </b>
   <?
   }
?>
<br clear=both>
<hr>
<p><small><small><em><pre>$Id: approve-and-trust.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $</pre></em></small></small>
</td>
</tr>
</table>
</body>
</html>
