<?
//
// $Id: authorities.phtml 7092 2020-04-29 19:03:43Z kevinanlipscomb $
//
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
//
$ini = AppSettings();
$db_link = DbLink($ini);
$dbkalipso_link = DbkalipsoLink($ini);
?>
<html>

<head><title>OSCAR - Authorities</title></head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
           <h6 align="center">
              KVEO-IT-PROJECT - <a href="javascript:close();">OSCAR SYSTEM</a></h6>
           <h1 align="center">Authorities</h1>
        <hr>
        <? PutLibPhotoRandomPlaced($ini,$dbkalipso_link,"oscarsystem",1,"right"); ?>
        <p>Only OSCAR system authorities have the ability to read the special request notes that users can submit with 
           their availabilities.&nbsp;  These authorities are:<p>
        <ul>
           <li><p>For all submissions, the OSCAR System Administrator;</p>
           <li><p>For all submissions, the VBDEMS schedule coordinator, backup coordinator(s), Deputy Chief and Chief;</p>
           <li><p>For submissions to a particular squad, that squad's schedule coordinator, backup coordinator(s),
              assistant squad commander(s) and squad commander.</p>
        </ul>
        <p>Special request notes are not revealed to any other OSCAR system users.</p>
        <p>You (or someone familiar with the technology) can verify these claims by browsing the
           production source code at <<a href=http://cvs.sourceforge.net/cgi-bin/viewcvs.cgi/kveo-it-project/oscar/>http://cvs.sourceforge.net/cgi-bin/viewcvs.cgi/kveo-it-project/oscar/</a>>.</p>
        <p>If you have questions or concerns about the technical aspects of this process, feel free to contact the
           <a href=mailto:"<? echo RoleEmailAddress($db_link,""); ?>">OSCAR System Administrator</a>.</p>
        <hr>
        <p><small><small><em><pre>$Id: authorities.phtml 7092 2020-04-29 19:03:43Z kevinanlipscomb $</pre></em></small></small></center></td>
    </tr>
  </table>
</body>

</html>

