<?
//
// $Id$
//
require_once("f_password.phtml");
require_once("f_oscarhomepageurl.phtml");
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("f_showavailsheetrecdetail.phtml");
//
// Give arguments meaningful names.  The obtuse names and base 64 encoding are measly attempts to protect generated URLs to this script
// from being abused.
//
$last_name = base64_decode($a);
$first_name = base64_decode($b);
$month = base64_decode($c);
//
?>
<html>
<head><title>OSCAR - Record Detail</title></head>
<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
<tr>
<td>
   <table>
      <tr>
         <td>
           <? PutLibPhotoRandomPlaced("sasquatch",1); ?>
         </td>
         <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
         <td>
            <h6 align="center">
            KVEO-IT-PROJECT<br>
            <a href="<? echo OscarHomePageUrl(); ?>">OSCAR SYSTEM</a><br>
            <a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></h6>
            <H1 ALIGN="CENTER">Record Detail</H1>
         </td>
      </tr>
   </table>
<hr>
<?
//
// Connect to the database.
//
mysql_connect(localhost,kalipso,Password());
mysql_select_db(oscar);
//
$result = mysql_query
   (
   "select * from avail_sheet"
   .  " where last_name = '" . addslashes($last_name) . "'"
   .  "    and first_name = '" . addslashes($first_name) . "'"
   .  "    and month = '$month'"
   )
   or die("The query failed with error:  " . mysql_error());
$num_rows = mysql_num_rows($result);
echo "<h4>Found $num_rows ";
if ($num_rows == 1)
   {
   echo "record.";
   }
else
   {
   echo "records.";
   }
echo "</h4>\n";
if ($num_rows)
   {
   echo "<blockquote>\n";
   $record_index = 0;
   while ($row = mysql_fetch_array($result))
      {
      $record_index++;
      extract($row);
      ShowAvailSheetRecDetail
         (
         $timestamp,
         $first_name,
         $last_name,
         $email_addr,
         $squad,
         $month,
         $be_on_team_5,
         $be_on_team_30,
         $num_extras,
         $d1,$d2,$d3,$d4,$d5,$d6,$d7,$d8,$d9,$d10,$d11,$d12,$d13,$d14,$d15,$d16,$d17,$d18,$d19,$d20,$d21,$d22,$d23,$d24,$d25,$d26,$d27,$d28,$d29,$d30,$d31,
         $n1,$n2,$n3,$n4,$n5,$n6,$n7,$n8,$n9,$n10,$n11,$n12,$n13,$n14,$n15,$n16,$n17,$n18,$n19,$n20,$n21,$n22,$n23,$n24,$n25,$n26,$n27,$n28,$n29,$n30,$n31,
         $note,
         $expiration
         );
      if ($record_index < $num_rows)
         {
         echo "<br><hr><br>\n";
         }
      }
   echo "</blockquote>\n";
   }
?>
<hr>
<p><small><small><em><pre>$Id$</pre></em></small></small>
</td>
</tr>
</table>
</body>
</html>
