<?
//
// $Id: ers-tda-input-form.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $
//
// Assign incoming arguments to themselves *prior* to error_reporting() so we won't get 'undefined variable' errors later.
//
$email_addr = $email_addr;
$applicable_month_num = $applicable_month_num;
//
require_once("f_bodyopen.phtml");
require_once("" . "f_roleemailaddress.phtml");
//
$ini = AppSettings();
$dbkalipso_link = DbkalipsoLink($ini);
//
if ($ini[app][do_report_all_errors]) error_reporting(E_ALL);
?>
<html>

<head>
<title>OSCAR - ERS TDA Input Form</title>
</head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
        <table><tr><td>
           <h6 align="center">
              KVEO-IT-PROJECT<br>
              <a href="javascript:close();">OSCAR SYSTEM</a><br>
              <a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></h6>
           <h1 align="center">ERS TDA Input Form</h1>
           <h2 align="center">for VBFD Scheduling Officers</h2>
        </td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>
           <? PutLibPhotoRandomPlaced($ini,$dbkalipso_link,"oscarsystem",1); ?>
        </td></tr></table>
        <hr>
        <p>This form is intended for the use of VBFD Scheduling Officers.</p>
        <form method="POST" action="add-ers-tda-inputs.phtml">
              <?
              if ((!$email_addr) or (!$applicable_month_num))
                 {
                 //
                 // Prompt user for email_addr and aplicable_month_num.
                 //
                 ?>
                 <table>
                    <tr>
                       <td>Scheduling officer email address:</td>
                       <td><input type=text name=email_addr size="64" maxlength=64></td>
                    </tr>
                    <tr>
                       <td>Applicable month:</td>
                       <td><select size=1 name=applicable_month_num>
                          <option value="">Select</option>
                          <?
                          $next_month_num = date("n") + 1;
                          echo "<option value=" . $next_month_num . ">" . date("F",mktime(12,0,0,$next_month_num,1)) . "</option>\n";
                          echo "<option value=" . ($next_month_num + 1) . ">" . date("F",mktime(12,0,0,($next_month_num + 1),1)) . "</option>\n";
                          ?>
                       </select></td>
                    </tr>
                 </table>
                 <h3><br>Temporary Duty Assignments</h3>
                 <?
                 }
              else
                 {
                 //
                 // Reuse values passed in.
                 //
                 ?>
                 <table>
                    <tr>
                       <td>Scheduling officer email address:</td>
                       <?
                       echo "<td>"
                          . "<input type=hidden name=email_addr value=\"$email_addr\">"
                          . "<b>$email_addr</b>"
                          . "</td>\n";
                       ?>
                    </tr>
                    <tr>
                       <td>Applicable month:</td>
                       <?
                       echo "<td>"
                          . "<input type=hidden name=applicable_month_num value=\"$applicable_month_num\">"
                          . "<b>" . date("F",mktime(12,0,0,$applicable_month_num,1)) . "</b>"
                          . "</td>\n";
                       ?>
                    </tr>
                 </table>
                 <h3><br>Temporary Duty Assignments <i>(continued)</i></h3>
                 <?
                 }
                 ?>
           <blockquote>
           <table cellpadding=3>
              <tr>
                 <td colspan=2 align=center valign=middle>Paramedic-firefighter</td>
                 <td colspan=2 align=center valign=middle>Zone car shift</td>
              </tr>
              <tr>
                 <td align=center valign=middle>Last name</td>
                 <td align=center valign=middle>First name</td>
                 <td align=center valign=middle>Day of<br>month</td>
                 <td align=center valign=middle>Day<br>(0800-2000)/<br>Night<br>(2000-0800)</td>
              </tr>
              <?
              //
              // Set up a standard shift_num option list.
              //
              $shift_num_option_list = "<option></option>\n"
                 .  "<option>1</option>\n"
                 .  "<option>2</option>\n"
                 .  "<option>3</option>\n"
                 .  "<option>4</option>\n"
                 .  "<option>5</option>\n"
                 .  "<option>6</option>\n"
                 .  "<option>7</option>\n"
                 .  "<option>8</option>\n"
                 .  "<option>9</option>\n"
                 .  "<option>10</option>\n"
                 .  "<option>11</option>\n"
                 .  "<option>12</option>\n"
                 .  "<option>13</option>\n"
                 .  "<option>14</option>\n"
                 .  "<option>15</option>\n"
                 .  "<option>16</option>\n"
                 .  "<option>17</option>\n"
                 .  "<option>18</option>\n"
                 .  "<option>19</option>\n"
                 .  "<option>20</option>\n"
                 .  "<option>21</option>\n"
                 .  "<option>22</option>\n"
                 .  "<option>23</option>\n"
                 .  "<option>24</option>\n"
                 .  "<option>25</option>\n"
                 .  "<option>26</option>\n"
                 .  "<option>27</option>\n"
                 .  "<option>28</option>\n"
                 .  "<option>29</option>\n"
                 .  "<option>30</option>\n"
                 .  "<option>31</option>\n";
              //
              // Set up a standard shift_day_night option_list.
              //
              $shift_day_night_option_list = "<option></option>\n"
                 .  "<option value=day>day</option>\n"
                 .  "<option value=night>night</option>\n";
              //
              // Make a bunch of identical rows.
              //
              for ($i = 1; $i <= 8; $i++)
                 {
                 ?>
                 <tr><td colspan=4><hr></td></tr>
                 <tr>
                    <td rowspan=2 align=center valign=middle><input type=text name="last_name[<? echo $i; ?>]" size=15 maxlength=32>,</td>
                    <td rowspan=2 align=center valign=middle><input type=text name="first_name[<? echo $i; ?>]" size=15 maxlength=32></td>
                    <td align=center valign=middle>
                       <select name="shift_a_num[<? echo $i; ?>]">
                          <? echo $shift_num_option_list; ?>
                       </select>
                    </td>
                    <td align=center valign=middle>
                       <select name="shift_a_day_night[<? echo $i; ?>]">
                          <? echo $shift_day_night_option_list; ?>
                       </select>
                    </td>
                 </tr>
                 <tr>
                    <td align=center valign=middle>
                       <select name="shift_b_num[<? echo $i; ?>]">
                          <? echo $shift_num_option_list; ?>
                       </select>
                    </td>
                    <td align=center valign=middle>
                       <select name="shift_b_day_night[<? echo $i; ?>]">
                          <? echo $shift_day_night_option_list; ?>
                       </select>
                    </td>
                 </tr>
                 <?
                 }
              ?>
           </table>
           </blockquote>
           <small>
           <ul>
             <li>Any row without a last name, first name, and at least one zone car shift will not be processed.
             <li>You'll have a chance to submit more TDAs after you press Submit.
           </ul>
           </small>
           <p><input type="submit" value="Submit"><input type="reset" value="Reset"></p>
        </form>
        <hr>
        <small><small><em><pre>$Id: ers-tda-input-form.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $</pre></em></small></small>
       </td>
    </tr>
  </table>
</body>

</html>

