<?
//
// $Id: escalate.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $
//
// Emulate register_globals on
if (!ini_get('register_globals'))
  {
  $superglobals = array($_SERVER,$_ENV,$_FILES,$_COOKIE,$_POST,$_GET);
  if (isset($_SESSION))
    {
    array_unshift($superglobals, $_SESSION);
    }
  foreach ($superglobals as $superglobal)
    {
    extract($superglobal, EXTR_SKIP);
    }
  }
//
if (isset($email_addr)) $email_addr = kix\k::Safe($email_addr,kix\k::PhpValueOf_safe_hint_type("EMAIL_ADDRESS"));
if (isset($coord_agency)) $coord_agency = kix\k::Safe($coord_agency,kix\k::PhpValueOf_safe_hint_type("ALPHANUM"));
//
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_oscarmailheaders.phtml");
require_once("f_sendapprovalnotice.phtml");
//
$ini = AppSettings();
$db_link = DbLink($ini);
$dbkalipso_link = DbkalipsoLink($ini);
//
if ($ini[app][do_report_all_errors]) error_reporting(E_ALL);
//
$html = "<html>\n"
      . "   <head><title>Request Escalation</title></head>\n"
      . "   " . BodyOpen() . "\n"
      . "      <table align=center width=80%><tr><td>\n"
      . "         <H6 ALIGN=CENTER>KVEO-IT-PROJECT<br>\n"
      . "         <a href=\"javascript:close();\">OSCAR SYSTEM</a><br>\n"
      . "         <a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></H6>\n"
      . "         <H1 ALIGN=CENTER>Request Escalation</H1>\n"
      . "         <hr>\n";
//
echo $html;
//
// Create the notice.
//
$result = $db_link->query
   (
   "select 1 from trusted_user "
   .  " where email_address='$email_addr' "
   .  "    and coord_agency='$coord_agency' "
   )
   or die("Trust check failed with error:  " . mysqli_error($db_link));
//
if (mysqli_num_rows($result) or ($email_addr == RoleEmailAddress($db_link,"schedule-coordinator",$coord_agency)))
   {
   //
   // Then someone has registered the requestor as trusted in the time since they first received their claim ticket.
   // Just send an approval notice to the requestor directly and forget actual escalation.
   //
   $result = SendApprovalNotice($ini,$db_link,$email_addr,$digest);
   PutLibPhotoRandomPlaced($ini,$dbkalipso_link,"oscarsystem",1,"right");
   echo "<p>An OSCAR authority from $coord_agency has registered you as a trusted user.&nbsp; </p>";
   echo "<p><b>Check your email for a message titled, <u>Your OSCAR report</u>.</b></p>";
   echo "<p>If you have feedback about the technical aspects of this process, please contact the <a href=mailto:" . RoleEmailAddress($db_link,"") . ">OSCAR System Administrator</a>.</p>";
   }
else
   {
   //
   // Notify the next authority in the chain.
   //
   $screen_notice_recipient = RoleEmailAddress($db_link,"escalation-level-" . $level . "-recipient",$coord_agency);
   if ($screen_notice_recipient == "")
      {
      $result=0;
      }
   else
      {
      $screen_notice_subject = "-> Escalated OSCAR request ->";
      //
      // Give the authority a chance to approve (weakly or strongly) or disapprove of the request.
      //
      //                 0        1         2         3         4         5         6         7
      //                 123456789012345678901234567890123456789012345678901234567890123456789012
      $screen_notice =  "The OSCAR system has received a request for a(n) $coord_agency Availability Report\n";
      $screen_notice .= "from a user who identified him or herself as:\n\n";
      $screen_notice .= "   Name:           $name\n";
      $screen_notice .= "   Email address:  $email_addr\n\n";
      $screen_notice .= "The user got tired of waiting for your subordinate to approve the\n";
      $screen_notice .= "request, so the user escalated the request to you.\n\n";
      $screen_notice .= "Please take one of the following actions:\n\n\n";
      $screen_notice .= "1. To MARK THIS USER AS TRUSTED (ie, approve this\n";
      $screen_notice .= "   and subsequent OSCAR requests from this user),\n";
      $screen_notice .= "   click here:\n";
      $screen_notice .= $ini[server][root_url] . "/approve-and-trust.phtml?digest=$digest&email_addr=$email_addr&coord_agency=$coord_agency\n\n\n";
      $screen_notice .= "2. To approve JUST THIS ONE request without\n";
      $screen_notice .= "   marking the user as trusted, click here:\n";
      $screen_notice .= $ini[server][root_url] . "/approve.phtml?digest=$digest&email_addr=$email_addr\n\n\n";
      $screen_notice .= "3. To DISAPPROVE the request, DO NOTHING.\n\n\n";
      $screen_notice .= "The report is available for review at:\n";
      $screen_notice .= $ini[server][root_url] . "/get-report.phtml?digest=$digest\n\n\n";
      //
      // Add sig lines.
      //
      $screen_notice .= "-- OSCAR\n";
      $screen_notice .= "-- Home page: " . $ini[server][host_url] . "/" . $ini[app][superapp] . "\n";
      $screen_notice .= "-- Sysadmin: " . RoleEmailAddress($db_link,"") . "\n";
      //
      // Then send a claim ticket to the requestor directly.
      //
      $claim_ticket_recipient = $email_addr;
      $next_level = $level + 1;
      //
      //                0        1         2         3         4         5         6         7
      //                123456789012345678901234567890123456789012345678901234567890123456789012
      $claim_ticket =  "Your *escalated* request for a(n) $coord_agency Availability Report has been\n";
      $claim_ticket .= "submitted to $screen_notice_recipient for screening.  Check\n";
      $claim_ticket .= "your email periodically for approval.\n\n";
      //
      $next_authority = RoleEmailAddress($db_link,"escalation-level-$next_level-recipient",$coord_agency);
      if ($next_authority != "")
         {
         $claim_ticket .= "Save this message and discard the previous claim ticket.  This is the\n";
         $claim_ticket .= "NEW CLAIM TICKET for your report.\n\n";
         $claim_ticket .= "If excessive time goes by and you wish to escalate your request to a\n";
         $claim_ticket .= "higher authority, you can do so by clicking the link near the bottom of\n";
         $claim_ticket .= "this message.\n\n";
         $claim_ticket .= "   WARNING\n";
         $claim_ticket .= "   -------\n";
         $claim_ticket .= "   Do not escalate your request without due cause.  To do so is to\n";
         $claim_ticket .= "   'jump the chain of command', which is poor discipline and may be\n";
         $claim_ticket .= "   punishable.  The option to escalate is provided for cases where the\n";
         $claim_ticket .= "   primary schedule coordinator is unable to respond in a timely manner.\n";
         $claim_ticket .= "   Generally, it is better to wait for the regular approval notice.\n\n";
         $claim_ticket .= "The next authority in the chain is:\n\n";
         $claim_ticket .= "   $next_authority\n\n";
         $claim_ticket .= "To escalate your request to the above\n";
         $claim_ticket .= "authority, click here:\n\n";
         $claim_ticket .= $ini[server][root_url] . "/escalate.phtml?level=" . $next_level . "&digest=$digest&name=" . urlencode($name) . "&email_addr=$email_addr&coord_agency=$coord_agency\n\n";
         //
         $claim_ticket_subject = "OSCAR claim ticket";
         }
      else
         {
         $claim_ticket_subject = "OSCAR max escalation notice";
         }
      //
      // Add sig lines.
      //
      $claim_ticket .= "-- OSCAR\n";
      $claim_ticket .= "-- Home page: " . $ini[server][host_url] . "/" . $ini[app][superapp] . "\n";
      $claim_ticket .= "-- Sysadmin: " . RoleEmailAddress($db_link,"") . "\n";
      //
      // Send the mail.
      //
      kix\k::SmtpMailSend
        (
        RoleEmailAddress($db_link,""), //from
        $screen_notice_recipient, //to
        $screen_notice_subject, //subject
        $screen_notice, //message_string
        false, //be_html
        "", //cc
        "", //bcc
        RoleEmailAddress($db_link,"") //reply_to
        );
      kix\k::SmtpMailSend
        (
        RoleEmailAddress($db_link,""), //from
        $claim_ticket_recipient, //to
        $claim_ticket_subject, //subject
        $claim_ticket, //message_string
        false, //be_html
        "", //cc
        "", //bcc
        RoleEmailAddress($db_link,"") //reply_to
        );
      $result = 1;
      }
   if ($result)
      {
      PutLibPhotoRandomPlaced($ini,$dbkalipso_link,"oscarsystem",1,"right");
      echo "<p>The OSCAR system has successfully escalated your request.&nbsp;  Because the report you requested contains "
         . "personal information, a screening notice has been sent to the <a href=mailto:\""
         . RoleEmailAddress($db_link,"escalation-level-$level-recipient",$coord_agency)
         . "\">$coord_agency Escalation Level $level Authority</a>.&nbsp; The authority will forward the report to you "
         . "once screening is complete.</p>";
      echo "<p><b>Check your email periodically for the report.</b></p>";
      echo "<p>If you have feedback about the technical aspects of this process, please contact the <a href=mailto:" . RoleEmailAddress($db_link,"") . ">OSCAR System Administrator</a>.</p>";
      }
   else
      {
      //
      // Fill the page out with a warning and instructions.
      //
      ?>
      <h2><i>Error!</i></h2>
      <b>
      <blockquote>
         <p>The OSCAR system encountered an internal error while processing your request.  Please do the following:</p>
         <ul>
            <?
            echo "<li><p>Use another method (like email or telephone) to ask the authority for the information you need.</p>";
            echo "<li><p>Let the <a href=mailto:" . RoleEmailAddress($db_link,"") . "?subj=OSCAR-bug-report>OSCAR System Administrator</a> know this error occurred.</p>";
            ?>
         </ul>
      </blockquote>            
      </b>
      <?
      }
   }
?>
<hr>
<p><small><small><em><pre>$Id: escalate.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $</pre></em></small></small>
</td>
</tr>
</table>
</body>
</html>
