<?
//
// $Id: f_agencyselectionlist.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $
//
function AgencySelectionList($db_link)
   {
   $saved_error_level = error_reporting(E_ALL);
   //
   $result = $db_link->query("select * from agency where be_active='TRUE'")
      or die("AgencySelectionList query failed with error: " . mysqli_error($db_link));
   //
   echo "<select name=coord_agency>\n";
   if (mysqli_num_rows($result) > 1)
      {
      echo "<option value=\"\">Select</option>\n";
      }
   //
   while($row = mysqli_fetch_array($result))
      {
      $enumeral = $description = "";
      extract($row);
      echo "<option value=\"$enumeral\">$description</option>\n";
      }
   //
   echo "</select>\n";
   //
   error_reporting($saved_error_level);
   }
?>