<?
//
// $Id: f_availlist.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $
//
function AvailList
   (
   $v1,$v2,$v3,$v4,$v5,$v6,$v7,$v8,$v9,$v10,$v11,$v12,$v13,$v14,$v15,$v16,$v17,$v18,$v19,$v20,$v21,$v22,$v23,$v24,$v25,$v26,$v27,$v28,$v29,$v30,$v31,
   $supress_ordinals = "",
   $use_spaces = "",
   $encoded_sheet_segment_key = ""
   )
   {
   if (!ini_get('register_globals'))
     {
     $superglobals = array($_SERVER,$_ENV,$_FILES,$_COOKIE,$_POST,$_GET);
     if (isset($_SESSION))
       {
       array_unshift($superglobals, $_SESSION);
       }
     foreach ($superglobals as $superglobal)
       {
       extract($superglobal, EXTR_SKIP);
       }
     }
   //
   if (RunMode($_SERVER['PHP_SELF'])) error_reporting(E_ALL);
   //
   $v = array(1 => $v1,$v2,$v3,$v4,$v5,$v6,$v7,$v8,$v9,$v10,$v11,$v12,$v13,$v14,$v15,$v16,$v17,$v18,$v19,$v20,$v21,$v22,$v23,$v24,$v25,$v26,$v27,$v28,$v29,$v30,$v31);
   $avail_string = "";
   //
   $format_string = "";
   if ($encoded_sheet_segment_key) $format_string .= "[";
   if ($supress_ordinals)
      {
      $format_string .= "j";
      }
   else
      {
      $format_string .= "jS";
      }
   //
   for ($i=1; $i<=31; $i++)
      {
      if ($v[$i])
         {
         $avail_string .= date($format_string,mktime(12,0,0,1,$i));
            //
            // The call to mktime() gets us the day number (j) and the ordinal value (S) for time:
            //
            //    currentyear-01-$i 12:00:00
            //
            // This works for us no matter what the actual month of interest is, because January of any year has all 31
            // days and all 31 proper ordinal values, and those are the only elements we're really interested in.  The 
            // choice of noon is arbitrary.
            //
         if ($encoded_sheet_segment_key)
            {
            $avail_string .= "<input type=checkbox name=\""
               .  $encoded_sheet_segment_key
               .  $i
               .  "\" value=1>]";
            }
         if ($use_spaces) $avail_string .= " ";
         $avail_string .= ", ";
         }
      }
   return substr($avail_string,0,-2);
   }
?>