<?
//
// $Id: f_beauthority.phtml 7164 2020-05-18 20:50:04Z kevinanlipscomb $
//
function BeAuthority
   (
   $db_link,
   $email_addr,
   $coord_agency = "EMS"
   )
   {
   $saved_error_level = error_reporting(E_ALL);
   //
   $found_email_addr = "";
   //
   $result = $db_link->query
      (
      "select email_addr as found_email_addr from authority "
      .  "   where email_addr='" . kix\k::Safe($email_addr,kix\k::PhpValueOf_safe_hint_type("EMAIL_ADDRESS")) . "'"
      .  "      and ( coord_agency like '" . kix\k::Safe($coord_agency,kix\k::PhpValueOf_safe_hint_type("KI_SORT_EXPRESSION")) . "' or coord_agency like 'EMS' ) "
      .  "      and has_clearance='TRUE' "
      )
      or die("BeAuthority query failed with error:  " . mysqli_error($db_link));
   //
   if (mysqli_num_rows($result)) extract(mysqli_fetch_array($result));
   //
   error_reporting($saved_error_level);
   return ($found_email_addr != "");
   }
?>