<?
//
// $Id$
//
function BeAuthority
   (
   $db_link,
   $email_addr,
   $mode = "",
   $coord_agency = "EMS"
   )
   {
   $saved_error_level = error_reporting(E_ALL);
   //
   $found_email_addr = "";
   //
   $result = $db_link->query
      (
      "select email_addr as found_email_addr from " . $mode . "authority "
      .  "   where email_addr='$email_addr'"
      .  "      and ( coord_agency like '$coord_agency' or coord_agency like 'EMS' ) "
      .  "      and has_clearance='TRUE' "
      )
      or die("BeAuthority query failed with error:  " . mysqli_error($db_link));
   //
   if (mysqli_num_rows($result)) extract(mysqli_fetch_array($result));
   //
   error_reporting($saved_error_level);
   return ($found_email_addr != "");
   }
?>