<?
//
// $Id: f_beemsschedcoord.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $
//
function BeEmsSchedCoord
   (
   $db_link,
   $email_addr
   )
   {
   $saved_error_level = error_reporting(E_ALL);
   //
   $found_email_addr = "";
   //
   $result = $db_link->query
      (
      "select 1 from authority "
      .  "   where email_addr='" . kix\k::Safe($email_addr,kix\k::PhpValueOf_safe_hint_type("EMAIL_ADDRESS")) . "' "
      .  "      and role='schedule-coordinator' "
      .  "      and coord_agency='EMS' "
      .  "      and has_clearance='TRUE' "
      )
      or die("BeEmsSchedCoord query failed with error:  " . mysqli_error($db_link));
   //
   error_reporting($saved_error_level);
   return (mysqli_num_rows($result));
   }
?>