<?
//
// $Id$
//
function BeAuthority
   (
   $email_addr,
   $mode = "",
   $coord_agency = "EMS"
   )
   {
   $saved_error_level = error_reporting(E_ALL);
   //
   $found_email_addr = "";
   //
   $result = mysql_query
      (
      "select email_addr as found_email_addr from " . $mode . "authority "
      .  "   where email_addr='$email_addr'"
      .  "      and ( coord_agency='$coord_agency' or coord_agency='EMS' ) "
      .  "      and has_clearance == 'TRUE' "
      )
      or die("BeAuthority query failed with error:  " . mysql_error());
   //
   if (mysql_num_rows($result)) extract(mysql_fetch_array($result));
   //
   error_reporting($saved_error_level);
   return ($found_email_addr != "");
   }
?>