<?
//
// $Id$
//
function BeEmsSchedCoord
   (
   $db_link,
   $email_addr,
   $mode = ""   )
   {
   $saved_error_level = error_reporting(E_ALL);
   //
   $found_email_addr = "";
   //
   $result = $db_link->query
      (
      "select 1 from " . $mode . "authority "
      .  "   where email_addr='$email_addr' "
      .  "      and role='schedule-coordinator' "
      .  "      and coord_agency='EMS' "
      .  "      and has_clearance='TRUE' "
      )
      or die("BeEmsSchedCoord query failed with error:  " . mysqli_error($db_link));
   //
   error_reporting($saved_error_level);
   return (mysqli_num_rows($result));
   }
?>