<?
//
// $Id: f_coordagencyofclearedemailaddr.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $
//
function CoordAgencyOfClearedEmailAddr
   (
   $db_link,
   $email_addr
   )
   {
   $saved_error_level = error_reporting(E_ALL);
   //
   $coord_agency = "";
   //
   $result = $db_link->query
      (
      "select coord_agency from authority "
      .  "   where email_addr='" . kix\k::Safe($email_addr,kix\k::PhpValueOf_safe_hint_type("EMAIL_ADDRESS")) . "'"
      .  "      and has_clearance='TRUE' "
      )
      or die("CoordAgencyOfClearedEmailAddr query failed with error:  " . mysqli_error($db_link));
   //
   if (mysqli_num_rows($result)) extract(mysqli_fetch_array($result));
   //
   error_reporting($saved_error_level);
   return $coord_agency;
   }
?>