<?
//
// $Id: f_harvestedlist.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $
//
function HarvestedList($resource)
//
   {
   $saved_error_level = error_reporting(E_ALL);
   //
   $s = "";
   //
   while ($entry_row = mysqli_fetch_array($resource))
      {
      $last_name = $first_name = $email_addr = "";
      extract($entry_row);
      $s .= "   $last_name, $first_name, $email_addr\n";
      }
   //
   error_reporting($saved_error_level);
   return $s;
   }
?>
