<?
//
// $Id: f_harvestemailaddresses.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $
//
function HarvestEmailAddresses
   (
   $ini,
   $db_link
   )
   {
   $saved_error_level = error_reporting(E_ALL);
   //
   $result = $db_link->query
      (
      "select count(*) as count "
      .  " from avail_sheet "
      .  " where expiration < CURRENT_DATE "
      )
      or die("Query 1 failed with error: " . mysqli_error($db_link));
   $row = mysqli_fetch_array($result);
   $count = 0;
   extract($row);
   if ($count)
      {
      $agency_result = $db_link->query("select distinct coord_agency from authority where role='egroup-manager'")
         or die("Query 2 failed with error: " . mysqli_error($db_link));
      if (mysqli_num_rows($agency_result))
         {
         while ($agency_row = mysqli_fetch_array($agency_result))
            {
            $coord_agency = "";
            extract($agency_row);
            $harvest_message_subject = "OSCAR email address harvest for $coord_agency";
            //
            $harvest_message_recipient = RoleEmailAddress($db_link,"egroup-manager",$coord_agency);
            $query = "select distinct last_name, first_name, email_addr "
               .  " from avail_sheet "
               .  " where expiration < CURRENT_DATE "
               .  "    and email_addr not like '%vbgov.com' ";
            if ($coord_agency != "EMS")
               {
               $query .= " and coord_agency='$coord_agency' or squad='" . SquadOfCoordAgency($db_link,$coord_agency) . "' ";
               }
            $query .= " order by last_name, first_name, email_addr ";
            $entry_result = $db_link->query($query) or die("Query 3 failed with error: " . mysqli_error($db_link));
            if ($num_rows = mysqli_num_rows($entry_result))
               {
               //                  0        1         2         3         4         5         6         7
               //                  123456789012345678901234567890123456789012345678901234567890123456789012
               $harvest_message = "Dear egroup manager,\n\n"
                                . "OSCAR has harvested the following $num_rows email addresses for agency\n"
                                . "'$coord_agency'.  This report does not include email addresses in the\n"
                                . "VBGOV.COM domain:\n\n";
               //
               $harvest_message .= HarvestedList($entry_result);
               //
               // Add sig lines.
               //
               $harvest_message .= "\n";
               $harvest_message .= "-- OSCAR\n";
               $harvest_message .= "-- Home page: " . $ini[server][host_url] . "/" . $ini[app][superapp] . "\n";
               $harvest_message .= "-- Sysadmin: " . RoleEmailAddress($db_link,"") . "\n";
               //
               // Send the mail.
               //
               kix\k::SmtpMailSend
                 (
                 RoleEmailAddress($db_link,""), //from
                 $harvest_message_recipient, //to
                 $harvest_message_subject, //subject
                 $harvest_message, //message_string
                 false, //be_html
                 "", //cc
                 "", //bcc
                 RoleEmailAddress($db_link,"") //reply_to
                 );
               }
            }
         }
      }
   error_reporting($saved_error_level);
   return $count;
   }
?>
