<?
//
// $Id: f_numdistinctusers.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $
//
function NumDistinctUsers
   (
   $db_link,
   $month_abbrev,
   $coord_agency = ""
   )
   {
   $saved_error_level = error_reporting(E_ALL);
   //
   $coord_agency = kix\k::Safe($coord_agency,kix\k::PhpValueOf_safe_hint_type("ALPHANUM"));
   $month_abbrev = kix\k::Safe($month_abbrev,kix\k::PhpValueOf_safe_hint_type("ALPHA"));
   //
   $num_distinct_users = 0;
   $qry = "select distinct email_addr from avail_sheet "
      .  "   where month='$month_abbrev' ";
   if ($coord_agency)
      {
      $qry .= "and coord_agency='$coord_agency' ";
      }
   $result = $db_link->query($qry)
      or die("NumDistinctUsers query failed with error:  " . mysqli_error($db_link));
   $num_distinct_users = mysqli_num_rows($result);
   //
   error_reporting($saved_error_level);
   return $num_distinct_users;
   }
?>