<?
//
// $Id$
//
function NumSheets
   (
   $month_abbrev,
   $mode = "",
   $coord_agency = "",
   $be_tda_inclusive = ""
   )
   {
   $saved_error_level = error_reporting(E_ALL);
   //
   $num_submitters = 0;
   $qry = "select count(distinct last_name, first_name) as num_submitters from oscar." . $mode . "avail_sheet "
      .  "   where month='$month_abbrev' ";
   if ($be_tda_inclusive != "") $qry .= "and be_tda != 'TRUE' ";
   if (!$coord_agency)
      {
      $qry .= " group by month";
      }
   else
      {
      $qry .= "and coord_agency='$coord_agency' "
      .  " group by month, coord_agency";
      }
   $result = mysql_query($qry)
      or die("NumSheets query failed with error:  " . mysql_error());
   if (mysql_num_rows($result)) extract(mysql_fetch_array($result));
   //
   error_reporting($saved_error_level);
   return $num_submitters;
   }
?>