<?
//
// $Id: f_properties.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $
//
function Properties
   (
   $db_link,
   $be_on_team_5,
   $be_on_team_30,
   $be_on_team_air,
   $be_tda,
   $be_als,
   $squad,
   $coord_agency = "EMS",
   $be_third = "",
   $be_nondriver = "",
   $be_needing_driver = "",
   $be_combined_agency_format = ""
   )
   {
   //
   $s = "-";
   if ($be_on_team_air == "TRUE") $s .= "H"; else $s .= "-";
   $s .= "-";
   if ($be_on_team_5 == "TRUE") $s .= "S"; else $s .= "-";
   $s .= "-";
   if ($be_on_team_30 == "TRUE") $s .= "30"; else $s .= "--";
   $s .= "-";
   if ($coord_agency == "EMS")
      {
      if ($be_tda == "TRUE") $s .= "TDA"; else $s .= "---";
      $s .= "-";
      if ($be_als == "TRUE") $s .= "Z"; else $s .= "-";
      if ($be_combined_agency_format == "TRUE") $s .= "--------";
      $s .= "- ";
      if ($squad != "ERS") $squad = sprintf("R%02s",$squad);
      $s .= sprintf("%3s",$squad);
      }
   else // coord_agency is not EMS
      {
      //
      // Build patient care indicator: {---|aic|ALS}
      //
      if ($be_combined_agency_format == "TRUE") $s .= "------";
      if ($be_third == "TRUE")
         {
         $s .="---";
         }
      else
         {
         if ($be_needing_driver == "TRUE")
            {
            $s .= "ALS";
            }
         else
            {
            $s .= "aic";
            }
         }
      $s .= "-";
      //
      // Build driver indicator
      //
      if ($be_nondriver == "TRUE")
         {
         $s .= "---";
         }
      else
         {
         $s .= "drv";
         }
      $s .= "- ";
      if ($be_combined_agency_format == "TRUE")
         {
         $s .= sprintf("%3s",SquadOfCoordAgency($db_link,$coord_agency));
         }
      }
   //
   return $s;
   }
?>