<?
//
// $Id$
//
function Properties
   (
   $be_on_team_5,
   $be_on_team_30,
   $be_tda,
   $be_als,
   $squad,
   $mode = "",
   $coord_agency = "EMS",
   $be_third = "",
   $be_nondriver = "",
   $be_needing_driver = ""
   )
   {
   if ($mode) $saved_error_level = error_reporting(E_ALL);
   //
   $s = "-";
   if ($coord_agency == "EMS")
      {
      if ($be_on_team_5 == "TRUE") $s .= "5"; else $s .= "-";
      $s .= "-";
      if ($be_on_team_30 == "TRUE") $s .= "30"; else $s .= "--";
      $s .= "-";
      if ($be_tda == "TRUE") $s .= "TDA"; else $s .= "---";
      $s .= "-";
      if ($be_als == "TRUE") $s .= "Z"; else $s .= "-";
      $s .= "- ";
      if ($squad != "ERS") $squad = sprintf("R%02s",$squad);
      $s .= sprintf("%3s",$squad);
      }
   else // coord_agency is not EMS
      {
      //
      // Build patient care indicator: {---|aic|ALS}
      //
      if ($be_third == "TRUE")
         {
         $s .="---";
         }
      else
         {
         if ($be_needing_driver == "TRUE")
            {
            $s .= "ALS";
            }
         else
            {
            $s .= "aic";
            }
         }
      $s .= "-";
      //
      // Build driver indicator
      //
      if
         (
            ($be_nondriver == "TRUE")
         or
            ($be_third == "TRUE")
         )
      // then
         {
         $s .= "---";
         }
      else
         {
         $s .= "drv";
         }
      $s .= "- ";
      }
   //
   if ($mode) error_reporting($saved_error_level);
   return $s;
   }
?>