<?
//
// $Id$
//
require_once("f_connectselectdbinstanceunpublishedkalipso.phtml");
//
function PutLibPhotoRandomPlaced
   (
   $placement,
   $limit = "",
   $align = ""
   )
   {
   //
   // Connect to the database.
   //
   $conn = ConnectSelectDbInstanceUNPUBLISHEDkalipso($db_link);
   //
   // Create the SQL statement
   //
   $sql = "select div_spec,frame_num from photo_detail where placement like '%$placement%' order by rand()";
   if ($limit != "") $sql = $sql . " limit $limit";
   //
   // Execute the statement
   //
   $result_set = $db_link->query($sql) or die(mysqli_error($db_link));
   //
   // Check how many rows were returned
   //
   $rows = mysqli_num_rows($result_set);
   if ((!$result_set) || ($rows == 0))
      {
      echo "<br><b>Could not find any such photographs.</b><br>";
      }
   else
      {
      //
      while ($field_array = mysqli_fetch_array($result_set))
         {
         extract($field_array);
            //
            // This sets up the $div_spec and $frame_num variables.
            //
         $image_source_spec = "http://kalipso.phpwebhosting.com/photolib/div/$div_spec/$frame_num-i.jpg";
         echo "<a href=\"http://kalipso.phpwebhosting.com/photolib/present-photo.phtml?div_spec=$div_spec&frame_num=$frame_num\">\n";
         $size = @GetImageSize("$image_source_spec");
         echo "   <img border=\"2\" src=$image_source_spec $size[3] align=$align>\n";
         echo "</a>\n";
         }
      }
   }
?>
