<?
//
// $Id: f_writecalendarbody.phtml 541 2001-12-02 04:01:08Z kevinanlipscomb $
//
function ReferToOscarTrack()
   {
   echo "<table border=\"1\" cellspacing=\"0\" cellpadding=\"5\">\n"
   .    "  <tr>\n"
   .    "    <td align=\"center\">\n"
   .    "      <small>Looking for the Roster, Fleet Status, or more?&nbsp;Visit...</small><br/>\n"
   .    "      <big><i><b><a href=\"http://frompaper2web.com/OscarTRACK\">OscarTRACK</a></b></i></big>\n"
   .    "    </td>\n"
   .    "  </tr>\n"
   .    "</table>\n";
   }
?>