<?
//
// $Id$
//
// Note:
//    To expand a role into multiple email addresses, separate the addresses
//    with a comma ONLY -- no spaces.
//
function RoleEmailAddress($role)
   {
   switch ($role)
      {
      //
      // Roles for use by production code
      //
      case "schedule-coordinator":
         return "ebrazle@vbgov.com";
         break;
      case "escalation-level-1-recipient":
         return "wkiley@vbgov.com";
         break;
      case "escalation-level-2-recipient":
         return "NONE";
         break;
      //
      // Roles for use by experimental code
      //
      case "x-schedule-coordinator":
         return "ebrazle@vbgov.com";
         break;
      case "x-escalation-level-1-recipient":
         return "wkiley@vbgov.com";
         break;
      case "x-escalation-level-2-recipient":
         return "NONE";
         break;
      default:
         return "kevin.lipscomb@kvrs.org";
         break;
      }
   }
?>