<?
//
// $Id: f_showavailsheetrecdetail.phtml 2953 2009-10-22 15:01:51Z KevinAnLipscomb $
//
function SetAvailComment
   (
   $db_link,
   $applicable_month_abbrev,
   $last_name,
   $first_name,
   $timestamp,
   $coord_agency,
   $shift_designator,
   $nominal_day_of_month,
   $comment
   )
   {
   //
   $applicable_month_abbrev = kix\k::Safe($applicable_month_abbrev,kix\k::PhpValueOf_safe_hint_type("ALPHA"));
   $last_name = kix\k::Safe($last_name,kix\k::PhpValueOf_safe_hint_type("HUMAN_NAME"));
   $first_name = kix\k::Safe($first_name,kix\k::PhpValueOf_safe_hint_type("HUMAN_NAME"));
   $timestamp = kix\k::Safe($timestamp,kix\k::PhpValueOf_safe_hint_type("DATE_TIME"));
   $coord_agency = kix\k::Safe($coord_agency,kix\k::PhpValueOf_safe_hint_type("ALPHANUM"));
   $shift_designator = kix\k::Safe($shift_designator,kix\k::PhpValueOf_safe_hint_type("ALPHA"));
   $nominal_day_of_month = kix\k::Safe($nominal_day_of_month,kix\k::PhpValueOf_safe_hint_type("NUM"));
   $comment = kix\k::Safe($comment,kix\k::PhpValueOf_safe_hint_type("HYPHENATED_NUM"));
   //
   $sql = "replace avail_comment set month = '$applicable_month_abbrev'"
   . " , last_name = '" . addslashes(trim($last_name)) ."'"
   . " , first_name = '" . addslashes(trim($first_name)) . "'"
   . " , timestamp = '$timestamp'"
   . " , coord_agency = '$coord_agency'"
   . " , shift_designator = '$shift_designator'"
   . " , nominal_day_of_month = '$nominal_day_of_month'"
   . " , comment = '$comment'";
   $db_link->query($sql)
     or die
       (
       "Sorry, the database operation failed with this error:  <i>"
       .  mysqli_error($db_link)
       .  "</i>\n\nPlease notify the <a href=mailto:\""
       .  RoleEmailAddress($db_link,"")
       .  "\">OSCAR System Administrator</a>."
       );
   //
   // As a failsafe in case the database becomes unavailable at any critical time after the insertion, send the
   // data to the sysadmin via email.
   //
   kix\k::SmtpMailSend
     (
     RoleEmailAddress($db_link,""), //from
     RoleEmailAddress($db_link,"failsafe-recipient"), //to
     "OSCAR insert op", //subject
     stripslashes($sql) //message_string
     );
   //
   }
?>
