<?
//
// $Id: f_sendapprovalnotice.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $
//
function SendApprovalNotice
   (
   $ini,
   $db_link,
   $email_addr,
   $digest
   )
   {
   $approval_notice_recipient = $email_addr;
   $approval_notice_subject = "Your OSCAR report";
   //
   //                   0        1         2         3         4         5         6         7
   //                   123456789012345678901234567890123456789012345678901234567890123456789012
   $approval_notice =  "The OSCAR Availability Report\n";
   $approval_notice .= "you requested is available at:\n\n";
   $approval_notice .= $ini[server][root_url] . "/get-report.phtml?digest=$digest\n\n";
   //
   // Add sig lines.
   //
   $approval_notice .= "-- OSCAR\n";
   $approval_notice .= "-- Home page: " . $ini[server][host_url] . "/" . $ini[app][superapp] . "\n";
   $approval_notice .= "-- Sysadmin: " . RoleEmailAddress($db_link,"") . "\n";
   //
   // Send the mail.
   //
    kix\k::SmtpMailSend
      (
      RoleEmailAddress($db_link,""), //from
      $approval_notice_recipient, //to
      $approval_notice_subject, //subject
      $approval_notice, //message_string
      false, //be_html
      "", //cc
      "", //bcc
      RoleEmailAddress($db_link,"") //reply_to
      );
   return true;
   }
?>
