<?
//
// $Id: f_serverstatus.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $
//
function ServerStatus($db_link)
   {
   error_reporting(E_ALL);
   //
   $value = 0;
   $result = $db_link->query("select value from db_status limit 1")
      or die("ServerStatus query failed with error:  " . mysqli_error($db_link));
   if (mysqli_num_rows($result)) extract(mysqli_fetch_array($result));
   //
   return $value;
   }
?>