<?
//
// $Id: f_squadofcoordagency.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $
//
function SquadOfCoordAgency
   (
   $db_link,
   $coord_agency
   )
//
   {
   $saved_error_level = error_reporting(E_ALL);
   //
   $coord_agency = kix\k::Safe($coord_agency,kix\k::PhpValueOf_safe_hint_type("ALPHANUM"));
   //
   $squad = "";
   $result = $db_link->query("select squad from squad_of_coord_agency where coord_agency='$coord_agency'")
      or die("SquadOfCoordAgency query failed with error: " . mysqli_error($db_link));
   @extract(mysqli_fetch_array($result));
   //
   error_reporting($saved_error_level);
   return $squad;
   }
?>