<?
//
// $Id$
//
function sShowAvailSheetRecDetail
   (
   $timestamp,
   $first_name,
   $last_name,
   $email_addr,
   $squad,
   $month,
   $be_on_team_5,
   $be_on_team_30,
   $num_extras,
   $d1,$d2,$d3,$d4,$d5,$d6,$d7,$d8,$d9,$d10,$d11,$d12,$d13,$d14,$d15,$d16,$d17,$d18,$d19,$d20,$d21,$d22,$d23,$d24,$d25,$d26,$d27,$d28,$d29,$d30,$d31,
   $n1,$n2,$n3,$n4,$n5,$n6,$n7,$n8,$n9,$n10,$n11,$n12,$n13,$n14,$n15,$n16,$n17,$n18,$n19,$n20,$n21,$n22,$n23,$n24,$n25,$n26,$n27,$n28,$n29,$n30,$n31,
   $note,
   $expiration,
   $be_authority = ""
   )
   {
   $s =  "";
   $s .= "TIME OF SUBMISSION:      ";
   $s .= substr($timestamp,0,4)
      .  "-"
      .  substr($timestamp,4,2)
      .  "-"
      .  substr($timestamp,6,2)
      .  " "
      .  substr($timestamp,8,2)
      .  ":"
      .  substr($timestamp,10,2)
      .  ":"
      .  substr($timestamp,12,2);
   $s .= "FIRST NAME:              " . stripslashes($first_name) . "\n";
   $s .= "LAST NAME:               " . stripslashes($last_name) . "\n";
   $s .= "EMAIL ADDRESS:           " . stripslashes($email_addr) . "\n";
   $s .= "HOME SQUAD:              $squad\n";
   $s .= "APPLICABLE MONTH:        $month\n";
   $s .= "ON EMS-5 TEAM:           $be_on_team_5\n";
   $s .= "ON SQUAD TRUCK TEAM:     $be_on_team_30\n";
   $s .= "#EXTRA DUTIES WILL RUN:  $num_extras\n";
   $s .= "AVAILABLE DAYS:          ";
   $d = array(1 => $d1,$d2,$d3,$d4,$d5,$d6,$d7,$d8,$d9,$d10,$d11,$d12,$d13,$d14,$d15,$d16,$d17,$d18,$d19,$d20,$d21,$d22,$d23,$d24,$d25,$d26,$d27,$d28,$d29,$d30,$d31);
   for ($i=1; $i<=31; $i++)
      {
      if ($d[$i]) $avail_days_string .= "$i, ";
      }
   $s .= substr($avail_days_string,0,-2);
   $s .= "\n";
   $s .= "AVAILABLE NIGHTS:        ";
   $n = array(1 => $n1,$n2,$n3,$n4,$n5,$n6,$n7,$n8,$n9,$n10,$n11,$n12,$n13,$n14,$n15,$n16,$n17,$n18,$n19,$n20,$n21,$n22,$n23,$n24,$n25,$n26,$n27,$n28,$n29,$n30,$n31);
   for ($i=1; $i<=31; $i++)
      {
      if ($n[$i]) $avail_nights_string .= "$i, ";
      }
   $s .= substr($avail_nights_string,0,-2);
   $s .= "\n";
   if ($be_authority == 1)
      {
      $s .= "NOTE:                 " . stripslashes($note) . "\n";
      }
   $s .= "RECORD EXPIRES:          $expiration\n";
   //
   return $s;
   }
?>