<?
//
// $Id: f_writecalendarsubform.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $
//
function WriteCalendarSubform
   (
   $applicable_month_num,
   $instruction_string = ""
   )
//
   {
   $time_noon_first_day = mktime(12,0,0,$applicable_month_num,1);
   $applicable_month_name = date("F",$time_noon_first_day);
   $day_of_week_of_1st = date("w",$time_noon_first_day);
   $num_days_in_applicable_month = date("t",$time_noon_first_day);
   ?>
   <table>
      <tr>
         <td colspan=2><? echo $instruction_string; ?><p>&nbsp;</p></td>
      </tr>
      <tr>
         <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
         <td>
            <table border=1 cellspacing=0 cellpadding=4>
               <tr bgcolor=#D0D0D0><td colspan=7><h2><? echo $applicable_month_name; ?> DAYS</h2></td></tr>
               <tr bgcolor=#E8E8E8>
                  <td align=center>Sun</td>
                  <td align=center>Mon</td>
                  <td align=center>Tue</td>
                  <td align=center>Wed</td>
                  <td align=center>Thu</td>
                  <td align=center>Fri</td>
                  <td align=center>Sat</td>
               </tr>
               <? WriteCalendarBody("d",$day_of_week_of_1st,$num_days_in_applicable_month); ?>
            </table>
         </td>
      </tr>
      <tr><td colspan=2>&nbsp;</td></tr>
      <tr>
         <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
         <td>
            <table border=1 cellspacing=0 cellpadding=4>
               <tr bgcolor=#D0D0D0><td colspan=7><h2><? echo $applicable_month_name; ?> NIGHTS</h2></td></tr>
               <tr bgcolor=#E8E8E8>
                  <td align=center>Sun</td>
                  <td align=center>Mon</td>
                  <td align=center>Tue</td>
                  <td align=center>Wed</td>
                  <td align=center>Thu</td>
                  <td align=center>Fri</td>
                  <td align=center>Sat</td>
               </tr>
               <? WriteCalendarBody("n",$day_of_week_of_1st,$num_days_in_applicable_month); ?>
            </table>
         </td>
      </tr>
   </table>
   <?
   }
?>