<?
//
// $Id: faq.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $
//
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
//
$ini = AppSettings();
$db_link = DbLink($ini);
$dbkalipso_link = DbkalipsoLink($ini);
//
if ($ini[app][do_report_all_errors]) error_reporting(E_ALL);
?>
<html>

<head>
<title>OSCAR - FAQ</title>
</head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
        <table><tr><td>
           <h6 align="center">
              KVEO-IT-PROJECT<br>
              <a href="javascript:close();">OSCAR SYSTEM</a><br>
              <a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></h6>
           <h1 align="center">Frequently Asked Questions</h1>
        </td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>
           <? PutLibPhotoRandomPlaced($ini,$dbkalipso_link,"oscarsystem",1); ?>
        </td></tr></table>
        <hr>
           <p>To search for a particular word or phrase, press CTRL-F.</p>
           <ul>
              <?
              $result = $db_link->query("select * from faq")
                 or die("Query failed with error: " . mysqli_error($db_link));
              $num_rows = mysqli_num_rows($result);
              for ($i=1; $i<=$num_rows; $i++)
                 {
                 extract(mysqli_fetch_array($result));
                 echo "<li><a href=#$position>$question</a></li><br>\n";
                 }
              ?>
           </ul>
           <hr>
           <blockquote>
              <?
              if ($num_rows > 0)
                 {
                 mysqli_data_seek($result,0);
                 for ($i=1; $i<=$num_rows; $i++)
                    {
                    extract(mysqli_fetch_array($result));
                    echo "<a name=\"$position\"></a><b>$question</b></a><blockquote>$answer</blockquote>\n";
                    }
                 }
              ?>
           </blockquote>
        <hr>
        <p><small><small><em><pre>$Id: faq.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $</pre></em></small></small>
       </td>
    </tr>
  </table>
</body>

</html>

