<?
//
// $Id: form-set-agency.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $
//
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
//
$ini = AppSettings();
$db_link = DbLink($ini);
$dbkalipso_link = DbkalipsoLink($ini);
//
if ($ini[app][do_report_all_errors]) error_reporting(E_ALL);
?>
<html>

<head>
<title>OSCAR - Set squad participation</title>
</head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
        <table><tr><td>
           <h6 align="center">
              KVEO-IT-PROJECT<br>
              <a href="javascript:close();">OSCAR SYSTEM</a><br>
              <a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></h6>
           <h1 align="center">Set Squad Participation</h1>
        </td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>
           <? PutLibPhotoRandomPlaced($ini,$dbkalipso_link,"oscarsystem",1); ?>
        </td></tr></table>
        <hr>
           <p>This form allows the Master OSCAR Authority to enable and disable OSCAR features on a squad-by-squad basis.</p>
           <blockquote>
              <table align=center bgcolor=#E8E8E8>
                 <tr>
                    <td align=center valign=middle>
                       <small><i>To guard against misuse, the OSCAR system authenticates each modification request by
                          sending a "challenge message" to the registered email address of the appropriate authority.&nbsp;
                          Modifications only take effect once OSCAR receives a proper response to the
                          challenge.</i></small>
                    </td>
                 </tr>
              </table>
           </blockquote>
           <br>
           <p><b>WARNING:&nbsp; The buttons on this page send traceable email messages to the Master OSCAR Authority
              (<? echo RoleEmailAddress($db_link,"master"); ?>).&nbsp; These links are not intended for general use.</i></p>
           <blockquote>
              <table cellpadding=4>
                 <tr>
                    <td><b>Agency</b></td>
                    <td align=center><b>OSCAR status</b></td>
                    <td>&nbsp;</td>
                 </tr>
                 <?
                 $result = $db_link->query("select * from agency")
                    or die("Query failed with error: " . mysqli_error($db_link));
                 $num_rows = mysqli_num_rows($result);
                 for ($i=1; $i<=$num_rows; $i++)
                    {
                    extract(mysqli_fetch_array($result));
                    echo "<tr>\n"
                       . "<form action=perform-prep-mod-agency.phtml method=post>\n"
                       . "<input type=hidden name=enumeral value=$enumeral>\n"
                       . "<input type=hidden name=current_be_active value=$be_active>\n"
                       . "<td>$description</td>\n"
                       . "<td align=right>";
                    if ($be_active == "FALSE") echo "NON";
                    echo "PARTICIPANT</td>\n"
                       . "<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type=submit value=Toggle></td>\n"
                       . "</form>\n"
                       . "</tr>\n";
                    }
                 ?>
              </table>
           </blockquote>
        <hr>
        <p><small><small><em><pre>$Id: form-set-agency.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $</pre></em></small></small>
       </td>
    </tr>
  </table>
</body>

</html>

