<?
//
// $Id: form-set-role-2.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $
//
// Emulate register_globals on
if (!ini_get('register_globals'))
  {
  $superglobals = array($_SERVER,$_ENV,$_FILES,$_COOKIE,$_POST,$_GET);
  if (isset($_SESSION))
    {
    array_unshift($superglobals, $_SESSION);
    }
  foreach ($superglobals as $superglobal)
    {
    extract($superglobal, EXTR_SKIP);
    }
  }
//
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_writecalendarsubform.phtml");
require_once("f_writecalendarbody.phtml");
//
$ini = AppSettings();
$db_link = DbLink($ini);
$dbkalipso_link = DbkalipsoLink($ini);
//
if ($ini[app][do_report_all_errors]) error_reporting(E_ALL);
?>
<html>

<head>
<title>OSCAR - Set Role (Part 2)</title>
</head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
        <table><tr>
           <td><? PutLibPhotoRandomPlaced($ini,$dbkalipso_link,"oscarsystem",1); ?></td>
           <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
           <td>
              <h6 align="center">
                 KVEO-IT-PROJECT<br>
                 <a href="javascript:close();">OSCAR SYSTEM</a><br>
                 <a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></h6>
              <h1 align="center">Set Role (Part 2)</h1>
           </td>
        </tr></table>
        <hr>
        <?
        //
        // Validate parameters.
        //
        if
           (
              ($agency != "")
           and
              ($role != "")
           )
        // then
        {
        $agency = kix\k::Safe($agency,kix\k::PhpValueOf_safe_hint_type("ALPHANUM"));
        $role = kix\k::Safe($role,kix\k::PhpValueOf_safe_hint_type("HYPHENATED_ALPHANUM"));
        //
        // Show what was collected in Part 1.
        //
        echo "<br>\n"
           . "<table>\n"
           . "   <tr><td>Agency:</td><td><b>$agency</b></td></tr>\n"
           . "   <tr><td>Role:</td><td><b>$role</b></td></tr>\n"
           . "</table>\n"
           . "<br>\n";
        ?>
        The current value of the specified role is:
        <?
        $result = $db_link->query
           (
           "select email_addr from authority "
           .  "where coord_agency='$agency' "
           .  "   and role='$role' "
           )
           or die("Current value query failed with error: " . mysqli_error($db_link));
        //
        echo "<blockquote>\n";
        if ($num_rows = mysqli_num_rows($result))
           {
           extract(mysqli_fetch_array($result));
           echo "   <b>$email_addr</b>\n";
           }
        else
           {
           echo "   <b>UNDEFINED</b>\n";
           $email_addr = "UNDEFINED";
           }
        //
        echo "</blockquote>\n";
        //
        // Get the new value
        //
        ?>
        <form action=perform-set-role-challenge.phtml method=post>
           <?
           echo "<input type=hidden name=agency value=\"$agency\">\n"
              . "<input type=hidden name=role value=\"$role\">\n"
              . "<input type=hidden name=current_email_addr value=\"$email_addr\">\n";
           ?>
           What email address would you like to assign to this role?
           <blockquote>
              <input type=text name=proposed_email_addr size=40 maxlength=64>
           </blockquote>
           Which OSCAR Authority will be approving this change?
           <blockquote>
              <?
              //
              // Generate a drop-down selection list showing existing authorities in the affected agency as well as EMS
              // authorities.
              //
              $result = $db_link->query
                 (
                 "select coord_agency as approving_agency "
                 .  "   , role as approving_role "
                 .  "   , email_addr as approving_email_addr "
                 .  "from authority "
                 .  "where "
                 .  "      ( "
                 .  "         coord_agency='$agency' "
                 .  "      or "
                 .  "         coord_agency='EMS' "
                 .  "      ) "
                 .  "   and "
                 .  "      has_clearance='TRUE' "
                 .  "   and "
                 .  "      role != 'sysadmin' "
                 .  "   and "
                 .  "      role != 'failsafe-recipient' "
                 )
                 or die("Eligible authorities query failed with error: " . mysqli_error($db_link));
              //
              echo "<select name=approving_email_addr>\n";
              if (mysqli_num_rows($result) > 1)
                 {
                 echo "<option value=\"\">Select</option>\n";
                 }
              //
              while($row = mysqli_fetch_array($result))
                 {
                 $approving_agency = $approving_role = $approving_email_addr = "";
                 extract($row);
                 echo "<option value=\"$approving_email_addr\">"
                    . "$approving_email_addr ($approving_agency $approving_role)"
                    . "</option>\n";
                 }
              //
              echo "</select>\n";
              ?>
           </blockquote>
           <p><b>WARNING:&nbsp; This form sends a traceable email message to the specified OSCAR Authority.&nbsp; It is not
              intended for general use.</b></p>
           <input type="submit" value="Submit"><input type=reset>
           <?
           //
           // What about the 'has_clearance' value for 'Other' roles?
           //
           ?>
        </form>
        <?
        }
        else
           {
           //
           // Fill the page out with a warning and instructions.
           //
           ?>
           <h2><i>Error!</i></h2>
           <b>
           <blockquote>
              <p>You did not supply one or more of the required parameters.&nbsp; You must supply values for these fields:</p>
              <ul>
                 <li><p>Agency</p>
                 <li><p>Role</p>
              </ul>
              <p>Please press your browser's [<--&nbsp;BACK] button to correct the problems.</p>
           </blockquote>            
           </b>
           <?
           echo "<p>If you have feedback about the technical aspects of this process, please contact the <a href=mailto:" . RoleEmailAddress($db_link,"") . ">OSCAR System Administrator</a>.</p>";
           }
        ?>
        <p><small><small><em><pre>$Id: form-set-role-2.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $</pre></em></small></small></td>
    </tr>
  </table>
</body>

</html>

