<?
//
// $Id: form-set-role-1.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $
//
require_once("f_bodyopen.phtml");
require_once("f_agencyselectionlist.phtml");
//
$ini = AppSettings();
$db_link = DbLink($ini);
$dbkalipso_link = DbkalipsoLink($ini);
//
if ($ini[app][do_report_all_errors]) error_reporting(E_ALL);
?>
<html>

<head>
<title>OSCAR - Set Role (Part 1)</title>
</head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
        <table><tr><td>
           <h6 align="center">
              KVEO-IT-PROJECT<br>
              <a href="javascript:close();">OSCAR SYSTEM</a><br>
              <a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></h6>
           <h1 align="center">Set Role (Part 1)</h1>
        </td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>
           <? PutLibPhotoRandomPlaced($ini,$dbkalipso_link,"oscarsystem",1); ?>
        </td></tr></table>
        <hr>
           <p>This form allows OSCAR Authorities to change OSCAR Role settings.</p>
           <blockquote>
              <table align=center bgcolor=#E8E8E8>
                 <tr>
                    <td align=center valign=middle>
                       <small><i>To guard against misuse, the OSCAR system authenticates each modification request by
                          sending a "challenge message" to the registered email address of the appropriate authority.&nbsp;
                          Modifications only take effect once OSCAR receives a proper response to the
                          challenge.</i></small>
                    </td>
                 </tr>
              </table>
           </blockquote>
           <br>
           <form action=form-set-role-2.phtml method=post>
              Select the Agency-Role combination that you want to change:
              <blockquote>
                 <?
                 $result = $db_link->query("select enumeral from agency ")
                    or die("Agency query failed with error: " . mysqli_error($db_link));
                 echo "<select name=agency>\n";
                 if (mysqli_num_rows($result) > 1)
                    {
                    echo "<option value=\"\">Select</option>\n";
                    }
                 //
                 while($row = mysqli_fetch_array($result))
                    {
                    $enumeral = "";
                    extract($row);
                    echo "<option value=\"$enumeral\">$enumeral</option>\n";
                    }
                 //
                 echo "</select>\n";
                 ?>
                 <select name=role>
                    <option value="">Select</option>
                    <option value=schedule-coordinator>Schedule Coordinator</option>
                    <option value=schedule-coordinator-pager>Schedule Coordinator Pager</option>
                    <option value=escalation-level-1-recipient>Escalation Level 1 Recipient</option>
                    <option value=escalation-level-2-recipient>Escalation Level 2 Recipient</option>
                    <option value=escalation-level-3-recipient>Escalation Level 3 Recipient</option>
                    <option value=egroup-manager>Egroup Manager</option>
                    <option value=other>Other</option>
                 </select>
              </blockquote>
              <input type="submit" value="Continue...">
           </form>
        <hr>
        <p><small><small><em><pre>$Id: form-set-role-1.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $</pre></em></small></small>
       </td>
    </tr>
  </table>
</body>

</html>

