<?
//
// $Id$
//
require_once("f_runmode.phtml");
$mode = RunMode($PHP_SELF);
if ($mode) error_reporting(E_ALL);
//
require_once("f_oscarhomepageurl.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_connectselectdb.phtml");
require_once("f_password.phtml");
require_once($mode . "f_writecalendarsubform.phtml");
?>
<html>

<head>
<title>OSCAR - Availability Submission (Part 2)</title>
</head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
        <table><tr>
           <td><? PutLibPhotoRandomPlaced("sasquatch",1); ?></td>
           <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
           <td>
              <h6 align="center">
                 KVEO-IT-PROJECT<br>
                 <a href="<? echo OscarHomePageUrl(); ?>">OSCAR SYSTEM</a><br>
                 <a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></h6>
              <h1 align="center">Availability Submission (Part 2)</h1>
           </td>
        </tr></table>
        <hr>
        <?
        if (ConnectSelectDb("localhost","kalipso",Password(),"oscar") == "TRUE")
        {
        
        //
        // Validate parameters.
        //
        if
           (
              ($first_name != "")
           and
              ($last_name != "")
           and
              ($email_addr != "")
           and
              ($applicable_month_num != "")
           and
              ($coord_agency != "")
           )
        // then
        {
        //
        // Show what was collected in Part 1.
        //
        echo "<br>\n"
           . "<table>\n"
           . "   <tr><td>Name:</td><td><b>$first_name $last_name</b></td></tr>\n"
           . "   <tr><td>Email address:</td><td><b>$email_addr</b></td></tr>\n"
           . "   <tr><td>Applicable month:</td><td><b>"
           . date("F",mktime(12,0,0,$applicable_month_num,1))
           . "</b></td></tr>\n"
           . "   <tr><td>Coordinating agency:&nbsp;&nbsp;</td><td><b>$coord_agency</b></td></tr>\n"
           . "</table>\n"
           . "<br>\n";
        ?>
        <p><i>For the values you supplied in Part 1, the following additional information is required.&nbsp; Complete the
           form below and press the "Submit" button to finish the process.</i></p>
        <form method="POST" action="<? echo $mode; ?>perform-add-avail-sheet.phtml">
          <?
          echo "<input type=hidden name=first_name value=\"$first_name\">\n"
             . "<input type=hidden name=last_name value=\"$last_name\">\n"
             . "<input type=hidden name=email_addr value=\"$email_addr\">\n"
             . "<input type=hidden name=applicable_month_num value=$applicable_month_num>\n"
             . "<input type=hidden name=coord_agency value=$coord_agency>\n";
          //
          if ($coord_agency == "EMS")
             {
             ?>
             Home squad:
             <select size="1" name=squad>
                <option value="">Select</option>
                <option value="1">1 - Ocean Park</option>
                <option value="2">2 - Davis Corner</option>
                <option value="4">4 - Chesapeake Beach</option>
                <option value="5">5 - Courthouse</option>
                <option value="6">6 - Creeds</option>
                <option value="9">9 - Kempsville</option>
                <option value="13">13 - Blackwater</option>
                <option value="14">14 - Virginia Beach</option>
                <option value="15">15 - Knotts Island</option>
                <option value="16">16 - Plaza</option>
                <option value="17">17 - Sandbridge</option>
                <option value="ERS">ERS - VBFD</option>
             </select>
             <br>
             <p>Check all that apply as of today's date:</p>
             <ul>
                <li><input type=checkbox name=be_als value="TRUE" checked>I am a Zone Car ALS provider.</li>
                <li><input type=checkbox name=be_on_team_30 value="TRUE">I am on the Squad Truck Team.</li>
                <li><input type=checkbox name=be_on_team_5 value="TRUE">I am an EMS-5.</li>
             </ul>
             <?
             }
          else
             {
             ?>
             <p>Check all that apply as of today's date:</p>
             <ul>
                <li><input type=checkbox name=be_third value="TRUE">I am a "third" on the ambulance.</li>
                <li><input type=checkbox name=be_nondriver value="TRUE">I am <b>not</b> qualified to drive the
                   ambulances.</li>
                <li><input type=checkbox name=be_needing_driver value="TRUE">I am an ALS provider (includes ST).</li>
             </ul>
             <?
             }
          WriteCalendarSubform
             (
             $applicable_month_num,
             "Check all shifts for which you are available for at least one type of duty:",
             $mode
             );
          ?>
        <p align="left">How many extra shifts are you willing to be scheduled
          for?&nbsp; <input type="text" name=num_extras size="2" value="0"></p>
          <blockquote>
            <table border="1">
               <tr>
                  <td width="100%">
                     <p align="center"><u>Survey box</u><br>
                     <small>Please take a moment to fill out the survey questions,
                     if any.</small></p>
                     <ul>
                        <li>No survey questions at this time.</li>
                     </ul>
                  </td>
               </tr>
            </table>
          </blockquote>
          <p align=left>Special requests (will only be visible to <a href=authorities.phtml>OSCAR authorities</a>):<br>
          <textarea rows="8" name=note cols="60"></textarea></p>
        <ul>
          <li>
            <p align=left>Availability sheets are due on the 10th day of the proceeding month.</li>
          <li>
            <p align=left>Abusive or fraudulent submissions are traceable and are cause for disciplinary action.</li>
          <li>
            <p align=left>Double check your selections before submitting this form.</li>
          <?
          echo "<li><p align=left>If you have feedback about this form, please send it to the <a href=mailto:" . RoleEmailAddress("",$mode) . ">OSCAR System Administrator</a>.</li>";
          ?>
        </ul>
          <p><input type="submit" value="Submit"><input type=reset></p>
        </form>
        <?
        }
        else
           {
           //
           // Fill the page out with a warning and instructions.
           //
           ?>
           <h2><i>Error!</i></h2>
           <b>
           <blockquote>
              <p>You did not supply one or more of the required parameters.&nbsp; You must supply values for these fields:</p>
              <ul>
                 <li><p>First name</p>
                 <li><p>Last name</p>
                 <li><p>Email address</p>
                 <li><p>Applicable month</p>
                 <li><p>Recieving agency</p>
              </ul>
              <p>Please press your browser's [<--&nbsp;BACK] button to correct the problems.</p>
           </blockquote>            
           </b>
           <?
           echo "<p>If you have feedback about the technical aspects of this process, please contact the <a href=mailto:" . RoleEmailAddress("") . ">OSCAR System Administrator</a>.</p>";
           }
        }
        else
           {
            ?>
            <h2><i>Sorry...</i></h2>
            <b>
            <blockquote>
               <? echo "<p>OSCAR's database has gone offline.&nbsp; Please retry the submission process later.</p>"; ?>
            </blockquote>            
            </b>
            <?
           }
        ?>
        <p><small><small><em><pre>$Id$</pre></em></small></small></td>
    </tr>
  </table>
</body>

</html>

