<?
//
// $Id: form-submit-class-act.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $
//
require_once("f_bodyopen.phtml");
//
$ini = AppSettings();
//
if ($ini[app][do_report_all_errors]) error_reporting(E_ALL);
?>
<html>

<head>
<title>OSCAR - Class Act Award Nomination Form</title>
</head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
        <table align=center><tr><td>
           <h6 align="center">
              KVEO-IT-PROJECT<br>
              <a href="javascript:close();">OSCAR SYSTEM</a><br>
              <a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a>
           </h6>
           <table cellpadding=10>
              <tr>
                 <td><img src=static-image/trophy-icon.gif></td>
                 <td valign=middle><center><big><big><big><b>Class Act Award Nomination Form</b></big></big></big></center></td>
                 <td><img src=static-image/trophy-icon.gif></td>
              </tr>
           </table>
        </td></tr></table>
        <hr>
        <blockquote>
           <table cellpadding=10>
              <tr>
                 <td align=right valign=top><b>Purpose</b></td>
                 <td>
                   To provide a way for VBEMS members to credit fellow VBEMS members for actions deserving of recognition.&nbsp; Your submission will be taken to the Recruitment & Retention Committee at their next
                   meeting.&nbsp; If your nominee is awarded a Class Act Award by the committee, our Retention Officer, Katelyn Snell, will reach out to you.
                 </td>
              </tr>
              <tr>
                 <td align=right valign=top><b>Criteria</b></td>
                 <td>Members who have gone above and beyond in their service, while fulfilling their commitments to the Department of EMS and the Volunteer Rescue Squads</td>
              </tr>
              <tr>
                 <td align=right valign=top><b>Eligibility</b></td>
                 <td>Any currently active VBEMS member</td>
              </tr>
           </table>
        </blockquote>
        <hr>
        <form action=<?php echo ""; ?>perform-send-class-act.phtml method=post>
           <table>
              <tr>
                 <td align=right valign=top>Station:</td>
                 <td><input type=text name=station size=15></td>
              </tr>
              <tr>
                 <td align=right valign=top>Person(s) nominated:</td>
                 <td><textarea name=nominees rows=3 cols=40></textarea></td>
              </tr>
              <tr>
                 <td align=right valign=top>Description of situation, event, or initiative:</td>
                 <td><textarea name=description rows=15 cols=60></textarea></td>
              </tr>
              <tr>
                 <td align=right valign=top>Your name:</td>
                 <td><input type=text name=submitter size=40></td>
              </tr>
              <tr>
                 <td align=right valign=top>Your daytime phone number:</td>
                 <td><input type=text name=phonenum size=15></td>
              </tr>
              <tr>
                 <td align=right valign=top>Your email address:</td>
                 <td><input type=text name=emailaddr size=40></td>
              </tr>
              <tr>
                 <td align=center colspan=2>
                    <input type=submit value="Submit">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <input type=reset>
                 </td>
              </tr>
           </table>
        </form>
        <hr>
        <p><small><small><em><pre>$Id: form-submit-class-act.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $</pre></em></small></small>
       </td>
    </tr>
  </table>
</body>

</html>

