<?
//
// $Id: form-submit-avails-1.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $
//
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_agencyselectionlist.phtml");
//
$ini = AppSettings();
$db_link = DbLink($ini);
$dbkalipso_link = DbkalipsoLink($ini);
//
if ($ini[app][do_report_all_errors]) error_reporting(E_ALL);
?>
<html>

<head>
<title>OSCAR - Availability Submission (Part 1)</title>
</head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
        <table><tr><td>
           <h6 align="center">
              KVEO-IT-PROJECT<br>
              <a href="javascript:close();">OSCAR SYSTEM</a><br>
              <a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></h6>
           <h1 align="center">Availability Submission (Part 1)</h1>
        </td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>
           <? PutLibPhotoRandomPlaced($ini,$dbkalipso_link,"oscarsystem",1); ?>
        </td></tr></table>
        <hr>
           <p><i>Submission is a simple two-step process.&nbsp; To 
              complete Part 1, fill out this form and press the "Continue..." button.</i></p>
           <p>All fields on this page are required.</p>
           <form method="POST" action="form-submit-avails-2.phtml">
             <table>
               <tr>
                 <td>First name:</td>
                 <td><input type="text" name=first_name size="32" maxlength=32></td>
               </tr>
               <tr>
                 <td>Last name:</td>
                 <td><input type="text" name=last_name size="32" maxlength=32></td>
               </tr>
               <tr>
                 <td>Email address:</td>
                 <td><input type="text" name=email_addr size=40 maxlength=64></td><td valign=middle><small>(of person entering
                    data)</small></td>
               </tr>
               <tr>
                  <td>Applicable month:</td>
                  <td><select size=1 name=applicable_month_num>
                     <option value="">Select</option>
                     <?
                     $next_month_num = date("n") + 1;
                     echo "<option value=" . $next_month_num . ">" . date("F",mktime(12,0,0,$next_month_num,1)) . "</option>\n";
                     echo "<option value=" . ($next_month_num + 1) . ">" . date("F",mktime(12,0,0,($next_month_num + 1),1)) . "</option>\n";
                     ?>
                  </select></td>
               </tr>
               <tr>
                  <td>Send availabilities to:</td>
                  <td><? AgencySelectionList($db_link); ?></td><td valign=middle><small>If you get scheduled by both EMS and your squad,
                     send <b>only</b> to EMS.&nbsp; EMS will relay leftover availabilities to your squad.</small></td>
               </tr>
             </table>
            <br>
            <p>The next page collects details required by your schedule coordinator, including the shifts for which you will
               be available.</p>
            <p><input type="submit" value="Continue..."><input type="reset"></p>
            </form>
         <p><small><small><em><pre>$Id: form-submit-avails-1.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $</pre></em></small></small>
       </td>
    </tr>
  </table>
</body>

</html>

