<?
//
// $Id$
//
require_once("f_runmode.phtml");
$mode = RunMode($PHP_SELF);
if ($mode) error_reporting(E_ALL);
//
require_once("f_oscarhomepageurl.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("f_bodyopen.phtml");
require_once("f_connectselectdb.phtml");
require_once("f_password.phtml");
require_once("f_agencyselectionlist.phtml");
?>
<html>

<head>
<title>OSCAR - Reconfirmation/Retraction Request Form</title>
</head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
        <table><tr><td>
           <h6 align="center">
              KVEO-IT-PROJECT<br>
              <a href="<? echo OscarHomePageUrl(); ?>">OSCAR SYSTEM</a><br>
              <a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></h6>
           <h1 align="center">Reconfirmation/Retraction Request Form</h1>
        </td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>
           <? PutLibPhotoRandomPlaced("sasquatch",1); ?>
        </td></tr></table>
        <hr>
        <?
        if (ConnectSelectDb("localhost","kalipso",Password(),"oscar") != "TRUE")
           {
           ?>
           <h2><i>Sorry...</i></h2>
           <b>
           <blockquote>
              <? echo "<p>OSCAR's database is temporarily offline.&nbsp; Please try again later.</p>"; ?>
           </blockquote>            
           </b>
           <?
           }
        else
        {
        ?>
        <p>This form allows you to reconfirm what you have submitted to the OSCAR system, or even to "take back" your 
           previous submissions.</p>
        <blockquote>
           <table align=center bgcolor=#E8E8E8>
              <tr>
                 <td align=center valign=middle>
                    <small><i>To guard against misuse, the OSCAR system authenticates each reconfirmation/retraction 
                       request by sending a "challenge message" to the email address <u>originally specified</u> on a
                       person's availability sheet.&nbsp; A retraction, if requested, will only take effect once OSCAR
                       receives a proper response to the challenge.</i></small>
                 </td>
              </tr>
           </table>
        </blockquote>
        <p>If you are using this form to trigger a <b>retraction</b>, you should <b>wait for further instructions</b>
           that will arrive with the email challenge message.&nbsp; <b>Do not immediately resubmit</b> after completing
           this form.</p>
        <p>In practice, reconfirming or retracting is easy, safe, and secure.  To begin the process, complete
           the following form:</p>
        <br>
        <blockquote>
           <form action=<? echo $mode; ?>perform-gen-challenge.phtml method=post>
              <table>
                 <tr>
                    <td>First name:</td>
                    <td><input type=text name=first_name size=32></td>
                    <td valign=middle rowspan=2><small>(of EMS/ERS provider)</small></td>
                 </tr>
                 <tr>
                    <td>Last name:</td>
                    <td><input type=text name=last_name size=32></td>
                 </tr>
                 <tr>
                    <td>Applicable month:</td>
                    <td><select size=1 name=applicable_month_num>
                       <option value="">Select</option>
                       <?
                       $next_month_num = date("n") + 1;
                       echo "<option value=" . $next_month_num . ">" . date("F",mktime(12,0,0,$next_month_num,1)) . "</option>\n";
                       echo "<option value=" . ($next_month_num + 1) . ">" . date("F",mktime(12,0,0,($next_month_num + 1),1)) . "</option>\n";
                       ?>
                    </select></td>
                 </tr>
                 <tr>
                    <td>Which agency?</td>
                    <td><? AgencySelectionList($mode); ?></td>
                 </tr>
              </table>
              <p>Please double check your entries before completing your request.&nbsp; They must match what you
                 supplied on your availability sheet (although uppercase & lowercase do not matter).</p>
              <input type=submit value="Send request"><input type=reset>
           </form>
        </blockquote>
        <?
        }
        ?>
        <hr>
        <p><small><small><em><pre>$Id$</pre></em></small></small>
       </td>
    </tr>
  </table>
</body>

</html>

