<?
//
// $Id$
//
$mode="";
   //
   // Set to "" for production, "x_" to debug.
   //
//
// Assign passed-in arguments to themselves to prevent 'undefined var' warnings later.
//
$first_name = $first_name;
$last_name = $last_name;
$$applicable_month_num = $applicable_month_num;
//
if ($mode) error_reporting(E_ALL);
//
require_once("f_oscarhomepageurl.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("f_bodyopen.phtml");
require_once("f_password.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_sshowavailsheetrecdetail.phtml");
require_once("f_oscarmailheaders.phtml");
//
$first_name = trim($first_name);
$last_name = trim($last_name);
//
$html = "<html>\n";
$html .= "<head><title>Retraction Request</title></head>\n";
$html .= "<body bgcolor=#FFFFFF>\n";
$html .= "<table align=center width=80%><tr><td>\n";
$html .= "<H6 ALIGN=CENTER>KVEO-IT-PROJECT<br><a href=" . OscarHomePageUrl() . ">OSCAR</a><br><a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></H6>\n";
$html .= "<H1 ALIGN=CENTER>Retraction Request</H1>\n";
$html .= "<hr>\n";
//
echo $html;
//
// Validate parameters.
//
if
   (
      ($first_name != "")
   and
      ($last_name != "")
   and
      ($applicable_month_num != "")
   )
// then
   {
   //
   // All required values are present.
   // Connect to the database.
   //
   mysql_connect("localhost","kalipso",Password());
   mysql_select_db("oscar");
   //
   // Generate the challenge message.
   //
   //             0        1         2         3         4         5         6         7
   //             123456789012345678901234567890123456789012345678901234567890123456789012
   $challenge = "";
   $challenge .= "The OSCAR system has received your request to retract your availability\n"
              .  "sheet submission(s).  This is the challenge message.\n\n"
              .  "The retraction process is not yet complete.  To complete the process,\n"
              .  "you will have to click the link near the bottom of this message.\n\n"
              .  "You have the following records on file with the OSCAR system for the\n"
              .  "month you specified.  If you continue with the retraction process, OSCAR\n"
              .  "will *permanently* delete these records:\n\n";
   //
   // Determine the three-letter abbreviation for the specified month.
   //
   $applicable_month_time = mktime(12,0,0,$applicable_month_num,1);
   $applicable_month_abbrev = strtoupper(date("M",$applicable_month_time));
   //
   // Generate the record detail to include in the challenge message.  This is so the requestor will know exactly what they're
   // about to retract.
   //
   $result = mysql_query
      (
      "select * from " . $mode . "avail_sheet"
      .  " where last_name = \"" . addslashes(addslashes($last_name)) . "\""
      .  "    and first_name = \"" . addslashes(addslashes($first_name)) . "\""
      .  "    and month = '$applicable_month_abbrev'"
      )
      or die("The query failed with error:  " . mysql_error());
   $num_rows = mysql_num_rows($result);
   $challenge .= "Found $num_rows ";
   if ($num_rows == 1)
      {
      $challenge .= "record.\n\n";
      }
   else
      {
      $challenge .= "records.\n\n";
      }
   if ($num_rows)
      {
      $record_index = 0;
      while ($row = mysql_fetch_array($result))
         {
         $record_index++;
         extract($row);
         $challenge .= sShowAvailSheetRecDetail
            (
            $timestamp,
            $first_name,
            $last_name,
            $email_addr,
            $squad,
            $month,
            $be_on_team_5,
            $be_on_team_30,
            $be_tda,
            $num_extras,
            $d1,$d2,$d3,$d4,$d5,$d6,$d7,$d8,$d9,$d10,$d11,$d12,$d13,$d14,$d15,$d16,$d17,$d18,$d19,$d20,$d21,$d22,$d23,$d24,$d25,$d26,$d27,$d28,$d29,$d30,$d31,
            $n1,$n2,$n3,$n4,$n5,$n6,$n7,$n8,$n9,$n10,$n11,$n12,$n13,$n14,$n15,$n16,$n17,$n18,$n19,$n20,$n21,$n22,$n23,$n24,$n25,$n26,$n27,$n28,$n29,$n30,$n31,
            $note,
            $expiration,
            1
            );
         if ($record_index < $num_rows)
            {
            $challenge .= "\n   ---\n\n";
            }
         //
         // Clear variables for next pass except for first_name and last_name (which by definition must match what we queried on, and
         // which we need for later), and the latest email_addr value (which we'll need later).
         //
         $timestamp = $squad = $month = $be_on_team_5 = $be_on_team_30 = $be_tda =
            $num_extras = "";
         $d1 = $d2 = $d3 = $d4 = $d5 = $d6 = $d7 = $d8 = $d9 = $d10 = $d11 = $d12 = $d13 = $d14 = $d15 = $d16 =
            $d17 = $d18 = $d19 = $d20 = $d21 = $d22 = $d23 = $d24 = $d25 = $d26 = $d27 = $d28 = $d29 = $d30 = $d31 = "";
         $n1 = $n2 = $n3 = $n4 = $n5 = $n6 = $n7 = $n8 = $n9 = $n10 = $n11 = $n12 = $n13 = $n14 = $n15 = $n16 =
            $n17 = $n18 = $n19 = $n20 = $n21 = $n22 = $n23 = $n24 = $n25 = $n26 = $n27 = $n28 = $n29 = $n30 = $n31 = "";
         $note = $expiration = "";
         }
      }
   //             0        1         2         3         4         5         6         7
   //             123456789012345678901234567890123456789012345678901234567890123456789012
   $challenge .= "\n"
              .  "To complete the retraction process and\n"
              .  "remove the above record(s) from the\n"
              .  "OSCAR system, click here:\n";
   $challenge .= OscarRootUrl()
      .  "/" . $mode . "retract.phtml?a="
      .  base64_encode($first_name)
      .  "&b="
      .  base64_encode($last_name)
      .  "&c="
      .  base64_encode($applicable_month_abbrev);
   $challenge .= "\n\n"
              .  "TO ABORT the retraction process, DO NOTHING.\n\n";
   //
   // Add sig lines.
   //
   $challenge .= "-- OSCAR\n"
              .  "-- Home page: " . OscarHomePageUrl() . "\n"
              .  "-- Sysadmin: " . RoleEmailAddress("") . "\n";
   //
   // Send the mail.
   //
   $result = mail($email_addr, "OSCAR Retraction Challenge", $challenge, OscarMailHeaders());
   //
   if ($result)
      {
      PutLibPhotoRandomPlaced("sasquatch",1,"right");
      echo "<p>The OSCAR system has sent the challenge message to <b>$email_addr</b>.&nbsp; When you receive the "
         .  "challenge message, follow the instructions contained therein.&nbsp; The retraction only takes effect once "
         .  "OSCAR receives a proper response to the challenge.</p>";
      echo "<p><b>Check your email periodically for the challenge message.</b></p>";
      echo "<p>If you have feedback about the technical aspects of this process, please contact the <a href=mailto:\""
         .  RoleEmailAddress("")
         .  "\">OSCAR System Administrator</a>.</p>";
      }
   else
      {
      //
      // Fill the page out with a warning and instructions.
      //
      ?>
      <h2><i>Error!</i></h2>
      <b>
      <blockquote>
         <p>The OSCAR system encountered an internal error while processing your request.  Please do the following:</p>
         <ul>
            <?
            echo "<li><p>Use another method (like email or telephone) to ask the <a href=mailto:\""
               .  RoleEmailAddress("schedule-coordinator")
               .  "\">VBDEMS Central Schedule Coordinator</a> to retract your submission(s).</p>";
            echo "<li><p>Let the <a href=mailto:" . RoleEmailAddress("") . "?subj=\"OSCAR Bug Report\">OSCAR System "
               .  "Administrator</a> know this error occurred.</p>";
            ?>
         </ul>
      </blockquote>            
      </b>
      <?
      }
   }
else
   {
   //
   // Fill the page out with a warning and instructions.
   //
   ?>
   <h2><i>Error!</i></h2>
   <b>
   <blockquote>
      <p>You did not supply one or more of the required parameters.&nbsp; You must supply values for these fields:</p>
      <ul>
         <li><p>First name</p>
         <li><p>Last name</p>
         <li><p>Applicable month</p>
      </ul>
      <p>Please press your browser's [<-- BACK] button to correct the problems.</p>
   </blockquote>            
   </b>
   <?
   echo "<p>If you have feedback about the technical aspects of this process, please contact the <a href=mailto:" . RoleEmailAddress("") . ">OSCAR System Administrator</a>.</p>";
   }
?>
<br clear=both>
<hr>
<p><small><small><em><pre>$Id$</pre></em></small></small>
</td>
</tr>
</table>
</body>
</html>
