<?
//
// $Id: gen-date.phtml 7092 2020-04-29 19:03:43Z kevinanlipscomb $
//
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
//
$ini = AppSettings();
$db_link = DbLink($ini);
$dbkalipso_link = DbkalipsoLink($ini);
?>
<html>

<head><title>OSCAR - Explanation of report generation times</title></head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
           <h6 align="center">
              KVEO-IT-PROJECT - <a href="javascript:close();">OSCAR SYSTEM</a></h6>
           <h1 align="center">Explanation of report generation times</h1>
        <hr>
        <? PutLibPhotoRandomPlaced($ini,$dbkalipso_link,"oscarsystem",1,"right"); ?>
        <p>Sometimes your report may have been generated before you actually requested it.</p>
        <p><i>How can this be?</i></p>
        <p>The OSCAR system <i>caches</i> the reports that it generates.&nbsp; This means that any generated report is kept
           in the OSCAR database for possible future use (until it reaches a logical expiration date).&nbsp; If another
           person had submitted a request that is identical to yours, and nothing in the OSCAR database has changed since
           that time, then the OSCAR system will simply point you to the existing report rather than generate a new one
           from scratch.&nbsp; Under such circumstances, the generation time on your report will be the time the report was
           generated for the <i>original</i> requestor.</p>
        <p>If, however, the OSCAR system has received submissions or retractions since the last similar report was 
           requested, the OSCAR system will generate a brand new report for you.&nbsp; In this case, the generation time on
           your report will match the time you made your request.</p>
        <p>This scheme assures that you receive up-to-date information in your report.&nbsp; It also conserves server
           resources while providing a useful security screening mechanism.<p>
        <p>If you have questions or concerns about the technical aspects of this process, feel free to contact the
           <a href=mailto:"<? echo RoleEmailAddress($db_link,""); ?>">OSCAR System Administrator</a>.</p>
        <hr>
        <p><small><small><em><pre>$Id: gen-date.phtml 7092 2020-04-29 19:03:43Z kevinanlipscomb $</pre></em></small></small></center></td>
    </tr>
  </table>
</body>

</html>
