<?
//
// $Id: get-report.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $
//
// Emulate register_globals on
if (!ini_get('register_globals'))
  {
  $superglobals = array($_SERVER,$_ENV,$_FILES,$_COOKIE,$_POST,$_GET);
  if (isset($_SESSION))
    {
    array_unshift($superglobals, $_SESSION);
    }
  foreach ($superglobals as $superglobal)
    {
    extract($superglobal, EXTR_SKIP);
    }
  }
//
// Assign incoming argument to itself to avoid "uninitialized variable" error later.
//
$digest = kix\k::Safe($digest,kix\k::PhpValueOf_safe_hint_type("HEX"));
//
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
//
$ini = AppSettings();
$db_link = DbLink($ini);
//
if ($ini[app][do_report_all_errors]) error_reporting(E_ALL);
//
$result = $db_link->query("select report from report_cache where digest = '$digest'")
   or die("The query failed with error:  " . mysqli_error($db_link));
if (mysqli_num_rows($result))
   {
   $row = mysqli_fetch_object($result);
   echo $row->report;
   }
else
   {
   ?>
   <html>
      <head><title>OSCAR - Get Report Failure</title></head>
      <? BodyOpen(); ?>
         <table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
            <tr>
               <td>
                  <h6 align="center">
                     KVEO-IT-PROJECT<br>
                     <a href="javascript:close();">OSCAR SYSTEM</a><br>
                     <a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></h6>
                  <H1 ALIGN="CENTER">Get Report Failure</H1>
                  <hr>
                  <h2><i>Sorry...</i></h2>
                  <blockquote>
                     <p>The OSCAR system could not locate the requested report.&nbsp; It has probably expired.</p>
                     <?
                     echo "<p>If you have feedback about the technical aspects of this process, please contact the <a href=mailto:" . RoleEmailAddress($db_link,"") . ">OSCAR System Administrator</a>.</p>";
                     ?>
                  </blockquote>            
                  <br clear=both>
                  <hr>
                  <p><small><small><em><pre>$Id: get-report.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $</pre></em></small></small>
               </td>
            </tr>
         </table>
      </body>
   </html>
   <?
   }
?>