<html>

<head>
<meta http-equiv="Content-Language" content="en-us">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>OSCAR Home Page</title>
</head>

<body>

<div align="center">
   <center>
   <table border="0" width="80%">
      <tr>
         <td width="100%">
            <div align="left">
               <table border="0" cellspacing="0" cellpadding="0" width="523">
                  <tr>
                     <td width="22">
                        <h5></h5>
                     </td>
                     <td align="center" width="25">
                        <h1>O</h1>
                     </td>
                     <td width="110">
                        <h2>nline</h2>
                     </td>
                     <td rowspan="5" width="20">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                     <td rowspan="5" width="336">
                        <p align="center">
                        Designed by volunteer emergency workers for manpower systems
                        that utilize geographically distributed personnel with
                        highly variable schedules.</p>
                     </td>
                  </tr>
                  <tr>
                     <td width="22">
                        <h5></h5>
                     </td>
                     <td align="center" width="25">
                        <h1>S</h1>
                     </td>
                     <td width="110">
                        <h2>ubmission</h2>
                     </td>
                  </tr>
                  <tr>
                     <td width="22">
                        <h5>and&nbsp;</h5>
                     </td>
                     <td align="center" width="25">
                        <h1>C</h1>
                     </td>
                     <td width="110">
                        <h2>ompilation</h2>
                     </td>
                  </tr>
                  <tr>
                     <td width="22">
                        <h5>of&nbsp;</h5>
                     </td>
                     <td align="center" width="25">
                        <h1>A</h1>
                     </td>
                     <td width="110">
                        <h2>vailability</h2>
                     </td>
                  </tr>
                  <tr>
                     <td width="22">
                        <h5></h5>
                     </td>
                     <td align="center" width="25">
                        <h1>R</h1>
                     </td>
                     <td width="110">
                        <h2>ecords</h2>
                     </td>
                  </tr>
               </table>
               <hr>
               <ul>
                  <li><a href="als-avail-sub-form.phtml">VBDEMS ALS availability
                     submission form</a></li>
               </ul>
               <p>Contact the <a href="mailto:infotech@kvrs.org">OSCAR
               Administrator</a>
            </div>
         </td>
      </tr>
   </table>
   </center>
</div>

</body>

</html>
