<html>

<head><title>OSCAR Home Page</title></head>

<? BodyOpen(); ?>

<div align="center">
   <center>
   <table border="0" width="80%">
      <tr>
         <td width="100%">
            <div align="left">
               <table border="0" cellspacing="0" cellpadding="0">
                  <tr>
                     <td rowspan="5"><a href=http://kalipso.phpwebhosting.com/present-photo.phtml?div_spec=2001-003&frame_num=096><img src=http://kalipso.phpwebhosting.com/div/2001-003/096-i.jpg border=2 width=288 height=192 alt="Oscar, the System Mascot"></a></td>
                     <td rowspan="5" width="20">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                     <td width="22">
                        <h5></h5>
                     </td>
                     <td align="center" width="25" bgcolor="#D0D0D0">
                        <h1>O</h1>
                     </td>
                     <td width="110">
                        <h2>nline</h2>
                     </td>
                     <td rowspan="5" width="20">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                     <td rowspan="5">
                        <p align="center"><small>
                        An open-source system designed by volunteers, for volunteers.</small></p>
                     </td>
                  </tr>
                  <tr>
                     <td width="22">
                        <h5></h5>
                     </td>
                     <td align="center" width="25" bgcolor="#D0D0D0">
                        <h1>S</h1>
                     </td>
                     <td width="110">
                        <h2>ubmission</h2>
                     </td>
                  </tr>
                  <tr>
                     <td width="22">
                        <h5>and&nbsp;</h5>
                     </td>
                     <td align="center" width="25" bgcolor="#D0D0D0">
                        <h1>C</h1>
                     </td>
                     <td width="110">
                        <h2>ompilation</h2>
                     </td>
                  </tr>
                  <tr>
                     <td width="22">
                        <h5>of&nbsp;</h5>
                     </td>
                     <td align="center" width="25" bgcolor="#D0D0D0">
                        <h1>A</h1>
                     </td>
                     <td width="110">
                        <h2>vailability</h2>
                     </td>
                  </tr>
                  <tr>
                     <td width="22">
                        <h5></h5>
                     </td>
                     <td align="center" width="25" bgcolor="#D0D0D0">
                        <h1>R</h1>
                     </td>
                     <td width="110">
                        <h2>ecords</h2>
                     </td>
                  </tr>
               </table>
               <hr>
               <h3>Actions</h3>
               <ul>
                  <li><a href="als-avail-sub-form.phtml">Submit an availability sheet.</a>
                  <li>Retrieve compiled availability lists.
               </ul>
               <h3>Administrivia</h3>
               <ul>
                  <li>See what's new.
                  <li>Learn how to become a <b>kveo-it-project</b> open-source developer.
                  <li><a href="mailto:infotech@kvrs.org">Contact the OSCAR Administrator.</a>
               </ul>
               <hr>
               <p><small><small><em><pre>$Id$</pre></em></small></small>
            </div>
         </td>
      </tr>
   </table>
   </center>
</div>

</body>

</html>
