<?
//
// $Id: meaning-of-vorp.phtml 7092 2020-04-29 19:03:43Z kevinanlipscomb $
//
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
//
$ini = AppSettings();
$dbkalipso_link = DbkalipsoLink($ini);
?>
<html>

<head><title>OSCAR - Meaning of VORP</title></head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
           <h6 align="center">
              KVEO-IT-PROJECT - <a href="javascript:close();">OSCAR SYSTEM</a></h6>
           <h1 align="center">What is a "VORP"?</h1>
        <hr>
        <? PutLibPhotoRandomPlaced($ini,$dbkalipso_link,"oscarsystem",1,"right"); ?>
        <p><b>VORP</b> stands for Volunteer Operations Response Personnel.&nbsp; VORPs include volunteers who staff the
        following EMS resources:</p>
        <ul>
           <li>Ambulances</li>
           <li>Squad trucks</li>
           <li>Volunteer Duty Field Supervisor unit</li>
           <li>Support 9</li>
           <li>Dive Team</li>
        </ul>
        <p>Tracking of VORPs is important because the numbers are strong indicators of the ability of our system's
        volunteer component to autonomously staff front-line response units.</p>
        <hr>
        <p><small><small><em><pre>$Id: meaning-of-vorp.phtml 7092 2020-04-29 19:03:43Z kevinanlipscomb $</pre></em></small></small></center></td>
    </tr>
  </table>
</body>

</html>

