<?
//
// $Id: modify.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $
//
// Emulate register_globals on
if (!ini_get('register_globals'))
  {
  $superglobals = array($_SERVER,$_ENV,$_FILES,$_COOKIE,$_POST,$_GET);
  if (isset($_SESSION))
    {
    array_unshift($superglobals, $_SESSION);
    }
  foreach ($superglobals as $superglobal)
    {
    extract($superglobal, EXTR_SKIP);
    }
  }
error_reporting(E_ALL);
//
require_once("f_bodyopen.phtml");
//
$ini = AppSettings();
$dbkalipso_link = DbkalipsoLink($ini);
?>
<html>

<head><title>OSCAR - Modify settings</title></head>

<? BodyOpen(); ?>
<table width="80%" align="center">
   <tr>
      <td>
         <table>
            <tr>
               <td>
                  <h6 align="center">
                     KVEO-IT-PROJECT<br>
                     <a href="javascript:close();">OSCAR SYSTEM</a>
                  </h6>
                  <h1 align="center">Modify settings</h1>
               </td>
               <td><? PutLibPhotoRandomPlaced($ini,$dbkalipso_link,"oscarsystem",1,"right"); ?></td>
            </tr>
         </table>
         <hr>
         The setting modification capability is provided for the benefit of OSCAR Authorities only.
         <blockquote>
            <table align=center bgcolor=#E8E8E8>
               <tr>
                  <td align=center valign=middle>
                     <small><i>To guard against misuse, the OSCAR system authenticates each modification request by
                        sending a "challenge message" to the registered email address of the appropriate authority.&nbsp;
                        Modifications only take effect once OSCAR receives a proper response to the challenge.</i></small>
                  </td>
               </tr>
            </table>
         </blockquote>
         Modifiable settings:
         <table cellspacing=10>
            <tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td align=right valign=top><b><font color="#C0C0C0">Squad participation</b></font></td><td valign=top>Specify which squads use OSCAR (Master OSCAR Authorities only).</td>
            <tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td align=right valign=top><b><a href=form-set-role-1.phtml>Roles</b></a></td><td valign=top>Specify schedule coordinators, escalation authorities, eGroup managers, etc.</td>
            <tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td align=right valign=top><b><a href=form-set-trust.phtml>Trusted users</a></b></td><td valign=top>Specify which users may directly receive compiled availability reports.</td>
         </table>
         <hr>
         <p><small><small><em><pre>$Id: modify.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $</pre></em></small></small>
      </td>
   </tr>
</table>
</body>

</html>
