<?
//
// $Id: perform-gen-challenge.phtml 7466 2021-04-10 00:29:54Z kevinanlipscomb $
//
// Emulate register_globals on
if (!ini_get('register_globals'))
  {
  $superglobals = array($_SERVER,$_ENV,$_FILES,$_COOKIE,$_POST,$_GET);
  if (isset($_SESSION))
    {
    array_unshift($superglobals, $_SESSION);
    }
  foreach ($superglobals as $superglobal)
    {
    extract($superglobal, EXTR_SKIP);
    }
  }
//
// Assign passed-in arguments to themselves to prevent 'undefined var' warnings later.
//
$last_name = $last_name;
$applicable_month_num = $applicable_month_num;
$coord_agency = $coord_agency;
//
if (isset($coord_agency)) $coord_agency = kix\k::Safe($coord_agency,kix\k::PhpValueOf_safe_hint_type("ALPHANUM"));
if (isset($first_name)) $first_name = trim(kix\k::Safe($first_name,kix\k::PhpValueOf_safe_hint_type("HUMAN_NAME")));
if (isset($last_name)) $last_name = trim(kix\k::Safe($last_name,kix\k::PhpValueOf_safe_hint_type("HUMAN_NAME")));
//
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_availlist.phtml");
require_once("f_plaintextofnote.phtml");
require_once("f_sshowavailsheetrecdetail.phtml");
require_once("f_oscarmailheaders.phtml");
//
$ini = AppSettings();
$db_link = DbLink($ini);
$dbkalipso_link = DbkalipsoLink($ini);
//
if ($ini[app][do_report_all_errors]) error_reporting(E_ALL);
//
$html = "<html>\n";
$html .= "<head><title>Reconfirmation/Retraction Request</title></head>\n";
$html .= "<body bgcolor=#FFFFFF>\n";
$html .= "<table align=center width=80%><tr><td>\n";
$html .= "<H6 ALIGN=CENTER>KVEO-IT-PROJECT<br><a href=\"javascript:close();\">OSCAR SYSTEM</a><br><a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></H6>\n";
$html .= "<H1 ALIGN=CENTER>Reconfirmation/Retraction Request</H1>\n";
$html .= "<hr>\n";
//
echo $html;
//
// Validate parameters.
//
if
   (
      ($first_name != "")
   and
      ($last_name != "")
   and
      ($applicable_month_num != "")
   and
      ($coord_agency != "")
   )
// then
   {
   //
   // All required values are present.
   // Generate the challenge message.
   //
   //             0        1         2         3         4         5         6         7
   //             123456789012345678901234567890123456789012345678901234567890123456789012
   $challenge = "";
   $challenge .= "Someone (possibly you) sent a request to OSCAR to reconfirm or retract\n"
              .  "your $coord_agency availability sheet submission(s).\n\n"
              .  "If your intention is to retract these submissions, be advised that\n"
              .  "RETRACTION IS NOT YET COMPLETE.  To complete the retraction process, you\n"
              .  "must click the link near the bottom of this message.\n\n"
              .  "Retracting availabilities after the monthly submission deadline may have\n"
              .  "NO EFFECT, and you may still be held responsible for covering your\n"
              .  "assigned shifts.  You MUST contact your scheduling officer directly when\n"
              .  "retracting after the monthly submission deadline.\n\n"
              .  "You have the following records on file with the OSCAR system for the\n"
              .  "month and agency you specified:\n\n";
   //
   // Determine the three-letter abbreviation for the specified month.
   //
   $applicable_month_time = mktime(12,0,0,$applicable_month_num,1);
   $applicable_month_abbrev = strtoupper(date("M",$applicable_month_time));
   //
   // Generate the record detail to include in the challenge message.  This is so the requestor will know exactly what 
   // they're about to retract.
   //
   $result = $db_link->query
      (
      "select * from avail_sheet"
      .  " where month = '$applicable_month_abbrev'"
      .  "    and last_name = \"" . addslashes(addslashes($last_name)) . "\""
      .  "    and first_name = \"" . addslashes(addslashes($first_name)) . "\""
      .  "    and coord_agency = '$coord_agency'"
      )
      or die("The query failed with error:  " . mysqli_error($db_link));
   $num_rows = mysqli_num_rows($result);
   $challenge .= "Found $num_rows ";
   if ($num_rows == 1)
      {
      $challenge .= "record.\n\n";
      }
   else
      {
      $challenge .= "records.\n\n";
      }
   if ($num_rows)
      {
      $record_index = 0;
      while ($row = mysqli_fetch_array($result))
         {
         $record_index++;
         $timestamp = $month = $be_on_team_5 = $be_on_team_30 = $be_on_team_air = $be_tda = $be_als = $be_third = $be_nondriver = 
            $be_needing_driver = $num_extras = $squad = "";
         $d1 = $d2 = $d3 = $d4 = $d5 = $d6 = $d7 = $d8 = $d9 = $d10 = $d11 = $d12 = $d13 = $d14 = $d15 = $d16 =
            $d17 = $d18 = $d19 = $d20 = $d21 = $d22 = $d23 = $d24 = $d25 = $d26 = $d27 = $d28 = $d29 = $d30 = $d31 = "";
         $n1 = $n2 = $n3 = $n4 = $n5 = $n6 = $n7 = $n8 = $n9 = $n10 = $n11 = $n12 = $n13 = $n14 = $n15 = $n16 =
            $n17 = $n18 = $n19 = $n20 = $n21 = $n22 = $n23 = $n24 = $n25 = $n26 = $n27 = $n28 = $n29 = $n30 = $n31 = "";
         $note = $expiration = "";
         extract($row);
         $challenge .= sShowAvailSheetRecDetail
            (
            $timestamp,
            $first_name,
            $last_name,
            $email_addr,
            $squad,
            $month,
            $be_on_team_5,
            $be_on_team_30,
            $be_on_team_air,
            $be_tda,
            $be_als,
            $num_extras,
            $d1,$d2,$d3,$d4,$d5,$d6,$d7,$d8,$d9,$d10,$d11,$d12,$d13,$d14,$d15,$d16,$d17,$d18,$d19,$d20,$d21,$d22,$d23,$d24,$d25,$d26,$d27,$d28,$d29,$d30,$d31,
            $n1,$n2,$n3,$n4,$n5,$n6,$n7,$n8,$n9,$n10,$n11,$n12,$n13,$n14,$n15,$n16,$n17,$n18,$n19,$n20,$n21,$n22,$n23,$n24,$n25,$n26,$n27,$n28,$n29,$n30,$n31,
            $note,
            $expiration,
            1,
            $coord_agency,
            $be_needing_driver,
            $be_nondriver,
            $be_third
            );
         if ($record_index < $num_rows)
            {
            $challenge .= "\n   ---\n\n";
            }
         }
      }
   //             0        1         2         3         4         5         6         7
   //             123456789012345678901234567890123456789012345678901234567890123456789012
   $challenge .= "\n"
              .  "If you want to RETRACT (*permanently*\n"
              .  "remove) the above record(s) from the\n"
              .  "OSCAR system, click here:\n"
              .  $ini[server][root_url]
              .  "/retract.phtml?a="
              .  base64_encode($first_name)
              .  "&b="
              .  base64_encode($last_name)
              .  "&c="
              .  base64_encode($applicable_month_num)
              .  "&d="
              .  base64_encode($email_addr)
              .  "&e="
              .  base64_encode($coord_agency)
              .  "\n\n"
              .  "To let OSCAR keep the above records, DO NOTHING.\n\n";
   //
   // Add sig lines.
   //
   $challenge .= "-- OSCAR\n"
              .  "-- Home page: " . $ini[server][host_url] . "/" . $ini[app][superapp] . "\n"
              .  "-- Sysadmin: " . RoleEmailAddress($db_link,"") . "\n";
   //
   if ($result)
      {
      PutLibPhotoRandomPlaced($ini,$dbkalipso_link,"oscarsystem",1,"right");
      //
      if ($num_rows)
        {
        // Send the mail.
        //
        //
        kix\k::SmtpMailSend
          (
          RoleEmailAddress($db_link,""), //from
          $email_addr, //to
          "OSCAR Reconfirm/Retract Challenge", //subject
          $challenge, //message_string
          false, //be_html
          "", //cc
          "", //bcc
          RoleEmailAddress($db_link,"") //reply_to
          );
        echo "<p>The OSCAR system has sent the reconfirmation/challenge message to <b>$email_addr</b>.</p>";
        echo "<p>If you intend to retract your submissions, be advised that <u>retraction is not yet complete</u>.&nbsp; "
           .  "Check your email periodically for the challenge message, which contains instructions for completing the "
           .  "retraction process.</b></p>";
        }
      else
        {
        echo "<p>No records found.</p>";
        }
      echo "<p>If you have feedback about the technical aspects of this process, please contact the <a href=mailto:\""
          .  RoleEmailAddress($db_link,"")
          .  "\">OSCAR System Administrator</a>.</p>";
      }
   else
      {
      //
      // Fill the page out with a warning and instructions.
      //
      ?>
      <h2><i>Error!</i></h2>
      <b>
      <blockquote>
         <p>The OSCAR system encountered an internal error while processing your request.  Please do the following:</p>
         <ul>
            <?
            echo "<li><p>Use another method (like email or telephone) to ask the <a href=mailto:\""
               .  RoleEmailAddress($db_link,"schedule-coordinator",$coord_agency)
               .  "\">$coord_agency Schedule Coordinator</a> to reconfirm or retract your submission(s).</p>";
            echo "<li><p>Let the <a href=mailto:" . RoleEmailAddress($db_link,"") . "?subj=\"OSCAR Bug Report\">OSCAR System "
               .  "Administrator</a> know this error occurred.</p>";
            ?>
         </ul>
      </blockquote>
      </b>
      <?
      }
   }
else
   {
   //
   // Fill the page out with a warning and instructions.
   //
   ?>
   <h2><i>Error!</i></h2>
   <b>
   <blockquote>
      <p>You did not supply one or more of the required parameters.&nbsp; You must supply values for these fields:</p>
      <ul>
         <li><p>First name</p>
         <li><p>Last name</p>
         <li><p>Applicable month</p>
         <li><p>Coordinating agency</p>
      </ul>
      <p>Please press your browser's [<--&nbsp;BACK] button to correct the problems.</p>
   </blockquote>            
   </b>
   <?
   }
?>
<br clear=both>
<hr>
<p><small><small><em><pre>$Id: perform-gen-challenge.phtml 7466 2021-04-10 00:29:54Z kevinanlipscomb $</pre></em></small></small>
</td>
</tr>
</table>
</body>
</html>
