<?
//
// $Id: perform-prep-mod-agency.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $
//
// Assign passed-in arguments to themselves to prevent 'undefined var' warnings later.
//
$enumeral = $enumeral;
$current_be_active = $current_be_active;
//
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_oscarmailheaders.phtml");
//
$ini = AppSettings();
$db_link = DbLink($ini);
$dbkalipso_link = DbkalipsoLink($ini);
//
if ($ini[app][do_report_all_errors]) error_reporting(E_ALL);
//
$html = "<html>\n";
$html .= "<head><title>Toggle Squad Participation</title></head>\n";
$html .= "<body bgcolor=#FFFFFF>\n";
$html .= "<table align=center width=80%><tr><td>\n";
$html .= "<H6 ALIGN=CENTER>KVEO-IT-PROJECT<br><a href=\"javascript:close();\">OSCAR SYSTEM</a><br><a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></H6>\n";
$html .= "<H1 ALIGN=CENTER>Toggle Squad Participation</H1>\n";
$html .= "<hr>\n";
//
echo $html;
//
// Validate parameters.
//
if 
   (
      ($enumeral != "")
   and
      ($current_be_active != "")
   )
// then
   {
   //
   // All required values are present.
   // Generate a random token and enter a record in the pend_mod_agency table.
   //
   if ($current_be_active == "TRUE")
      {
      $new_be_active = "FALSE";
      }
   else
      {
      $new_be_active = "TRUE";
      }
   srand((double)microtime()*1000000); 
   $raw_token =  rand() . " $enumeral $new_be_active";
   $result = $db_link->query("select md5(\"$raw_token\") as token")
      or die("Token generation failed with error: " . mysqli_error($db_link));
   extract(mysqli_fetch_array($result));
   $db_link->query
      (
      "insert into pend_mod_agency set token='$token' "
      .  ", enumeral='$enumeral' "
      .  ", new_be_active='$new_be_active' "
      )
      or die("Insert failed with error: " . mysqli_error($db_link));
   //
   // Generate the challenge message.
   //
   //             0        1         2         3         4         5         6         7
   //             123456789012345678901234567890123456789012345678901234567890123456789012
   $challenge = "";
   $challenge .= "Someone at IP address $REMOTE_ADDR (possibly you) wants to change a\n"
              .  "squad's participation status in the OSCAR system.  Specifically, OSCAR\n"
              .  "received a request to change this agency:\n\n"
              .  "   $enumeral\n\n"
              .  "to this status:\n\n"
              .  "   ";
   if ($current_be_active == "TRUE") $challenge .= "NON";
   $challenge .= "PARTICIPANT.\n\n"
              .  "THE CHANGE IS NOT YET COMPLETE.  To\n"
              .  "complete the process, click here:\n"
              .  $ini[server][root_url]
              .  "/perform-mod-agency.phtml?token=$token\n\n"
              .  "To ABORT the change, DO NOTHING.\n\n";
   //
   // Add sig lines.
   //
   $challenge .= "-- OSCAR\n"
              .  "-- Home page: " . $ini[server][host_url] . "/" . $ini[app][superapp] . "\n"
              .  "-- Sysadmin: " . RoleEmailAddress($db_link,"") . "\n";
   //
   // Send the mail.
   //
   $email_addr = RoleEmailAddress($db_link,"master");
   kix\k::SmtpMailSend
     (
     RoleEmailAddress($db_link,""), //from
     $email_addr, //to
     "OSCAR Modification Challenge", //subject
     $challenge, //message_string
     false, //be_html
     "", //cc
     "", //bcc
     RoleEmailAddress($db_link,"") //reply_to
     );
   $result = true;
   //
   if ($result)
      {
      PutLibPhotoRandomPlaced($ini,$dbkalipso_link,"oscarsystem",1,"right");
      echo "<p>The OSCAR system has sent a challenge message to <b>$email_addr</b>.</p>";
      echo "<p><b>Check your email periodically for the challenge message, which contains instructions for completing the "
         . "modification process.</b></p>"
         . "Related destinations:\n"
         . "<ul>\n"
         . "   <li><a href=form-set-agency.phtml>Toggle Squad Participation page</a></li>\n"
         . "   <li><a href=modify.phtml>Modify other OSCAR settings</a></li>\n"
         . "   <li><a href=index.phtml>Main OSCAR page</a></li>\n"
         . "</ul>\n";
      echo "<p>If you have feedback about the technical aspects of this process, please contact the <a href=mailto:\""
         .  RoleEmailAddress($db_link,"")
         .  "\">OSCAR System Administrator</a>.</p>";
      }
   else
      {
      //
      // Fill the page out with a warning and instructions.
      //
      ?>
      <h2><i>Error!</i></h2>
      <b>
      <blockquote>
         <p>The OSCAR system encountered an internal error while processing your request.&nbsp; Contact the
            <a href=mailto:"<? echo RoleEmailAddress($db_link,""); ?>">OSCAR System Administrator</a>.</p>
      </blockquote>            
      </b>
      <?
      }
   }
else
   {
   //
   // Fill the page out with a warning and instructions.
   //
   ?>
   <h2><i>Error!</i></h2>
   <b>
   <blockquote>
      <p>Invalid parameters</p>
   </blockquote>            
   </b>
   <?
   }
?>
<br clear=both>
<hr>
<p><small><small><em><pre>$Id: perform-prep-mod-agency.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $</pre></em></small></small>
</td>
</tr>
</table>
</body>
</html>
