<?
//
// $Id: perform-hand-off.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $
//
$month_abbrev = kix\k::Safe($month_abbrev,kix\k::PhpValueOf_safe_hint_type("ALPHA"));
//
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_availlist.phtml");
require_once("f_plaintextofnote.phtml");
require_once("f_sshowavailsheetrecdetail.phtml");
require_once("f_oscarmailheaders.phtml");
require_once("f_formattednoteappendage.phtml");
require_once("f_htmlofnote.phtml");
//
$ini = AppSettings();
$db_link = DbLink($ini);
$dbkalipso_link = DbkalipsoLink($ini);
//
if ($ini[app][do_report_all_errors]) error_reporting(E_ALL);
//
unset($HTTP_POST_VARS['month_abbrev']);
   //
   // The above unconventional "unset" operation is appropriate for this routine because the remainder of this routine
   // treats HTTP_POST_VARS as an array of unknown key-value pairs.  By "unsetting" the only *known* key-value pair
   // -- $month_abbrev -- we avoid having to scan past it later.
   //
?>
<html>

<head><title>OSCAR - Relay results</title></head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
        <table><tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>
           <? PutLibPhotoRandomPlaced($ini,$dbkalipso_link,"oscarsystem",1); ?>
        </td><td>
           <h6 align="center">
              KVEO-IT-PROJECT<br>
              <a href="javascript:close();">OSCAR SYSTEM</a><br>
              <a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></h6>
           <h1 align="center">Relay Results</h1>
        </td></tr></table>
        <hr>
<?
//
// $HTTP_POST_VARS holds the array of argument-value pairs that are sent to this page via HTTP's POST method.  From the
// EMS schedule-coordinator 'Relay unused' form of our perform-gen-report.phtml script, a sample representation of
// $HTTP_POST_VARS is:
//
//    QWxiZXJ0c29u-SG9sbGll-d3=1
//    QmFrZXI=-UmljaGFyZA==-d7=1
//    QmFrZXI=-UmljaGFyZA==-n9=1
//    QnVkeQ==-S2F0aHk=-NONE=1
//    U3Rlcmxpbmc=-Tm9ybWFu-n8=1
//    VGFt-S2V2aW4=-d4=1
//
// The argument names indicate the availabilities allocated by the EMS schedule-coordinator, in base64_encoded form.  When
// decoded later by this script, they could be written as:
//
//    Albertson-Hollie-d3=1
//    Baker-Richard-d7=1
//    Baker-Richard-n9=1
//    Budy-Kathy-NONE=1
//    Finch-Linda-n8=1
//    Tam-Kevin-d4=1
//
// The semantics of the first two fields are:
//
//    LastName-FirstName
//
// The third field is 'd' for day or 'n' for night followed by the day-of-the-month.  So 'd3' is the day of the 3rd and
// 'n9' is the night of the 9th.  These are the availabilities that should *not* be relayed to the squad-level 
// coordinators.The third field might also be 'NONE' to indicate that EMS does not intend to allocate any of the member's 
// availabilities.  The '=1' is the value part, which we ignore.
//

//
// Setup temp tables
//
//    INTERMEDIATE_AVAIL_SHEET table
//
//       Do this lazily.  Instead of maintaining table structure code here, just do a create...select to assure that the
//       structure of the temp table is an exact match for the structure of the master table throughout the lifetime of the
//       OSCAR project.
//
$db_link->query
   (
   "create temporary table intermediate_avail_sheet "
   .  " select * from avail_sheet "
   .  "    where month='$month_abbrev' and coord_agency='EMS' "
   )
   or die("Creation of temp table intermediate_avail_sheet failed with error: " . mysqli_error($db_link));
//
//    MISSING_RELAY_TARGET table
//
$db_link->query
   (
   "create temporary table missing_relay_target "
   .  " ( "
   .  " last_name varchar(32) NOT NULL, "
   .  " first_name varchar(32) NOT NULL, "
   .  " PRIMARY KEY (last_name,first_name) "
   .  " ) "
   )
   or die("Creation of temp table missing_relay_target failed with error: " . mysqli_error($db_link));
//
// Initialize $census
//
$result = $db_link->query
   (
   "select coord_agency, count(*) as num_sheets from avail_sheet "
   .  "    where coord_agency != 'EMS' "
   .  "    group by coord_agency "
   )
   or die("Census initialization failed with error: " . mysqli_error($db_link));
while ($row = mysqli_fetch_array($result))
   {
   extract($row);
   $census[$coord_agency] = $num_sheets;
   }
//
// PHP's 'foreach' construct walks an array.  The 'as' option provides a way to extract both the argument name (which is
// the part that's really of importance to us here) as well as the value (=1), which we simply ignore.
//
$ignore_mask = "";
//
foreach ($HTTP_POST_VARS as $encoded_avail_spec => $value)
   {
   //
   // "Explode" (break apart) the $encoded_avail_spec into its constituent parts.
   //
   list($encoded_last_name,$encoded_first_name,$parameter) = explode("-",$encoded_avail_spec);
   //
   // Make sure that this entry is worth processing.
   //
   if (
         (
            ("$encoded_last_name-$encoded_first_name" != $ignore_mask)
         and
            ($value)
         )
      or
         (
            ("$encoded_last_name-$encoded_first_name" == $ignore_mask)
         and
            ($parameter == "COMMENT")
         )
      )
   // then
      {
      //
      // Decode the encoded parts.
      //
      $target_last_name = trim(kix\k::Safe(base64_decode($encoded_last_name),kix\k::PhpValueOf_safe_hint_type("HUMAN_NAME")));
      $target_first_name = trim(kix\k::Safe(base64_decode($encoded_first_name),kix\k::PhpValueOf_safe_hint_type("HUMAN_NAME")));
      //
      // Make sure there's still an avail_sheet that matches what EMS was working with.
      //
      $sql = "select * from intermediate_avail_sheet "
         .  " where last_name='$target_last_name' "
         .  "    and first_name='$target_first_name' "
         .  " order by timestamp desc limit 1 ";  // to assure that we get the latest one, same as the sched coord saw
      //
      $result = $db_link->query($sql) or die("Retrieval of an intermediate_avail_sheet failed with error: " & mysqli_error($db_link));
      //
      if (!mysqli_num_rows($result))
         {
         //
         // No avail_sheet matched what EMS was working with.  Store key info for use in a later warning.
         //
         $db_link->query
            (
            "insert ignore into missing_relay_target "
            .  " set last_name='$target_last_name', "
            .  "    first_name='$target_first_name' "
            )
            or die("Insert into table missing_relay_target failed with error: " . mysqli_error($db_link));
         }
      else
         {
         //
         // One or more matching records found.
         //
         extract(mysqli_fetch_array($result));
         if ($squad != "ERS")  // Don't relay any ERS records.
            {
            $sql = "update intermediate_avail_sheet "
               .  " set timestamp=timestamp, "  // Preserve timestamps at all costs.
               .  "    be_needing_driver='$be_als', "
               .  "    coord_agency='Rescue$squad' ";
            //
            $note_appendage_ems_comment = "";
            if ($parameter == "NONE")
               {
               //
               // The member's availabilities should be relayed to his or her squad unaltered.  Also, no further entries in
               // HTTP_POST_VARS should be considered for this member.
               //
               $ignore_mask = "$encoded_last_name-$encoded_first_name";
               }
            elseif ($parameter == "COMMENT")
               {
               if (!strstr($note,"mesg(COMMENT)"))
                  {
                  $note_appendage_ems_comment = FormattedNoteAppendage
                     (
                     "INFO",  // condition
                     "COMMENT",  // mnemonic
                     $value,
                     strtoupper(RoleEmailAddress($db_link,"schedule-coordinator","EMS"))
                     );
                  }
               }
            else
               {
               //
               // The parameter denotes the actual field in the record that should be blanked out.
               //
               $sql .= ", $parameter='' ";
               }
            //
            $note_appendage_relay = "";
            if (!strstr($note,"mesg(RELAY)"))
               {
               $note_appendage_relay = FormattedNoteAppendage
                  (
                  "INFO",  // condition
                  "RELAY",  // mnemonic
                  "Relayed from EMS"
                  );
               }
            $note_appendage_emtorst = "";
            if (($be_als == 'FALSE') && (!strstr($note,"mesg(EMTORST)")))
               {
               //
               // A member (such as a Shock-Trauma Tech) who is NOT ALS for EMS (zone car) purposes might be ALS for squad 
               // (ambulance) purposes.  OSCAR currently has no way of knowing if the member is an ST or not, so a caution 
               // note is in order.
               //
               $note_appendage_emtorst = FormattedNoteAppendage
                  (
                  "WARNING",  // condition
                  "EMTORST",  // mnemonic
                  "EMT versus ST status is unknown to OSCAR on records relayed from EMS."
                  );
               }
            if ($note_appendage = ($note_appendage_ems_comment . $note_appendage_relay . $note_appendage_emtorst))
               {
               $sql .= ", note='" . addslashes($note) . $note_appendage . "'";
               }
            $sql .= " where last_name='$target_last_name' "
               .  "    and first_name='$target_first_name' ";
            $db_link->query($sql) or die("Intermediate relay update failed with error: " . mysqli_error($db_link));
            }
         }
      }
   $value = "";
   }
//
$relay_select_clause = "select * from intermediate_avail_sheet where coord_agency != 'EMS'";
   //
   // Any record so selected must be one of the ones modified by the foreach loop above, because when
   // intermediate_avail_sheet was created, we only put records whose coord_agency = 'EMS'.
   //
//
$db_link->query("insert into avail_sheet " . $relay_select_clause)
   or die("Relay insertion failed with error: " . mysqli_error($db_link));
//
$num_rows_affected = mysqli_affected_rows($db_link);
//
// Display indications of successful relays.
//
echo "<p>Your relay operation has been processed as follows:</p>\n"
   . "<ol>\n"
   . "<li><p><b>Data handling:</b>&nbsp; Availability sheets for the following personnel -- minus the allocations you made "
   . "-- were successfully processed for use by squad schedule coordinators as indicated.&nbsp; The availability sheets "
   . "originally submitted to EMS have not been altered.</p>\n"
   . "<table border=1 cellspacing=0 cellpadding=3>\n"
   . "<tr bgcolor=#D0D0D0>\n"
   . "   <td><small>#</small></td>\n"
   . "   <td><small>Last name</small></td>\n"
   . "   <td><small>First name</small></td>\n"
   . "   <td><small>Squad</small></td>\n"
   . "</tr>\n";
//
$result = $db_link->query($relay_select_clause)
   or die("Simple retrieval using relay_select_clause failed with error: " . mysqli_error($db_link));
$n = 1;
while ($row = mysqli_fetch_array($result))
   {
   extract($row);
   echo "<tr>\n"
      . "   <td><small>$n</small></td>\n"
      . "   <td><small>$last_name</small></td>\n"
      . "   <td><small>$first_name</small></td>\n"
      . "   <td><small>$squad</small></td>\n"
      . "</tr>";
   $n++;
   }
echo "</table>\n";
//
if (($num_already_relayed = ($n - 1 - $num_rows_affected)) > 0)
   {
   echo "<p><b>Note</b> that <b>$num_already_relayed</b> of these sheets had apparently been relayed before and ";
   if ($num_already_relayed == 1)
      {
      echo "was ";
      }
   else
      {
      echo "were ";
      }
   echo "not actually relayed again.</p>\n";
   }
echo "<p>&nbsp;</p></li>\n";
//
// Generate appropriate notifications for squad schedule coordinators and display progress indications.
//
echo "<li><p><b>Notifications:</b>&nbsp; Email notifications have been sent to squad schedule coordinators as "
   . "follows:</p>\n"
   . "<table border=1 cellspacing=0 cellpadding=3>\n"
   . "<tr bgcolor=#D0D0D0>\n"
   . "   <td><small>Squad</small></td>\n"
   . "   <td><small>Relayed sheets</small></td>\n"
   . "   <td><small>Notification sent...</small></td>\n"
   . "   <td><small>Pager alerted?</small></td>\n"
   . "</tr>\n";
//
//    RELAY NOTIFICATIONS
//
//    First, determine which squads actually received relayed sheets.
//
$result = $db_link->query
   (
   "select coord_agency, count(*) as num_sheets from avail_sheet "
   .  " where coord_agency != 'EMS' "
   .  " group by coord_agency "
   )
   or die("Determination of num_sheets per agency failed with error: " . mysqli_error($db_link));
while ($row = mysqli_fetch_array($result))
   {
   extract($row);
   if (!array_key_exists($coord_agency,$census)) $census[$coord_agency] = 0;
   if (($num_relayed_sheets = ($num_sheets - $census[$coord_agency])) > 0)
      {
      //
      // Insert a record into the relay journal.  Although not mentioned in the below insert statement, each of the relay
      // journal's records also has a timestamp, which is implicitly set to now-time during the insert.
      //
      $db_link->query
         (
         "insert into relay_journal "
         .  " set month='$month_abbrev' "
         .  "    , coord_agency='$coord_agency' "
         )
         or die("Insertion of relay journal record for agency $coord_agency failed with error: " . mysqli_error($db_link));
      //
      if (!mysqli_affected_rows($db_link))
         {
         echo "<p><b>" . HtmlOfNote
            (
            FormattedNoteAppendage
               (
               "ERROR",
               "JOUENTFAI",
               "Insertion of relay journal record for agency $coord_agency failed.  The $coord_agency schedule "
               .  "coordinator may not be able to see relayed records in his or her report.  To workaround this error, the "
               .  "EMS Schedule Coordinator should submit a single availability record directly to $coord_agency for an "
               .  "Imaginary Person."
               )
            )
            . "</b></p>\n";
         }
      //
      // Determine whether or not the agency is an OSCAR participant.
      //
      $participation_test_result = $db_link->query
         ("select 1 from agency where enumeral='$coord_agency' and be_active='TRUE'")
         or die("OSCAR participant check failed for $coord_agency with error: " . mysqli_error($db_link));
      if (mysqli_num_rows($participation_test_result))
         {
         //
         // Agency IS an OSCAR participant.  Send a notice directly to the squad schedule coordinator.
         //
         $relay_notice_recipient = RoleEmailAddress($db_link,"schedule-coordinator",$coord_agency);
         $relay_notice_subject = "Relay notice from EMS";
         //               0        1         2         3         4         5         6         7
         //               123456789012345678901234567890123456789012345678901234567890123456789012
         $relay_notice = "Dear $coord_agency Schedule Coordinator,\n\n"
                       . "I have used OSCAR to relay $num_relayed_sheets availability sheet(s) to $coord_agency.\n\n"
                       . "Please click here to retrieve an up-to-date\n"
                       . "compiled availability report:\n"
                       . $ini[server][root_url] . "/perform-gen-report.phtml"
                       . "?name=" . $coord_agency . "SchedCoord"
                       . "&email_addr=$relay_notice_recipient"
                       . "&applicable_month_num=" . date("n",strtotime("$month_abbrev 1"))
                       . "&coord_agency=$coord_agency"
                       . "&team_filter=everyone"
                       . "&shift_filter=all"
                       . "&relay=TRUE\n\n"
                       . "If you have any questions, please send me a reply.\n\n";
         //
         // Add sig lines.
         //
         $relay_notice .= "-- EMS Schedule Coordinator (via OSCAR)\n";
         $relay_notice .= "-- " . RoleEmailAddress($db_link,"schedule-coordinator","EMS") . "\n";
         //
         kix\k::SmtpMailSend
           (
           RoleEmailAddress($db_link,"schedule-coordinator","EMS"), //from
           $relay_notice_recipient, //to
           $relay_notice_subject, //subject
           $relay_notice, //message_string
           false, //be_html
           "", //cc
           "", //bcc
           RoleEmailAddress($db_link,"schedule-coordinator","EMS") //reply_to
           );
         //
         if (($relay_page_recipient = RoleEmailAddress($db_link,"schedule-coordinator-pager",$coord_agency)) != '')
            {
            $relay_page_headers = "From: " . RoleEmailAddress($db_link,"schedule-coordinator","EMS") . "\r\n";
            $relay_page_notice = "Check email for OSCAR RELAY notice";
            kix\k::SmtpMailSend
              (
              RoleEmailAddress($db_link,""), //from
              $relay_page_recipient, //to
              '', //subject
              $relay_page_notice, //message_string
              false, //be_html
              "", //cc
              "", //bcc
              '' //reply_to
              );
            $be_alerted = 'YES';
            }
         else
            {
            $be_alerted = 'no known pgr';
            }
         //
         echo "<tr>\n"
            . "   <td><small>$coord_agency</small></td>\n"
            . "   <td align=center><small>$num_relayed_sheets</small></td>\n"
            . "   <td><small>Direct to $relay_notice_recipient</small></td>\n"
            . "   <td><small>$be_alerted</small></td>\n"
            . "</tr>\n";
         }
      else
         {
         //
         // Agency is NOT an OSCAR participant.  Send a message to the EMS schedule coordinator that he can forward as 
         // appropriate.
         //
         $relay_report_recipient = RoleEmailAddress($db_link,"schedule-coordinator","EMS");
         $relay_report_subject = "OSCAR availability relay for $coord_agency";
         //               0        1         2         3         4         5         6         7
         //               123456789012345678901234567890123456789012345678901234567890123456789012
         $relay_report = "For indirect delivery to $coord_agency schedule coordinator...\n\n\n"
                       . "EMS -> $coord_agency RELAY REPORT\n"
                       . "---------------------------------\n";
         //
         $report_query_result = $db_link->query
            (
            "select * from intermediate_avail_sheet where coord_agency = '$coord_agency' order by last_name, first_name"
            )
            or die("Indirect report query failed with error:  " . mysqli_error($db_link));
         $num_rows = mysqli_num_rows($report_query_result);
         $relay_report .= "Found $num_rows ";
         if ($num_rows == 1)
            {
            $relay_report .= "record.\n\n";
            }
         else
            {
            $relay_report .= "records.\n\n";
            }
         if ($num_rows)
            {
            $record_index = 0;
            while ($row = mysqli_fetch_array($report_query_result))
               {
               $record_index++;
               $timestamp = $month = $be_on_team_5 = $be_on_team_30 = $be_tda = $be_als = $be_third = $be_nondriver = 
                  $be_needing_driver = $num_extras = $squad = "";
               $d1 = $d2 = $d3 = $d4 = $d5 = $d6 = $d7 = $d8 = $d9 = $d10 = $d11 = $d12 = $d13 = $d14 = $d15 = $d16 =
                  $d17 = $d18 = $d19 = $d20 = $d21 = $d22 = $d23 = $d24 = $d25 = $d26 = $d27 = $d28 = $d29 = $d30 = $d31 = "";
               $n1 = $n2 = $n3 = $n4 = $n5 = $n6 = $n7 = $n8 = $n9 = $n10 = $n11 = $n12 = $n13 = $n14 = $n15 = $n16 =
                  $n17 = $n18 = $n19 = $n20 = $n21 = $n22 = $n23 = $n24 = $n25 = $n26 = $n27 = $n28 = $n29 = $n30 = $n31 = "";
               $note = $expiration = "";
               extract($row);
               $relay_report .= sShowAvailSheetRecDetail
                  (
                  $timestamp,
                  $first_name,
                  $last_name,
                  $email_addr,
                  $squad,
                  $month,
                  $be_on_team_5,
                  $be_on_team_30,
                  $be_tda,
                  $be_als,
                  $num_extras,
                  $d1,$d2,$d3,$d4,$d5,$d6,$d7,$d8,$d9,$d10,$d11,$d12,$d13,$d14,$d15,$d16,$d17,$d18,$d19,$d20,$d21,$d22,$d23,$d24,$d25,$d26,$d27,$d28,$d29,$d30,$d31,
                  $n1,$n2,$n3,$n4,$n5,$n6,$n7,$n8,$n9,$n10,$n11,$n12,$n13,$n14,$n15,$n16,$n17,$n18,$n19,$n20,$n21,$n22,$n23,$n24,$n25,$n26,$n27,$n28,$n29,$n30,$n31,
                  $note,
                  $expiration,
                  1,
                  $coord_agency,
                  $be_needing_driver,
                  $be_nondriver,
                  $be_third
                  );
               if ($record_index < $num_rows)
                  {
                  $relay_report .= "\n   ---\n\n";
                  }
               }
            }
         //
         // Add sig lines.
         //
         $relay_report .= "\n\n-- End of OSCAR report ---\n";
         //
         kix\k::SmtpMailSend
           (
           RoleEmailAddress($db_link,""), //from
           $relay_report_recipient, //to
           $relay_report_subject, //subject
           $relay_report, //message_string
           false, //be_html
           "", //cc
           "", //bcc
           RoleEmailAddress($db_link,"") //reply_to
           );
         //
         echo "<tr>\n"
            . "   <td><small>$coord_agency</small></td>\n"
            . "   <td align=center><small>$num_relayed_sheets</small></td>\n"
            . "   <td><small>To YOU for forwarding</small></td>\n"
            . "   <td><small>n/a</small></td>\n"
            . "</tr>\n";
         }
      }
   }
echo "</table><p>&nbsp;</p></li>\n";
//
// Report missing relay targets.
//
$result = $db_link->query("select * from missing_relay_target")
   or die("Query of table missing_relay_target failed with error: " . mysqli_error($db_link));
//
if (mysqli_num_rows($result))
   {
   echo "<li><p><b>Relay failures:</b>  Data from the following availability sheets could not be relayed because the "
      . "sheets could no longer be found in OSCAR.&nbsp; These sheets may have been retracted by their submitters:</p>\n"
      . "<table border=1 cellspacing=0 cellpadding=3>\n"
      . "<tr bgcolor=#D0D0D0>\n"
      . "   <td><small>Last name</small></td>\n"
      . "   <td><small>First name</small></td>\n"
      . "</tr>\n";
   while ($row = mysqli_fetch_array($result))
      {
      extract($row);
      echo "<tr>\n"
         . "   <td><small>$last_name</small></td>\n"
         . "   <td><small>$first_name</small></td>\n"
         . "</tr>";
      }
   echo "</table><p>&nbsp;</p></li>\n";
   }
echo "<li><p><b>ERS:</b>&nbsp; Availabilities on sheets with a Home Squad indication of 'ERS' have not been relayed to any "
   . "squad.</p></li>\n";
echo "</ol>\n";
//
// Drop temp tables.
//
$db_link->query("drop table missing_relay_target")
   or die("Drop of table missing_relay_target failed with error:  " . mysqli_error($db_link));
$db_link->query("drop table intermediate_avail_sheet")
   or die("Drop of table intermediate_avail_sheet failed with error:  " . mysqli_error($db_link));
//
echo "</blockquote>\n";
echo "<br><p>If you have feedback about the technical aspects of this process, please contact the <a href=mailto:\""
   . RoleEmailAddress($db_link,"") . "\">OSCAR System Administrator</a>.</p>";
?>
         <hr>
         <p><small><small><em><pre>$Id: perform-hand-off.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $</pre></em></small></small>
      </td>
    </tr>
  </table>
</body>

</html>
