<?
//
// $Id: perform-set-role-challenge.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $
//
// Emulate register_globals on
if (!ini_get('register_globals'))
  {
  $superglobals = array($_SERVER,$_ENV,$_FILES,$_COOKIE,$_POST,$_GET);
  if (isset($_SESSION))
    {
    array_unshift($superglobals, $_SESSION);
    }
  foreach ($superglobals as $superglobal)
    {
    extract($superglobal, EXTR_SKIP);
    }
  }
//
// Assign passed-in arguments to themselves to prevent 'undefined var' warnings later.
//
$agency = $agency;
$role = $role;
$current_email_addr = $current_email_addr;
$proposed_email_addr = $proposed_email_addr;
$approving_email_addr = $approving_email_addr;
//
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_oscarmailheaders.phtml");
//
$ini = AppSettings();
$db_link = DbLink($ini);
$dbkalipso_link = DbkalipsoLink($ini);
//
if ($ini[app][do_report_all_errors]) error_reporting(E_ALL);
//
$html = "<html>\n";
$html .= "<head><title>Set Role Approval</title></head>\n";
$html .= "<body bgcolor=#FFFFFF>\n";
$html .= "<table align=center width=80%><tr><td>\n";
$html .= "<H6 ALIGN=CENTER>KVEO-IT-PROJECT<br><a href=\"javascript:close();\">OSCAR SYSTEM</a><br><a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></H6>\n";
$html .= "<H1 ALIGN=CENTER>Set Role Approval</H1>\n";
$html .= "<hr>\n";
//
echo $html;
//
// Validate parameters.
//
if 
   (
      ($agency != "")
   and
      ($role != "")
   and
      ($current_email_addr != "")
   and
      ($proposed_email_addr != "")
   and
      ($approving_email_addr != "")
   )
// then
   {
   //
   // All required values are present.
   // Generate the challenge message.
   //
   //             0        1         2         3         4         5         6         7
   //             123456789012345678901234567890123456789012345678901234567890123456789012
   $challenge = "";
   $challenge .= "Someone at IP $REMOTE_ADDR (possibly you) wants to change a role setting\n"
              .  "in the OSCAR system, and the requestor named you as the approving\n"
              .  "authority.  Specifically, OSCAR received a request to change this\n"
              .  "agency-role combination:\n\n"
              .  "   $agency $role\n\n"
              .  "from the current value, which is:\n\n"
              .  "   $current_email_addr\n\n"
              .  "to this email address:\n\n"
              .  "   $proposed_email_addr\n\n"
              .  "THE CHANGE IS NOT YET COMPLETE.  To\n"
              .  "complete the process, click here:\n"
              .  $ini[server][root_url]
              .  "/perform-set-role.phtml?a="
              .  base64_encode($agency)
              .  "&b="
              .  base64_encode($role)
              .  "&c="
              .  base64_encode($proposed_email_addr)
              .  "\n\n"
              .  "To ABORT the change, DO NOTHING.\n\n";
   //
   // Add sig lines.
   //
   $challenge .= "-- OSCAR\n"
              .  "-- Home page: " . $ini[server][host_url] . "/" . $ini[app][superapp] . "\n"
              .  "-- Sysadmin: " . RoleEmailAddress($db_link,"") . "\n";
   //
   // Send the mail.
   //
   kix\k::SmtpMailSend
     (
     RoleEmailAddress($db_link,""), //from
     $approving_email_addr, //to
     "OSCAR Role Change Challenge", //subject
     $challenge, //message_string
     false, //be_html
     "", //cc
     "", //bcc
     RoleEmailAddress($db_link,"") //reply_to
     );
   $result = true;
   //
   if ($result)
      {
      PutLibPhotoRandomPlaced($ini,$dbkalipso_link,"oscarsystem",1,"right");
      echo "<p>The OSCAR system has sent a challenge message to <b>$approving_email_addr</b>.</p>";
      echo "Related destinations:\n"
         . "<ul>\n"
         . "   <li><a href=form-set-role-1.phtml>Role Modification page</a></li>\n"
         . "   <li><a href=modify.phtml>Modify other OSCAR settings</a></li>\n"
         . "   <li><a href=index.phtml>Main OSCAR page</a></li>\n"
         . "</ul>\n";
      echo "<p>If you have feedback about the technical aspects of this process, please contact the <a href=mailto:\""
         .  RoleEmailAddress($db_link,"")
         .  "\">OSCAR System Administrator</a>.</p>";
      }
   else
      {
      //
      // Fill the page out with a warning and instructions.
      //
      ?>
      <h2><i>Error!</i></h2>
      <b>
      <blockquote>
         <p>The OSCAR system encountered an internal error while processing your request.&nbsp; Contact the
            <a href=mailto:"<? echo RoleEmailAddress($db_link,""); ?>">OSCAR System Administrator</a>.</p>
      </blockquote>            
      </b>
      <?
      }
   }
else
   {
   //
   // Fill the page out with a warning and instructions.
   //
   ?>
   <h2><i>Error!</i></h2>
   <b>
   <blockquote>
      <p>Invalid parameters</p>
   </blockquote>            
   </b>
   <?
   }
?>
<br clear=both>
<hr>
<p><small><small><em><pre>$Id: perform-set-role-challenge.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $</pre></em></small></small>
</td>
</tr>
</table>
</body>
</html>
