<?
//
// $Id$
//
require_once("f_runmode.phtml");
$mode = RunMode($PHP_SELF);
//
// Assign incoming arguments to themselves to prevent 'uninitialized variable' warnings later.
//
$first_name = $first_name;
$last_name = $last_name;
$email_addr = $email_addr;
$squad = $squad;
$applicable_month_num = $applicable_month_num;
$be_on_team_30 = $be_on_team_30;
$be_on_team_5 = $be_on_team_5;
$be_on_team_air = $be_on_team_air;
$be_als = $be_als;
$coord_agency = $coord_agency;
$be_third = !$be_aic;  //Same logic, different user interface
$be_nondriver = !$be_driver;  //Same logic, different user interface
$be_needing_driver = $be_needing_driver;
$d1 = $d1;
$d2 = $d2;
$d3 = $d3;
$d4 = $d4;
$d5 = $d5;
$d6 = $d6;
$d7 = $d7;
$d8 = $d8;
$d9 = $d9;
$d10 = $d10;
$d11 = $d11;
$d12 = $d12;
$d13 = $d13;
$d14 = $d14;
$d15 = $d15;
$d16 = $d16;
$d17 = $d17;
$d18 = $d18;
$d19 = $d19;
$d20 = $d20;
$d21 = $d21;
$d22 = $d22;
$d23 = $d23;
$d24 = $d24;
$d25 = $d25;
$d26 = $d26;
$d27 = $d27;
$d28 = $d28;
$d29 = $d29;
$d30 = $d30;
$d31 = $d31;
$n1 = $n1;
$n2 = $n2;
$n3 = $n3;
$n4 = $n4;
$n5 = $n5;
$n6 = $n6;
$n7 = $n7;
$n8 = $n8;
$n9 = $n9;
$n10 = $n10;
$n11 = $n11;
$n12 = $n12;
$n13 = $n13;
$n14 = $n14;
$n15 = $n15;
$n16 = $n16;
$n17 = $n17;
$n18 = $n18;
$n19 = $n19;
$n20 = $n20;
$n21 = $n21;
$n22 = $n22;
$n23 = $n23;
$n24 = $n24;
$n25 = $n25;
$n26 = $n26;
$n27 = $n27;
$n28 = $n28;
$n29 = $n29;
$n30 = $n30;
$n31 = $n31;
$odnmid = $odnmid;
//
if ($mode) error_reporting(E_ALL);
//
require_once("f_oscarhomepageurl.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("f_bodyopen.phtml");
require_once("f_connectselectdbinstanceunpublished.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_availlist.phtml");
require_once("f_htmlofnote.phtml");
require_once("f_setavailcomment.phtml");
require_once("f_showavailsheetrecdetail.phtml");
require_once("f_showavailcomments.phtml");
require_once("f_showspecialeventshiftavails.phtml");
//
// Preserve intended logic, which is that be_needing_driver actually indicates be_ALS.  If one is ALS, then one is clearly
// not a third.
//
if ($be_needing_driver) $be_third = FALSE;
//
?>
<html>
<head><title>OSCAR - Confirmation</title></head>
<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
         <h6 align="center">
         KVEO-IT-PROJECT<br>
         <a href="<? echo OscarHomePageUrl(); ?>">OSCAR SYSTEM</a><br>
         <a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></h6>
         <H1 ALIGN="CENTER">Confirmation</H1>
         <hr>
         <?
         //
         // Validate parameters.
         //
         if (($coord_agency == "EMS") and ($squad == ""))
            {
            //
            // Fill the page out with a warning and instructions.
            //
            ?>
            <h2><i>Error!</i></h2>
            <b>
            <blockquote>
               <p>You did not supply a required parameter.&nbsp; You must supply a value for this field:</p>
               <ul>
                  <li><p>Home squad</p>
               </ul>
               <p>Please press your browser's [<--&nbsp;BACK] button to correct the problem.</p>
            </blockquote>            
            </b>
            <?
            echo "<p>If you have feedback about the technical aspects of this process, please contact the <a href=mailto:" . RoleEmailAddress($db_link,"") . ">OSCAR System Administrator</a>.</p>";
            }
         else
         {
         if (ConnectSelectDbInstanceUNPUBLISHED($db_link) == "TRUE")
            {
            //
            // Calculate the expiration date for this availability sheet.  For the expiration date calculation, the 0th day
            // of month+1 resolves to the last day of month.
            //
            $applicable_month_time = mktime(12,0,0,$applicable_month_num,1);
            $applicable_month_abbrev = strtoupper(date("M",$applicable_month_time));
            $expiration_date = date("Y-m-d",mktime(0,0,0,($applicable_month_num + 1),0));
            //
            // Create and execute the SQL statement to insert the record.
            //
            $sql = "insert into " . $mode . "avail_sheet set first_name='" . addslashes(trim($first_name)) . "'"
               . ", last_name='" . addslashes(trim($last_name)) ."'"
               . ", email_addr='" . addslashes(trim($email_addr)) . "'"
               . ", month='" . $applicable_month_abbrev . "'"
               . ", coord_agency='$coord_agency'";
            if ($coord_agency == "EMS")
               {
               $sql .= ", squad='$squad'";
               if ($be_on_team_30 == "TRUE") $sql .= ", be_on_team_30='TRUE'";
               if ($be_on_team_5 == "TRUE") $sql .= ", be_on_team_5='TRUE'";
               if ($be_on_team_air == "TRUE") $sql .= ", be_on_team_air='TRUE'";
               if ($be_als == "TRUE") $sql .= ", be_als='TRUE'";
               }
            else
               {
               if ($be_on_team_30 == "TRUE") $sql .= ", be_on_team_30='TRUE'";
               if ($be_on_team_5 == "TRUE") $sql .= ", be_on_team_5='TRUE'";
               if ($be_on_team_air == "TRUE") $sql .= ", be_on_team_air='TRUE'";
               if ($be_third == "TRUE") $sql .= ", be_third='TRUE'";
               if ($be_nondriver == "TRUE") $sql .= ", be_nondriver='TRUE'";
               if ($be_needing_driver == "TRUE") $sql .= ", be_needing_driver='TRUE'";
               }
            $sql .= ", d1='$d1', d2='$d2', d3='$d3', d4='$d4', d5='$d5', d6='$d6', d7='$d7', d8='$d8', d9='$d9', d10='$d10', d11='$d11', d12='$d12', d13='$d13', d14='$d14', d15='$d15', d16='$d16', d17='$d17', d18='$d18', d19='$d19', d20='$d20', d21='$d21', d22='$d22', d23='$d23', d24='$d24', d25='$d25', d26='$d26', d27='$d27', d28='$d28', d29='$d29', d30='$d30', d31='$d31'"
               . ", n1='$n1', n2='$n2', n3='$n3', n4='$n4', n5='$n5', n6='$n6', n7='$n7', n8='$n8', n9='$n9', n10='$n10', n11='$n11', n12='$n12', n13='$n13', n14='$n14', n15='$n15', n16='$n16', n17='$n17', n18='$n18', n19='$n19', n20='$n20', n21='$n21', n22='$n22', n23='$n23', n24='$n24', n25='$n25', n26='$n26', n27='$n27', n28='$n28', n29='$n29', n30='$n30', n31='$n31'"
               . ", num_extras='$num_extras'"
               . ", note='" . addslashes(trim($note)) . "'"
               . ", submitting_node='$REMOTE_ADDR'"
               . ", expiration='$expiration_date'"
               . ", odnmid=NULLIF('$odnmid','')";
            $db_link->query($sql)
               or die
                  (
                  "Sorry, the database operation failed with this error:  <i>"
                  .  mysqli_error($db_link)
                  .  "</i>\n\nPlease notify the <a href=mailto:\""
                  .  RoleEmailAddress($db_link,"")
                  .  "\">OSCAR System Administrator</a>."
                  );
            //
            // As a failsafe in case the database becomes unavailable at any critical time after the insertion, send the
            // data to the sysadmin via email.
            //
            @mail
               (
               RoleEmailAddress($db_link,"failsafe-recipient",$mode),
               "OSCAR insert op",
               stripslashes
                  (
                  "The \'OSCAR - "
                  . $mode
                  . "perform-add-avail-sheet.phtml\' script has processed the following operation:\n\n$sql"
                  )
               );
            //
            // For a more meaningful acknowledgement, reinitialize all the dependent variables and restore them by 
            // retrieving the very record we just inserted.
            //
            $email_addr = $squad = $be_on_team_5 = $be_on_team_30 = $be_als = $coord_agency = $be_third = $be_nondriver =
               $be_needing_driver = "";
            $d1 = $d2 = $d3 = $d4 = $d5 = $d6 = $d7 = $d8 = $d9 = $d10 = $d11 = $d12 = $d13 = $d14 = $d15 = $d16 = $d17 =
               $d18 = $d19 = $d20 = $d21 = $d22 = $d23 = $d24 = $d25 = $d26 = $d27 = $d28 = $d29 = $d30 = $d31 = "";
            $n1 = $n2 = $n3 = $n4 = $n5 = $n6 = $n7 = $n8 = $n9 = $n10 = $n11 = $n12 = $n13 = $n14 = $n15 = $n16 = $n17 =
               $n18 = $n19 = $n20 = $n21 = $n22 = $n23 = $n24 = $n25 = $n26 = $n27 = $n28 = $n29 = $n30 = $n31 = "";
            $num_extras = $note = $expiration = $odnmid = "";
            $be_tda = "";
               //
               // Break be_tda out separately so it won't get flagged as an undefined var and so I don't have to declare it
               // as an argument (above), which it is not in this case.
               //
            //
            $result = $db_link->query
               (
               $qry = "select * from " . $mode . "avail_sheet"
               .  " where month='$applicable_month_abbrev'"
               .  "    and last_name='" . addslashes(trim($last_name)) . "'"
               .  "    and first_name='" . addslashes(trim($first_name)) . "'"
               .  " order by timestamp desc"
               .  " limit 1"
               );
            if ($num_rows = mysqli_num_rows($result))
               {
               //
               // Reinitialize the independent variables now that the select is done.  This way, anything that gets
               // displayed is assured to get its value from the extract call below.
               //
               $first_name = $last_name = "";
               //
               extract($row = mysqli_fetch_array($result));
               //
               // The insert and subsequent select must've succeeded.
               //
               echo "<p><b>Success!&nbsp; OSCAR has accepted your submission.</b></p>\n";
               echo "<blockquote>\n";
               //echo "<p>OSCAR wishes to thank its sponsor:</p>\n"
               //   . "   <table border><tr><td>\n"
               //   . "   <table cellpadding=10>\n"
               //   . "      <tr><td align=center colspan=2><img src=fire-brand-banner.jpg></td></tr>\n"
               //   . "      <tr>\n"
               //   . "         <td align=center width="50%">\n"
               //   . "            <h3><font color=red>Fire Brand</font></h3>\n"
               //   . "            <small>\n"
               //   . "               <em><a href=http://www.fire-brand.com>Take a look at this month's special!</a></em>\n"
               //   . "            </small>\n"
               //   . "         </td>\n"
               //   . "         <td align=center>\n"
               //   . "            <small>\n"
               //   . "               3025 S. Military Highway<br>\n"
               //   . "               Chesapeake, VA 23323<br>\n"
               //   . "               (757) 487-4646<br>\n"
               //   . "               <a href=http://www.fire-brand.com>www.fire-brand.com</a>\n"
               //   . "            </small>\n"
               //   . "         </td>\n"
               //   . "      </tr>\n"
               //   . "   </table>\n"
               //   . "   </td></tr></table>\n";
               echo "Know of someone who deserves a <b>Class Act Award</b>?  <a href=" . $mode . "form-submit-class-act.phtml>Tell EMS Admin!</a>\n";
               echo "</blockquote>\n";
               echo "<p>Your availability sheet has been recorded as follows:</p>\n";
               echo "<blockquote>\n";
               ShowAvailSheetRecDetail
                  (
                  $timestamp,
                  $first_name,
                  $last_name,
                  $email_addr,
                  $squad,
                  $month,
                  $be_on_team_5,
                  $be_on_team_30,
                  $be_on_team_air,
                  $be_tda,
                  $be_als,
                  $num_extras,
                  $d1,$d2,$d3,$d4,$d5,$d6,$d7,$d8,$d9,$d10,$d11,$d12,$d13,$d14,$d15,$d16,$d17,$d18,$d19,$d20,$d21,$d22,$d23,$d24,$d25,$d26,$d27,$d28,$d29,$d30,$d31,
                  $n1,$n2,$n3,$n4,$n5,$n6,$n7,$n8,$n9,$n10,$n11,$n12,$n13,$n14,$n15,$n16,$n17,$n18,$n19,$n20,$n21,$n22,$n23,$n24,$n25,$n26,$n27,$n28,$n29,$n30,$n31,
                  $note,
                  $expiration,
                  1,
                  $mode,
                  $coord_agency,
                  $be_needing_driver,
                  $be_nondriver,
                  $be_third
                  );
               echo "</blockquote>\n";
               //
               // Record partial-shift comment data.  Do it after the read-back so that we'll have the timestamp value that forms part of the key that links the records.
               //
               if ($d1_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"d",1,$d1_comment);
               if ($d2_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"d",2,$d2_comment);
               if ($d3_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"d",3,$d3_comment);
               if ($d4_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"d",4,$d4_comment);
               if ($d5_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"d",5,$d5_comment);
               if ($d6_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"d",6,$d6_comment);
               if ($d7_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"d",7,$d7_comment);
               if ($d8_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"d",8,$d8_comment);
               if ($d9_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"d",9,$d9_comment);
               if ($d10_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"d",10,$d10_comment);
               if ($d11_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"d",11,$d11_comment);
               if ($d12_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"d",12,$d12_comment);
               if ($d13_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"d",13,$d13_comment);
               if ($d14_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"d",14,$d14_comment);
               if ($d15_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"d",15,$d15_comment);
               if ($d16_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"d",16,$d16_comment);
               if ($d17_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"d",17,$d17_comment);
               if ($d18_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"d",18,$d18_comment);
               if ($d19_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"d",19,$d19_comment);
               if ($d20_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"d",20,$d20_comment);
               if ($d21_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"d",21,$d21_comment);
               if ($d22_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"d",22,$d22_comment);
               if ($d23_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"d",23,$d23_comment);
               if ($d24_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"d",24,$d24_comment);
               if ($d25_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"d",25,$d25_comment);
               if ($d26_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"d",26,$d26_comment);
               if ($d27_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"d",27,$d27_comment);
               if ($d28_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"d",28,$d28_comment);
               if ($d29_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"d",29,$d29_comment);
               if ($d30_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"d",30,$d30_comment);
               if ($d31_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"d",31,$d31_comment);
               if ($n1_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"n",1,$n1_comment);
               if ($n2_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"n",2,$n2_comment);
               if ($n3_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"n",3,$n3_comment);
               if ($n4_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"n",4,$n4_comment);
               if ($n5_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"n",5,$n5_comment);
               if ($n6_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"n",6,$n6_comment);
               if ($n7_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"n",7,$n7_comment);
               if ($n8_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"n",8,$n8_comment);
               if ($n9_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"n",9,$n9_comment);
               if ($n10_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"n",10,$n10_comment);
               if ($n11_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"n",11,$n11_comment);
               if ($n12_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"n",12,$n12_comment);
               if ($n13_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"n",13,$n13_comment);
               if ($n14_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"n",14,$n14_comment);
               if ($n15_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"n",15,$n15_comment);
               if ($n16_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"n",16,$n16_comment);
               if ($n17_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"n",17,$n17_comment);
               if ($n18_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"n",18,$n18_comment);
               if ($n19_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"n",19,$n19_comment);
               if ($n20_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"n",20,$n20_comment);
               if ($n21_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"n",21,$n21_comment);
               if ($n22_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"n",22,$n22_comment);
               if ($n23_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"n",23,$n23_comment);
               if ($n24_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"n",24,$n24_comment);
               if ($n25_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"n",25,$n25_comment);
               if ($n26_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"n",26,$n26_comment);
               if ($n27_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"n",27,$n27_comment);
               if ($n28_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"n",28,$n28_comment);
               if ($n29_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"n",29,$n29_comment);
               if ($n30_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"n",30,$n30_comment);
               if ($n31_comment) SetAvailComment($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,"n",31,$n31_comment);
               //
               echo "<p>Also, the following specific shift availability comments have been recorded:</p>\n";
               echo "<blockquote>\n";
               ShowAvailComments($db_link,$mode,$applicable_month_abbrev,$last_name,$first_name,$timestamp,$coord_agency,$applicable_month_num);
               echo "</blockquote>\n";
               //
               foreach ($_REQUEST as $key => $value)
                 {
                 if (strpos($key,"special_event_shift_id_") !== FALSE)
                   {
                   $result = $db_link->query("insert ignore special_event_avail set shift_id = '$value', odnmid = '$odnmid'")
                     or die("Query failed with error: " . mysqli_error($db_link));
                   }
                 }
               echo "<p>And, the following special event shift availabilities have been recorded:</p>\n";
               echo "<blockquote>\n";
               ShowSpecialEventShiftAvails($db_link,$odnmid,$applicable_month_num);
               echo "</blockquote>\n";
               //
               echo "<p><b>Thanks!&nbsp; You may want to print this page for your records.</b></p>";
               echo "<p>If you have feedback about the technical aspects of this process, please contact the <a href=mailto:" . RoleEmailAddress($db_link,"") . ">OSCAR System Administrator</a>.</p>";
               }
            else
               {
               //
               // Fill the page out with a warning and instructions.
               //
               ?>
               <h2><i>Error!</i></h2>
               <b>
               <blockquote>
                  <p>The OSCAR system was unable to find what it thinks it just inserted into the database.&nbsp; Possible causes
                     include:</p>
                  <ul>
                     <li>The network may be very congested.
                     <li>The database server may be bogged down, or may have gone offline due to error or maintenance.
                     <li>OSCAR may have a bug.
                  </ul>
                  <p>Please try submitting your information again later, or contact the <a href=mailto:\"<? echo 
                     RoleEmailAddress($db_link,""); ?>\">OSCAR System Administrator</a>.</p>
               </blockquote>            
               </b>
               <?
               }
            }
         else
            {
            //
            // Fill the page out with a warning and instructions.
            //
            ?>
            <h2><i>Sorry...</i></h2>
            <b>
            <blockquote>
               <? echo "<p>OSCAR's database is temporarily offline.&nbsp; Please retry your submission later.</p>"; ?>
            </blockquote>            
            </b>
            <?
            echo "<p>If you have feedback about the technical aspects of this process, please contact the <a href=mailto:" . RoleEmailAddress($db_link,"") . ">OSCAR System Administrator</a>.</p>";
            }
         }
         ?>
         <br clear=both>
         <hr>
         <p><small><small><em><pre>$Id$</pre></em></small></small>
      </td>
   </tr>
</table>
</body>
</html>
