<?
//
// $Id$
//
require_once("f_runmode.phtml");
$mode = RunMode($PHP_SELF);
//
// Assign passed-in arguments to themselves to prevent 'undefined var' warnings later.
//
$agency = $agency;
$role = $role;
$current_email_addr = $current_email_addr;
$proposed_email_addr = $proposed_email_addr;
$approving_email_addr = $approving_email_addr;
//
if ($mode) error_reporting(E_ALL);
//
require_once("f_oscarhomepageurl.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("f_bodyopen.phtml");
require_once("f_password.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_oscarmailheaders.phtml");
require_once("f_connectselectdb.phtml");
//
$html = "<html>\n";
$html .= "<head><title>Set Role Approval</title></head>\n";
$html .= "<body bgcolor=#FFFFFF>\n";
$html .= "<table align=center width=80%><tr><td>\n";
$html .= "<H6 ALIGN=CENTER>KVEO-IT-PROJECT<br><a href=" . OscarHomePageUrl() . ">OSCAR SYSTEM</a><br><a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></H6>\n";
$html .= "<H1 ALIGN=CENTER>Set Role Approval</H1>\n";
$html .= "<hr>\n";
//
echo $html;
//
// Validate parameters.
//
if 
   (
      ($agency != "")
   and
      ($role != "")
   and
      ($current_email_addr != "")
   and
      ($proposed_email_addr != "")
   and
      ($approving_email_addr != "")
   )
// then
   {
   //
   // All required values are present.
   // Connect to the database.
   //
   if (ConnectSelectDb("localhost","kalipso",Password(),"oscar") != "TRUE")
      {
      ?>
      <h2><i>Sorry...</i></h2>
      <b>
      <blockquote>
         <? echo "<p>OSCAR's database has gone offline.&nbsp; Please try your toggle operation later.</p>"; ?>
      </blockquote>            
      </b>
      <?
      }
   else
   {
   //
   // Generate the challenge message.
   //
   //             0        1         2         3         4         5         6         7
   //             123456789012345678901234567890123456789012345678901234567890123456789012
   $challenge = "";
   $challenge .= "Someone at IP $REMOTE_ADDR (possibly you) wants to change a role setting\n"
              .  "in the OSCAR system, and the requestor named you as the approving\n"
              .  "authority.  Specifically, OSCAR received a request to change this\n"
              .  "agency-role combination:\n\n"
              .  "   $agency $role\n\n"
              .  "from the current value, which is:\n\n"
              .  "   $current_email_addr\n\n"
              .  "to this email address:\n\n"
              .  "   $proposed_email_addr\n\n"
              .  "THE CHANGE IS NOT YET COMPLETE.  To\n"
              .  "complete the process, click here:\n"
              .  OscarRootUrl()
              .  "/" . $mode . "perform-set-role.phtml?a="
              .  base64_encode($agency)
              .  "&b="
              .  base64_encode($role)
              .  "&c="
              .  base64_encode($proposed_email_addr)
              .  "\n\n"
              .  "To ABORT the change, DO NOTHING.\n\n";
   //
   // Add sig lines.
   //
   $challenge .= "-- OSCAR\n"
              .  "-- Home page: " . OscarHomePageUrl() . "\n"
              .  "-- Sysadmin: " . RoleEmailAddress("",$mode) . "\n";
   //
   // Send the mail.
   //
   $result = mail($approving_email_addr, "OSCAR Role Change Challenge", $challenge, OscarMailHeaders());
   //
   if ($result)
      {
      PutLibPhotoRandomPlaced("sasquatch",1,"right");
      echo "<p>The OSCAR system has sent a challenge message to <b>$approving_email_addr</b>.</p>";
      echo "Related destinations:\n"
         . "<ul>\n"
         . "   <li><a href=" . $mode . "form-set-role-1.phtml>Role Modification page</a></li>\n"
         . "   <li><a href=" . $mode . "modify.phtml>Modify other OSCAR settings</a></li>\n"
         . "   <li><a href=" . $mode . "index.phtml>Main OSCAR page</a></li>\n"
         . "</ul>\n";
      echo "<p>If you have feedback about the technical aspects of this process, please contact the <a href=mailto:\""
         .  RoleEmailAddress("",$mode)
         .  "\">OSCAR System Administrator</a>.</p>";
      }
   else
      {
      //
      // Fill the page out with a warning and instructions.
      //
      ?>
      <h2><i>Error!</i></h2>
      <b>
      <blockquote>
         <p>The OSCAR system encountered an internal error while processing your request.&nbsp; Contact the
            <a href=mailto:"<? echo RoleEmailAddress("",$mode); ?>">OSCAR System Administrator</a>.</p>
      </blockquote>            
      </b>
      <?
      }
   }
   }
else
   {
   //
   // Fill the page out with a warning and instructions.
   //
   ?>
   <h2><i>Error!</i></h2>
   <b>
   <blockquote>
      <p>Invalid parameters</p>
   </blockquote>            
   </b>
   <?
   }
?>
<br clear=both>
<hr>
<p><small><small><em><pre>$Id$</pre></em></small></small>
</td>
</tr>
</table>
</body>
</html>
