<?
//
// $Id$
//
// Emulate register_globals on
if (!ini_get('register_globals'))
  {
  $superglobals = array($_SERVER,$_ENV,$_FILES,$_COOKIE,$_POST,$_GET);
  if (isset($_SESSION))
    {
    array_unshift($superglobals, $_SESSION);
    }
  foreach ($superglobals as $superglobal)
    {
    extract($superglobal, EXTR_SKIP);
    }
  }
//
if (isset($token)) $token = kix\k::Safe($token,kix\k::PhpValueOf_safe_hint_type("HEX"));
//
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_oscarmailheaders.phtml");
//
$ini = AppSettings();
$db_link = DbLink($ini);
$dbkalipso_link = DbkalipsoLink($ini);
//
if ($ini[app][do_report_all_errors]) error_reporting(E_ALL);
?>
<html>
<head><title>Modify Squad Participant Status</title></head>
<? BodyOpen(); ?>
<table align=center width=80%><tr><td>
<H6 ALIGN=CENTER>KVEO-IT-PROJECT<br><a href="javascript:close();">OSCAR SYSTEM</a><br><a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></H6>
<H1 ALIGN=CENTER>Modify Squad Participant Status</H1>
<hr>
<?
if ($token != "")
   {
      //
      // Get the parameters associated with the token.
      //
      $result = $db_link->query
         (
         "select enumeral, new_be_active from pend_mod_agency where token='$token' "
         )
         or die("Query failed with error: " . mysqli_error($db_link));
      if (mysqli_num_rows($result))
         {
         extract(mysqli_fetch_array($result));
         //
         // Perform the specified update.
         //
         $sql = "update agency "
            .  "set be_active='$new_be_active' "
            .  "where enumeral='$enumeral' ";
         $db_link->query($sql) or die("Update failed with error: " . mysqli_error($db_link));
         //
         // This single change can have major ramifications for hundreds of individuals.  Notify sysadmin.
         //
         kix\k::SmtpMailSend
           (
           RoleEmailAddress($db_link,""), //from
           RoleEmailAddress($db_link,""), //to
           "OSCAR Participant Change", //subject
           stripslashes
             (
             "The \'OSCAR - "
             . ""
             . "perform-mod-agency.phtml\' script has processed the following operation on behalf of the Master OSCAR "
             . "Authority:\n\n$sql"
             ) //message_string
           );
         //
         // Clean up the pending operation record.
         //
         $db_link->query
            (
            "delete from pend_mod_agency where token='$token' "
            )
            or die("Clean-up failed with error: " . mysqli_error($db_link));
         //
         PutLibPhotoRandomPlaced($ini,$dbkalipso_link,"oscarsystem",1,"right");
         echo "<p>The status of agency '$enumeral' has been changed to ";
         if ($new_be_active == "FALSE") echo "NON";
         echo "PARTICIPANT.</p>\n"
            . "Related destinations:\n"
            . "<ul>\n"
            . "   <li><a href=form-set-agency.phtml>Toggle Squad Participation page</a></li>\n"
            . "   <li><a href=modify.phtml>Modify other OSCAR settings</a></li>\n"
            . "   <li><a href=index.phtml>Main OSCAR page</a></li>\n"
            . "</ul>\n";
         }
      else
         {
         //
         // Fill the page out with a warning and instructions.
         //
         ?>
         <h2><i>Error!</i></h2>
         <b>
         <blockquote>
            <p>Specified token not found.&nbsp; Consider:</p>
            <ul>
               <li>Make sure the URL in your browser's address field exactly matches the URL
                  in your challenge email message.</li>
               <li>Maybe you have already completed this modification.</li>
            </ul>
            <p>If the above hints don't help, contact the <a href=mailto:"<? echo RoleEmailAddress($db_link,""); ?>">OSCAR
               System Administrator</a>.</p>
         </blockquote>            
         </b>
         <?
         }
   }
else
   {
   //
   // Fill the page out with a warning and instructions.
   //
   ?>
   <h2><i>Error!</i></h2>
   <b>
   <blockquote>
      <p>Invalid arguments.</p>
   </blockquote>            
   </b>
   <?
   }
?>
<br clear=both>
<hr>
<p><small><small><em><pre>$Id$</pre></em></small></small>
</td>
</tr>
</table>
</body>
</html>
