<?
//
// $Id: perform-send-class-act.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $
//
// Emulate register_globals on
if (!ini_get('register_globals'))
  {
  $superglobals = array($_SERVER,$_ENV,$_FILES,$_COOKIE,$_POST,$_GET);
  if (isset($_SESSION))
    {
    array_unshift($superglobals, $_SESSION);
    }
  foreach ($superglobals as $superglobal)
    {
    extract($superglobal, EXTR_SKIP);
    }
  }
//
// Assign passed-in arguments to themselves to prevent 'undefined var' warnings later.
//
$station = $station;
$nominees = $nominees;
$description = $description;
$submitter = $submitter;
$phone_num = $phonenum;
$emailaddr = $emailaddr;
//
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_oscarmailheaders.phtml");
//
$ini = AppSettings();
$db_link = DbLink($ini);
$dbkalipso_link = DbkalipsoLink($ini);
//
if ($ini[app][do_report_all_errors]) error_reporting(E_ALL);
//
$html = "<html>\n";
$html .= "<head><title>Class Act Award Nomination Processing</title></head>\n";
$html .= "<body bgcolor=#FFFFFF>\n";
$html .= "<table align=center width=80%><tr><td>\n";
$html .= "<H6 ALIGN=CENTER>KVEO-IT-PROJECT<br><a href=\"javascript:close();\">OSCAR SYSTEM</a><br><a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></H6>\n";
$html .= "<H1 ALIGN=CENTER>Class Act Award Nomination Processing</H1>\n";
$html .= "<hr>\n";
//
echo $html;
//
// Validate parameters.
//
if
   (
      ($nominees != "")
   and
      ($description != "")
   )
// then
   {
   //
   // All required values are present.  Generate the email message.
   //
      //
      //           0        1         2         3         4         5         6         7
      //           123456789012345678901234567890123456789012345678901234567890123456789012
      $message = "";
      $message .= "Please accept the following Class Act Nomination, received via OSCAR:\n\n"
               .  "   STATION:\n\n"
               .  "      " . wordwrap(stripslashes(trim($station)),66,"\n      ") . "\n\n"
               .  "   NOMINEE(S):\n\n"
               .  "      " . wordwrap(stripslashes(trim($nominees)),66,"\n      ") . "\n\n"
               .  "   DESCRIPTION:\n\n"
               .  "      " . wordwrap(stripslashes(trim($description)),66,"\n      ") . "\n\n"
               .  "   SUBMITTER'S NAME:\n\n"
               .  "      " . wordwrap(stripslashes(trim($submitter)),66,"\n      ") . "\n\n"
               .  "   SUBMITTER'S DAYTIME PHONE NUMBER:\n\n"
               .  "      " . wordwrap(stripslashes(trim($phonenum)),66,"\n      ") . "\n\n"
               .  "   SUBMITTER'S EMAIL ADDRESS:\n\n"
               .  "      " . wordwrap(stripslashes(trim($emailaddr)),66,"\n      ") . "\n\n\n"
               .  "Follow up tasks:\n\n"
               .  "   Certificate issued:\n"
               .  "      [ ]Yes  [ ]No\n"
               .  "   Copy to:\n"
               .  "      [ ]Personnel file\n"
               .  "      [ ]Squad Commander\n"
               .  "   Personnel database entry:\n"
               .  "      [ ]Yes  [ ]No\n"
               .  "   Congrat letter sent:\n"
               .  "      [ ]Yes  [ ]No\n"
               .  "   Gift issued:\n"
               .  "      [ ]Yes  [ ]No\n"
               .  "   Comments:\n\n\n\n\n";
      //
      // Add sig lines.
      //
      $message .= "-- OSCAR\n"
               .  "-- Home page: " . $ini[server][host_url] . "/" . $ini[app][superapp] . "\n"
               .  "-- Sysadmin: " . RoleEmailAddress($db_link,"") . "\n";
      //
      // Send the mail.
      //
      $recipient = RoleEmailAddress($db_link,'class-act-coord');
      $from_reply_to_value = stripslashes(trim($submitter)) . '<' . stripslashes(trim($emailaddr)) . '>';
      kix\k::SmtpMailSend
        (
        $from_reply_to_value, //from
        $recipient, //to
        "Class Act Nomination (via OSCAR)", //subject
        $message, //message_string
        false, //be_html
        "", //cc
        "", //bcc
        $from_reply_to_value //reply_to
        );
      $result = true;
      //
      if ($result)
         {
         PutLibPhotoRandomPlaced($ini,$dbkalipso_link,"oscarsystem",1,"right");
         echo "<p><b>Thanks!</b></p>";
         echo "<p>OSCAR has sent your nomination to <b>$recipient</b>.</p>";
         }
      else
         {
         //
         // Fill the page out with a warning and instructions.
         //
         ?>
         <h2><i>Error!</i></h2>
         <b>
         <blockquote>
            <p>OSCAR encountered an internal error while processing your request.  Please do the following:</p>
            <ul>
               <?
               echo "<li><p>Use another method (like email or telephone) to submit your nomination to the <a href=mailto:\""
                  .  RoleEmailAddress($db_link,"class-act-coord")
                  .  "\">Class Act Coordinator</a>.</p>";
               echo "<li><p>Let the <a href=mailto:" . RoleEmailAddress($db_link,"") . "?subj=\"OSCAR Bug Report\">OSCAR System "
                  .  "Administrator</a> know this error occurred.</p>";
               ?>
            </ul>
         </blockquote>            
         </b>
         <?
         }
   }
else
   {
   //
   // Fill the page out with a warning and instructions.
   //
   ?>
   <h2><i>Error!</i></h2>
   <b>
   <blockquote>
      <p>You did not supply one or more of the required parameters.&nbsp; You must supply values for these fields:</p>
      <ul>
         <li><p>Person(s) nominated</p>
         <li><p>Description</p>
      </ul>
      <p>Please press your browser's [<--&nbsp;BACK] button to correct the problems.</p>
   </blockquote>            
   </b>
   <?
   }
?>
<br clear=both>
<hr>
<p><small><small><em><pre>$Id: perform-send-class-act.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $</pre></em></small></small>
</td>
</tr>
</table>
</body>
</html>
