<?
//
// $Id: perform-gen-report.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $
//
// Emulate register_globals on
if (!ini_get('register_globals'))
  {
  $superglobals = array($_SERVER,$_ENV,$_FILES,$_COOKIE,$_POST,$_GET);
  if (isset($_SESSION))
    {
    array_unshift($superglobals, $_SESSION);
    }
  foreach ($superglobals as $superglobal)
    {
    extract($superglobal, EXTR_SKIP);
    }
  }
//
// Assign incoming arguments to themselves to prevent 'uninitialized variable' warnings later.
//
$applicable_month_num = $applicable_month_num;
$team_filter = $team_filter;
$shift_filter = $shift_filter;
$relay = $relay;
$d1 = $d1;
$d2 = $d2;
$d3 = $d3;
$d4 = $d4;
$d5 = $d5;
$d6 = $d6;
$d7 = $d7;
$d8 = $d8;
$d9 = $d9;
$d10 = $d10;
$d11 = $d11;
$d12 = $d12;
$d13 = $d13;
$d14 = $d14;
$d15 = $d15;
$d16 = $d16;
$d17 = $d17;
$d18 = $d18;
$d19 = $d19;
$d20 = $d20;
$d21 = $d21;
$d22 = $d22;
$d23 = $d23;
$d24 = $d24;
$d25 = $d25;
$d26 = $d26;
$d27 = $d27;
$d28 = $d28;
$d29 = $d29;
$d30 = $d30;
$d31 = $d31;
$n1 = $n1;
$n2 = $n2;
$n3 = $n3;
$n4 = $n4;
$n5 = $n5;
$n6 = $n6;
$n7 = $n7;
$n8 = $n8;
$n9 = $n9;
$n10 = $n10;
$n11 = $n11;
$n12 = $n12;
$n13 = $n13;
$n14 = $n14;
$n15 = $n15;
$n16 = $n16;
$n17 = $n17;
$n18 = $n18;
$n19 = $n19;
$n20 = $n20;
$n21 = $n21;
$n22 = $n22;
$n23 = $n23;
$n24 = $n24;
$n25 = $n25;
$n26 = $n26;
$n27 = $n27;
$n28 = $n28;
$n29 = $n29;
$n30 = $n30;
$n31 = $n31;
//
if (isset($coord_agency)) $coord_agency = kix\k::Safe($coord_agency,kix\k::PhpValueOf_safe_hint_type("KI_SORT_EXPRESSION"));
if (isset($email_addr)) $email_addr = trim(kix\k::Safe($email_addr,kix\k::PhpValueOf_safe_hint_type("EMAIL_ADDRESS")));
if (isset($name)) $name = trim(kix\k::Safe($name,kix\k::PhpValueOf_safe_hint_type("HUMAN_NAME")));
//
$foundation_dir = "../foundation";
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_oscarmailheaders.phtml");
require_once("f_sendapprovalnotice.phtml");
require_once("f_properties.phtml");
require_once("f_beauthority.phtml");
require_once("f_availlist.phtml");
require_once("f_squadofcoordagency.phtml");
require_once("f_harvestedlist.phtml");
require_once("f_harvestemailaddresses.phtml");
require_once("f_beemsschedcoord.phtml");
require_once("f_htmlofnote.phtml");
require_once("f_formattednoteappendage.phtml");
//require_once("$foundation_dir/std_style_class.php");
require_once("f_coordagencyofclearedemailaddr.phtml");
//
$ini = AppSettings();
$db_link = DbLink($ini);
$dbkalipso_link = DbkalipsoLink($ini);
//
if ($ini[app][do_report_all_errors]) error_reporting(E_ALL);
//
$report = "<html>\n";
$report .= "<head><title>Report generation</title></head>\n";
$report .= "<body bgcolor=#FFFFFF>\n";
$report .= "<table align=center width=80%><tr><td>\n";
$report .= "<H6 ALIGN=CENTER>KVEO-IT-PROJECT<br><a href=\"javascript:close();\">OSCAR SYSTEM</a><br><a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></H6>\n";
$report .= "<H1 ALIGN=CENTER>Availability Report</H1>\n";
$report .= "<hr>\n";
//
echo $report;
//
// Validate parameters.
//
if
   (
      ($name != "")
   and
      ($email_addr != "")
   and
      ($applicable_month_num != "")
   and
      ($coord_agency != "")
   )
// then
{
$name = trim($name);
//
// CODEGENCOAL ("code-gen-coal")
//    COndition DEscriptor GENeration/COmparison ALgorithm
//
//    The CODEGENCOAL is the set of statements in this script that contribute to the generation and comparison of condition
//    descriptors.
//
//    The condition descriptor summarizes the conditions under which the report was requested.  We use the MD5 digest of the
//    condition descriptor as the key for the report in the report cache.
//
//    Currently, elements of the CODEGENCOAL are interspersed with elements of other conceptual algorithms that contribute
//    to perform-gen-report.  A potential future improvement would be to extract and modularize the CODEGENCOAL.
//

//
// Retrieve timestamp of latest avail_sheet record.  Later, we'll use it to see if database conditions have changed
// significantly since a report with these parameters was last run.  If we determine that a user has asked this routine to
// generate a report that's already been generated, we'll avoid regeneration and just retrieve what's in the cache.
//
$sql = "select max(timestamp) as timestamp_of_latest_submission "
   .  " from avail_sheet "
   .  " where coord_agency like '$coord_agency' ";
$result = $db_link->query($sql)
   or die("The attempt to select the latest timestamp from the avail_sheet table failed with this error:  " . mysqli_error($db_link));
//
$row = mysqli_fetch_object($result);
//
$condition_descriptor = "timestamp_of_latest_submission=" . $row->timestamp_of_latest_submission . "\n";
//
// Retrieve timestamp of latest relay_journal record for this agency.  If records have been relayed, but no relayed record
// has a submission time later than the latest non-relayed submission, then knowing the timestamp_of_latest_submission
// (above) is not sufficient.
//
$sql = "select max(timestamp) as timestamp_of_latest_relay "
   .  " from relay_journal "
   .  " where coord_agency like '$coord_agency' ";
$result = $db_link->query($sql)
   or die("The attempt to select the latest timestamp from the relay journal failed with this error:  " . mysqli_error($db_link));
$row = mysqli_fetch_object($result);
//
$condition_descriptor .= "timestamp_of_latest_relay=" . $row->timestamp_of_latest_relay . "\n";
//
$be_combined_agency_format = 'FALSE';
//
switch ($coord_agency)
   {
   case '%':
      $be_combined_agency_format = 'TRUE';
      $presentation_clause = 'order by be_on_team_air desc '
         .  '   , be_on_team_5 desc '
         .  '   , be_on_team_30 desc '
         .  '   , be_als desc '
         .  '   , coord_agency asc '
         .  '   , be_third asc '
         .  '   , be_nondriver desc '
         .  '   , be_needing_driver desc ';
      break;
   case 'EMS':
      $presentation_clause = " order by be_on_team_air desc, be_on_team_5 desc, be_on_team_30 desc, be_tda desc, squad ";
      break;
   default:
      $presentation_clause = " order by be_third asc, be_nondriver desc, be_needing_driver desc ";
   }
//
// The request form, under certain conditions, sends a value of 13 for applicable_month_num.  Cast it into the range 1..12.
//
$normalized_month_num = date("n",mktime(12,0,0,$applicable_month_num,1));
$applicable_month_time = mktime(12,0,0,$applicable_month_num,1);
$days_in_applicable_month = date("t",$applicable_month_time);
//
$condition_descriptor .= "month_num=$normalized_month_num\n";
//
$month_word = strtoupper(date("F",mktime(12,0,0,$applicable_month_num,1)));
$month_abbrev = substr($month_word,0,3);
$where_clause = " month='$month_abbrev' and coord_agency like '$coord_agency' ";
//
$be_authority_for_any_agency = BeAuthority($db_link,$email_addr,'%');
$be_authority_for_this_agency = BeAuthority($db_link,$email_addr,$coord_agency);
$be_ems_sched_coord = BeEmsSchedCoord($db_link,$email_addr);
$be_relayable = ($be_ems_sched_coord && ($coord_agency == "EMS"));
//
if ($shift_filter == "all")
   {
   //
   // Determine if the requestor is an OSCAR system authority (ie, privileged to see special request notes & warnings).
   //
   if ($be_authority_for_any_agency)
      {
      $condition_descriptor .= "partial-authority=TRUE\n";
      //
      if ($be_authority_for_this_agency)
         {
         $condition_descriptor .= "full-authority=TRUE\n";
         }
      else
         {
         $condition_descriptor .= "authority-of=" . CoordAgencyOfClearedEmailAddr($db_link,$email_addr) . "\n";
         $condition_descriptor .= "full-authority=FALSE\n";
         }
      //
      if ($be_relayable)
         {
         $condition_descriptor .= "relayable=TRUE\n";
         }
      else
         {
         $condition_descriptor .= "relayable=FALSE\n";
         }
      }
   else
      {
      $condition_descriptor .= "authority=FALSE\n";
      }
   //
   // Full report
   //
   // Maybe the required report has already been run under these same conditions, and cached in the database.  If so, just
   // retrieve it.
   //
   $condition_descriptor .= "shift_filter=all\n";
   $condition_descriptor .= "team_filter=$team_filter\n";
   $condition_descriptor .= "coord_agency=$coord_agency\n";
   $result = $db_link->query("select md5(\"$condition_descriptor\") as digest")
      or die("The digest calculation failed with this error:  " . mysqli_error($db_link));
   $row = mysqli_fetch_object($result);
   $digest = $row->digest;
   $result = $db_link->query("select report from report_cache where digest = '$digest'")
      or die("The cache check failed with error:  " . mysqli_error($db_link));
   if (mysqli_num_rows($result))
      {
      $row = mysqli_fetch_object($result);
      $report = $row->report;
      }
   else
      {
      //
      // The required report has never been run before under these conditions.  Generate it from scratch and cache it.
      //
      if ($be_ems_sched_coord)
         {
         // Then this is also a good time to harvest email addresses and to purge the database of expired records, as
         // from-scratch requests from the EMS schedule coordinator for full reports don't happen excessively but do happen
         // regularly.
         //
         HarvestEmailAddresses($ini,$db_link);
         $db_link->query("delete from avail_sheet where expiration < CURRENT_DATE");
         $db_link->query("delete from report_cache where expiration < CURRENT_DATE");
         }
      //
      $base_sql_statement = "select distinct last_name"
         .  ", first_name";
      switch ($coord_agency)
         {
         case '%':
            $base_sql_statement .= ", coord_agency";
            // NO BREAK
         case 'EMS':
            $base_sql_statement .= ", squad"
               .  ", be_on_team_30"
               .  ", be_on_team_5"
               .  ", be_on_team_air"
               .  ", be_tda"
               .  ", be_als";
            if ($coord_agency != '%') break;
         default:
            $base_sql_statement .= ", be_needing_driver"
               .  ", be_nondriver"
               .  ", be_third";
         }
      $base_sql_statement .= ", (note != \"\") as be_a_note"
         .  " from avail_sheet ";
      switch ($team_filter)
         {
         case "als_only":
            $where_clause .= " and be_als = 'TRUE' ";
            $info_message = "This report ONLY includes Zone Car ALS providers.";
            break;
         case "team_5_only":
            $where_clause .= " and be_on_team_5 = 'TRUE' ";
            $info_message = "This report ONLY includes EMS-5 team members.";
            break;
         case "team_30_only":
            $where_clause .= " and be_on_team_30 = 'TRUE' ";
            $info_message = "This report ONLY includes SQUAD TRUCK team members.";
            break;
         case "team_air_only":
            $where_clause .= " and be_on_team_air = 'TRUE' ";
            $info_message = "This report ONLY includes AIR AMBULANCE team members.";
            break;
         case "tda_only":
            $where_clause .= " and be_tda = 'TRUE' ";
            $info_message = "This report ONLY includes TDA personnel.";
            break;
         case "released_only":
            $where_clause .= " and be_third = 'FALSE' ";
            $info_message = "This report ONLY includes released patient care providers.";
            break;
         case "drivers_only":
            $where_clause .= " and be_nondriver = 'FALSE' ";
            $info_message = "This report ONLY includes qualified drivers.";
            break;
         case "thirds_only":
            $where_clause .= " and be_third = 'TRUE' ";
            $info_message = "This report ONLY includes \"thirds\".";
            break;
         default:
            $info_message = "";
         }
      $report .= "<pre>\n";
      $report .= "<b><u>";
      if ($coord_agency != '%')
         {
         $report .= $coord_agency;
         }
      else
         {
         $report .= 'SYSTEM-WIDE';
         }
      $report .= "</u></b> availability report for $month_word <a href=gen-date.phtml>generated " . date("l Y-M-d H:i:s T") . "</a>\n\n";
      //
      $shortcuts  = "<p>Shortcuts:&nbsp; \n";
      $shortcuts .= "<a href=#Days>Days</a>";
      $shortcuts .= "&nbsp; |&nbsp; ";
      $shortcuts .= "<a href=#Nights>Nights</a>";
      $shortcuts .= "&nbsp; |&nbsp; ";
      $shortcuts .= "<a href=#Summaries>Submission summaries</a>";
      $shortcuts .= "&nbsp; |&nbsp; ";
      $shortcuts .= "<a href=#End>End</a></p><br>\n";
      //
      $report .= "</pre>$shortcuts<pre>";
      //
      if ($coord_agency == "EMS")
         {
         $report .= "   +---------------------------------------------+\n";
         $report .= "   | Legend:                                     |\n";
         $report .= "   |    -H-S-30-TDA-Z- Rxx Lastname, Firstname * |\n";
         $report .= "   |     ^ ^  ^     ^   ^                      ^ |\n";
         $report .= "   |     | |  |     |   |                      | |\n";
         $report .= "   |     | |  |     |   +- Home rescue squad   | |\n";
         $report .= "   |     | |  |     |      (ERS for VBFD)      | |\n";
         $report .= "   |     | |  |     |                          | |\n";
         $report .= "   |     | |  |     +- Zone Car ALS            | |\n";
         $report .= "   |     | |  |                                | |\n";
         $report .= "   |     | |  +- Squad truck team member       | |\n";
         $report .= "   |     | |                                   | |\n";
         $report .= "   |     | +- VFS team member                  | |\n";
         $report .= "   |     |                                     | |\n";
         $report .= "   |     +- Air Ambulance team member          | |\n";
         $report .= "   |                                           | |\n";
         $report .= "   |                      See special request -+ |\n"; 
         $report .= "   |                      in Note section        |\n";
         $report .= "   +---------------------------------------------+\n\n\n";
         }
      elseif ($coord_agency != '%')
         {
         $report .= "   +------------------------------------+\n";
         $report .= "   | Legend:                            |\n";
         $report .= "   |    -Aaa-drv- Lastname, Firstname * |\n";
         $report .= "   |      ^   ^                       ^ |\n";
         $report .= "   |      |   |                       | |\n";
         $report .= "   |      |   +- Qualified driver     | |\n";
         $report .= "   |      |                           | |\n";
         $report .= "   |      +- aic/ALS                  | |\n";
         $report .= "   |                                  | |\n";
         $report .= "   |             See special request -+ |\n"; 
         $report .= "   |             in Note section        |\n";
         $report .= "   +------------------------------------+\n\n\n";
         }
      $report .= "This report includes ALL shifts.\n";
      if ($info_message) $report .= "$info_message\n";
      $report .= "\n";
      //
      // Save the coord_agency value specified in the request form, for use after the Day and Night loops.  In the
      // following Day and Night loops, the extract($row) statement will overwrite coord_agency.
      //
      $saved_coord_agency = $coord_agency;
      //
      $report .= "<a name=Days>";
      $report .= "+------+\n";
      $report .= "| Days |\n";
      $report .= "+------+</a>\n\n";
      for ($day_index = 1; $day_index <= $days_in_applicable_month; $day_index++)
         {
         $day_description = date("jS \d\a\y (l):",mktime(9,0,0,$applicable_month_num,$day_index));
         $where_clause_2 = " and d$day_index='AVAILABLE' ";
         $sql_statement = stripslashes($base_sql_statement . " where " . $where_clause . $where_clause_2 . $presentation_clause);
         $result = $db_link->query($sql_statement) or die("Query failed with error:  " . mysqli_error($db_link));
         if ($num_rows = mysqli_num_rows($result))
            {
            $report .= $day_description . "\n";
            while ($row = mysqli_fetch_array($result))
               {
               if ($be_combined_agency_format == 'TRUE') $coord_agency = '';
               $be_on_team_5 = $be_on_team_30 = $be_on_team_air = $be_tda = $be_als = $squad = $be_third = $be_nondriver =
                  $be_needing_driver = $be_a_note = "";
               extract($row);
               $report .= "   "
                  .  Properties
                        (
                        $db_link,
                        $be_on_team_5,
                        $be_on_team_30,
                        $be_on_team_air,
                        $be_tda,
                        $be_als,
                        $squad,
                        $coord_agency,
                        $be_third,
                        $be_nondriver,
                        $be_needing_driver,
                        $be_combined_agency_format
                        )
                  .  " ";
               $last_name = stripslashes($last_name);
               $first_name = stripslashes($first_name);
               $be_authority_to_member = ($be_authority_for_this_agency || BeAuthority($db_link,$email_addr,('Rescue' . $squad)));
               if ($be_authority_to_member)
                  {
                  $highlighted_squad = 'Rescue' . $squad;
                  $report .= "<a href=detail.phtml?a="
                     .  base64_encode($last_name)
                     .  "&b="
                     .  base64_encode($first_name)
                     .  "&c="
                     .  base64_encode($month_abbrev)
                     .  "&d="
                     .  base64_encode($be_authority_to_member)
                     .  "&e="
                     .  base64_encode($coord_agency)
                     .  ">";
                  }
               $report .= "$last_name, $first_name";
               if ($be_authority_to_member)
                  {
                  $report .= "</a>";
                  if ($be_a_note) $report .= " *";
                  }
               $report .= "\n";
               $last_name = $first_name = $squad = $be_on_team_30 = $be_on_team_5 = $be_tda = $be_als = $be_third = 
                  $be_nondriver = $be_needing_driver = $be_a_note = "";
               }
            }
         else
            {
            $report .= $day_description . " None\n";
            }
         $report .= "\n";
         }
      $report .= "\n";
      //
      $report .= "</pre>$shortcuts<pre>";
      //
      $report .= "<a name=Nights>";
      $report .= "+--------+\n";
      $report .= "| Nights |\n";
      $report .= "+--------+</a>\n\n";
      for ($night_index = 1; $night_index <= $days_in_applicable_month; $night_index++)
         {
         $night_description = date("jS \\n\i\g\h\\t (l):",mktime(21,0,0,$applicable_month_num,$night_index));
         $where_clause_2 = " and n$night_index='AVAILABLE' ";
         $sql_statement = stripslashes($base_sql_statement . " where " . $where_clause . $where_clause_2 . $presentation_clause);
         $result = $db_link->query($sql_statement) or die("Query failed with error:  " . mysqli_error($db_link));
         if ($num_rows = mysqli_num_rows($result))
            {
            $report .= $night_description . "\n";
            while ($row = mysqli_fetch_array($result))
               {
               if ($be_combined_agency_format == 'TRUE') $coord_agency = '';
               $be_on_team_5 = $be_on_team_30 = $be_tda = $be_als = $squad = $be_third = $be_nondriver =
                  $be_needing_driver = $be_a_note = "";
               extract($row);
               $report .= "   "
                  .  Properties
                        (
                        $db_link,
                        $be_on_team_5,
                        $be_on_team_30,
                        $be_on_team_air,
                        $be_tda,
                        $be_als,
                        $squad,
                        $coord_agency,
                        $be_third,
                        $be_nondriver,
                        $be_needing_driver,
                        $be_combined_agency_format
                        )
                  .  " ";
               $last_name = stripslashes($last_name);
               $first_name = stripslashes($first_name);
               $be_authority_to_member = ($be_authority_for_this_agency || BeAuthority($db_link,$email_addr,('Rescue' . $squad)));
               if ($be_authority_to_member)
                  {
                  $report .= "<a href=detail.phtml?a="
                     .  base64_encode($last_name)
                     .  "&b="
                     .  base64_encode($first_name)
                     .  "&c="
                     .  base64_encode($month_abbrev)
                     .  "&d="
                     .  base64_encode($be_authority_to_member)
                     .  "&e="
                     .  base64_encode($coord_agency)
                     .  ">";
                  }
               $report .= "$last_name, $first_name";
               if ($be_authority_to_member)
                  {
                  $report .= "</a>";
                  if ($be_a_note) $report .= " *";
                  }
               $report .= "\n";
               $last_name = $first_name = $squad = $be_on_team_30 = $be_on_team_5 = $be_tda = $be_als = $be_third = 
                  $be_nondriver = $be_needing_driver = $be_a_note = "";
               }
            }
         else
            {
            $report .= $night_description . " None\n";
            }
         $report .= "\n";
         }
      $report .= "</pre>\n";
      //
      $coord_agency = $saved_coord_agency;
      //
      $report .= $shortcuts;
      //
      if ($be_authority_for_any_agency)
         {
         //
         // GENERATE NOTES AND WARNINGS.
         //
         $report .= "<h3><u><a name=Summaries>Submission Summaries</a></u></h3>\n";
         if (!$be_authority_for_this_agency)
            {
            $report .= "<p><b>This section ONLY includes personnel from $highlighted_squad who sent submissions to agency EMS.</b></p>\n";
            }
         $relay_instructions = "<table width=100%><tr><td><b>EMS Schedule Coordinator:</b></td>"
            .  "<td align=right><small><a href=relay-all-details.phtml>What is <b>Relay all</b>?</a></small>"
            .  "</td></tr></table>\n"
            .  "<ul>\n"
            .  "   <li><p>Use the checkboxes to indicate availabilities you have allocated for the centralized "
            .  "      schedule.&nbsp; Relay comments are optional.</p></li>\n"
            .  "   <li><p>Press \"Relay unused\" below to pass unallocated availabilities to squad schedule coordinators, "
            .  "      or \"Reset\" to abort your allocations and start again.</p></li>\n"
            .  "   <li><p>If you leave <i>all</i> of a member's fields untouched, none of that member's availabilities "
            .  "      will be relayed at this time (but you may relay them later if you wish).</p></li>\n"
            .  "</ul>\n";
         if ($be_relayable)
            {
            $report .= "<form action=perform-hand-off.phtml method=post>\n"
               . "<input type=hidden name=month_abbrev value=$month_abbrev>\n";
            $report .= $relay_instructions;
            }
         $db_link->query
            (
            "create temporary table aggregated "
            .  " select last_name "
            .  "    , first_name "
            .  "    , count(*) as num_submissions"
            .  "    , max(timestamp) as timestamp "
            .  " from avail_sheet "
            .  " where $where_clause "
            .  " group by last_name "
            .  "    , first_name "
            )
            or die("Create/select aggregated failed with error:  " . mysqli_error($db_link));
         //
         $query = "select aggregated.last_name "
            .  "    , aggregated.first_name ";
         switch ($coord_agency)
            {
            case '%':
               $query .= ", coord_agency";
               // NO BREAK
            case 'EMS':
               $query .= ", squad"
                  .  ", be_on_team_30"
                  .  ", be_on_team_5"
                  .  ", be_on_team_air"
                  .  ", be_tda"
                  .  ", be_als"
                  .  ", aggregated.timestamp";
               if ($coord_agency != '%') break;
            default:
               $query .= ", be_needing_driver"
                  .  ", be_nondriver"
                  .  ", be_third";
            }
         $query .= ", d1,d2,d3,d4,d5,d6,d7,d8,d9,d10,d11,d12,d13,d14,d15,d16,d17,d18,d19,d20,d21,d22,d23,d24,d25,d26,d27,d28,d29,d30,d31 "
            .  "    , n1,n2,n3,n4,n5,n6,n7,n8,n9,n10,n11,n12,n13,n14,n15,n16,n17,n18,n19,n20,n21,n22,n23,n24,n25,n26,n27,n28,n29,n30,n31 "
            .  "    , num_extras "
            .  "    , note "
            .  "    , num_submissions "
            .  " from aggregated left join avail_sheet "
            .  "    using (last_name, first_name, timestamp)"
            .  " where $where_clause "
            .  " order by last_name, first_name ";
         $result = $db_link->query($query)
            or die("Select from join failed with error:  " . mysqli_error($db_link));
         if ($num_rows = mysqli_num_rows($result))
            {
            while ($row = mysqli_fetch_array($result))
               {
               if ($be_combined_agency_format == 'TRUE') $coord_agency = '';
               $last_name = $first_name = $squad = $be_on_team_30 = $be_on_team_5 = $be_tda = $be_als = $be_third = 
                  $be_nondriver = $be_needing_driver = $num_extras = $note = $num_submissions = $timestamp = "";
               $d1 = $d2 = $d3 = $d4 = $d5 = $d6 = $d7 = $d8 = $d9 = $d10 = $d11 = $d12 = $d13 = $d14 = $d15 = $d16 =
                   $d17 = $d18 = $d19 = $d20 = $d21 = $d22 = $d23 = $d24 = $d25 = $d26 = $d27 = $d28 = $d29 = $d30 =
                   $d31 = "";
               $n1 = $n2 = $n3 = $n4 = $n5 = $n6 = $n7 = $n8 = $n9 = $n10 = $n11 = $n12 = $n13 = $n14 = $n15 = $n16 =
                  $n17 = $n18 = $n19 = $n20 = $n21 = $n22 = $n23 = $n24 = $n25 = $n26 = $n27 = $n28 = $n29 = $n30 =
                  $n31 = "";
               extract($row);
               //
               $be_authority_to_member = ($be_authority_for_this_agency || BeAuthority($db_link,$email_addr,('Rescue' . $squad)));
               if ($be_authority_to_member)
                  {
                  $last_name = stripslashes($last_name);
                  $first_name = stripslashes($first_name);
                  //
                  $encoded_last_name = base64_encode($last_name);
                  $encoded_first_name = base64_encode($first_name);
                  //
                  if ($be_relayable)
                     {
                     $encoded_sheet_key = $encoded_last_name . "-" . $encoded_first_name;
                     }
                  $report .= "<table width=100%><tr><td><a href=detail.phtml?a="
                     .  $encoded_last_name
                     .  "&b="
                     .  $encoded_first_name
                     .  "&c="
                     .  base64_encode($month_abbrev)
                     .  "&d="
                     .  base64_encode($be_authority_for_any_agency)
                     .  "&e="
                     .  base64_encode($coord_agency)
                     .  ">$last_name, $first_name</a>&nbsp; ["
                     .  Properties
                           (
                           $db_link,
                           $be_on_team_5,
                           $be_on_team_30,
                           $be_on_team_air,
                           $be_tda,
                           $be_als,
                           $squad,
                           $coord_agency,
                           $be_third,
                           $be_nondriver,
                           $be_needing_driver,
                           $be_combined_agency_format
                           )
                     .  "]";
                  if ($num_extras) $report .= "&nbsp; <b>(+$num_extras)</b>";
                  $report .= "</td>";
                  if ($be_relayable)
                     {
                     $report .= "<td align=right><input type=checkbox name=$encoded_sheet_key-NONE value=1>"
                        .  "<small>Relay all</small></td>";
                     }
                  $report .= "</tr></table>\n"
                     .  "<blockquote>\n";
                  if ($num_submissions > 1)
                     {
                     $report .= "<p><b>" . HtmlOfNote
                        (
                        FormattedNoteAppendage
                           (
                           "WARNING",
                           "MULTSUB",
                           "Submission count = $num_submissions, verification recommended."
                           )
                        );
                     $report .= "</b></p>\n";
                     }
                  $report .= "<table>\n";
                  $report .= "<tr><td valign=top>Days:</td><td valign=top>";
                  if ($be_relayable)
                     {
                     $report .= AvailList
                       (
                       $d1,$d2,$d3,$d4,$d5,$d6,$d7,$d8,$d9,$d10,$d11,$d12,$d13,$d14,$d15,$d16,$d17,$d18,$d19,$d20,$d21,$d22,$d23,$d24,$d25,$d26,$d27,$d28,$d29,$d30,$d31,
                       "",
                       "use_spaces",
                       $encoded_sheet_key . "-d"
                       );
                     }
                  else
                     {
                     $report .= AvailList
                       (
                       $d1,$d2,$d3,$d4,$d5,$d6,$d7,$d8,$d9,$d10,$d11,$d12,$d13,$d14,$d15,$d16,$d17,$d18,$d19,$d20,$d21,$d22,$d23,$d24,$d25,$d26,$d27,$d28,$d29,$d30,$d31,
                       "use_spaces",
                       ""
                       );
                     }
                  $report .= "</td></tr>\n"
                     . "   <tr><td valign=top>Nights:</td><td valign=top>";
                  if ($be_relayable)
                     {
                     $report .= AvailList
                       (
                       $n1,$n2,$n3,$n4,$n5,$n6,$n7,$n8,$n9,$n10,$n11,$n12,$n13,$n14,$n15,$n16,$n17,$n18,$n19,$n20,$n21,$n22,$n23,$n24,$n25,$n26,$n27,$n28,$n29,$n30,$n31,
                       "",
                       "use_spaces",
                       $encoded_sheet_key . "-n"
                       );
                     }
                  else
                     {
                     $report .= AvailList
                       (
                       $n1,$n2,$n3,$n4,$n5,$n6,$n7,$n8,$n9,$n10,$n11,$n12,$n13,$n14,$n15,$n16,$n17,$n18,$n19,$n20,$n21,$n22,$n23,$n24,$n25,$n26,$n27,$n28,$n29,$n30,$n31,
                       "",
                       "use_spaces"
                       );
                     }
                  $report .= "</td></tr>\n";
                  $report .= "</table>\n";
                  if ($note != "")
                     {
                     $report .= "   <p><i>" . HtmlOfNote(stripslashes($note)) . "</i></p>\n";
                     }
                  if ($be_relayable)
                     {
                     $report .= "   <p><small>Relay comment:</small><br>\n";
                     $report .= "   <textarea name=$encoded_sheet_key-COMMENT cols=60 rows=2></textarea></p>\n";
                     }
                  $report .= "</blockquote>\n<br>\n";
                  } // if ($be_authority_to_member)
               }
            }
         else
            {
            $report .= "None\n";
            }
         //
         $db_link->query("drop table aggregated")
            or die("Drop of aggregated failed with error:  " . mysqli_error($db_link));
         }
      //
      $report .= "<pre><a name=End>--- END ---</a></pre><br>\n";
      //
      $report .= $shortcuts;
      //
      if ($be_relayable)
         {
         $report .= $relay_instructions
            .  "<input type=submit value=\"Relay unused\"><input type=reset>\n"
            .  "</form>\n";
         }
      $report .= "<small><i><pre>\$Id: perform-gen-report.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $</pre></i></small>\n";
      $report .= "</td></tr></table>\n";
      $report .= "</body>\n";
      $report .= "</html>\n";
      //
      // Calculate the expiration date for this report.  For the mktime() function, the 0th day of the month+1 resolves
      // to the last day of month.
      //
      $expiration_date = date("Y-m-d",mktime(0,0,0,($applicable_month_num + 1),0));
      //
      // Store the report in the cache.
      //
      $report = addslashes($report);
      $result = $db_link->query("insert into report_cache set digest='$digest'"
         . ", report='$report'"
         . ", expiration='$expiration_date'")
         or die("Report insertion failed with this error:  " . mysqli_error($db_link));
      }
   }
else
   {
   //
   // shift_filter must be "some"
   //
   //
   // Convert sequence of day/night scalars into 1-based arrays for easier looping later.
   //
   $d = array(1 => $d1,$d2,$d3,$d4,$d5,$d6,$d7,$d8,$d9,$d10,$d11,$d12,$d13,$d14,$d15,$d16,$d17,$d18,$d19,$d20,$d21,$d22,$d23,$d24,$d25,$d26,$d27,$d28,$d29,$d30,$d31);
   $n = array(1 => $n1,$n2,$n3,$n4,$n5,$n6,$n7,$n8,$n9,$n10,$n11,$n12,$n13,$n14,$n15,$n16,$n17,$n18,$n19,$n20,$n21,$n22,$n23,$n24,$n25,$n26,$n27,$n28,$n29,$n30,$n31);
   //
   // Maybe the required report has already been run under these same conditions, and cached in the database.  If so, just
   // retrieve it.
   //
   $condition_descriptor .= "shift_filter=some\n";
   $condition_descriptor .= "team_filter=$team_filter\n";
   $condition_descriptor .= "coord_agency=$coord_agency\n";
   $condition_descriptor .= "days=";
   $expiration_day = "";
   for ($i=1; $i<=$days_in_applicable_month; $i++)
      {
      if ($d[$i])
         {
         $condition_descriptor .= "1";
         $expiration_day = $i;
         }
      else
         {
         $condition_descriptor .= "0";
         }
      }
   $condition_descriptor .= "\n";
   $condition_descriptor .= "nights=";
   for ($i=1; $i<=$days_in_applicable_month; $i++)
      {
      if ($n[$i])
         {
         $condition_descriptor .= "1";
         if ($i > $expiration_day) $expiration_day = $i;
         }
      else
         {
         $condition_descriptor .= "0";
         }
      }
   $condition_descriptor .= "\n";
   $result = $db_link->query("select md5(\"$condition_descriptor\") as digest")
      or die("The digest calculation failed with this error:  " . mysqli_error($db_link));
   $row = mysqli_fetch_object($result);
   $digest = $row->digest;
   $result = $db_link->query("select report from report_cache where digest = '$digest'")
      or die("The cache check failed with error:  " . mysqli_error($db_link));
   if (mysqli_num_rows($result))
      {
      $row = mysqli_fetch_object($result);
      $report = $row->report;
      }
   else
      {
      $base_sql_statement = "select distinct last_name"
         .  ", first_name";
      switch ($coord_agency)
         {
         case '%':
            $base_sql_statement .= ", coord_agency";
            // NO BREAK
         case 'EMS':
            $base_sql_statement .= ", squad"
               .  ", be_on_team_30"
               .  ", be_on_team_5"
               .  ", be_on_team_air"
               .  ", be_tda"
               .  ", be_als";
            if ($coord_agency != '%') break;
         default:
            $base_sql_statement .= ", be_needing_driver"
               .  ", be_nondriver"
               .  ", be_third";
         }
      $base_sql_statement .= " from avail_sheet ";
      switch ($team_filter)
         {
         case "als_only":
            $where_clause .= " and be_als = 'TRUE' ";
            $info_message = "This report ONLY includes Zone Car ALS providers.";
            break;
         case "team_5_only":
            $where_clause .= " and be_on_team_5 = 'TRUE' ";
            $info_message = "This report ONLY includes EMS-5 team members.";
            break;
         case "team_30_only":
            $where_clause .= " and be_on_team_30 = 'TRUE' ";
            $info_message = "This report ONLY includes SQUAD TRUCK team members.";
            break;
         case "team_air_only":
            $where_clause .= " and be_on_team_air = 'TRUE' ";
            $info_message = "This report ONLY includes AIR AMBULANCE team members.";
            break;
         case "tda_only":
            $where_clause .= " and be_tda = 'TRUE' ";
            $info_message = "This report ONLY includes TDA personnel.";
            break;
         case "released_only":
            $where_clause .= " and be_third = 'FALSE' ";
            $info_message = "This report ONLY includes released patient care providers.";
            break;
         case "drivers_only":
            $where_clause .= " and be_nondriver = 'FALSE' ";
            $info_message = "This report ONLY includes qualified drivers.";
            break;
         case "thirds_only":
            $where_clause .= " and be_third = 'TRUE' ";
            $info_message = "This report ONLY includes \"thirds\".";
            break;
         default:
            $info_message = "";
         }
      //
      $report .= "<pre>\n";
      $report .= "<b><u>";
      if ($coord_agency != '%')
         {
         $report .= $coord_agency;
         }
      else
         {
         $report .= 'SYSTEM-WIDE';
         }
      $report .= "</u></b> availability report for $month_word <a href=gen-date.phtml>generated " . date("l Y-M-d H:i:s T") . "</a>\n\n";
      if ($coord_agency == "EMS")
         {
         $report .= "   +-------------------------------------------+\n";
         $report .= "   | Legend:                                   |\n";
         $report .= "   |    -H-7-30-TDA-Z- Rxx Lastname, Firstname |\n";
         $report .= "   |     ^ ^  ^     ^   ^                      |\n";
         $report .= "   |     | |  |     |   |                      |\n";
         $report .= "   |     | |  |     |   +- Home rescue squad   |\n";
         $report .= "   |     | |  |     |      (ERS for VBFD)      |\n";
         $report .= "   |     | |  |     |                          |\n";
         $report .= "   |     | |  |     +- Zone Car ALS            |\n";
         $report .= "   |     | |  |                                |\n";
         $report .= "   |     | |  +- Squad truck team member       |\n";
         $report .= "   |     | |                                   |\n";
         $report .= "   |     | +- EMS-7 team member                |\n";
         $report .= "   |     |                                     |\n";
         $report .= "   |     +- Air Ambulance team member          |\n";
         $report .= "   +-------------------------------------------+\n\n\n";
         }
      elseif ($coord_agency != '%')
         {
         $report .= "   +----------------------------------+\n";
         $report .= "   | Legend:                          |\n";
         $report .= "   |    -Aaa-drv- Lastname, Firstname |\n";
         $report .= "   |      ^   ^                       |\n";
         $report .= "   |      |   |                       |\n";
         $report .= "   |      |   +- Qualified driver     |\n";
         $report .= "   |      |                           |\n";
         $report .= "   |      +- aic/ALS                  |\n";
         $report .= "   +----------------------------------+\n\n\n";
         }
      $report .= "This report ONLY includes selected shifts.\n";
      if ($info_message) $report .= "$info_message\n";
      $report .= "\n";
      //
      // Save the coord_agency value specified in the request form, for use after the Day and Night loops.  In the
      // following Day and Night loops, the extract($row) statement will overwrite coord_agency.
      //
      $saved_coord_agency = $coord_agency;
      //
      for ($day_index = 1; $day_index <= $days_in_applicable_month; $day_index++)
         {
         if ($d[$day_index])
            {
            $day_description = date("jS \d\a\y (l):",mktime(9,0,0,$applicable_month_num,$day_index));
            $where_clause_2 = " and d$day_index='AVAILABLE' ";
            $sql_statement = stripslashes($base_sql_statement . " where " . $where_clause . $where_clause_2 . $presentation_clause);
            $result = $db_link->query($sql_statement) or die("Query failed with error:  " . mysqli_error($db_link));
            if ($num_rows = mysqli_num_rows($result))
               {
               $report .= $day_description . "\n";
               while ($row = mysqli_fetch_array($result))
                  {
                  if ($be_combined_agency_format == 'TRUE') $coord_agency = '';
                  $last_name = $first_name = $squad = $be_on_team_30 = $be_on_team_5 = $be_tda = $be_als = $be_third =
                     $be_nondriver = $be_needing_driver = "";
                  extract($row);
                  $report .= "   "
                     .  Properties
                           (
                           $db_link,
                           $be_on_team_5,
                           $be_on_team_30,
                           $be_on_team_air,
                           $be_tda,
                           $be_als,
                           $squad,
                           $coord_agency,
                           $be_third,
                           $be_nondriver,
                           $be_needing_driver,
                           $be_combined_agency_format
                           )
                     . " ";
                  $last_name = stripslashes($last_name);
                  $first_name = stripslashes($first_name);
                  if ($be_authority_for_this_agency)
                     {
                     $report .= "<a href=detail.phtml?a="
                        .  base64_encode($last_name)
                        .  "&b="
                        .  base64_encode($first_name)
                        .  "&c="
                        .  base64_encode($month_abbrev)
                        .  "&d="
                        .  base64_encode($be_authority_for_this_agency)
                        .  "&e="
                        .  base64_encode($coord_agency)
                        .  ">";
                     }
                  $report .= "$last_name, $first_name";
                  if ($be_authority_for_this_agency)
                     {
                     $report .= "</a>";
                     }
                  $report .= "\n";
                  }
               }
            else
               {
               $report .= $day_description . " None\n";
               }
            $report .= "\n";
            }
         }
      for ($night_index = 1; $night_index <= $days_in_applicable_month; $night_index++)
         {
         if ($n[$night_index])
            {
            $night_description = date("jS \\n\i\g\h\\t (l):",mktime(9,0,0,$applicable_month_num,$night_index));
            $where_clause_2 = " and n$night_index='AVAILABLE' ";
            $sql_statement = stripslashes($base_sql_statement . " where " . $where_clause . $where_clause_2 . $presentation_clause);
            $result = $db_link->query($sql_statement) or die("Query failed with error:  " . mysqli_error($db_link));
            if ($num_rows = mysqli_num_rows($result))
               {
               $report .= $night_description . "\n";
               while ($row = mysqli_fetch_array($result))
                  {
                  if ($be_combined_agency_format == 'TRUE') $coord_agency = '';
                  $last_name = $first_name = $squad = $be_on_team_30 = $be_on_team_5 = $be_tda = $be_als = $be_third =
                     $be_nondriver = $be_needing_driver = "";
                  extract($row);
                  $report .= "   "
                     .  Properties
                           (
                           $db_link,
                           $be_on_team_5,
                           $be_on_team_30,
                           $be_on_team_air,
                           $be_tda,
                           $be_als,
                           $squad,
                           $coord_agency,
                           $be_third,
                           $be_nondriver,
                           $be_needing_driver,
                           $be_combined_agency_format
                           )
                     . " ";
                  $last_name = stripslashes($last_name);
                  $first_name = stripslashes($first_name);
                  if ($be_authority_for_this_agency)
                     {
                     $report .= "<a href=detail.phtml?a="
                        .  base64_encode($last_name)
                        .  "&b="
                        .  base64_encode($first_name)
                        .  "&c="
                        .  base64_encode($month_abbrev)
                        .  "&d="
                        .  base64_encode($be_authority_for_this_agency)
                        .  "&e="
                        .  base64_encode($coord_agency)
                        .  ">";
                     }
                  $report .= "$last_name, $first_name";
                  if ($be_authority_for_this_agency)
                     {
                     $report .= "</a>";
                     }
                  $report .= "\n";
                  }
               }
            else
               {
               $report .= $night_description . " None\n";
               }
            $report .= "\n";
            }
         }
      $report .= "</pre>\n";
      //
      $coord_agency = $saved_coord_agency;
      //
      $report .= "<pre>--- END ---</pre><br>\n";
      $report .= "<small><i><pre>\$Id: perform-gen-report.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $</pre></i></small>\n";
      $report .= "</td></tr></table>\n";
      $report .= "</body>\n";
      $report .= "</html>\n";
      //
      // Calculate the expiration date for this report.  For the mktime() function, the 0th day of the month+1 resolves
      // to the last day of month.
      //
      $expiration_date = date("Y-m-d",mktime(0,0,0,$applicable_month_num,$expiration_day));
      //
      // Store the report in the cache.
      //
      $report = addslashes($report);
      $result = $db_link->query("insert into report_cache set digest='$digest', report='$report', expiration='$expiration_date'")
         or die("Report insertion failed with this error:  " . mysqli_error($db_link));
      }
   }
//
// Create the notice.
//
$result = $db_link->query
   (
   "select 1 "
   .  " from trusted_user "
   .  " where email_address='$email_addr' "
   .  "    and coord_agency like '$coord_agency' "
   )
   or die("Trust check failed with error:  " . mysqli_error($db_link));
if ($direct_approval = (mysqli_num_rows($result) || $be_authority_for_any_agency))
   {
   //
   // Then send an approval notice to the requestor directly.
   //
   $result = SendApprovalNotice($ini,$db_link,$email_addr,$digest);
   }
else
   {
   //
   // Someone else requested the report.  Notify the schedule coordinator.
   //
   $screen_notice_recipient = RoleEmailAddress($db_link,"schedule-coordinator",$coord_agency);
   $screen_notice_subject = "-> OSCAR request ->";
   //
   // Give the schedule coordinator a chance to approve (weakly or strongly) or disapprove of the request.
   //
   //                 0        1         2         3         4         5         6         7
   //                 123456789012345678901234567890123456789012345678901234567890123456789012
   $screen_notice =  "The OSCAR system has received a request for a(n) $coord_agency Availability\n";
   $screen_notice .= "Report from a user who identified him or herself as:\n\n";
   $screen_notice .= "   Name:           $name\n";
   $screen_notice .= "   Email address:  $email_addr\n\n";
   $screen_notice .= "The user gave this reason for the request:\n\n";
   $screen_notice .= "   " . wordwrap($reason,72,"\n   ") . "\n\n";
   $screen_notice .= "Please take one of the following actions:\n\n\n";
   $screen_notice .= "1. To MARK THIS USER AS TRUSTED (ie, approve this\n";
   $screen_notice .= "   and subsequent OSCAR requests from this user),\n";
   $screen_notice .= "   click here:\n";
   $screen_notice .= $ini[server][root_url] . "/approve-and-trust.phtml?digest=$digest&email_addr=$email_addr&coord_agency=$coord_agency\n\n\n";
   $screen_notice .= "2. To approve JUST THIS ONE request without\n";
   $screen_notice .= "   marking the user as trusted, click here:\n";
   $screen_notice .= $ini[server][root_url] . "/approve.phtml?digest=$digest&email_addr=$email_addr\n\n\n";
   $screen_notice .= "3. To DISAPPROVE the request, DO NOTHING.\n\n\n";
   $screen_notice .= "The report is available for review at:\n";
   $screen_notice .= $ini[server][root_url] . "/get-report.phtml?digest=$digest\n\n\n";
   //
   // Add sig lines.
   //
   $screen_notice .= "-- OSCAR\n";
   $screen_notice .= "-- Home page: " . $ini[server][host_url] . "/" . $ini[app][superapp] . "\n";
   $screen_notice .= "-- Sysadmin: " . RoleEmailAddress($db_link,"") . "\n";
   //
   // Then send a claim ticket to the requestor directly.
   //
   $claim_ticket_recipient = $email_addr;
   $claim_ticket_subject = "OSCAR claim ticket";
   //
   //                0        1         2         3         4         5         6         7
   //                123456789012345678901234567890123456789012345678901234567890123456789012
   $claim_ticket =  "Your request for an OSCAR Availability Report has been submitted to the\n";
   $claim_ticket .= "$coord_agency schedule coordinator for screening.  Check your email periodically\n";
   $claim_ticket .= "for approval.\n\n";
   $claim_ticket .= "Save this message.  It's the CLAIM TICKET for your report.\n\n";
   $claim_ticket .= "If excessive time goes by and you wish to escalate your request to a\n";
   $claim_ticket .= "higher authority, you can do so by clicking the link near the bottom of\n";
   $claim_ticket .= "this message.\n\n";
   $claim_ticket .= "   WARNING\n";
   $claim_ticket .= "   -------\n";
   $claim_ticket .= "   Do not escalate your request without due cause.  To do so is to\n";
   $claim_ticket .= "   'jump the chain of command', which is poor discipline and may be\n";
   $claim_ticket .= "   punishable.  The option to escalate is provided for cases where the\n";
   $claim_ticket .= "   primary schedule coordinator is unable to respond in a timely manner.\n";
   $claim_ticket .= "   Generally, it is better to wait for the regular approval notice.\n\n";
   $claim_ticket .= "The next authority in the chain is:\n\n";
   $claim_ticket .= "   " . RoleEmailAddress($db_link,"escalation-level-1-recipient",$coord_agency) . "\n\n";
   $claim_ticket .= "To escalate your request to the above\n";
   $claim_ticket .= "authority, click here:\n\n";
   $claim_ticket .= $ini[server][root_url] . "/escalate.phtml?level=1&digest=$digest&name=" . urlencode($name) . "&email_addr=$email_addr&coord_agency=$coord_agency\n\n";
   //
   // Add sig lines.
   //
   $claim_ticket .= "-- OSCAR\n";
   $claim_ticket .= "-- Home page: " . $ini[server][host_url] . "/" . $ini[app][superapp] . "\n";
   $claim_ticket .= "-- Sysadmin: " . RoleEmailAddress($db_link,"") . "\n";
   //
   // Send the mail.
   //
   kix\k::SmtpMailSend
     (
     RoleEmailAddress($db_link,""), //from
     $screen_notice_recipient, //to
     $screen_notice_subject, //subject
     $screen_notice, //message_string
     false, //be_html
     "", //cc
     "", //bcc
     RoleEmailAddress($db_link,"") //reply_to
     );
   kix\k::SmtpMailSend
     (
     RoleEmailAddress($db_link,""), //from
     $claim_ticket_recipient, //to
     $claim_ticket_subject, //subject
     $claim_ticket, //message_string
     false, //be_html
     "", //cc
     "", //bcc
     RoleEmailAddress($db_link,"") //reply_to
     );
   $result = true;
   }
if ($result)
   {
   PutLibPhotoRandomPlaced($ini,$dbkalipso_link,"oscarsystem",1,"right");
   if ($direct_approval)
      {
      if ($relay == "TRUE")
         {
         echo "<p><b>Your Post-Relay Report has just been generated.</b></p>\n"
            . "<blockquote>Because the report contains personal information, an "
            . "access link has been sent to your email address ($email_addr).</blockquote>\n";
         }
      else
         {
         echo "<p><b>Success!</b></p>\n"
            . "<blockquote>OSCAR has generated your report.&nbsp; Because the report contains personal information, an "
            . "access link has been sent to your email address ($email_addr).</blockquote>\n";
         }
      echo "<p><b>Check your email periodically for a message with the link to the report.</b></p>\n";
      //
      if ($relay == "TRUE")
         {
         echo "<p><b>Identifying relayed records</b></p>\n"
            . "<blockquote>In your post-relay report, records relayed from EMS will be annotated with the text:\n"
            . "<blockquote><tt>mesg(RELAY)...Relayed&nbsp;by&nbsp;EMS</tt></blockquote></blockquote>\n";
         }
      //
      echo "<p><b>Security note</b></p>\n"
         . "<blockquote>Because you are an OSCAR Authority or a Trusted User, your request does not need to be "
         . "screened.&nbsp; Requests from regular users, however, must be screened by a schedule coordinator or an "
         . "escalation authority prior to fulfillment.</blockquote>\n";
      }
   else
      {
      echo "<p><b>Success!</b></p>\n"
         . "<blockquote>OSCAR has successfully generated your report.&nbsp;  Because the report contains personal "
         . "information, a screening notice has been sent to the <a href=mailto:\""
         . RoleEmailAddress($db_link,"schedule-coordinator",$coord_agency)
         . "\">$coord_agency Schedule Coordinator</a>.&nbsp; The coordinator will forward the report to you once "
         . "screening is complete.</blockquote>";
      echo "<p><b>Check your email periodically for the report.</b></p>";
      }
   echo "<p>If you have feedback about the technical aspects of this process, please contact the <a href=mailto:\""
      . RoleEmailAddress($db_link,"")
      . "\">OSCAR System Administrator</a>.</p>";
   //
   if ("" != "")
      {
      echo "<pre>\n"
         . "condition_descriptor\n"
         . "--------------------\n"
         . "$condition_descriptor\n\n"
         . "digest: $digest\n"
         . "</pre>\n";
      }
   //
   }
else
   {
   //
   // Fill the page out with a warning and instructions.
   //
   ?>
   <h2><i>Error!</i></h2>
   <b>
   <blockquote>
      <p>The OSCAR system encountered an internal error while processing your request.  Please do the following:</p>
      <ul>
         <?
         echo "<li><p>Use another method (like email or telephone) to ask the <a href=mailto:\""
            . RoleEmailAddress($db_link,"schedule-coordinator",$coord_agency)
            . "\">$coord_agency Schedule Coordinator</a> for the information you need.</p>";
         echo "<li><p>Let the <a href=mailto:\""
            . RoleEmailAddress($db_link,"")
            . "?subj=\"OSCAR Bug Report\">OSCAR System Administrator</a> know this error occurred.</p>";
         ?>
      </ul>
   </blockquote>            
   </b>
   <?
   }
}
else
   {
   //
   // Fill the page out with a warning and instructions.
   //
   ?>
   <h2><i>Error!</i></h2>
   <b>
   <blockquote>
      <p>You did not supply one or more of the required parameters.&nbsp; You must supply values for these fields:</p>
      <ul>
         <li><p>Name</p>
         <li><p>Email address</p>
         <li><p>Applicable month</p>
         <li><p>Coordinating agency</p>
      </ul>
      <p>Please press your browser's [<--&nbsp;BACK] button to correct the problems.</p>
   </blockquote>            
   </b>
   <?
   echo "<p>If you have feedback about the technical aspects of this process, please contact the <a href=mailto:\""
      . RoleEmailAddress($db_link,"")
      . "\">OSCAR System Administrator</a>.</p>";
   }
?>
<hr>
<p><small><small><em><pre>$Id: perform-gen-report.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $</pre></em></small></small>
</td>
</tr>
</table>
</body>
</html>
