<?
//
// $Id: perform-set-role.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $
//
// Emulate register_globals on
if (!ini_get('register_globals'))
  {
  $superglobals = array($_SERVER,$_ENV,$_FILES,$_COOKIE,$_POST,$_GET);
  if (isset($_SESSION))
    {
    array_unshift($superglobals, $_SESSION);
    }
  foreach ($superglobals as $superglobal)
    {
    extract($superglobal, EXTR_SKIP);
    }
  }
//
// Assign passed-in arguments to themselves to prevent 'undefined var' warnings later.
//
$a = $a;
$b = $b;
$c = $c;
//
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_oscarmailheaders.phtml");
//
$ini = AppSettings();
$db_link = DbLink($ini);
$dbkalipso_link = DbkalipsoLink($ini);
//
if ($ini[app][do_report_all_errors]) error_reporting(E_ALL);
//
?>
<html>
<head><title>Role Modification Confirmation</title></head>
<? BodyOpen(); ?>
<table align=center width=80%><tr><td>
<H6 ALIGN=CENTER>KVEO-IT-PROJECT<br><a href="javascript:close();">OSCAR SYSTEM</a><br><a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></H6>
<H1 ALIGN=CENTER>Role Modification Confirmation</H1>
<hr>
<?
//
// Decode the arguments.
//
$agency = kix\k::Safe(base64_decode($a),kix\k::PhpValueOf_safe_hint_type("ALPHANUM"));
$role = kix\k::Safe(base64_decode($b),kix\k::PhpValueOf_safe_hint_type("HYPHENATED_ALPHANUM"));
$new_email_addr = kix\k::Safe(base64_decode($c),kix\k::PhpValueOf_safe_hint_type("EMAIL_ADDRESS"));
//
   //
   // Determine whether or not the specified role is defined.
   //
   $result = $db_link->query("select 1 from authority where coord_agency='$agency' and role='$role' ")
      or die("Role existence check failed with error: " . mysqli_error($db_link));
   if (mysqli_num_rows($result))
      {
      //
      // This role is already defined.  Update it.
      //
      $db_link->query
         (
         "update authority "
         .  "set email_addr='$new_email_addr' "
         .  "where coord_agency = '$agency' "
         .  "   and role = '$role' "
         )
         or die("Update failed with error:  " . mysqli_error($db_link));
      }
   else
      {
      //
      // The role is undefined.  Insert a new record.
      //
      if ($role == "egroup-manager")
         {
         $has_clearance = "FALSE";
         }
      else
         {
         $has_clearance = "TRUE";
         }
      $db_link->query
         (
         "insert into authority "
         .  " set coord_agency = '$agency' "
         .  "    , role = '$role' "
         .  "    , email_addr = '$new_email_addr' "
         .  "    , has_clearance = '$has_clearance' "
         )
         or die("Insert failed with error:  " . mysqli_error($db_link));
      }
   //
   PutLibPhotoRandomPlaced($ini,$dbkalipso_link,"oscarsystem",1,"right");
   echo "<p>OSCAR has accepted the new role setting.</p>\n";
   echo "<p>If you have feedback about the technical aspects of this process, please contact the <a href=mailto:\""
      . RoleEmailAddress($db_link,"")
      . "\">OSCAR System Administrator</a>.</p>";
?>
<hr>
<p><small><small><em><pre>$Id: perform-set-role.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $</pre></em></small></small>
</td>
</tr>
</table>
</body>
</html>
