<?
//
// $Id$
//
require_once("f_oscarhomepageurl.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
?>
<html>

<head><title>OSCAR - Privacy Policy</title></head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
           <h6 align="center">
              KVEO-IT-PROJECT - <a href="<? echo OscarHomePageUrl(); ?>">OSCAR SYSTEM</a></h6>
           <h1 align="center">Privacy Policy</h1>
        <hr>
        <h3>The short version</h3><? PutLibPhotoRandomPlaced("sasquatch",1,"right"); ?>
        <blockquote>
           <p>The OSCAR system (which does not include <a href=http://kalipso.phpwebhosting.com/photolib/index.phtml>Kevin Andrew 
              Lipscomb's photography archive</a>) was designed to enhance the efforts of the Virginia Beach Department of 
              EMS (VBDEMS) to schedule its large community of autonomous members.&nbsp; With one exception, none of the 
              information collected by the OSCAR system will be used <i>for any other purpose</i>.</p>
           <p>The exception is that email addresses collected by the OSCAR system may be added to mailing lists owned and
              operated by VBDEMS, the Council of Virginia Beach Volunteer Rescue Squads, Inc., or any of the volunteer 
              rescue squads of Virginia Beach.&nbsp; You will always have the option of unsubscribing from any such 
              lists.</p>
           <p>We will notify you ahead of time if we change any of the above.</p>
           <p>You (or someone familiar with HTML, PHP, and MySQL) can verify the veracity of these claims by browsing the
              production source code at <<a href=http://cvs.sourceforge.net/cgi-bin/viewcvs.cgi/kveo-it-project/oscar/>http://cvs.sourceforge.net/cgi-bin/viewcvs.cgi/kveo-it-project/oscar/</a>>.</p>
        </blockquote>
        <h3>The long version</h3>
        <blockquote>
           <p>The OSCAR system web service is designed, maintained, and managed by:
           <blockquote>
              Kevin Andrew Lipscomb<br>
              4708 Sweetwood Court<br>
              Virginia Beach, VA 23462<br>
              +1-757-270-9994<br>
              <?
              $email_address = RoleEmailAddress("");
              echo "<a href=mailto:\"$email_address\">$email_address</a>"
              ?>
           </blockquote>
           <p><a href=http://kalipso.phpwebhosting.com/photolib/index.phtml>Kevin Andrew Lipscomb's photography archive</a> is 
              accessible from, but is not a part of, the OSCAR system.</p>
           <p>To prevent fraud and abuse, the OSCAR system automatically recognizes the IP address of each visitor who 
              submits availability information.</p>
           <p>The information we collect is (a) used to enhance the efforts of the Virginia Beach Department of EMS 
              (VBDEMS) to schedule its large community of autonomous members, (b) used to update mailing lists owned and
              operated by VBDEMS, the Council of Virginia Beach Volunteer Rescue Squads, Inc., or any of the volunteer 
              rescue squads of Virginia Beach, (c) then discarded.&nbsp; The information we collect is not shared with 
              any other organizations, nor is it used for any other purpose.&nbsp; You will always have the option of
              unsubscribing from any of the aforementioned lists.</p>
           <p>We do not use "cookies", "web bugs", or any similar technology.</p>
           <? PutLibPhotoRandomPlaced("sasquatch",1,"left"); ?>
           <p>We do not partner with or have special relationships with any ad server companies.</p>
           <p>From time to time, we may use visitor information for new, unanticipated uses not previously disclosed in 
              our privacy notice.&nbsp; If our information practices change at some time in the future we will contact you
              before we use your data for these new purposes to notify you of the policy change and to provide you with 
              the ability to opt out of these new uses.</p>
           <p>Upon request we provide site visitors with access to all information (including proprietary information) 
              that we maintain about them.&nbsp; Any visitor can also access this information by requesting an availability
              report in which the visitor is listed and clicking on his or her name.</p>
           <p>Visitors can have this information corrected by sending us e-mail at the above address, calling us at the 
              above telephone number, or writing to us at the above address.</p>
           <p>With respect to security: The information we collect is stored in an online database that is accessible only
              (a) under OSCAR system control via its web-based user interface; (b) under password control by the OSCAR 
              System Administrator; (b) by the OSCAR system hosting service, currently a company called PhpWebHosting.com,
              which maintains its own privacy policy at 
              <a href=http://www.phpwebhosting.com/priv.html>http://www.phpwebhosting.com/priv.html</a>.</p>
           <p>You (or someone familiar with HTML, PHP, and MySQL) can verify the veracity of these claims by browsing the
              production source code at <<a href=http://cvs.sourceforge.net/cgi-bin/viewcvs.cgi/kveo-it-project/oscar/>http://cvs.sourceforge.net/cgi-bin/viewcvs.cgi/kveo-it-project/oscar/</a>>.</p>
           <p>If you feel that this site is not following its stated information policy, you may contact us at the 
              aforementioned postal address, email addresses, or phone number, or you may contact the service sponsor as
              follows:</p>
              <blockquote>
              Virginia Beach Department of EMS<br>
              1917 Arctic Avenue<br>
              Virginia Beach, VA 23451<br>
              +1-757-437-4850<br>
              <a href=mailto:ems@vbgov.com>ems@vbgov.com</a><br>
              <a href=http://www.vabeachems.com>www.VaBeachEMS.com</a>
              </blockquote>
           </blockquote>
        <hr>
        <p><small><small><em><pre>$Id$</pre></em></small></small></center></td>
    </tr>
  </table>
</body>

</html>

