CREATE TABLE avail_sheet
   (
   month ENUM("JAN","FEB","MAR","APR","MAY","JUN","JUL","AUG","SEP","OCT","NOV","DEC") not null,
   cad_num CHAR (6) not null,
   timestamp TIMESTAMP not null,
   last_name VARCHAR (32) not null,
   first_name VARCHAR (32),
   email_addr VARCHAR (64) not null,
   squad ENUM("ERS","1","2","4","5","6","9","13","14","15","16","17")  not null,
   be_on_team_5 ENUM("FALSE","TRUE") not null,
   be_on_team_30 ENUM("FALSE","TRUE") not null,
   num_extras TINYINT,
   note TEXT,
   d1 ENUM("","AVAILABLE"),
   d2 ENUM("","AVAILABLE"),
   d3 ENUM("","AVAILABLE"),
   d4 ENUM("","AVAILABLE"),
   d5 ENUM("","AVAILABLE"),
   d6 ENUM("","AVAILABLE"),
   d7 ENUM("","AVAILABLE"),
   d8 ENUM("","AVAILABLE"),
   d9 ENUM("","AVAILABLE"),
   d10 ENUM("","AVAILABLE"),
   d11 ENUM("","AVAILABLE"),
   d12 ENUM("","AVAILABLE"),
   d13 ENUM("","AVAILABLE"),
   d14 ENUM("","AVAILABLE"),
   d15 ENUM("","AVAILABLE"),
   d16 ENUM("","AVAILABLE"),
   d17 ENUM("","AVAILABLE"),
   d18 ENUM("","AVAILABLE"),
   d19 ENUM("","AVAILABLE"),
   d20 ENUM("","AVAILABLE"),
   d21 ENUM("","AVAILABLE"),
   d22 ENUM("","AVAILABLE"),
   d23 ENUM("","AVAILABLE"),
   d24 ENUM("","AVAILABLE"),
   d25 ENUM("","AVAILABLE"),
   d26 ENUM("","AVAILABLE"),
   d27 ENUM("","AVAILABLE"),
   d28 ENUM("","AVAILABLE"),
   d29 ENUM("","AVAILABLE"),
   d30 ENUM("","AVAILABLE"),
   d31 ENUM("","AVAILABLE"),
   n1 ENUM("","AVAILABLE"),
   n2 ENUM("","AVAILABLE"),
   n3 ENUM("","AVAILABLE"),
   n4 ENUM("","AVAILABLE"),
   n5 ENUM("","AVAILABLE"),
   n6 ENUM("","AVAILABLE"),
   n7 ENUM("","AVAILABLE"),
   n8 ENUM("","AVAILABLE"),
   n9 ENUM("","AVAILABLE"),
   n10 ENUM("","AVAILABLE"),
   n11 ENUM("","AVAILABLE"),
   n12 ENUM("","AVAILABLE"),
   n13 ENUM("","AVAILABLE"),
   n14 ENUM("","AVAILABLE"),
   n15 ENUM("","AVAILABLE"),
   n16 ENUM("","AVAILABLE"),
   n17 ENUM("","AVAILABLE"),
   n18 ENUM("","AVAILABLE"),
   n19 ENUM("","AVAILABLE"),
   n20 ENUM("","AVAILABLE"),
   n21 ENUM("","AVAILABLE"),
   n22 ENUM("","AVAILABLE"),
   n23 ENUM("","AVAILABLE"),
   n24 ENUM("","AVAILABLE"),
   n25 ENUM("","AVAILABLE"),
   n26 ENUM("","AVAILABLE"),
   n27 ENUM("","AVAILABLE"),
   n28 ENUM("","AVAILABLE"),
   n29 ENUM("","AVAILABLE"),
   n30 ENUM("","AVAILABLE"),
   n31 ENUM("","AVAILABLE"),
   PRIMARY KEY (month, cad_num, timestamp)
   )
