<?
//
// $Id$
//
require_once("f_oscarhomepageurl.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("f_bodyopen.phtml");
require_once("f_password.phtml");
?>
<html>
<head><title>Report generation</title></head>
<? BodyOpen(); ?>
<table align=center width="80%"><tr><td>
<H6 ALIGN="CENTER">KVEO-IT-PROJECT<br><a href="<? echo OscarHomePageUrl(); ?>">OSCAR</a><br><a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></H6>
<H1 ALIGN="CENTER">Report generation</H1>
<hr>
<?
mysql_connect(localhost,kalipso,Password());
mysql_select_db(oscar);
//
$base_sql_statement = "select cad_num, last_name, first_name, squad, be_on_team_30, be_on_team_5, note from avail_sheet ";
$presentation_clause = "order by be_on_team_5 desc, be_on_team_30 desc, squad";
$where_clause = "";
if ($report_type == "FULL")
   {
   $where_clause = "month='$month' ";
   echo "<pre>\n";
   echo "Full availability report for $month generated " . date("l Y-M-d H:i:s T") . "\n\n";
   echo "Legend:\n";
   echo "   -5-    : EMS-5 team member\n";
   echo "   -30-   : Squad truck team member\n";
   echo "   Rxx    : Home rescue squad\n";
   echo "   ERS    : VBFD firefighter\n";
   echo "   8xxxxx : Officer code (also 7xxxxx)\n";
   echo "   *      : See Notes section for special request.\n\n\n";
   for ($index = 1; $index <= 31; $index++)
      {
      $where_clause_2 = "and d$index='AVAILABLE' ";
      $sql_statement = stripslashes($base_sql_statement . "where " . $where_clause . $where_clause_2 . $presentation_clause);
      $result = mysql_query($sql_statement) or die("Query failed with error:  " . mysql_error());
      if ($num_rows = mysql_num_rows($result))
         {
         echo "$index day:\n";
         while ($row = mysql_fetch_array($result))
            {
            extract($row);
            echo "   -";
            if ($be_on_team_5) echo "5"; else echo "-";
            echo "-";
            if ($be_on_team_30) echo "30"; else echo "--";
            echo "- ";
            if ($squad != "ERS") $squad = sprintf("R%02s",$squad);
            printf("%3s %6s %s, %s ",$squad,$cad_num,$last_name,$first_name);
            if ($note != "") echo "*";
            echo "\n";
            $cad_num = $last_name = $first_name = $squad = $be_on_team_30 = $be_on_team_5 = $note = "";
            }
         }
      else
         {
         echo "$index day: None\n";
         }
      echo "\n";
      }
   for ($index = 1; $index <= 31; $index++)
      {
      $where_clause_2 = "and n$index='AVAILABLE' ";
      $sql_statement = stripslashes($base_sql_statement . "where " . $where_clause . $where_clause_2 . $presentation_clause);
      $result = mysql_query($sql_statement) or die("Query failed with error:  " . mysql_error());
      if ($num_rows = mysql_num_rows($result))
         {
         echo "$index night:\n";
         while ($row = mysql_fetch_array($result))
            {
            extract($row);
            echo "   -";
            if ($be_on_team_5) echo "5"; else echo "-";
            echo "-";
            if ($be_on_team_30) echo "30"; else echo "--";
            echo "- ";
            if ($squad != "ERS") $squad = sprintf("R%02s",$squad);
            printf("%3s %6s %s, %s ",$squad,$cad_num,$last_name,$first_name);
            if ($note != "") echo "*";
            echo "\n";
            $cad_num = $last_name = $first_name = $squad = $be_on_team_30 = $be_on_team_5 = $note = "";
            }
         }
      else
         {
         echo "$index night: None\n";
         }
      echo "\n";
      }
   ?>
   </pre>
   <h3><u>Notes</u></h3>
   <?
   $result = mysql_query("select cad_num, last_name, first_name, squad, be_on_team_30, be_on_team_5, note from avail_sheet where month=\"$month\" and note != \"\" order by last_name, first_name") or die("Query failed with error:  " . mysql_error());
   if ($num_rows = mysql_num_rows($result))
      {
      while ($row = mysql_fetch_array($result))
         {
         extract($row);
         echo "$last_name, $first_name [-";
         if ($be_on_team_5) echo "5"; else echo "-";
         echo "-";
         if ($be_on_team_30) echo "30"; else echo "--";
         echo "- ";
         if ($squad != "ERS") $squad = sprintf("R%02s",$squad);
         echo "$squad $cad_num]\n";
         echo "<blockquote><i>" . stripslashes($note) . "<br></i></blockquote>";
         $cad_num = $last_name = $first_name = $squad = $be_on_team_30 = $be_on_team_5 = $note = "";
         }
      }
   else
      {
      echo "None\n";
      }
   }
else
   {
//   if ($div_spec_criteria != "")
//      {
//      $where_clause = $where_clause . "div_spec $div_spec_criteria ";
//      }
//   if ($frame_num_criteria != "")
//      {
//      if ($where_clause != "")
//         {
//         $where_clause = $where_clause . "and ";
//         }
//      $where_clause = $where_clause . "frame_num $frame_num_criteria ";
//      }
//   if ($be_avail_as_huge_criteria != "")
//      {
//      if ($where_clause != "")
//         {
//         $where_clause = $where_clause . "and ";
//         }
//      $where_clause = $where_clause . "be_avail_as_huge $be_avail_as_huge_criteria ";
//      }
//   if ($caption_criteria != "")
//      {
//      if ($where_clause != "")
//         {
//         $where_clause = $where_clause . "and ";
//         }
//      $where_clause = $where_clause . "caption $caption_criteria ";
//      }
//   if ($tech_details_criteria != "")
//      {
//      if ($where_clause != "")
//         {
//         $where_clause = $where_clause . "and ";
//         }
//      $where_clause = $where_clause . "tech_details $tech_details_criteria ";
//      }
//   if ($era_criteria != "")
//      {
//      if ($where_clause != "")
//         {
//         $where_clause = $where_clause . "and ";
//         }
//      $where_clause = $where_clause . "era $era_criteria ";
//      }
//   if ($copyright_year_criteria != "")
//      {
//      if ($where_clause != "")
//         {
//         $where_clause = $where_clause . "and ";
//         }
//      $where_clause = $where_clause . "copyright_year $copyright_year_criteria ";
//      }
//   if ($hits_criteria != "")
//      {
//      if ($where_clause != "")
//         {
//         $where_clause = $where_clause . "and ";
//         }
//      $where_clause = $where_clause . "hits $hits_criteria ";
//      }
//   if ($keywords_criteria != "")
//      {
//      if ($where_clause != "")
//         {
//         $where_clause = $where_clause . "and ";
//         }
//      $where_clause = $where_clause . "keywords $keywords_criteria ";
//      }
//   if ($placement_criteria != "")
//      {
//      if ($where_clause != "")
//         {
//         $where_clause = $where_clause . "and ";
//         }
//      $where_clause = $where_clause . "placement $placement_criteria ";
//      }
   }
//
?>
</td></tr></table>
</body>
</html>
