<?
//
// $Id$
//
require_once("f_oscarhomepageurl.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("f_bodyopen.phtml");
require_once("f_password.phtml");
// require_once("f_roleemailaddress");
//
$msg = "<html>\n";
$msg .= "<head><title>Report generation</title></head>\n";
$msg .= BodyOpen() . "\n";
$msg .= "<table align=center width=80%><tr><td>\n";
$msg .= "<H6 ALIGN=CENTER>KVEO-IT-PROJECT<br><a href=" . OscarHomePageUrl() . ">OSCAR</a><br><a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></H6>\n";
$msg .= "<H1 ALIGN=CENTER>Report generation</H1>\n";
$msg .= "<hr>\n";
//
mysql_connect(localhost,kalipso,Password());
mysql_select_db(oscar);
//
$presentation_clause = "order by be_on_team_5 desc, be_on_team_30 desc, squad";
$month_num = date("n");
$year_num = date("Y");
if ($relative_month == "NEXT")
   {
   if ($month_num < 12)
      {
      $month_num++;
      }
   else
      {
      $month_num = 1;
      $year_num++;
      }
   }
switch ($month_num)
   {
   case 1: $month_word = "JANUARY"; break;
   case 2: $month_word = "FEBRUARY"; break;
   case 3: $month_word = "MARCH"; break;
   case 4: $month_word = "APRIL"; break;
   case 5: $month_word = "MAY"; break;
   case 6: $month_word = "JUNE"; break;
   case 7: $month_word = "JULY"; break;
   case 8: $month_word = "AUGUST"; break;
   case 9: $month_word = "SEPTEMBER"; break;
   case 10: $month_word = "OCTOBER"; break;
   case 11: $month_word = "NOVEMBER"; break;
   case 12: $month_word = "DECEMBER"; break;
   }
$where_clause = "month='" . substr($month_word,0,3) ."' ";
if ($report_type == "FULL")
   {
   $base_sql_statement = "select cad_num, last_name, first_name, squad, be_on_team_30, be_on_team_5, note from avail_sheet ";
   $msg .= "<pre>\n";
   $msg .= "Full availability report for $month_word generated " . date("l Y-M-d H:i:s T") . "\n\n";
   $msg .= "   +--------------------------------------------+\n";
   $msg .= "   | Legend:                                    |\n";
   $msg .= "   |    -5-30- Rxx 8xxxxx Lastname, Firstname * |\n";
   $msg .= "   |     ^  ^   ^    ^                        ^ |\n";
   $msg .= "   |     |  |   |    |                        | |\n";
   $msg .= "   |     |  |   |    +- Officer code          | |\n";
   $msg .= "   |     |  |   |       (also 7xxxxx)         | |\n";
   $msg .= "   |     |  |   |                             | |\n";
   $msg .= "   |     |  |   +- Home rescue squad          | |\n";
   $msg .= "   |     |  |      (ERS for VBFD)             | |\n";
   $msg .= "   |     |  |                                 | |\n";
   $msg .= "   |     |  +- Squad truck team member        | |\n";
   $msg .= "   |     |                                    | |\n";
   $msg .= "   |     +- EMS-5 team member                 | |\n";
   $msg .= "   |                                          | |\n";
   $msg .= "   |    See special request in Notes section -+ |\n";
   $msg .= "   +--------------------------------------------+\n\n\n";
   $msg .= "Days\n";
   $msg .= "----\n\n";
   for ($day_index = 1; $day_index <= 31; $day_index++)
      {
      $day_description = date("jS (l)",mktime(9,0,0,$month_num,$day_index,$year_num)) . " day:";
      $where_clause_2 = "and d$day_index='AVAILABLE' ";
      $sql_statement = stripslashes($base_sql_statement . "where " . $where_clause . $where_clause_2 . $presentation_clause);
      $result = mysql_query($sql_statement) or die("Query failed with error:  " . mysql_error());
      if ($num_rows = mysql_num_rows($result))
         {
         $msg .= $day_description . "\n";
         while ($row = mysql_fetch_array($result))
            {
            extract($row);
            $msg .= "   -";
            if ($be_on_team_5) $msg .= "5"; else $msg .= "-";
            $msg .= "-";
            if ($be_on_team_30) $msg .= "30"; else $msg .= "--";
            $msg .= "- ";
            if ($squad != "ERS") $squad = sprintf("R%02s",$squad);
            $msg .= sprintf("%3s %6s %s, %s ",$squad,$cad_num,$last_name,$first_name);
            if ($note != "") $msg .= "*";
            $msg .= "\n";
            $cad_num = $last_name = $first_name = $squad = $be_on_team_30 = $be_on_team_5 = $note = "";
            }
         }
      else
         {
         $msg .= $day_description . " None\n";
         }
      $msg .= "\n";
      }
   $msg .= "\n";
   $msg .= "Nights\n";
   $msg .= "------\n\n";
   for ($night_index = 1; $night_index <= 31; $night_index++)
      {
      $night_description = date("jS (l)",mktime(21,0,0,$month_num,$night_index,$year_num)) . " night:";
      $where_clause_2 = "and n$night_index='AVAILABLE' ";
      $sql_statement = stripslashes($base_sql_statement . "where " . $where_clause . $where_clause_2 . $presentation_clause);
      $result = mysql_query($sql_statement) or die("Query failed with error:  " . mysql_error());
      if ($num_rows = mysql_num_rows($result))
         {
         $msg .= $night_description . "\n";
         while ($row = mysql_fetch_array($result))
            {
            extract($row);
            $msg .= "   -";
            if ($be_on_team_5) $msg .= "5"; else $msg .= "-";
            $msg .= "-";
            if ($be_on_team_30) $msg .= "30"; else $msg .= "--";
            $msg .= "- ";
            if ($squad != "ERS") $squad = sprintf("R%02s",$squad);
            $msg .= sprintf("%3s %6s %s, %s ",$squad,$cad_num,$last_name,$first_name);
            if ($note != "") $msg .= "*";
            $msg .= "\n";
            $cad_num = $last_name = $first_name = $squad = $be_on_team_30 = $be_on_team_5 = $note = "";
            }
         }
      else
         {
         $msg .= $night_description . " None\n";
         }
      $msg .= "\n";
      }
   $msg .= "</pre>\n";
   $msg .= "<h3><u>Notes</u></h3>\n";
   $result = mysql_query("select cad_num, last_name, first_name, squad, be_on_team_30, be_on_team_5, note from avail_sheet where month=\"" . substr($month_word,0,3) . "\" and note != \"\" order by last_name, first_name") or die("Query failed with error:  " . mysql_error());
   if ($num_rows = mysql_num_rows($result))
      {
      while ($row = mysql_fetch_array($result))
         {
         extract($row);
         $msg .= "$last_name, $first_name&nbsp; [-";
         if ($be_on_team_5) $msg .= "5"; else $msg .= "-";
         $msg .= "-";
         if ($be_on_team_30) $msg .= "30"; else $msg .= "--";
         $msg .= "- ";
         if ($squad != "ERS") $squad = sprintf("R%02s",$squad);
         $msg .= "$squad $cad_num]\n";
         $msg .= "<blockquote><i>" . stripslashes($note) . "</i></blockquote>\n<br>";
         $cad_num = $last_name = $first_name = $squad = $be_on_team_30 = $be_on_team_5 = $note = "";
         }
      }
   else
      {
      $msg .= "None\n";
      }
   }
else
   {
   //
   // Filtered report
   //
   $base_sql_statement = "select cad_num, last_name, first_name, squad, be_on_team_30, be_on_team_5 from avail_sheet ";
   switch ($team_filter)
      {
      case "team_5_only":
         $where_clause .= "and be_on_team_5 = 'TRUE' ";
         $info_message = "As requested, this report ONLY includes EMS-5 team members.";
         break;
      case "team_30_only":
         $where_clause .= "and be_on_team_30 = 'TRUE' ";
         $info_message = "As requested, this report ONLY includes SQUAD TRUCK team members.";
         break;
      }
   //
   // Convert sequence of day/night scalars into 1-based arrays for easier looping later.
   //
   $d = array(1 => $d1,$d2,$d3,$d4,$d5,$d6,$d7,$d8,$d9,$d10,$d11,$d12,$d13,$d14,$d15,$d16,$d17,$d18,$d19,$d20,$d21,$d22,$d23,$d24,$d25,$d26,$d27,$d28,$d29,$d30,$d31);
   $n = array(1 => $n1,$n2,$n3,$n4,$n5,$n6,$n7,$n8,$n9,$n10,$n11,$n12,$n13,$n14,$n15,$n16,$n17,$n18,$n19,$n20,$n21,$n22,$n23,$n24,$n25,$n26,$n27,$n28,$n29,$n30,$n31);
   //
   $msg .= "<pre>\n";
   $msg .= "Filtered availability report for $month_word generated " . date("l Y-M-d H:i:s T") . "\n\n";
   $msg .= "   +------------------------------------------+\n";
   $msg .= "   | Legend:                                  |\n";
   $msg .= "   |    -5-30- Rxx 8xxxxx Lastname, Firstname |\n";
   $msg .= "   |     ^  ^   ^    ^                        |\n";
   $msg .= "   |     |  |   |    |                        |\n";
   $msg .= "   |     |  |   |    +- Officer code          |\n";
   $msg .= "   |     |  |   |       (also 7xxxxx)         |\n";
   $msg .= "   |     |  |   |                             |\n";
   $msg .= "   |     |  |   +- Home rescue squad          |\n";
   $msg .= "   |     |  |      (ERS for VBFD)             |\n";
   $msg .= "   |     |  |                                 |\n";
   $msg .= "   |     |  +- Squad truck team member        |\n";
   $msg .= "   |     |                                    |\n";
   $msg .= "   |     +- EMS-5 team member                 |\n";
   $msg .= "   +------------------------------------------+\n\n\n";
   if ($info_message) $msg .= "$info_message\n\n";
   for ($day_index = 1; $day_index <= 31; $day_index++)
      {
      if ($d[$day_index])
         {
         $day_description = date("jS (l)",mktime(9,0,0,$month_num,$day_index,$year_num)) . " day:";
         $where_clause_2 = "and d$day_index='AVAILABLE' ";
         $sql_statement = stripslashes($base_sql_statement . "where " . $where_clause . $where_clause_2 . $presentation_clause);
         $result = mysql_query($sql_statement) or die("Query failed with error:  " . mysql_error());
         if ($num_rows = mysql_num_rows($result))
            {
            $msg .= $day_description . "\n";
            while ($row = mysql_fetch_array($result))
               {
               extract($row);
               $msg .= "   -";
               if ($be_on_team_5) $msg .= "5"; else $msg .= "-";
               $msg .= "-";
               if ($be_on_team_30) $msg .= "30"; else $msg .= "--";
               $msg .= "- ";
               if ($squad != "ERS") $squad = sprintf("R%02s",$squad);
               $msg .= sprintf("%3s %6s %s, %s",$squad,$cad_num,$last_name,$first_name);
               $msg .= "\n";
               $cad_num = $last_name = $first_name = $squad = $be_on_team_30 = $be_on_team_5 = "";
               }
            }
         else
            {
            $msg .= $day_description . " None\n";
            }
         $msg .= "\n";
         }
      }
   for ($night_index = 1; $night_index <= 31; $night_index++)
      {
      if ($n[$night_index])
         {
         $night_description = date("jS (l)",mktime(9,0,0,$month_num,$night_index,$year_num)) . " night:";
         $where_clause_2 = "and n$night_index='AVAILABLE' ";
         $sql_statement = stripslashes($base_sql_statement . "where " . $where_clause . $where_clause_2 . $presentation_clause);
         $result = mysql_query($sql_statement) or die("Query failed with error:  " . mysql_error());
         if ($num_rows = mysql_num_rows($result))
            {
            $msg .= $night_description . "\n";
            while ($row = mysql_fetch_array($result))
               {
               extract($row);
               $msg .= "   -";
               if ($be_on_team_5) $msg .= "5"; else $msg .= "-";
               $msg .= "-";
               if ($be_on_team_30) $msg .= "30"; else $msg .= "--";
               $msg .= "- ";
               if ($squad != "ERS") $squad = sprintf("R%02s",$squad);
               $msg .= sprintf("%3s %6s %s, %s",$squad,$cad_num,$last_name,$first_name);
               $msg .= "\n";
               $cad_num = $last_name = $first_name = $squad = $be_on_team_30 = $be_on_team_5 = "";
               }
            }
         else
            {
            $msg .= $night_description . " None\n";
            }
         $msg .= "\n";
         }
      }
   $msg .= "</pre>\n";
   }
//
$msg .= "<pre>--- END ---</pre><br>\n";
$msg .= "<small><i><pre>$Id$</pre></i></small>\n";
$msg .= "</td></tr></table>\n";
$msg .= "</body>\n";
$msg .= "</html>\n";
//
echo $msg;
// $recipient = RoleEmailAddress("schedule-coordinator");
// $subject = "OSCAR report";
// $headers = "Reply-to: $name <$email_addr>\r\n";
// $headers .= "Content-type: text/html\r\n";
// mail($recipient, $subject, $msg, $headers);
?>