<?
//
// $Id$
//
require_once("f_oscarhomepageurl.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("f_bodyopen.phtml");
?>
<html>

<head>
<title>OSCAR - VBDEMS Compiled Availability Report Request Form</title>
</head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
        <table><tr><td>
           <h6 align="center">
              KVEO-IT-PROJECT<br>
              <a href="<? echo OscarHomePageUrl(); ?>">OSCAR SYSTEM</a><br>
              <a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></h6>
           <h1 align="center">Compiled Availabilities Report Request Form</h1>
        </td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>
           <? PutLibPhotoRandomPlaced("sasquatch",1); ?>
        </td></tr></table>
        <hr>
        <p>To guard against misuse of the OSCAR system, all generated reports are first sent to the VBDEMS Central Schedule Coordinator.&nbsp; Upon the coordinator's approval, the report will be forwarded to the email address that you specify.</p>
        <blockquote>
        <form action=request-full-report.phtml method=post>
           <table>
              <tr>
                 <td>Your email address:</td>
                 <td><input type=text name=email_addr size=64>
              </tr>
              <tr>
                 <td>Applicable month:</td>
                 <td>
                    <select size="1" name=month>
                       <option value="">Select</option>
                       <option value="JAN">January</option>
                       <option value="FEB">February</option>
                       <option value="MAR">March</option>
                       <option value="APR">April</option>
                       <option value="MAY">May</option>
                       <option value="JUN">June</option>
                       <option value="JUL">July</option>
                       <option value="AUG">August</option>
                       <option value="SEP">September</option>
                       <option value="OCT">October</option>
                       <option value="NOV">November</option>
                       <option value="DEC">December</option>
                    </select>
                 </td>
              </tr>
           </table>
           <input type=submit value="Request full report">
        </form>
        <blockquote>
        <hr>
        <p><small><small><em><pre>$Id$</pre></em></small></small>
       </td>
    </tr>
  </table>
</body>

</html>

