<?
//
// $Id: retract.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $
//
// Emulate register_globals on
if (!ini_get('register_globals'))
  {
  $superglobals = array($_SERVER,$_ENV,$_FILES,$_COOKIE,$_POST,$_GET);
  if (isset($_SESSION))
    {
    array_unshift($superglobals, $_SESSION);
    }
  foreach ($superglobals as $superglobal)
    {
    extract($superglobal, EXTR_SKIP);
    }
  }
//
// Assign passed-in arguments to themselves to prevent 'undefined var' warnings later.
//
$a = $a;
$b = $b;
$c = $c;
$d = $d;
$e = $e;
//
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_oscarmailheaders.phtml");
require_once("f_sendapprovalnotice.phtml");
require_once("f_formattednoteappendage.phtml");
//
$ini = AppSettings();
$db_link = DbLink($ini);
$dbkalipso_link = DbkalipsoLink($ini);
//
if ($ini[app][do_report_all_errors]) error_reporting(E_ALL);
?>
<html>
<head><title>Retraction Confirmation</title></head>
<? BodyOpen(); ?>
<table align="center" width="80%"><tr><td>
<H6 ALIGN="CENTER">KVEO-IT-PROJECT<br><a href="javascript:close();">OSCAR SYSTEM</a><br><a href="http://www.vabeachems.com">VIRGINIA BEACH DEPARTMENT OF EMS</a></H6>
<H1 ALIGN="CENTER">Retraction Confirmation</H1>
<hr>
<?
//
// Decode the arguments.
//
$first_name = kix\k::Safe(base64_decode($a),kix\k::PhpValueOf_safe_hint_type("HUMAN_NAME"));
$last_name = kix\k::Safe(base64_decode($b),kix\k::PhpValueOf_safe_hint_type("HUMAN_NAME"));
$applicable_month_num = base64_decode($c);
$email_addr = kix\k::Safe(base64_decode($d),kix\k::PhpValueOf_safe_hint_type("EMAIL_ADDRESS"));
$coord_agency = kix\k::Safe(base64_decode($e),kix\k::PhpValueOf_safe_hint_type("ALPHANUM"));
//
// Determine the three-letter abbreviation for the specified month.
//
$applicable_month_time = mktime(12,0,0,$applicable_month_num,1);
$applicable_month_abbrev = strtoupper(date("M",$applicable_month_time));
//
// Delete the appropriate records from the avail_sheet table.
//
$db_link->query
   (
   "delete from avail_sheet "
   .  " where month = '$applicable_month_abbrev' "
   .  "    and last_name = \"" . addslashes(addslashes($last_name)) . "\" "
   .  "    and first_name = \"" . addslashes(addslashes($first_name)) . "\" "
   .  "    and coord_agency = '$coord_agency' "
   )
   or die("Delete failed with error:  " . mysqli_error($db_link));
if ($num_rows_affected = mysqli_affected_rows($db_link))
   {
   $db_link->query
      (
      "insert into avail_sheet "
      .  " set last_name = \"" . addslashes(addslashes($last_name)) . "\""
      .  "    , first_name = \"" . addslashes(addslashes($first_name)) . "\""
      .  "    , email_addr = \"" . addslashes(addslashes($email_addr)) . "\""
      .  "    , coord_agency = '$coord_agency'"
      .  "    , month = '$applicable_month_abbrev'"
      .  "    , be_third = 'TRUE'"
      .  "    , be_nondriver = 'TRUE'"
      .  "    , note='"
      .  FormattedNoteAppendage
         (
         "WARNING",
         "RETRACT",
         "User at IP $REMOTE_ADDR retracted all availabilities."
         )
      .  "'"
      .  "    , expiration='" . date("Y-m-d",mktime(0,0,0,($applicable_month_num + 1),0)) . "'"
      )
      or die("Finalization query failed with error:  " . mysqli_error($db_link));
   }
//
PutLibPhotoRandomPlaced($ini,$dbkalipso_link,"oscarsystem",1,"right");
echo "<p>The OSCAR system has retracted $num_rows_affected record";
if ($num_rows_affected != 1) echo "s";
echo " from its database.</p>\n";
if ($num_rows_affected == 0)
   {
   echo "<i>\n"
      . "A <u>zero</u> result can be caused by:\n"
      . "   <ul>\n"
      . "      <li>an empty set of records, as shown in the challenge message;</li>\n"
      . "      <li>an attempt to retract records from months gone by;</li>\n"
      . "      <li>an OSCAR bug.</li>\n"
      . "   </ul>\n"
      . "If you suspect a bug, please report the problem to the following people:\n"
      . "   <ul>\n"
      . "      <li><a href=\"mailto:" . RoleEmailAddress($db_link,"schedule-coordinator",$coord_agency) . "\">the $coord_agency Schedule Coordinator</a></li>\n"
      . "      <li><a href=\"mailto:" . RoleEmailAddress($db_link,"") . "\">the OSCAR System Administrator</a></li>\n"
      . "   </ul>\n"
      . "</i>\n";
   }
echo "<p><b>Don't forget to submit an accurate availability sheet to agency \"" . strtoupper($coord_agency) . "\" by the deadline.</b></p>\n"
   . "<p>If you have feedback about the technical aspects of this process, please contact the <a href=\"mailto:"
   . RoleEmailAddress($db_link,"")
   . "\">OSCAR System Administrator</a>.</p>";
?>
<hr>
<p><small><small><em><pre>$Id: retract.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $</pre></em></small></small></p>
</td>
</tr>
</table>
</body>
</html>
