<?
//
// $Id$
//
require_once("f_oscarhomepageurl.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("f_bodyopen.phtml");
require_once("f_password.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_sendapprovalnotice.phtml");
//
?>
<html>
<head><title>Retraction Confirmation</title></head>
<? BodyOpen(); ?>
<table align=center width=80%><tr><td>
<H6 ALIGN=CENTER>KVEO-IT-PROJECT<br><a href=<? OscarHomePageUrl() ?>>OSCAR</a><br><a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></H6>
<H1 ALIGN=CENTER>Retraction Confirmation</H1>
<hr>
<?
//
// Decode the arguments.
//
$first_name = base64_decode($a);
$last_name = base64_decode($b);
$applicable_month_abbrev = base64_decode($c);
//
// Connect to the database.
//
mysql_connect(localhost,kalipso,Password());
mysql_select_db(oscar);
//
// Delete the appropriate records from the avail_sheet table.
//
mysql_query
   (
   "update avail_sheet"
   .  "set d1='', d2='', d3='', d4='', d5='', d6='', d7='', d8='', d9='', d10='', d11='', d12='', d13='', d14='', d15='', d16='', d17='', d18='', d19='', d20='', d21='', d22='', d23='', d24='', d25='', d26='', d27='', d28='', d29='', d30='', d31=''"
   .  "   , n1='', n2='', n3='', n4='', n5='', n6='', n7='', n8='', n9='', n10='', n11='', n12='', n13='', n14='', n15='', n16='', n17='', n18='', n19='', n20='', n21='', n22='', n23='', n24='', n25='', n26='', n27='', n28='', n29='', n30='', n31=''"
   .  "   , num_extras=0"
   .  "   , note='All availabilities retracted by user at IP address $REMOTE_ADDR'."
   .  " where last_name = \"" . addslashes(addslashes($last_name)) . "\""
   .  "    and first_name = \"" . addslashes(addslashes($first_name)) . "\""
   .  "    and month = '$applicable_month_abbrev'"
   )
   or die("Deletion failed with error:  " . mysql_error());
//
PutLibPhotoRandomPlaced("sasquatch",1,"right");
echo "<p>The OSCAR system has retracted "
   . mysql_affected_rows()
   . " record(s) from its database.</p>\n"
   . "<p><b>Don't forget to <a href="
   . OscarRootUrl()
   . "/als-avail-sub-form.phtml>submit an accurate availability sheet</a> by the deadline.</b></p>\n"
   . "<p>If you have feedback about the technical aspects of this process, please contact the <a href=mailto:\""
   . RoleEmailAddress("")
   . "\">OSCAR System Administrator</a>.</p>";

?>
<hr>
<p><small><small><em><pre>$Id$</pre></em></small></small>
</td>
</tr>
</table>
</body>
</html>
