<?
//
// $Id$
//
require_once("f_runmode.phtml");
$mode = RunMode($PHP_SELF);
//
// Assign passed-in arguments to themselves to prevent 'undefined var' warnings later.
//
$a = $a;
$b = $b;
$c = $c;
$d = $d;
$e = $e;
//
if ($mode) error_reporting(E_ALL);
//
require_once("f_oscarhomepageurl.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("f_bodyopen.phtml");
require_once("f_password.phtml");
require_once($mode . "f_roleemailaddress.phtml");
require_once("f_oscarmailheaders.phtml");
require_once("f_sendapprovalnotice.phtml");
require_once("f_connectselectdb.phtml");
//
?>
<html>
<head><title>Retraction Confirmation</title></head>
<? BodyOpen(); ?>
<table align=center width=80%><tr><td>
<H6 ALIGN=CENTER>KVEO-IT-PROJECT<br><a href=<? OscarHomePageUrl() ?>>OSCAR SYSTEM</a><br><a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></H6>
<H1 ALIGN=CENTER>Retraction Confirmation</H1>
<hr>
<?
//
// Decode the arguments.
//
$first_name = base64_decode($a);
$last_name = base64_decode($b);
$applicable_month_num = base64_decode($c);
$email_addr = base64_decode($d);
$squad = base64_decode($e);
//
// Determine the three-letter abbreviation for the specified month.
//
$applicable_month_time = mktime(12,0,0,$applicable_month_num,1);
$applicable_month_abbrev = strtoupper(date("M",$applicable_month_time));
//
// Connect to the database.
//
ConnectSelectDb("localhost","kalipso",Password(),"oscar");
//
// Delete the appropriate records from the avail_sheet table.
//
mysql_query
   (
   "delete from " . $mode . "avail_sheet "
   .  " where last_name = \"" . addslashes(addslashes($last_name)) . "\""
   .  "    and first_name = \"" . addslashes(addslashes($first_name)) . "\""
   .  "    and month = '$applicable_month_abbrev'"
   )
   or die("Delete failed with error:  " . mysql_error());
if ($num_rows_affected = mysql_affected_rows())
   {
   mysql_query
      (
      "insert into " . $mode . "avail_sheet "
      .  " set last_name = \"" . addslashes(addslashes($last_name)) . "\""
      .  "    , first_name = \"" . addslashes(addslashes($first_name)) . "\""
      .  "    , email_addr = \"" . addslashes(addslashes($email_addr)) . "\""
      .  "    , squad = '$squad'"
      .  "    , month = '$applicable_month_abbrev'"
      .  "    , note='</i><b>*** WARNING: User at IP address $REMOTE_ADDR retracted all availabilities on " . date("l Y-M-d H:i:s T") . ".</b><i>'"
      .  "    , expiration='" . date("Y-m-d",mktime(0,0,0,($applicable_month_num + 1),0)) . "'"
      )
      or die("Finalization query failed with error:  " . mysql_error());
   }
//
PutLibPhotoRandomPlaced("sasquatch",1,"right");
echo "<p>The OSCAR system has retracted $num_rows_affected record";
if ($num_rows_affected != 1) echo "s";
echo " from its database.</p>\n";
if ($num_rows_affected == 0)
   {
   echo "<i>\n"
      . "A <u>zero</u> result can be caused by:\n"
      . "   <ul>\n"
      . "      <li>an empty set of records, as shown in the challenge message;</li>\n"
      . "      <li>an attempt to retract records from months gone by;</li>\n"
      . "      <li>an OSCAR bug.</li>\n"
      . "   </ul>\n"
      . "If you suspect a bug, please report the problem to the following people:\n"
      . "   <ul>\n"
      . "      <li><a href=mailto:\"" . RoleEmailAddress("schedule-coordinator",$mode) . "\">the Schedule Coordinator</a></li>\n"
      . "      <li><a href=mailto:\"" . RoleEmailAddress("",$mode) . "\">the OSCAR System Administrator</a></li>\n"
      . "   </ul>\n"
      . "</i>\n";
   }
echo "<p><b>Don't forget to <a href="
   . OscarRootUrl()
   . "/" . $mode . "als-avail-sub-form.phtml>submit an accurate availability sheet</a> by the deadline.</b></p>\n"
   . "<p>If you have feedback about the technical aspects of this process, please contact the <a href=mailto:\""
   . RoleEmailAddress("",$mode)
   . "\">OSCAR System Administrator</a>.</p>";

?>
<hr>
<p><small><small><em><pre>$Id$</pre></em></small></small>
</td>
</tr>
</table>
</body>
</html>
