<?
//
// $Id: stats.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $
//
// Emulate register_globals on
if (!ini_get('register_globals'))
  {
  $superglobals = array($_SERVER,$_ENV,$_FILES,$_COOKIE,$_POST,$_GET);
  if (isset($_SESSION))
    {
    array_unshift($superglobals, $_SESSION);
    }
  foreach ($superglobals as $superglobal)
    {
    extract($superglobal, EXTR_SKIP);
    }
  }
error_reporting(E_ALL);
//
require_once("f_bodyopen.phtml");
require_once("f_numsheets.phtml");
require_once("f_numdistinctusers.phtml");
//
$ini = AppSettings();
$db_link = DbLink($ini);
$dbkalipso_link = DbkalipsoLink($ini);
//
?>
<html>

<head><title>OSCAR - Detailed statistics</title></head>

<? BodyOpen(); ?>
<table width="80%" align="center">
   <tr>
      <td>
         <table>
            <tr>
               <td>
                  <h6 align="center">
                     KVEO-IT-PROJECT<br>
                     <a href="javascript:close();">OSCAR SYSTEM</a>
                  </h6>
                  <h1 align="center">Detailed statistics</h1>
               </td>
               <td><? PutLibPhotoRandomPlaced($ini,$dbkalipso_link,"oscarsystem",1,"right"); ?></td>
            </tr>
         </table>
         <hr>
         <?
            //
            // Calculate month numbers and abbreviations.
            //
            $after_next_month_num = ($next_month_num = ($current_month_num = date("n")) + 1) + 1;
            $current_month_abbrev = date("M");
            $next_month_abbrev = date("M",mktime(12,0,0,$next_month_num,1));
            $after_next_month_abbrev = date("M",mktime(12,0,0,$after_next_month_num,1));
            ?>
            <br>
            <b>Sheets on file</b> (all inclusive)
            <blockquote>
               <table border=1 cellspacing=0 cellpadding=4>
                  <tr bgcolor=#E8E8E8>
                     <td align=center>&nbsp;<? echo $current_month_abbrev; ?>&nbsp;</td>
                     <td align=center>&nbsp;<? echo $next_month_abbrev; ?>&nbsp;</td>
                     <td align=center>&nbsp;<? echo $after_next_month_abbrev; ?>&nbsp;</td>
                  </tr>
                  <tr>
                     <?
                     echo "<td align=center>" . ($current_num_sheets = NumSheets($db_link,$current_month_abbrev,"",1,1,1)) . "</td>\n";
                     echo "<td align=center>" . ($next_num_sheets = NumSheets($db_link,$next_month_abbrev,"",1,1,1)) . "</td>\n";
                     echo "<td align=center>" . ($after_num_sheets = NumSheets($db_link,$after_next_month_abbrev,"",1,1,1)) . "</td>\n";
                     ?>
                  </tr>
               </table>
            </blockquote>
            <br>
            <b>Distinct users</b> (all inclusive)
            <blockquote>
               <table border=1 cellspacing=0 cellpadding=4>
                  <tr bgcolor=#E8E8E8>
                     <td align=center>&nbsp;<? echo $current_month_abbrev; ?>&nbsp;</td>
                     <td align=center>&nbsp;<? echo $next_month_abbrev; ?>&nbsp;</td>
                     <td align=center>&nbsp;<? echo $after_next_month_abbrev; ?>&nbsp;</td>
                     <td>&nbsp;</td>
                  </tr>
                  <tr>
                     <?
                     echo "<td align=center>" . ($current_num_users = NumDistinctUsers($db_link,$current_month_abbrev)) . "</td>\n";
                     echo "<td align=center>" . ($next_num_users = NumDistinctUsers($db_link,$next_month_abbrev)) . "</td>\n";
                     echo "<td align=center>" . ($after_num_users = NumDistinctUsers($db_link,$after_next_month_abbrev)) . "</td>\n";
                     echo "<td>Absolute</td>\n";
                     ?>
                  </tr>
                  <tr>
                     <?
                     echo "<td align=center>";
                     if ($current_num_sheets)
                        {
                        printf("%d",(100*$current_num_users/$current_num_sheets));
                        echo "%";
                        }
                     else
                        {
                        echo "NA";
                        }
                     echo "</td>\n";
                     //
                     echo "<td align=center>";
                     if ($next_num_sheets)
                        {
                        printf("%d",(100*$next_num_users/$next_num_sheets));
                        echo "%";
                        }
                     else
                        {
                        echo "NA";
                        }
                     echo "</td>\n";
                     //
                     echo "<td align=center>";
                     if ($after_num_sheets)
                        {
                        printf("%d",100*($after_num_users/$after_num_sheets));
                        echo "%";
                        }
                     else
                        {
                        echo "NA";
                        }
                     echo "</td>\n";
                     //
                     echo "<td>Relative to sheets on file</td>\n";
                     ?>
                  </tr>
               </table>
               <br>
               This table shows the approximate number of people who are using OSCAR to enter their own
               availability sheets.&nbsp; It is derived by counting the number of distinct email addresses submitted on
               availability sheets.&nbsp; The remaining availability sheets are entered by schedule coordination staff,
               etc.
            </blockquote>
            <br>
            <b>Number of shifts made available per person</b> (for all <a href="meaning-of-vorp.phtml">VORP</a> sheets on file)
            <blockquote>
               <table cellpadding=1>
                  <?
                  $db_link->query
                     (
                     "create temporary table aggregated "
                     .  " select month "
                     .  "    , last_name "
                     .  "    , first_name "
                     .  "    , coord_agency "
                     .  "    , max(timestamp) as timestamp "
                     .  " from avail_sheet "
                     .  " where be_tda != 'TRUE' "
                     .  "    and coord_agency != 'EMS' "
                     .  "    and coord_agency != 'SupSvcs' "
                     .  " group by month "
                     .  "    , last_name "
                     .  "    , first_name "
                     .  "    , coord_agency "
                     )
                     or die("Create/select aggregated failed with error:  " . mysqli_error($db_link));
                  $marker = "AVAILABLE";
                  $db_link->query
                     (
                     "create temporary table shift_avail_count "
                     .  " select aggregated.month "
                     .  "    , aggregated.last_name "
                     .  "    , aggregated.first_name "
                     .  "    , aggregated.coord_agency "
                     .  "    , if(d1='$marker',1,0) "
                     .  "    + if(d2='$marker',1,0) "
                     .  "    + if(d3='$marker',1,0) "
                     .  "    + if(d4='$marker',1,0) "
                     .  "    + if(d5='$marker',1,0) "
                     .  "    + if(d6='$marker',1,0) "
                     .  "    + if(d7='$marker',1,0) "
                     .  "    + if(d8='$marker',1,0) "
                     .  "    + if(d9='$marker',1,0) "
                     .  "    + if(d10='$marker',1,0) "
                     .  "    + if(d11='$marker',1,0) "
                     .  "    + if(d12='$marker',1,0) "
                     .  "    + if(d13='$marker',1,0) "
                     .  "    + if(d14='$marker',1,0) "
                     .  "    + if(d15='$marker',1,0) "
                     .  "    + if(d16='$marker',1,0) "
                     .  "    + if(d17='$marker',1,0) "
                     .  "    + if(d18='$marker',1,0) "
                     .  "    + if(d19='$marker',1,0) "
                     .  "    + if(d20='$marker',1,0) "
                     .  "    + if(d21='$marker',1,0) "
                     .  "    + if(d22='$marker',1,0) "
                     .  "    + if(d23='$marker',1,0) "
                     .  "    + if(d24='$marker',1,0) "
                     .  "    + if(d25='$marker',1,0) "
                     .  "    + if(d26='$marker',1,0) "
                     .  "    + if(d27='$marker',1,0) "
                     .  "    + if(d28='$marker',1,0) "
                     .  "    + if(d29='$marker',1,0) "
                     .  "    + if(d30='$marker',1,0) "
                     .  "    + if(d31='$marker',1,0) "
                     .  "    + if(n1='$marker',1,0) "
                     .  "    + if(n2='$marker',1,0) "
                     .  "    + if(n3='$marker',1,0) "
                     .  "    + if(n4='$marker',1,0) "
                     .  "    + if(n5='$marker',1,0) "
                     .  "    + if(n6='$marker',1,0) "
                     .  "    + if(n7='$marker',1,0) "
                     .  "    + if(n8='$marker',1,0) "
                     .  "    + if(n9='$marker',1,0) "
                     .  "    + if(n10='$marker',1,0) "
                     .  "    + if(n11='$marker',1,0) "
                     .  "    + if(n12='$marker',1,0) "
                     .  "    + if(n13='$marker',1,0) "
                     .  "    + if(n14='$marker',1,0) "
                     .  "    + if(n15='$marker',1,0) "
                     .  "    + if(n16='$marker',1,0) "
                     .  "    + if(n17='$marker',1,0) "
                     .  "    + if(n18='$marker',1,0) "
                     .  "    + if(n19='$marker',1,0) "
                     .  "    + if(n20='$marker',1,0) "
                     .  "    + if(n21='$marker',1,0) "
                     .  "    + if(n22='$marker',1,0) "
                     .  "    + if(n23='$marker',1,0) "
                     .  "    + if(n24='$marker',1,0) "
                     .  "    + if(n25='$marker',1,0) "
                     .  "    + if(n26='$marker',1,0) "
                     .  "    + if(n27='$marker',1,0) "
                     .  "    + if(n28='$marker',1,0) "
                     .  "    + if(n29='$marker',1,0) "
                     .  "    + if(n30='$marker',1,0) "
                     .  "    + if(n31='$marker',1,0) "
                     .  "    as num_avails "
                     .  " from aggregated left join avail_sheet "
                     .  "    using (month, last_name, first_name, coord_agency, timestamp)"
                     .  " order by num_avails desc"
                     )
                     or die("Create/select shift_avail_count failed with error: " . mysqli_error($db_link));
                  //
                  // Average and stddev
                  //
                  $result = $db_link->query
                     (
                     "select avg(num_avails) as average"
                     .  "   , stddev(num_avails) as stddev"
                     .  " from shift_avail_count "
                     )
                     or die("Select 1 failed with error: " . mysqli_error($db_link));
                  extract(mysqli_fetch_array($result));
                  //
                  echo "<tr><td>Average:</td><td>$average</td></tr>\n";
                  echo "<tr><td>Standard deviation:</td><td>$stddev</td></tr>\n";
                  //
                  // Most available personnel
                  //
                  echo "<tr><td colspan=2>\n"
                     . "   <br>Most available <a href=meaning-of-vorp.phtml><b>VORPs</b></a>:\n"
                     . "   <ol>\n";
                  $result = $db_link->query("select * from shift_avail_count limit 5")
                     or die("Select 2 failed with error: " . mysqli_error($db_link));
                  //
                  while ($row = mysqli_fetch_array($result))
                     {
                     $first_name = $last_name = $num_avails = $month = "";
                     extract($row);
                     echo "      <li>$first_name $last_name&nbsp; ($num_avails in $month for $coord_agency)</li>\n";
                     }
                  echo "   </ol>\n"
                     . "</td></tr>\n";
                  //
                  // Histogram
                  //
                  echo "<tr><td colspan=2>Histogram:\n"
                     . "   <blockquote><pre>";
                  $result = $db_link->query
                     (
                     "select num_avails, count(*) as occurrences "
                     .  " from shift_avail_count group by num_avails"
                     )
                     or die("Select 3 failed with error: " . mysqli_error($db_link));
                  //
                  while ($row = mysqli_fetch_array($result))
                     {
                     $num_avails = $occurrences = "";
                     extract($row);
                     printf("%2d: ",$num_avails);
                     for ($i=1; $i<=$occurrences; $i++) echo "#";
                     echo "\n";
                     }
                  echo "</pre></blockquote>\n"
                     . "</td></tr>\n";
                  ?>
               </table>
            </blockquote>
            <?
            $db_link->query("drop table aggregated, shift_avail_count")
               or die("Drop of temp tables failed with error:  " . mysqli_error($db_link));
            ?>
         <hr>
         <p><small><small><em><pre>$Id: stats.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $</pre></em></small></small>
      </td>
   </tr>
</table>
</body>

</html>
