<?
//
// $Id: training.phtml 7092 2020-04-29 19:03:43Z kevinanlipscomb $
//
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
//
$ini = AppSettings();
$dbkalipso_link = DbkalipsoLink($ini);
?>
<html>

<head><title>OSCAR - OSCAR U.</title></head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
        <h6 align="center">KVEO-IT-PROJECT - <a href="javascript:close();">OSCAR SYSTEM</a></h6>
        <h1 align="center">OSCAR U.</h1>
        <hr>
        <? PutLibPhotoRandomPlaced($ini,$dbkalipso_link,"oscarsystem",1,"right"); ?>
        <p>The following OSCAR training is available online.&nbsp; Note that HTML versions may be optimized for viewing
           with Internet Explorer 5.0 or higher:</p>
        <table cellpadding=5>
           <tr>
              <td valign=bottom><u><b>Title</b></u></td>
              <td align=center valign=bottom><u><small>Source format</small></u></td>
           </tr>
           <tr>
              <td><b><a href=doc/ppt/oscar-for-squad-sched-coords/oscar-for-squad-sched-coords.htm>OSCAR for Squad Schedule Coordinators</a></b> <i>(HTML)</i></td>
              <td align=center><small><a href=doc/ppt/oscar-for-squad-sched-coords/oscar-for-squad-sched-coords.ppt>PPT</small></td>
           </tr>
        </table>
        <hr>
        <p><small><small><em><pre>$Id: training.phtml 7092 2020-04-29 19:03:43Z kevinanlipscomb $</pre></em></small></small></center></td>
    </tr>
  </table>
</body>

</html>

