<?
//
// $Id: untrust.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $
//
// Emulate register_globals on
if (!ini_get('register_globals'))
  {
  $superglobals = array($_SERVER,$_ENV,$_FILES,$_COOKIE,$_POST,$_GET);
  if (isset($_SESSION))
    {
    array_unshift($superglobals, $_SESSION);
    }
  foreach ($superglobals as $superglobal)
    {
    extract($superglobal, EXTR_SKIP);
    }
  }
//
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_oscarmailheaders.phtml");
//
$ini = AppSettings();
$db_link = DbLink($ini);
$dbkalipso_link = DbkalipsoLink($ini);
//
if ($ini[app][do_report_all_errors]) error_reporting(E_ALL);
?>
<html>
<head><title>Remove Trust</title></head>
<? BodyOpen(); ?>
<table align=center width=80%><tr><td>
<H6 ALIGN=CENTER>KVEO-IT-PROJECT<br><a href="javascript:close();">OSCAR SYSTEM</a><br><a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></H6>
<H1 ALIGN=CENTER>Remove Trust</H1>
<hr>
<?
//
// Validate parameters
//
if
   (
      ($a != "")
   and
      ($b != "")
   )
// then
   {
      $email_address = kix\k::Safe(base64_decode($a),kix\k::PhpValueOf_safe_hint_type("EMAIL_ADDRESS"));
      $coord_agency = kix\k::Safe(base64_decode($b),kix\k::PhpValueOf_safe_hint_type("ALPHANUM"));
      //
      // Perform the specified update.
      //
      $db_link->query
         (
         "delete from trusted_user "
         .  "where email_address='$email_address' "
         .  "   and coord_agency='$coord_agency' "
         )
         or die("Deletion failed with error: " . mysqli_error($db_link));
      //
      PutLibPhotoRandomPlaced($ini,$dbkalipso_link,"oscarsystem",1,"right");
      echo "<p><b>$email_address</b> is no longer trusted by agency <b>$coord_agency</b>.</p>";
   }
else
   {
   //
   // Fill the page out with a warning and instructions.
   //
   ?>
   <h2><i>Error!</i></h2>
   <b>
   <blockquote>
      <p>Invalid arguments.</p>
   </blockquote>            
   </b>
   <?
   }
?>
<br clear=both>
<hr>
<p><small><small><em><pre>$Id: untrust.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $</pre></em></small></small></p>
</td>
</tr>
</table>
</body>
</html>
