<?
//
// $Id$
//
require_once("f_oscarhomepageurl.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("f_bodyopen.phtml");
?>
<html>

<head><title>OSCAR - What's New</title></head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
           <h6 align="center">
              KVEO-IT-PROJECT - <a href="<? echo OscarHomePageUrl(); ?>">OSCAR SYSTEM</a></h6>
           <h1 align="center">What's New</h1>
        <hr>
        <? PutLibPhotoRandomPlaced("sasquatch",1,"right"); ?>
        <p><b>2001-10-dd:&nbsp; </b>Went live.</p>
        <p><b>2001-10-29:&nbsp; </b>Began round-the-clock site response monitoring, with pager notificatoin to the OSCAR
           Sysadmin.</p>
        <p><b>2001-10-27:&nbsp; </b>Added ERS TDA handling.</p>
        <p><b>2001-10-25:&nbsp; </b>Demonstrated the system to VBDEMS.</p>
        <p><b>2001-10-23:&nbsp; </b>Added the <a href=privacy.phtml>Privacy Policy</a> and <a href=develop.phtml>How to 
           contribute</a> pages.</p>
        <p><b>2001-10-21:&nbsp; </b>Achieved Initial Operating Capability (IOC).</p>
        <hr>
        <p><small><small><em><pre>$Id$</pre></em></small></small></center></td>
    </tr>
  </table>
</body>

</html>

