<?
//
// $Id$
//
require_once("f_oscarhomepageurl.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("f_bodyopen.phtml");
?>
<html>

<head><title>OSCAR - What's New</title></head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
           <h6 align="center">
              KVEO-IT-PROJECT - <a href="<? echo OscarHomePageUrl(); ?>">OSCAR SYSTEM</a></h6>
           <h1 align="center">What's New</h1>
        <hr>
        <? PutLibPhotoRandomPlaced("sasquatch",1,"right"); ?>
        <p><b>2001-11-04:&nbsp; </b>Added the "Server status" indication on the main page.&nbsp; This feature forces a hit
           on the database, thereby assuring that both PHP and MySQL are up, and provides a keyword ("A-OK") that some
           site monitoring services will check for.&nbsp; Added clarifications for "surrogate" submitters.</p>
        <p><b>2001-11-03:&nbsp; </b>Fixed a bug noticed during a demo that was preventing legitimate OSCAR authorities from
           gaining access to special request comments.&nbsp; Made authority and role tracking more robust.</p>
        <p><b>2001-11-01:&nbsp; </b>Fixed bug 477171, which had been causing the dates shown on the standard submission 
           confirmation page to be off (earlier) by one day than the dates the user actually submitted.&nbsp; This bug had
           been introduced when TDA handling was added.</p>
        <p><b>2001-10-31:&nbsp; </b>Went live as www.Oscarsystem.com.</p>
        <p><b>2001-10-29:&nbsp; </b>Began round-the-clock site response monitoring, with pager notification to the OSCAR
           Sysadmin.</p>
        <p><b>2001-10-27:&nbsp; </b>Added ERS TDA handling.</p>
        <p><b>2001-10-25:&nbsp; </b>Demonstrated the system to VBDEMS.</p>
        <p><b>2001-10-23:&nbsp; </b>Added the <a href=privacy.phtml>Privacy Policy</a> and <a href=develop.phtml>How to 
           contribute</a> pages.</p>
        <p><b>2001-10-21:&nbsp; </b>Achieved Initial Operating Capability (IOC).</p>
        <hr>
        <p><small><small><em><pre>$Id$</pre></em></small></small></center></td>
    </tr>
  </table>
</body>

</html>

