<?
//
// $Id: whats-new.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $
//
$foundation_dir = "../foundation";
require_once("f_bodyopen.phtml");
require_once("$foundation_dir/std_style_class.php");
//
$ini = AppSettings();
$dbkalipso_link = DbkalipsoLink($ini);
?>
<html>

<head><title>OSCAR - What's New</title></head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
           <h6 align="center">
              KVEO-IT-PROJECT - <a href="javascript:close();">OSCAR SYSTEM</a></h6>
           <h1 align="center">What's New</h1>
        <hr>
        <? PutLibPhotoRandomPlaced($ini,$dbkalipso_link,"oscarsystem",1,"right"); ?>
        <?php echo std_style_class::CatchUpBlurb(); ?>
        <p><b>2009-10-08:&nbsp; </b>Added support for Air Ambulance team.&nbsp; Updated indicators to reflect EMS-7 program.&nbsp; Switched random photo display from cats to oscarsystem.&nbsp; Improved pre-production testing arrangement.</p>
        <p><b>2005-10-11:&nbsp; </b>Revised statistical reporting in some places to focus on submissions from volunteer ambulance personnel, as opposed to other ERS members.</p>
        <p><b>2005-07-04:&nbsp; </b>Corrected a misalignment of formatted-text indicators in the Daily Availability Report.</p>
        <p><b>2004-09-04:&nbsp; </b>Added link to Class Act Nomination Form to main page.</p>
        <p><b>2004-01-07:&nbsp; </b>Added Surrogate Submitters feature.</p>
        <p><b>2003-12-27:&nbsp; </b>Changed the special questions asked of squad-level submitters.</p>
        <p><b>2003-11-11:&nbsp; </b>Fixed a bug affecting squad-level authorities requesting full reports from EMS 
           Admin.&nbsp; Under certain circumstances, such reports provided incorrect drill-down links and summary 
           blocks.</p>
        <p><b>2003-02-04:&nbsp; </b>Revised Class Act Award nomination feature so that notices going to the Class Act
           Coordinator will appear to be from the nominator instead of from the OSCAR Sysadmin.</p>
        <p><b>2003-01-21:&nbsp; </b>Added code to send pager alerts to squad schedule coordinators whenever the EMS
           Schedule Coordinator performs a relay operation.</p>
        <p><b>2003-01-20:&nbsp; </b>Implemented feature # 657832, which allows EMS OSCAR Authorities to retrieve system-wide
           availability reports for all or selected shifts.</p>
        <p><b>2003-01-19:&nbsp; </b>Added Class Act Award nomination capability.</p>
        <p><b>2003-01-06:&nbsp; </b>Adjusted the Daily Availability Report to give schedule coordinators more time to
           act.&nbsp; Removed the image from the submission confirmation page because that page is frequently printed, and
           the image consumes a lot of ink.&nbsp; Clarified submission form verbage to indicate that OSCAR treats thirds
           Driver/NON-AICs the same.</p>
        <p><b>2002-12-13:&nbsp; </b>Fixed bug # 653448, which was preventing the Trusted User feature from operating
           correctly.</p>
        <p><b>2002-12-10:&nbsp; </b>Squad-level authorities now have full visibility into their members' submissions to EMS.&nbsp;
           This allows efficient enforcement of the submission deadline to occur at the squad level instead of at the EMS
           level.</p>
        <p><b>2002-11-26:&nbsp; </b>Added blurb about entering partial-shift availability details into the Special Requests
           block.</p>
        <p><b>2002-11-15:&nbsp; </b>Added Trends report feature, which automatically generates and distributes OSCAR
           submission activity data to designated OSCAR Authorities.</p>
        <p><b>2002-10-24:&nbsp; </b>Added support for recipients who cannot properly view the Daily Availability Reports
           in HTML format.</p>
        <p><b>2002-10-05:&nbsp; </b>Added Daily Availability Report feature, which automatically generates and distributes
           timely availability information to designated chiefs.</p>
        <p><b>2002-09-03:&nbsp; </b>Revised OSCAR U. to provided modules in both HTML and PPT formats.</p>
        <p><b>2002-08-26:&nbsp; </b>The training section is now referred to as <a href=training.phtml>OSCAR U.</a>&nbsp;
           Updated the <a href=privacy.phtml>Privacy Policy</a> to refer to the new company address.&nbsp; Updated the list
           of modules on the <a href=develop.phtml>Contribute page</a>.</p>
        <p><b>2002-08-22:&nbsp; </b>Added e-Training section and first training module.</p>
        <p><b>2002-07-18:&nbsp; </b>Moved yesterday's solution to a newly-created foundation class so that other products
           could make use of it.</p>
        <p><b>2002-07-17:&nbsp; </b>Added a note to the Report Generation form to suggest a workaround for a potential
           problem involving the ability of certain AOL email client configurations to properly process hyperlinks embedded
           in plaintext emails.</p>
        <p><b>2002-03-31:&nbsp; </b>Fixed bug 531168, which prevented squad schedule coordinators from seeing relayed
           availability sheets in their reports under certain circumstances.</p>
        <p><b>2002-03-29:&nbsp; </b>Fixed bug 535823, which was preventing regular users from requesting compiled
           availability reports.&nbsp; (The bug did not prevent authorities from requesting reports.)&nbsp; The bug was
           caused by misordering the parameters to an underlying PHP routine called "wordwrap()".</p>
        <p><b>2002-03-09:&nbsp; </b>Fixed bug 520008 which would've forced indirect relays of some availability sheets
           where direct relays should've been possible.&nbsp; The solution was to add a missing integrity check in
           perform-add-avail-sheet.phtml.</p>
        <p><b>2002-03-08:&nbsp; </b>Improved relay notices for OSCAR-participating squads.&nbsp; The new notices include 
           full links that automatically trigger generation of the up-to-date appropriate squad-level report.&nbsp; 
           This way the squad schedule coordinator does not have to fill out report request forms to get the report that
           OSCAR knew he needed in the first place.&nbsp; Made cosmetic changes to the formatted processing messages that
           get inserted into reports and notes.</p>
        <p><b>2002-03-06:&nbsp; </b>Clarified instructions to submitters who get scheduled by both EMS and their
           squad.&nbsp; Improved display cosmetics.</p>
        <p><b>2002-03-03:&nbsp; </b>Improved the way messages get appended to the note fields of availability sheets.&nbsp;
           Added capability for EMS schedule coordinator to add comments to availability sheets at relay time.</p>
        <p><b>2002-03-01:&nbsp; </b>Fixed a bug introduced when relay feature was added.&nbsp; The bug caused an annoying
           warning message on the main and stat pages when OSCAR tried to determine the number of submitters for a month
           that didn't actually have any submitters.&nbsp; The bug became apparent today because of the month rollover.</p>
        <p><b>2002-02-23:&nbsp; </b>Restored the "#num extras will run" indication on schedule coordinator reports.&nbsp; It
           was originally added on 2001-11-13 but somehow got lost in a subsequent revision.&nbsp; Revised the Set Agency
           Participation page to prevent visiting spiders, bots, etc from triggering the participation toggle feature, and 
           fixed a syntax error in perform-mod-agency.phtml.</p>
        <p><b>2002-02-21:&nbsp; </b>Implemented feature 496839 -- the robust ability for the EMS schedule coordinator to 
           "relay" members' remaining availabilities to those members' squad schedule coordinators after EMS-level
           allocations have been made.&nbsp; The EMS schedule coordinator can complete such relays even to squad schedule
           coordinators who do not yet use OSCAR.</p>
        <p><b>2002-02-13:&nbsp; </b>Added the <a href=faq.phtml>FAQ</a>.</p>
        <p><b>2002-01-04:&nbsp; </b>Added capability for OSCAR Authorities to change certain OSCAR Role settings.&nbsp;
           EMS authorities can change any role setting.&nbsp; Squad authorities can change roles for their particular
           squad.</p>
        <p><b>2001-12-31:&nbsp; </b>Added traceability to the squad participation toggle operation, and warning verbage to
           the Set Squad Participation page.&nbsp; Added capability for schedule coordinators to remove entries from their
           agency's trusted user table.</p>
        <p><b>2001-12-28:&nbsp; </b>Added capability for the Master OSCAR Authority to change squad participation statuses
           on his or her own.&nbsp; Previously, such a change could only be performed by the OSCAR System
           Administrator.</p>
        <p><b>2001-12-26:&nbsp; </b>Fixed bug 496823, which was causing day-of-week indications to be off by a day on
           January reports generated during December.</p>
        <p><b>2001-12-13:&nbsp; </b>Added a table to the <a href=stats.phtml>Detailed Statistics</a> page to show number
           of distinct users per month.</p>
        <p><b>2001-12-01:&nbsp; </b>Calendar subform generation is now modular and dynamic.&nbsp; Calendar subforms now look
           like conventional month-at-a-glance calendars.</p>
        <p><b>2001-11-21:&nbsp; </b>Revised verbage in a few sections to indicate that the first part of the retraction
           process may also be used to simply reconfirm prior submissions.</p>
        <? PutLibPhotoRandomPlaced($ini,$dbkalipso_link,"oscarsystem",1,"left"); ?>
        <p><b>2001-11-16:&nbsp; </b>Major enhancements to support availability coordination at both the department and 
           squad/team levels.&nbsp; Features will be activated on per-agency basis via database updates at direction of 
           EMS-2.&nbsp; Added availability summaries to the full reports that authorities get.&nbsp; Added failsafe
           submission recovery mechanism in case database becomes unavailable at any critical time after a
           submission.&nbsp; Added much more robust handling of database-down conditions.</p>
        <p><b>2001-11-13:&nbsp; </b>Revised report generator so that OSCAR authorities will be able to see the "# extras 
           will run" values at first glance in their versions of the full reports, rather than making them drill down per
           person.</p>
        <p><b>2001-11-12:&nbsp; </b>Revised report generator to report the latest submitted note (versus first or arbitrary) for 
           each person.&nbsp; Added the <a href=stats.phtml>Detailed stats</a> page.</p>
        <p><b>2001-11-08:&nbsp; </b>Revised main page to handle database-down condition gracefully.</p>
        <p><b>2001-11-05:&nbsp; </b>Improved retraction handling.</p>
        <p><b>2001-11-04:&nbsp; </b>Added the "Server status" indication on the main page.&nbsp; This feature forces a hit
           on the database, thereby assuring that both PHP and MySQL are up, and provides a keyword ("A-OK") that some
           site monitoring services will check for.&nbsp; Added clarifications for "surrogate" submitters.&nbsp; Added
           Zone Car ALS handling.</p>
        <p><b>2001-11-03:&nbsp; </b>Fixed a bug noticed during a demo that was preventing legitimate OSCAR authorities from
           gaining access to special request comments.&nbsp; Made authority and role tracking more robust.</p>
        <p><b>2001-11-01:&nbsp; </b>Fixed bug 477171, which had been causing the dates shown on the standard submission 
           confirmation page to be off (earlier) by one day than the dates the user actually submitted.&nbsp; This bug had
           been introduced when TDA handling was added.</p>
        <p><b>2001-10-31:&nbsp; </b>Went live as www.Oscarsystem.com.</p>
        <p><b>2001-10-29:&nbsp; </b>Began round-the-clock site response monitoring, with pager notification to the OSCAR
           Sysadmin.</p>
        <p><b>2001-10-27:&nbsp; </b>Added ERS TDA handling.</p>
        <p><b>2001-10-25:&nbsp; </b>Demonstrated the system to VBDEMS.</p>
        <p><b>2001-10-23:&nbsp; </b>Added the <a href=privacy.phtml>Privacy Policy</a> and <a href=develop.phtml>How to 
           contribute</a> pages.</p>
        <p><b>2001-10-21:&nbsp; </b>Achieved Initial Operating Capability (IOC).</p>
        <hr>
        <p><small><small><em><pre>$Id: whats-new.phtml 7094 2020-05-03 00:22:53Z kevinanlipscomb $</pre></em></small></small></center></td>
    </tr>
  </table>
</body>

</html>

