<?
//
// $Id$
//
require_once("f_runmode.phtml");
$mode = RunMode($PHP_SELF);
if ($mode) error_reporting(E_ALL);
//
require_once("f_oscarhomepageurl.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("f_bodyopen.phtml");
require_once("f_password.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_oscarmailheaders.phtml");
require_once("f_sendapprovalnotice.phtml");
require_once("f_connectselectdb.phtml");
//
?>
<html>
<head><title>Request Approval and Trust Registration</title></head>
<? BodyOpen(); ?>
<table align=center width=80%><tr><td>
<H6 ALIGN=CENTER>KVEO-IT-PROJECT<br><a href=<? OscarHomePageUrl() ?>>OSCAR SYSTEM</a><br><a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></H6>
<H1 ALIGN=CENTER>Request Approval and Trust Registration</H1>
<hr>
<?
if (
      ($email_addr != "")
   and
      ($digest != "")
   and
      ($coord_agency != "")
   )
//then
   {
   //
   // Connect to the database.
   //
   if (ConnectSelectDb("localhost","kalipso",Password(),"oscar") == "TRUE")
      {
      //
      // Insert the trusted email address into the trusted_user table.
      //
      mysql_query
         (
         "insert into " . $mode . "trusted_user "
         .  "set email_address='$email_addr'"
         .  ", coord_agency='$coord_agency'"
         )
         or die("Trust assertion failed with error: " . mysql_error());
      //
      if (SendApprovalNotice($email_addr,$digest,$mode))
         {
         PutLibPhotoRandomPlaced("sasquatch",1,"right");
         echo "<p>The OSCAR system has performed the following:</p>\n"
            . "<ul>\n"
            . "   <li><p>Sent instructions to <i>$email_addr</i> on how to retrieve the requested report;</p></li>\n"
            . "   <li><p>Registered <i>$email_addr</i> as a user who is trusted by coordinating agency \"$coord_agency\".</p></li>\n"
            . "</ul>\n";
         }
      else
         {
         //
         // Fill the page out with a warning and instructions.
         //
         ?>
         <h2><i>Error!</i></h2>
         <b>
         <blockquote>
            <? echo "<p>The OSCAR system encountered an internal error while processing your request.  Please let the <a href=mailto:" . RoleEmailAddress("",$mode) . "?subj=\"OSCAR Bug Report\">OSCAR System Administrator</a> know this error occurred.</p>"; ?>
         </blockquote>            
         </b>
         <?
         }
      }
   else
      {
      //
      // Fill the page out with a warning and instructions.
      //
      ?>
      <h2><i>Sorry...</i></h2>
      <b>
      <blockquote>
         <p>OSCAR's database is temporarily unavailable.&nbsp; Please try your approval-and-trust operation later.</p>
      </blockquote>            
      </b>
      <?
      }
   }
else
   {
   //
   // Fill the page out with a warning and instructions.
   //
   ?>
   <h2><i>Error!</i></h2>
   <b>
   <blockquote>
      <p>Invalid arguments.</p>
   </blockquote>            
   </b>
   <?
   }
?>
<br clear=both>
<hr>
<p><small><small><em><pre>$Id$</pre></em></small></small>
</td>
</tr>
</table>
</body>
</html>
