<?
//
// $Id$
//
require_once("f_oscarhomepageurl.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("f_bodyopen.phtml");
?>
<html>

<head>
<title>OSCAR - VBDEMS ALS Availability Submission Form</title>
</head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
        <table><tr><td>
           <h6 align="center">
              KVEO-IT-PROJECT<br>
              <a href="<? echo OscarHomePageUrl(); ?>">OSCAR SYSTEM</a><br>
              <a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></h6>
           <h1 align="center">Online Availability Submission Form</h1>
           <h2 align="center">for ALS Providers</h2>
        </td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>
           <? PutLibPhotoRandomPlaced("sasquatch",1); ?>
        </td></tr></table>
        <hr>
        <p>For ALS members only.&nbsp; <b>Bold</b> fields are required.</p>
        <form method="POST" action="add-avail-sheet.phtml">
          <table border="0" cellpadding="0" cellspacing="0" width="912">
            <tr>
              <td width="167">First name:</td>
              <td width="741"><input type="text" name=first_name size="32"></td>
            </tr>
            <tr>
              <td width="167"><b>Last name:</b></td>
              <td width="741"><input type="text" name=last_name size="32"></td>
            </tr>
            <tr>
              <td width="167"><b>Officer code:</b></td>
              <td width="741"><input type="text" name=cad_num size="6">&nbsp; (<-- Your MDT logon number)</td>
            </tr>
            <tr>
              <td width="167"><b>Email address:</b></td>
              <td width="741"><input type="text" name=email_addr size="64"></td>
            </tr>
<?
//$ReviewPoint--
?>
            <tr>
              <td width="167"><b>Applicable month:</b></td>
              <td width="741"><select size="1" name=month>
                  <option value="">Select</option>
                  <option value="JAN">January</option>
                  <option value="FEB">February</option>
                  <option value="MAR">March</option>
                  <option value="APR">April</option>
                  <option value="MAY">May</option>
                  <option value="JUN">June</option>
                  <option value="JUL">July</option>
                  <option value="AUG">August</option>
                  <option value="SEP">September</option>
                  <option value="OCT">October</option>
                  <option value="NOV">November</option>
                  <option value="DEC">December</option>
                </select></td>
            </tr>
            <tr>
              <td width="167"><b>Home squad:</b></td>
              <td width="741"><select size="1" name=squad>
                  <option value="">Select</option>
                  <option value="1">1 - Ocean Park</option>
                  <option value="2">2 - Davis Corner</option>
                  <option value="4">4 - Chesapeake Beach</option>
                  <option value="5">5 - Courthouse</option>
                  <option value="6">6 - Creeds</option>
                  <option value="9">9 - Kempsville</option>
                  <option value="13">13 - Blackwater</option>
                  <option value="14">14 - Virginia Beach</option>
                  <option value="15">15 - Knotts Island</option>
                  <option value="16">16 - Plaza</option>
                  <option value="17">17 - Sandbridge</option>
                  <option value="0">ERS - VBFD</option>
                </select></td>
            </tr>
          </table>
  </center>
        <p>Check all that apply as of today's date:</p>
        <ul>
          <li><input type="checkbox" name=be_on_team_30 value="TRUE">I
            am on the Squad Truck Team.</li>
          <li><input type="checkbox" name=be_on_team_5 value="TRUE">I
            am an EMS-5.</li>
        </ul>
        <div align="left">
          <table border="0" cellpadding="0" cellspacing="0" width="892">
            <tr>
              <td width="890" valign="bottom" colspan="3">Check all shifts for
                which you are available for at least one type of duty:
                <p>&nbsp;</td>
            </tr>
            <tr>
              <td width="136" valign="bottom">Leave nonapplicable days blank.
                <p>&nbsp;</td>
              <td width="125" valign="bottom">
                <p align="left">Day shifts</p>
                <ul>
                  <li><input type="checkbox" name="D1" value="AVAILABLE">1st</li>
                  <li><input type="checkbox" name="D2" value="AVAILABLE">2nd</li>
                  <li><input type="checkbox" name="D3" value="AVAILABLE">3rd</li>
                  <li><input type="checkbox" name="D4" value="AVAILABLE">4th</li>
                  <li><input type="checkbox" name="D5" value="AVAILABLE">5th</li>
                  <li><input type="checkbox" name="D6" value="AVAILABLE">6th</li>
                  <li><input type="checkbox" name="D7" value="AVAILABLE">7th</li>
                  <li><input type="checkbox" name="D8" value="AVAILABLE">8th</li>
                  <li><input type="checkbox" name="D9" value="AVAILABLE">9th</li>
                  <li><input type="checkbox" name="D10" value="AVAILABLE">10th</li>
                  <li><input type="checkbox" name="D11" value="AVAILABLE">11th</li>
                  <li><input type="checkbox" name="D12" value="AVAILABLE">12th</li>
                  <li><input type="checkbox" name="D13" value="AVAILABLE">13th</li>
                  <li><input type="checkbox" name="D14" value="AVAILABLE">14th</li>
                  <li><input type="checkbox" name="D15" value="AVAILABLE">15th</li>
                  <li><input type="checkbox" name="D16" value="AVAILABLE">16th</li>
                  <li><input type="checkbox" name="D17" value="AVAILABLE">17th</li>
                  <li><input type="checkbox" name="D18" value="AVAILABLE">18th</li>
                  <li><input type="checkbox" name="D19" value="AVAILABLE">19th</li>
                  <li><input type="checkbox" name="D20" value="AVAILABLE">20th</li>
                  <li><input type="checkbox" name="D21" value="AVAILABLE">21st</li>
                  <li><input type="checkbox" name="D22" value="AVAILABLE">22nd</li>
                  <li><input type="checkbox" name="D23" value="AVAILABLE">23rd</li>
                  <li><input type="checkbox" name="D24" value="AVAILABLE">24th</li>
                  <li><input type="checkbox" name="D25" value="AVAILABLE">25th</li>
                  <li><input type="checkbox" name="D26" value="AVAILABLE">26th</li>
                  <li><input type="checkbox" name="D27" value="AVAILABLE">27th</li>
                  <li><input type="checkbox" name="D28" value="AVAILABLE">28th</li>
                  <li><input type="checkbox" name="D29" value="AVAILABLE">29th</li>
                  <li><input type="checkbox" name="D30" value="AVAILABLE">30th</li>
                  <li><input type="checkbox" name="D31" value="AVAILABLE">31st</li>
                </ul>
              </td>
              <td width="625" valign="bottom">
                <p align="left">Night shifts</p>
                <ul>
                  <li><input type="checkbox" name="N1" value="AVAILABLE">1st</li>
                  <li><input type="checkbox" name="N2" value="AVAILABLE">2nd</li>
                  <li><input type="checkbox" name="N3" value="AVAILABLE">3rd</li>
                  <li><input type="checkbox" name="N4" value="AVAILABLE">4th</li>
                  <li><input type="checkbox" name="N5" value="AVAILABLE">5th</li>
                  <li><input type="checkbox" name="N6" value="AVAILABLE">6th</li>
                  <li><input type="checkbox" name="N7" value="AVAILABLE">7th</li>
                  <li><input type="checkbox" name="N8" value="AVAILABLE">8th</li>
                  <li><input type="checkbox" name="N9" value="AVAILABLE">9th</li>
                  <li><input type="checkbox" name="N10" value="AVAILABLE">10th</li>
                  <li><input type="checkbox" name="N11" value="AVAILABLE">11th</li>
                  <li><input type="checkbox" name="N12" value="AVAILABLE">12th</li>
                  <li><input type="checkbox" name="N13" value="AVAILABLE">13th</li>
                  <li><input type="checkbox" name="N14" value="AVAILABLE">14th</li>
                  <li><input type="checkbox" name="N15" value="AVAILABLE">15th</li>
                  <li><input type="checkbox" name="N16" value="AVAILABLE">16th</li>
                  <li><input type="checkbox" name="N17" value="AVAILABLE">17th</li>
                  <li><input type="checkbox" name="N18" value="AVAILABLE">18th</li>
                  <li><input type="checkbox" name="N19" value="AVAILABLE">19th</li>
                  <li><input type="checkbox" name="N20" value="AVAILABLE">20th</li>
                  <li><input type="checkbox" name="N21" value="AVAILABLE">21st</li>
                  <li><input type="checkbox" name="N22" value="AVAILABLE">22nd</li>
                  <li><input type="checkbox" name="N23" value="AVAILABLE">23rd</li>
                  <li><input type="checkbox" name="N24" value="AVAILABLE">24th</li>
                  <li><input type="checkbox" name="N25" value="AVAILABLE">25th</li>
                  <li><input type="checkbox" name="N26" value="AVAILABLE">26th</li>
                  <li><input type="checkbox" name="N27" value="AVAILABLE">27th</li>
                  <li><input type="checkbox" name="N28" value="AVAILABLE">28th</li>
                  <li><input type="checkbox" name="N29" value="AVAILABLE">29th</li>
                  <li><input type="checkbox" name="N30" value="AVAILABLE">30th</li>
                  <li><input type="checkbox" name="N31" value="AVAILABLE">31st</li>
                </ul>
              </td>
            </tr>
          </table>
        </div>
        <p align="left">How many extra shifts are you willing to be scheduled
          for?&nbsp; <input type="text" name=num_extras size="2" value="0"></p>
          <blockquote>
            <table border="1">
               <tr>
                  <td width="100%">
                     <p align="center"><u>Survey box</u><br>
                     <small>Please take a moment to fill out the survey questions,
                     if any.</small></p>
                     <ul>
                        <li>No survey questions at this time.</li>
                     </ul>
                  </td>
               </tr>
            </table>
          </blockquote>
          <p align="left">Special requests:<br>
          <textarea rows="8" name=note cols="60"></textarea></p>
        <ul>
          <li>
            <p align="left">Availability sheets are due on the 10th day of the
            proceeding month.</li>
          <li>
            <p align="left">Double check your selections before submitting this
            form.</li>
          <li>
            <p align="left">When you click Submit, this form will be converted
            into an email and sent to the VBDEMS Central Schedule Coordinator.</li>
          <li>
            <p align="left">If you have feedback about this form, please send it
            to the <a href="mailto:infotech@kvrs.org">OSCAR Administrator</a>.</li>
          <li>
            <p align="left">If you wish to print a copy of the completed form
            for your records, do so <b>before</b> you click Submit.</li>
        </ul>
  <center>
          <p><input type="submit" value="Submit" name="B1"><input type="reset" value="Reset" name="B2"></p>
        </form>
        <p><small><small><em><pre>$Id$</pre></em></small></small></center></td>
    </tr>
  </table>
</body>

</html>

