<?
//
// $Id$
//
require_once("f_oscarhomepageurl.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("f_bodyopen.phtml");
require_once("f_password.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_sendapprovalnotice.phtml");
//
?>
<html>
<head><title>Report generation</title></head>\n";
<? BodyOpen(); ?>
<table align=center width=80%><tr><td>
<H6 ALIGN=CENTER>KVEO-IT-PROJECT<br><a href=" . OscarHomePageUrl() . ">OSCAR</a><br><a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></H6>\n";
<H1 ALIGN=CENTER>Availability Report Request Approval</H1>
<hr>
<?
if (SendApprovalNotice($email_addr,$digest))
   {
   PutLibPhotoRandomPlaced("sasquatch",1,"left");
   echo "<p>Thanks for approving user $email_addr's request.&nbsp; The OSCAR system has sent the user instructions on how to retrieve the requested report.</p>";
   echo "<p><a href=mailto:" . RoleEmailAddress("") . "><i>OSCAR System Administrator</i></a></p>";
   }
else
   {
   //
   // Fill the page out with a warning and instructions.
   //
   ?>
   <h2><i>Error!</i></h2>
   <b>
   <blockquote>
      <? echo "<p>The OSCAR system encountered an internal error while processing your request.  Please let the <a href=mailto:" . RoleEmailAddress("") . "?subj=\"OSCAR Bug Report\">OSCAR System Administrator</a> know this error occurred.</p>"; ?>
   </blockquote>            
   </b>
   <?
   }
?>
<br clear=both>
<hr>
<p><small><small><em><pre>$Id$</pre></em></small></small>
</td>
</tr>
</table>
</body>
</html>
