<?
//
// $Id$
//
require_once("f_oscarhomepageurl.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
?>
<html>

<head><title>OSCAR - How to become a KVEO-IT-PROJECT developer</title></head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
           <h6 align="center">
              KVEO-IT-PROJECT - <a href="<? echo OscarHomePageUrl(); ?>">OSCAR SYSTEM</a></h6>
           <h1 align="center">How to become a KVEO-IT-PROJECT developer</h1>
        <hr>
        <? PutLibPhotoRandomPlaced("sasquatch",1,"right"); ?>
        <p>The OSCAR system is one of the modules in an <a href=http://www.osdn.com/history>open-source</a> project called 
           the Kempsville Volunteer Emergency Organization Information Technology Project (KVEO-IT-PROJECT), the purpose
           of which is...</p>
           <blockquote><i>To develop Information Technology resources for Volunteer Emergency Organizations.&nbsp; Domains include
              Kempsville, Virginia Beach, and VEO's in general.</i></blockquote>
        <p>Other modules in the project at the time of this writing include:</p>
        <dl>
           <dt><a href=http://www.kvrs.org>www.KVRS.org</a></dt>
           <dd><p>Official web site of the Kempsville Volunteer Rescue Squad, Virginia Beach, Virginia</p></dd>
           <dt><a href=http://users.exis.net/~klips/downloads/index.htm#ServiceRendered>ServiceRendered</a></dt>
           <dd><p>Palm OS application to allow EMS personnel to collect case summary information</p></dd>
        </ul>
        <p>The project, at its heart, is an effort by volunteer developers to create tools for volunteer emergency
           workers.</p>
        <p>You can help develop existing modules or you can propose new ones.&nbsp; Valuable contributions are not 
           limited to web site development and application coding.&nbsp; You might, for instance, contribute web content 
           or other documentation, graphic design or mutimedia skills, etc.&nbsp; The KVEO-IT-PROJECT is a platform from 
           which to launch any idea that fits the project's purpose.</p>
        <p>Items that need attention include
           <a href=http://sf.net/tracker/?atid=351099&group_id=1099&func=browse>feature requests</a>,
           <a href=http://sf.net/tracker/?atid=201099&group_id=1099&func=browse>support requests</a>, and 
           <a href=http://sf.net/tracker/?atid=101099&group_id=1099&func=browse>bugs</a>.</p>
        <p>At a minimum, anyone interested in contributing to the project should procede as follows:</p>
        <ol>
           <li><p>Know <a href=http://www.cvshome.org>what CVS is and basically how to use it.</a></p>
           <li><p>Visit <a href=http://sourceforge.net>SourceForge</a> and sign up as a New User.</p></li>
           <li><p><a href=mailto:<? echo RoleEmailAddress(""); ?>>Email me</a>, tell me how you'd like to contribute, and give me
              your SourceForge username.</p></li>
           <li><p>Visit <a href=http://sfsetup.sf.net>sfsetup.sourceforge.net</a>.&nbsp; Read the tutorial, then download 
              and run the SFSetup application.</p>
        </ol>
        <hr>
        <p><small><small><em><pre>$Id$</pre></em></small></small></center></td>
    </tr>
  </table>
</body>

</html>

