<?
//
// $Id$
//
function AvailList
   (
   $v1,$v2,$v3,$v4,$v5,$v6,$v7,$v8,$v9,$v10,$v11,$v12,$v13,$v14,$v15,$v16,$v17,$v18,$v19,$v20,$v21,$v22,$v23,$v24,$v25,$v26,$v27,$v28,$v29,$v30,$v31
   )
   {
   $v = array(1 => $v1,$v2,$v3,$v4,$v5,$v6,$v7,$v8,$v9,$v10,$v11,$v12,$v13,$v14,$v15,$v16,$v17,$v18,$v19,$v20,$v21,$v22,$v23,$v24,$v25,$v26,$v27,$v28,$v29,$v30,$v31);
   for ($i=1; $i<=31; $i++)
      {
      if ($v[$i]) $avail_string .= date("jS, ",mktime(12,0,0,"",$i));
      }
   return substr($avail_string,0,-2);
   }
?>