<?
//
// $Id: f_beauthority.phtml 3402 2010-11-28 01:36:33Z KevinAnLipscomb $
//
function BeValidPartialShiftSpec($s = "")
  {
  $saved_error_level = error_reporting(E_ALL);
  $be_valid_partial_shift_spec = FALSE;
  //
  $s = trim($s);
  //
  error_reporting($saved_error_level);
  return ($s == "")
    || preg_match("/^([0-1][0-9]|2[0-4])[0-5][0-9]-([0-1][0-9]|2[0-4])[0-5][0-9]$/",$s)
    || preg_match("/^([0-1][0-9]|2[0-4])-([0-1][0-9]|2[0-4])$/",$s);
  }
?>