<?
//
// $Id$
//
function CoordAgencyOfClearedEmailAddr
   (
   $db_link,
   $email_addr,
   $mode = ""
   )
   {
   $saved_error_level = error_reporting(E_ALL);
   //
   $coord_agency = "";
   //
   $result = $db_link->query
      (
      "select coord_agency from " . $mode . "authority "
      .  "   where email_addr='$email_addr'"
      .  "      and has_clearance='TRUE' "
      )
      or die("CoordAgencyOfClearedEmailAddr query failed with error:  " . mysqli_error($db_link));
   //
   if (mysqli_num_rows($result)) extract(mysqli_fetch_array($result));
   //
   error_reporting($saved_error_level);
   return $coord_agency;
   }
?>