<?
//
// $Id$
//
function FormattedNoteAppendage
   (
   $mode,
   $condition,
   $mnemonic,
   $message,
   $source = "OSCAR"
   )
   {
   if ($mode) $saved_error_level = error_reporting(E_ALL);
   //
   $pad_mask = "................";
   //
   $s =  "<br:br>"
      .  "<tt>"
      .  str_pad("mesg(" . strtoupper($mnemonic) . ")",16,$pad_mask)
      .  "from(" .  strtoupper($source) .  ")"
      .  "<br>"
      .  str_pad("type(" . strtoupper($condition) . ")",16,$pad_mask)
      .  "time(" .  date("Y-m-d-H:i-T") . ")"
      .  "</tt>"
      .  "<br>"
      .  addslashes($message);
   //
   if ($mode) error_reporting($saved_error_level);
   return $s;
   }
?>