<?
//
// $Id$
//
function NumDistinctUsers
   (
   $month_abbrev,
   $mode = "",
   $coord_agency = ""
   )
   {
   $saved_error_level = error_reporting(E_ALL);
   //
   $num_distinct_users = 0;
   $qry = "select distinct email_addr from oscar." . $mode . "avail_sheet "
      .  "   where month='$month_abbrev' ";
   if ($coord_agency)
      {
      $qry .= "and coord_agency='$coord_agency' ";
      }
   $result = mysql_query($qry)
      or die("NumSheets query failed with error:  " . mysql_error());
   $num_distinct_users = mysql_num_rows($result);
   //
   error_reporting($saved_error_level);
   return $num_distinct_users;
   }
?>