<?
//
// $Id$
//
function NumSheets
   (
   $month_abbrev,
   $mode = "",
   $coord_agency = "",
   $email_filter = ""
   )
   {
   error_reporting(E_ALL);
   //
   $num_sheets = 0;
   $qry = "select count(*) as num_sheets from oscar." . $mode . "avail_sheet "
      .  "   where month='$month_abbrev' ";
   switch ($email_filter)
      {
	  case "VBGOV":
	     $qry .= " and email_addr like '%VBGOV.COM%' ";
		 break;
      case "NONVBGOV":
	     $qry .= " and email_addr not like '%VBGOV.COM%' ";
		 break;
	  }
   if (!$coord_agency)
      {
      $qry .= " group by month";
      }
   else
      {
      $qry .= "and coord_agency='$coord_agency' "
      .  " group by month,coord_agency";
      }
   $result = mysql_query($qry)
      or die("NumSheets query failed with error:  " . mysql_error());
   if (mysql_num_rows($result)) extract(mysql_fetch_array($result));
   //
   return $num_sheets;
   }
?>