<?
//
// $Id$
//
function SquadOfCoordAgency
   (
   $db_link,
   $coord_agency,
   $mode = ""
   )
//
   {
   $saved_error_level = error_reporting(E_ALL);
   //
   $squad = "";
   $result = $db_link->query("select squad from " . $mode . "squad_of_coord_agency where coord_agency='$coord_agency'")
      or die("SquadOfCoordAgency query failed with error: " . mysqli_error($db_link));
   extract(mysqli_fetch_array($result));
   //
   error_reporting($saved_error_level);
   return $squad;
   }
?>