<?
//
// $Id$
//
function sShowAvailSheetRecDetail
   (
   $timestamp,
   $first_name,
   $last_name,
   $email_addr,
   $squad,
   $month,
   $be_on_team_5,
   $be_on_team_30,
   $be_tda,
   $be_als,
   $num_extras,
   $d1,$d2,$d3,$d4,$d5,$d6,$d7,$d8,$d9,$d10,$d11,$d12,$d13,$d14,$d15,$d16,$d17,$d18,$d19,$d20,$d21,$d22,$d23,$d24,$d25,$d26,$d27,$d28,$d29,$d30,$d31,
   $n1,$n2,$n3,$n4,$n5,$n6,$n7,$n8,$n9,$n10,$n11,$n12,$n13,$n14,$n15,$n16,$n17,$n18,$n19,$n20,$n21,$n22,$n23,$n24,$n25,$n26,$n27,$n28,$n29,$n30,$n31,
   $note,
   $expiration,
   $be_authority = "",
   $mode = "",
   $coord_agency = "EMS",
   $be_needing_driver = "",
   $be_nondriver = "",
   $be_third = ""
   )
   {
   if ($mode) $saved_error_level = error_reporting(E_ALL);
   //
   $s =  "";
   $s .= "   NAME:\n"
      .  "      " . stripslashes($first_name) . " " . stripslashes($last_name) . "\n";
   $s .= "   EMAIL ADDRESS:\n"
      .  "      " . stripslashes($email_addr) . "\n";
   $s .= "   Applicable month:\n"
      .  "      $month\n";
   $s .= "   Coordinating agency:\n"
      .  "      $coord_agency\n";
   if ($coord_agency == "EMS")
      {
      $s .= "   Home squad:\n"
         .  "      $squad\n";
      $s .= "   Zone car ALS:\n"
         .  "      $be_als\n";
      $s .= "   On squad truck team:\n"
         .  "      $be_on_team_30\n";
      $s .= "   On EMS-5 team:\n"
         .  "      $be_on_team_5\n";
      $s .= "   TDA:\n"
         .  "      $be_tda\n";
      }
   else
      {
      $s .= "   Ambulance ALS:\n"
         .  "      $be_needing_driver\n";
      $s .= "   Nondriver:\n"
         .  "      $be_nondriver\n";
      $s .= "   Third:\n"
         .  "      $be_third\n";
      }
   $s .= "   Time of submission:\n";
   $s .= "      "
      .  substr($timestamp,0,4)
      .  "-"
      .  substr($timestamp,4,2)
      .  "-"
      .  substr($timestamp,6,2)
      .  " "
      .  substr($timestamp,8,2)
      .  ":"
      .  substr($timestamp,10,2)
      .  ":"
      .  substr($timestamp,12,2)
      .  "\n";
   $s .= "   Record expires:\n"
      .  "      $expiration\n";
   $s .= "   AVAILABLE DAYS:\n"
      .  "      "
      . wordwrap
         (
         AvailList($d1,$d2,$d3,$d4,$d5,$d6,$d7,$d8,$d9,$d10,$d11,$d12,$d13,$d14,$d15,$d16,$d17,$d18,$d19,$d20,$d21,$d22,$d23,$d24,$d25,$d26,$d27,$d28,$d29,$d30,$d31),
         66,
         "\n      "
         )
      . "\n";
   $s .= "   AVAILABLE NIGHTS:\n"
      .  "      "
      . wordwrap
         (
         AvailList($n1,$n2,$n3,$n4,$n5,$n6,$n7,$n8,$n9,$n10,$n11,$n12,$n13,$n14,$n15,$n16,$n17,$n18,$n19,$n20,$n21,$n22,$n23,$n24,$n25,$n26,$n27,$n28,$n29,$n30,$n31),
         66,
         "\n      "
         )
      . "\n";
   $s .= "   #EXTRA DUTIES WILL RUN:\n"
      .  "      $num_extras\n";
   if ($be_authority == 1)
      {
      $s .= "   NOTE:\n"
         .  "      " . PlainTextOfNote(stripslashes($note),6,72,$mode) . "\n";
      }
   //
   if ($mode) error_reporting($saved_error_level);
   return $s;
   }
?>