<?
//
// $Id$
//
require_once("f_availlist.phtml");
//
function sShowAvailSheetRecDetail
   (
   $timestamp,
   $first_name,
   $last_name,
   $email_addr,
   $squad,
   $month,
   $be_on_team_5,
   $be_on_team_30,
   $be_tda,
   $num_extras,
   $d1,$d2,$d3,$d4,$d5,$d6,$d7,$d8,$d9,$d10,$d11,$d12,$d13,$d14,$d15,$d16,$d17,$d18,$d19,$d20,$d21,$d22,$d23,$d24,$d25,$d26,$d27,$d28,$d29,$d30,$d31,
   $n1,$n2,$n3,$n4,$n5,$n6,$n7,$n8,$n9,$n10,$n11,$n12,$n13,$n14,$n15,$n16,$n17,$n18,$n19,$n20,$n21,$n22,$n23,$n24,$n25,$n26,$n27,$n28,$n29,$n30,$n31,
   $note,
   $expiration,
   $be_authority = ""
   )
   {
   $s =  "";
   $s .= "       TIME OF SUBMISSION:  ";
   $s .= substr($timestamp,0,4)
      .  "-"
      .  substr($timestamp,4,2)
      .  "-"
      .  substr($timestamp,6,2)
      .  " "
      .  substr($timestamp,8,2)
      .  ":"
      .  substr($timestamp,10,2)
      .  ":"
      .  substr($timestamp,12,2)
      .  "\n";
   $s .= "               FIRST NAME:  " . stripslashes($first_name) . "\n";
   $s .= "                LAST NAME:  " . stripslashes($last_name) . "\n";
   $s .= "            EMAIL ADDRESS:  " . stripslashes($email_addr) . "\n";
   $s .= "               HOME SQUAD:  $squad\n";
   $s .= "         APPLICABLE MONTH:  $month\n";
   $s .= "            ON EMS-5 TEAM:  $be_on_team_5\n";
   $s .= "      ON SQUAD TRUCK TEAM:  $be_on_team_30\n";
   $s .= "                      TDA:  $be_tda\n";
   $s .= "   #EXTRA DUTIES WILL RUN:  $num_extras\n";
   $s .= "           AVAILABLE DAYS:  " . AvailList($d1,$d2,$d3,$d4,$d5,$d6,$d7,$d8,$d9,$d10,$d11,$d12,$d13,$d14,$d15,$d16,$d17,$d18,$d19,$d20,$d21,$d22,$d23,$d24,$d25,$d26,$d27,$d28,$d29,$d30,$d31) . "\n";
   $s .= "         AVAILABLE NIGHTS:  " . AvailList($n1,$n2,$n3,$n4,$n5,$n6,$n7,$n8,$n9,$n10,$n11,$n12,$n13,$n14,$n15,$n16,$n17,$n18,$n19,$n20,$n21,$n22,$n23,$n24,$n25,$n26,$n27,$n28,$n29,$n30,$n31) . "\n";
   if ($be_authority == 1)
      {
      $s .= "                     NOTE:  " . stripslashes($note) . "\n";
      }
   $s .= "           RECORD EXPIRES:  $expiration\n";
   //
   return $s;
   }
?>