<?
//
// $Id$
//
function WriteCalendarSubform
   (
   $instruction_string = "",
   $mode = ""
   )
//
   {
   ?>
   <table border="0" cellpadding="0" cellspacing="0" width="892">
     <tr>
       <td width="890" valign="bottom" colspan="3"><? echo $instruction_string; ?><p>&nbsp;</td>
     </tr>
     <tr>
       <td width="136" valign="bottom">Leave nonapplicable days blank.
         <p>&nbsp;</td>
       <td width="125" valign="bottom">
         <p align="left">Day shifts</p>
         <ul>
           <li><input type="checkbox" name="d1" value="AVAILABLE">1st</li>
           <li><input type="checkbox" name="d2" value="AVAILABLE">2nd</li>
           <li><input type="checkbox" name="d3" value="AVAILABLE">3rd</li>
           <li><input type="checkbox" name="d4" value="AVAILABLE">4th</li>
           <li><input type="checkbox" name="d5" value="AVAILABLE">5th</li>
           <li><input type="checkbox" name="d6" value="AVAILABLE">6th</li>
           <li><input type="checkbox" name="d7" value="AVAILABLE">7th</li>
           <li><input type="checkbox" name="d8" value="AVAILABLE">8th</li>
           <li><input type="checkbox" name="d9" value="AVAILABLE">9th</li>
           <li><input type="checkbox" name="d10" value="AVAILABLE">10th</li>
           <li><input type="checkbox" name="d11" value="AVAILABLE">11th</li>
           <li><input type="checkbox" name="d12" value="AVAILABLE">12th</li>
           <li><input type="checkbox" name="d13" value="AVAILABLE">13th</li>
           <li><input type="checkbox" name="d14" value="AVAILABLE">14th</li>
           <li><input type="checkbox" name="d15" value="AVAILABLE">15th</li>
           <li><input type="checkbox" name="d16" value="AVAILABLE">16th</li>
           <li><input type="checkbox" name="d17" value="AVAILABLE">17th</li>
           <li><input type="checkbox" name="d18" value="AVAILABLE">18th</li>
           <li><input type="checkbox" name="d19" value="AVAILABLE">19th</li>
           <li><input type="checkbox" name="d20" value="AVAILABLE">20th</li>
           <li><input type="checkbox" name="d21" value="AVAILABLE">21st</li>
           <li><input type="checkbox" name="d22" value="AVAILABLE">22nd</li>
           <li><input type="checkbox" name="d23" value="AVAILABLE">23rd</li>
           <li><input type="checkbox" name="d24" value="AVAILABLE">24th</li>
           <li><input type="checkbox" name="d25" value="AVAILABLE">25th</li>
           <li><input type="checkbox" name="d26" value="AVAILABLE">26th</li>
           <li><input type="checkbox" name="d27" value="AVAILABLE">27th</li>
           <li><input type="checkbox" name="d28" value="AVAILABLE">28th</li>
           <li><input type="checkbox" name="d29" value="AVAILABLE">29th</li>
           <li><input type="checkbox" name="d30" value="AVAILABLE">30th</li>
           <li><input type="checkbox" name="d31" value="AVAILABLE">31st</li>
         </ul>
       </td>
       <td width="625" valign="bottom">
         <p align="left">Night shifts</p>
         <ul>
           <li><input type="checkbox" name="n1" value="AVAILABLE">1st</li>
           <li><input type="checkbox" name="n2" value="AVAILABLE">2nd</li>
           <li><input type="checkbox" name="n3" value="AVAILABLE">3rd</li>
           <li><input type="checkbox" name="n4" value="AVAILABLE">4th</li>
           <li><input type="checkbox" name="n5" value="AVAILABLE">5th</li>
           <li><input type="checkbox" name="n6" value="AVAILABLE">6th</li>
           <li><input type="checkbox" name="n7" value="AVAILABLE">7th</li>
           <li><input type="checkbox" name="n8" value="AVAILABLE">8th</li>
           <li><input type="checkbox" name="n9" value="AVAILABLE">9th</li>
           <li><input type="checkbox" name="n10" value="AVAILABLE">10th</li>
           <li><input type="checkbox" name="n11" value="AVAILABLE">11th</li>
           <li><input type="checkbox" name="n12" value="AVAILABLE">12th</li>
           <li><input type="checkbox" name="n13" value="AVAILABLE">13th</li>
           <li><input type="checkbox" name="n14" value="AVAILABLE">14th</li>
           <li><input type="checkbox" name="n15" value="AVAILABLE">15th</li>
           <li><input type="checkbox" name="n16" value="AVAILABLE">16th</li>
           <li><input type="checkbox" name="n17" value="AVAILABLE">17th</li>
           <li><input type="checkbox" name="n18" value="AVAILABLE">18th</li>
           <li><input type="checkbox" name="n19" value="AVAILABLE">19th</li>
           <li><input type="checkbox" name="n20" value="AVAILABLE">20th</li>
           <li><input type="checkbox" name="n21" value="AVAILABLE">21st</li>
           <li><input type="checkbox" name="n22" value="AVAILABLE">22nd</li>
           <li><input type="checkbox" name="n23" value="AVAILABLE">23rd</li>
           <li><input type="checkbox" name="n24" value="AVAILABLE">24th</li>
           <li><input type="checkbox" name="n25" value="AVAILABLE">25th</li>
           <li><input type="checkbox" name="n26" value="AVAILABLE">26th</li>
           <li><input type="checkbox" name="n27" value="AVAILABLE">27th</li>
           <li><input type="checkbox" name="n28" value="AVAILABLE">28th</li>
           <li><input type="checkbox" name="n29" value="AVAILABLE">29th</li>
           <li><input type="checkbox" name="n30" value="AVAILABLE">30th</li>
           <li><input type="checkbox" name="n31" value="AVAILABLE">31st</li>
         </ul>
       </td>
     </tr>
   </table>
   <?
   }
?>