<?
//
// $Id$
//
function WriteCalendarSubform
   (
   $applicable_month_num,
   $instruction_string = "",
   $mode = ""
   )
//
   {
   $num_days_in_applicable_month = date("t",mktime(12,0,0,$applicable_month_num,1));
   $format_string = "jS (D)";
   ?>
   <table>
     <tr>
       <td valign="bottom" colspan="3"><? echo $instruction_string; ?><p>&nbsp;</td>
     </tr>
     <tr>
       <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
       <td>
         <p align="left">Day shifts</p>
         <ul>
           <?
           for ($i=1; $i<=$num_days_in_applicable_month; $i++)
              {
              echo "<li><input type=checkbox name=d$i value=\"AVAILABLE\">"
                 . date($format_string,mktime(12,0,0,$applicable_month_num,$i))
                 . "</li>\n";
              }
           ?>
         </ul>
       </td>
       <td>
         <p align="left">Night shifts</p>
         <ul>
           <?
           for ($i=1; $i<=$num_days_in_applicable_month; $i++)
              {
              echo "<li><input type=checkbox name=n$i value=\"AVAILABLE\">"
                 . date($format_string,mktime(12,0,0,$applicable_month_num,$i))
                 . "</li>\n";
              }
           ?>
         </ul>
       </td>
     </tr>
   </table>
   <?
   }
?>