<?
//
// $Id$
//
function WriteCalendarSubform
   (
   $applicable_month_num,
   $instruction_string = "",
   $mode = ""
   )
//
   {
   $num_days_in_applicable_month = date("t",mktime(12,0,0,$applicable_month_num,1));
   ?>
   <table>
     <tr>
       <td valign="bottom" colspan="3"><? echo $instruction_string; ?><p>&nbsp;</td>
     </tr>
     <tr>
       <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
       <td>
         <p align="left">Day shifts</p>
         <ul>
           <?
           for ($i=1; $i<=$num_days_in_applicable_month; $i++)
              {
              echo "<li><input type=checkbox name=d$i value=\"AVAILABLE\">"
                 . date("jS (D)",mktime(12,0,0,1,$i))
                 . "</li>\n";
                 //
                 // The call to mktime() gets us the day number (j) and the ordinal value (S) for time:
                 //
                 //    currentyear-01-$i 12:00:00
                 //
                 // This works for us because no matter what the actual month of interest is, because January of any year has all
                 // 31 days and all 31 proper ordinal values, and those are the only elements we're really interested in.  The
                 // choice of noon is arbitrary.
                 //
              }
           ?>
         </ul>
       </td>
       <td>
         <p align="left">Night shifts</p>
         <ul>
           <?
           for ($i=1; $i<=$num_days_in_applicable_month; $i++)
              {
              echo "<li><input type=checkbox name=n$i value=\"AVAILABLE\">"
                 . date("jS (D)",mktime(12,0,0,1,$i))
                 . "</li>\n";
                 //
                 // The call to mktime() gets us the day number (j) and the ordinal value (S) for time:
                 //
                 //    currentyear-01-$i 12:00:00
                 //
                 // This works for us because no matter what the actual month of interest is, because January of any year has all
                 // 31 days and all 31 proper ordinal values, and those are the only elements we're really interested in.  The
                 // choice of noon is arbitrary.
                 //
              }
           ?>
         </ul>
       </td>
     </tr>
   </table>
   <?
   }
?>