<?
//
// $Id$
//
//
// Emulate register_globals on
if (!ini_get('register_globals'))
  {
  $superglobals = array($_SERVER,$_ENV,$_FILES,$_COOKIE,$_POST,$_GET);
  if (isset($_SESSION))
    {
    array_unshift($superglobals, $_SESSION);
    }
  foreach ($superglobals as $superglobal)
    {
    extract($superglobal, EXTR_SKIP);
    }
  }
require_once("f_runmode.phtml");
$mode = "";
if (RunMode($PHP_SELF)) error_reporting(E_ALL);
//
require_once("f_oscarhomepageurl.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_connectselectdbinstanceunpublished.phtml");
require_once("f_writecalendarsubform.phtml");
require_once("f_writecalendarbody.phtml");
?>
<html>

<head>
<title>OSCAR - Availability Submission</title>
</head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
        <table><tr>
           <td><? PutLibPhotoRandomPlaced("oscarsystem",1); ?></td>
           <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
           <td>
              <h6 align="center">
                 KVEO-IT-PROJECT<br>
                 <a href="<? echo OscarHomePageUrl(); ?>">OSCAR SYSTEM</a><br>
                 <a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></h6>
              <h1 align="center">Availability Submission</h1>
           </td>
        </tr></table>
        <hr>
        <?
        if (ConnectSelectDbInstanceUNPUBLISHED($db_link) == "TRUE")
        {
        
        //
        // Validate parameters.
        //
        if
           (
              ($first_name != "")
           and
              ($last_name != "")
           and
              ($email_addr != "")
           and
              ($applicable_month_num != "")
           and
              ($coord_agency != "")
           and
              ($odnmid != "")
           and
              ($squad != "")
           )
        // then
        {
        //
        // Show what was collected in Part 1.
        //
        echo "<br>\n"
           . "<table>\n"
           . "   <tr><td>Name:</td><td><b>$first_name $last_name</b></td></tr>\n"
           . "   <tr><td>Email address:</td><td><b>$email_addr</b></td></tr>\n"
           . "   <tr><td>Applicable month:</td><td><b>" . date("F",mktime(12,0,0,$applicable_month_num,1)) . "</b></td></tr>\n"
           . "   <tr><td>Coordinating agency:</td><td><b>$coord_agency</b></td></tr>\n"
           . "   <tr><td>Home squad:</td><td><b>$squad</b></td></tr>\n"
           . "   <tr><td>Driver:</td><td><b>" . ($be_driver ? "TRUE" : "FALSE") . "</b></td></tr>\n"
           . "   <tr><td>AIC:</td><td><b>" . ($be_aic ? "TRUE" : "FALSE") . "</b></td></tr>\n"
           . "   <tr><td>ALS:</td><td><b>" . ($be_als ? "TRUE" : "FALSE") . "</b></td></tr>\n"
           . "   <tr><td>Be cross-agency submission:</td><td><b>" . ($be_cross_agency_submission ? "TRUE" : "FALSE") . "</b></td></tr>\n"
           . "</table>\n"
           . "<br>\n";
        ?>
        <form method="POST" action="<? echo $mode; ?>form-submit-avails-3.phtml">
          <?
          echo "<input type=hidden name=first_name value=\"$first_name\">\n"
             . "<input type=hidden name=last_name value=\"$last_name\">\n"
             . "<input type=hidden name=email_addr value=\"$email_addr\">\n"
             . "<input type=hidden name=applicable_month_num value=$applicable_month_num>\n"
             . "<input type=hidden name=coord_agency value=$coord_agency>\n"
             . "<input type=hidden name=odnmid value=\"$odnmid\">\n"
             . "<input type=hidden name=squad value=\"$squad\">\n"
             . "<input type=hidden name=be_als value=\"$be_als\">\n"
             . "<input type=hidden name=be_driver value=\"$be_driver\">\n"
             . "<input type=hidden name=be_aic value=\"$be_aic\">\n"
             . "<input type=hidden name=be_needing_driver value=\"$be_needing_driver\">\n"
             . "<input type=hidden name=be_cross_agency_submission value=\"$be_cross_agency_submission\">\n";
          //
          if ($coord_agency == "EMS")
             {
             ?>
             <p>Check all that apply as of today's date:</p>
             <ul>
                <li><input type=checkbox name=be_on_team_30 value="TRUE">I am on the Squad Truck Team.</li>
                <li><input type=checkbox name=be_on_team_5 value="TRUE">I am a Volunteer Duty Field Supervisor.</li>
                <li><input type=checkbox name=be_on_team_air value="TRUE">I am on the Air Ambulance Team.</li>
             </ul>
             <?
             }
          else if ($coord_agency == "SquadTruckTeam")
             {
             ?>
             <input type=hidden name=be_on_team_30 value="TRUE">
             <p>Check all that apply as of today's date:</p>
             <ul>
                <li><input type=checkbox name=be_on_team_5 value="TRUE">I am a Volunteer Duty Field Supervisor.</li>
                <li><input type=checkbox name=be_on_team_air value="TRUE">I am on the Air Ambulance Team.</li>
             </ul>
             <?
             }
          else
             {
             echo "<p>Check all that apply as of today's date:</p>\n";
             //
             ?>
             <ul>
                <li><input type=checkbox name=be_on_team_30 value="TRUE">I am on the Squad Truck Team.</li>
                <li><input type=checkbox name=be_on_team_5 value="TRUE">I am a Volunteer Duty Field Supervisor.</li>
             </ul>
             <?
             }
          WriteCalendarSubform
             (
             $applicable_month_num,
             "Check all shifts for which you are available for at least one type of duty.&nbsp; You will have an opportunity on the next page to specify particular hours and to make other special requests:",
             $mode
             );
          ?>
          <p align="left">How many <b>EXTRA</b> shifts are you willing to be scheduled for?&nbsp; <input type="text" name=num_extras size="2" value="0"></p>
          <p><input type="submit" value="Continue"><input type=reset></p>
        </form>
        <?
        }
        else
           {
           //
           // Fill the page out with a warning and instructions.
           //
           ?>
           <h2><i>Error!</i></h2>
           <b>
           <blockquote>
              <p>You did not supply one or more of the required parameters.&nbsp; You must supply values for these fields:</p>
              <ul>
                 <li><p>First name</p>
                 <li><p>Last name</p>
                 <li><p>Email address</p>
                 <li><p>Applicable month</p>
                 <li><p>Recieving agency</p>
                 <li><p>Home squad</p>
                 <li><p>ALS</p>
                 <li><p>Driver</p>
                 <li><p>AIC</p>
                 <li><p>Need driver</p>
              </ul>
              <p>Please press your browser's [<--&nbsp;BACK] button to correct the problems.</p>
           </blockquote>            
           </b>
           <?
           echo "<p>If you have feedback about the technical aspects of this process, please contact the <a href=mailto:" . RoleEmailAddress($db_link,"") . ">OSCAR System Administrator</a>.</p>";
           }
        }
        else
           {
            ?>
            <h2><i>Sorry...</i></h2>
            <b>
            <blockquote>
               <? echo "<p>OSCAR's database has gone offline.&nbsp; Please retry the submission process later.</p>"; ?>
            </blockquote>            
            </b>
            <?
           }
        ?>
        <p><small><small><em><pre>$Id$</pre></em></small></small></td>
    </tr>
  </table>
</body>

</html>

