<?php
//
// $Id$
//
error_reporting(E_ALL);
//
$foundation_dir = '../foundation';
require_once("$foundation_dir/f_runmode.phtml");
$mode = RunMode($PHP_SELF);
//
require_once("f_oscarhomepageurl.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("$foundation_dir/f_bodyopen.phtml");
require_once("$foundation_dir/f_connectselectdb.phtml");
require_once("f_roleemailaddress.phtml");
//
// Accept user-supplied parameters and copy them into local variables.
//
import_request_variables('PG','_');
$email_addr = $_email_addr;
$applicable_month_num = $_applicable_month_num;
$coord_agency = $_coord_agency;
//
?>
<html>

<head>
<title>OSCAR - Surrogate Submissions Form (Part 2)</title>
</head>

<?php BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
         <table><tr><td>
            <h6 align="center">
               KVEO-IT-PROJECT<br>
               <a href="<? echo OscarHomePageUrl(); ?>">OSCAR SYSTEM</a><br>
               <a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></h6>
            <h1 align="center">Surrogate Submissions Form (Part 2)</h1>
            <h2 align="center">for scheduling officers and their designees</h2>
         </td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>
            <?php PutLibPhotoRandomPlaced("sasquatch",1); ?>
         </td></tr></table>
         <hr>
         <?php
         if (ConnectSelectDb("localhost","kalipso",Password(),"oscar") != "TRUE")
            {
            ?>
            <h2><i>Sorry...</i></h2>
            <b>
            <blockquote>
               <?php echo "<p>OSCAR's database has gone offline.&nbsp; Please retry the submission process later.</p>"; ?>
            </blockquote>            
            </b>
            <?php
            }
         else
            {
            //
            // Validate parameters.
            //
            if (($email_addr == "") or ($applicable_month_num == "") or ($coord_agency == ""))
               {
               //
               // Fill the page out with a warning and instructions.
               //
               ?>
               <h2><i>Error!</i></h2>
               <b>
               <blockquote>
                  <p>You did not supply one or more of the required parameters.&nbsp; You must supply values for these
                     fields:</p>
                  <ul>
                     <li><p>Email address</p>
                     <li><p>Applicable month</p>
                     <li><p>Recieving agency</p>
                  </ul>
                  <p>Please press your browser's [<--&nbsp;BACK] button to correct the problems.</p>
               </blockquote>            
               </b>
               <?php
               echo "<p>If you have feedback about the technical aspects of this process, please contact the "
                  . "<a href=mailto:" . RoleEmailAddress("") . ">OSCAR System Administrator</a>.</p>";
               }
            else
               {
               //
               // Show what was collected in Part 1.
               //
               echo "<br>\n"
                  . "<table>\n"
                  . "   <tr><td>Surrogate submitter email address:</td><td><b>$email_addr</b></td></tr>\n"
                  . "   <tr><td>Applicable month:</td><td><b>"
                  . date("F",mktime(12,0,0,$applicable_month_num,1))
                  . "</b></td></tr>\n"
                  . "   <tr><td>Coordinating agency:&nbsp;&nbsp;</td><td><b>$coord_agency</b></td></tr>\n"
                  . "</table>\n"
                  . "<br>\n";
               ?>
               <p><i>For the values you supplied in Part 1, the following additional information is required.&nbsp;
                  Complete the form below and press the "Submit" button to finish the process.</i></p>
               <form>
                  <small>
                     <ul>
                        <li>Any row without a last name, first name, and at least one shift will not be processed.
                        <li>You'll have a chance to make more submissions after you press Submit.
                     </ul>
                  </small>
                  <p><input type="submit" value="Submit"><input type="reset" value="Reset"></p>
               </form>
               <?php
               }
            }
            ?>
         <hr>
         <small><small><em><pre>$Id$</pre></em></small></small>
      </td>
   </tr>
</table>
</body>

</html>

