<?
//
// $Id$
//
require_once("f_oscarhomepageurl.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("f_bodyopen.phtml");
require_once("f_password.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_sendapprovalnotice.phtml");
require_once("f_oscarmailheaders.phtml");
//
$first_name = trim($first_name);
$last_name = trim($last_name);
//
$html = "<html>\n";
$html .= "<head><title>Retraction Request</title></head>\n";
$html .= "<body bgcolor=#FFFFFF>\n";
$html .= "<table align=center width=80%><tr><td>\n";
$html .= "<H6 ALIGN=CENTER>KVEO-IT-PROJECT<br><a href=" . OscarHomePageUrl() . ">OSCAR</a><br><a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></H6>\n";
$html .= "<H1 ALIGN=CENTER>Retraction Request</H1>\n";
$html .= "<hr>\n";
//
echo $html;
//
// Validate parameters.
//
if
   (
      ($first_name != "")
   and
      ($last_name != "")
   and
      ($applicable_month_num != "")
   )
// then
   {
   //
   // All required values are present.
   //
   PutLibPhotoRandomPlaced("sasquatch",1,"right");
   //
   // Connect to the database.
   //
   mysql_connect(localhost,kalipso,Password());
   mysql_select_db(oscar);
   //
   // Generate the challenge message.
   //
   //             0        1         2         3         4         5         6         7
   //             123456789012345678901234567890123456789012345678901234567890123456789012
   $challenge = "";
   $challenge .= "The OSCAR system has received your request to retract your availability\n"
              .  "sheet submission.  This is the challenge message.\n\n"
              .  "
   //
   // Generate the record detail to include in the challenge message.  This is so the requestor will know exactly what they're
   // about to retract.
   //
   $result = mysql_query
      (
      "select * from avail_sheet"
      .  " where last_name = \"" . addslashes(addslashes($last_name)) . "\""
      .  "    and first_name = \"" . addslashes(addslashes($first_name)) . "\""
      .  "    and month = '$month'"
      )
      or die("The query failed with error:  " . mysql_error());
   $num_rows = mysql_num_rows($result);
   $challenge .= "Found $num_rows ";
   if ($num_rows == 1)
      {
      $challenge .= "record.";
      }
   else
      {
      $challenge .= "records.";
      }
   echo "\n";
   if ($num_rows)
      {
      $record_index = 0;
      while ($row = mysql_fetch_array($result))
         {
         $record_index++;
         extract($row);
         $challenge .= sShowAvailSheetRecDetail
            (
            $timestamp,
            $first_name,
            $last_name,
            $email_addr,
            $squad,
            $month,
            $be_on_team_5,
            $be_on_team_30,
            $num_extras,
            $d1,$d2,$d3,$d4,$d5,$d6,$d7,$d8,$d9,$d10,$d11,$d12,$d13,$d14,$d15,$d16,$d17,$d18,$d19,$d20,$d21,$d22,$d23,$d24,$d25,$d26,$d27,$d28,$d29,$d30,$d31,
            $n1,$n2,$n3,$n4,$n5,$n6,$n7,$n8,$n9,$n10,$n11,$n12,$n13,$n14,$n15,$n16,$n17,$n18,$n19,$n20,$n21,$n22,$n23,$n24,$n25,$n26,$n27,$n28,$n29,$n30,$n31,
            $note,
            $expiration,
            1
            );
         if ($record_index < $num_rows)
            {
            $challenge .= "\n   ---\n";
            }
         }
      }
   }
else
   {
   //
   // Fill the page out with a warning and instructions.
   //
   ?>
   <h2><i>Error!</i></h2>
   <b>
   <blockquote>
      <p>You did not supply one or more of the required parameters.&nbsp; You must supply values for these fields:</p>
      <ul>
         <li><p>First name</p>
         <li><p>Last name</p>
         <li><p>Applicable month</p>
      </ul>
      <p>Please press your browser's [<-- BACK] button to correct the problems.</p>
   </blockquote>            
   </b>
   <?
   echo "<p>If you have feedback about the technical aspects of this process, please contact the <a href=mailto:" . RoleEmailAddress("") . ">OSCAR System Administrator</a>.</p>";
   }
   ?>
<br clear=both>
<hr>
<p><small><small><em><pre>$Id$</pre></em></small></small>
</td>
</tr>
</table>
</body>
</html>






//
// Retrieve timestamp of latest avail_sheet record.  Later, we'll use it to see if database conditions have changed
// significantly since a report with these parameters was last run.  If we determine that a user has asked this routine to
// generate a report that's already been generated, we'll avoid regeneration and just retrieve what's in the cache.
//
$result = mysql_query("select max(timestamp) as timestamp_of_latest_submission from avail_sheet")
   or die("The attempt to select the latest timestamp from the avail_sheet table failed with this error:  " . mysql_error());
$row = mysql_fetch_object($result);
//
// The condition descriptor summarizes the conditions under which the report was requested.  We use the MD5 digest of the
// condition descriptor as the key for the report in the report cache.
//
$condition_descriptor = "timestamp_of_latest_submission=" . $row->timestamp_of_latest_submission . "\n";
//
//
$presentation_clause = "order by be_on_team_5 desc, be_on_team_30 desc, squad";
//
// The request form, under certain conditions, sends a value of 13 for applicable_month_num.  Cast it into the range 1..12.
//
$applicable_month_num = date("n",mktime(12,0,0,$applicable_month_num,1));
$applicable_month_time = mktime(12,0,0,$applicable_month_num,1);
$days_in_applicable_month = date("t",$applicable_month_time);
//
$condition_descriptor .= "month_num=$applicable_month_num\n";
//
$month_word = strtoupper(date("F",mktime(12,0,0,$applicable_month_num,1)));
$month_abbrev = substr($month_word,0,3);
$where_clause = "month='$month_abbrev' ";
//
if ($report_type == "FULL")
   {
   //
   // Determine if the requestor is an OSCAR system authority (ie, privileged to see special request notes & warnings).
   //
   if ($be_authority =
         ($email_addr == RoleEmailAddress("schedule-coordinator"))
      or
         ($email_addr == RoleEmailAddress("escalation-level-1-authority"))
      )
   //then
      {
      $condition_descriptor .= "authority=TRUE\n";
      }
   else
      {
      $condition_descriptor .= "authority=FALSE\n";
      }
   //
   // Full report
   //
   // Maybe the required report has already been run under these same conditions, and cached in the database.  If so, just
   // retrieve it.
   //
   $condition_descriptor .= "type=FULL\n";
   $result = mysql_query("select md5(\"$condition_descriptor\") as digest")
      or die("The digest calculation failed with this error:  " . mysql_error());
   $row = mysql_fetch_object($result);
   $digest = $row->digest;
   $result = mysql_query("select report from report_cache where digest = '$digest'")
      or die("The cache check failed with error:  " . mysql_error());
   if (mysql_num_rows($result))
      {
      $row = mysql_fetch_object($result);
      $report = $row->report;
      }
   else
      {
      //
      // The required report has never been run before under these conditions.  Generate it from scratch and cache it.
      // This is also a good time to purge the database of expired records, as from-scratch requests for full reports don't
      // happen excessively but do happen regularly.
      //
      mysql_query("delete from avail_sheet where expiration < CURRENT_DATE");
      mysql_query("delete from report_cache where expiration < CURRENT_DATE");
      //
      $base_sql_statement = "select distinct last_name, first_name, squad, be_on_team_30, be_on_team_5, (note != \"\") as be_a_note from avail_sheet ";
      $report .= "<pre>\n";
      $report .= "Full availability report for $month_word <a href=gen-date.phtml>generated " . date("l Y-M-d H:i:s T") . "</a>\n\n";
      $report .= "   +-------------------------------------+\n";
      $report .= "   | Legend:                             |\n";
      $report .= "   |    -5-30- Rxx Lastname, Firstname * |\n";
      $report .= "   |     ^  ^   ^                      ^ |\n";
      $report .= "   |     |  |   |                      | |\n";
      $report .= "   |     |  |   +- Home rescue squad   | |\n";
      $report .= "   |     |  |      (ERS for VBFD)      | |\n";
      $report .= "   |     |  |                          | |\n";
      $report .= "   |     |  +- Squad truck team member | |\n";
      $report .= "   |     |                             | |\n";
      $report .= "   |     +- EMS-5 team member          | |\n";
      $report .= "   |                                   | |\n";
      $report .= "   |              See special request -+ |\n"; 
      $report .= "   |              in Note section        |\n";
      $report .= "   +-------------------------------------+\n\n\n";
      $report .= "+------+\n";
      $report .= "| Days |\n";
      $report .= "+------+\n\n";
      for ($day_index = 1; $day_index <= $days_in_applicable_month; $day_index++)
         {
         $day_description = date("jS \d\a\y (l):",mktime(9,0,0,$applicable_month_num,$day_index));
            $where_clause_2 = "and d$day_index='AVAILABLE' ";
         $sql_statement = stripslashes($base_sql_statement . "where " . $where_clause . $where_clause_2 . $presentation_clause);
         $result = mysql_query($sql_statement) or die("Query failed with error:  " . mysql_error());
         if ($num_rows = mysql_num_rows($result))
            {
            $report .= $day_description . "\n";
            while ($row = mysql_fetch_array($result))
               {
               extract($row);
               $report .= "   -";
               if ($be_on_team_5) $report .= "5"; else $report .= "-";
               $report .= "-";
               if ($be_on_team_30) $report .= "30"; else $report .= "--";
               $report .= "- ";
               if ($squad != "ERS") $squad = sprintf("R%02s",$squad);
               $report .= sprintf("%3s ",$squad);
               $last_name = stripslashes($last_name);
               $first_name = stripslashes($first_name);
               $report .= "<a href=detail.phtml?a="
                  .  base64_encode($last_name)
                  .  "&b="
                  .  base64_encode($first_name)
                  .  "&c="
                  .  base64_encode($month_abbrev)
                  .  "&d="
                  .  base64_encode($be_authority)
                  .  ">$last_name, $first_name</a>";
               if ($be_a_note) $report .= " *";
               $report .= "\n";
               $last_name = $first_name = $squad = $be_on_team_30 = $be_on_team_5 = $be_a_note = "";
               }
            }
         else
            {
            $report .= $day_description . " None\n";
            }
         $report .= "\n";
         }
      $report .= "\n";
      $report .= "+--------+\n";
      $report .= "| Nights |\n";
      $report .= "+--------+\n\n";
      for ($night_index = 1; $night_index <= $days_in_applicable_month; $night_index++)
         {
         $night_description = date("jS \\n\i\g\h\\t (l):",mktime(21,0,0,$applicable_month_num,$night_index));
         $where_clause_2 = "and n$night_index='AVAILABLE' ";
         $sql_statement = stripslashes($base_sql_statement . "where " . $where_clause . $where_clause_2 . $presentation_clause);
         $result = mysql_query($sql_statement) or die("Query failed with error:  " . mysql_error());
         if ($num_rows = mysql_num_rows($result))
            {
            $report .= $night_description . "\n";
            while ($row = mysql_fetch_array($result))
               {
               extract($row);
               $report .= "   -";
               if ($be_on_team_5) $report .= "5"; else $report .= "-";
               $report .= "-";
               if ($be_on_team_30) $report .= "30"; else $report .= "--";
               $report .= "- ";
               if ($squad != "ERS") $squad = sprintf("R%02s",$squad);
               $report .= sprintf("%3s ",$squad);
               $last_name = stripslashes($last_name);
               $first_name = stripslashes($first_name);
               $report .= "<a href=detail.phtml?a="
                  .  base64_encode($last_name)
                  .  "&b="
                  .  base64_encode($first_name)
                  .  "&c="
                  .  base64_encode($month_abbrev)
                  .  "&d="
                  .  base64_encode($be_authority)
                  .  ">$last_name, $first_name</a>";
               if ($be_a_note) $report .= "*";
               $report .= "\n";
               $last_name = $first_name = $squad = $be_on_team_30 = $be_on_team_5 = $be_a_note = "";
               }
            }
         else
            {
            $report .= $night_description . " None\n";
            }
         $report .= "\n";
         }
      $report .= "</pre>\n";
      if ($be_authority)
         {
         //
         // Generate notes and warnings.
         //
         $report .= "<h3><u>Notes and Warnings</u></h3>\n";
         mysql_query
            (
            "create temporary table note_and_submission_count"
            .  " select last_name"
            .  "    , first_name"
            .  "    , squad"
            .  "    , be_on_team_30"
            .  "    , be_on_team_5"
            .  "    , note"
            .  "    , count(*) as num_submissions"
            .  " from avail_sheet"
            .  " where month=\"" . substr($month_word,0,3) . "\""
            .  " group by last_name"
            .  "    , first_name"
            )
            or die("Create...select note_and_submission_count failed with error:  " . mysql_error());
         //
         // The above statement copies some records that have no note and only one submission, so a clean up is required...
         //
         mysql_query
            (
            "delete from note_and_submission_count"
            .  " where note = \"\""
            .  "    and num_submissions = 1"
            )
            or die("Delete from note_and_submission_count failed with error:  " . mysql_error());
         //
         $result = mysql_query("select * from note_and_submission_count order by last_name, first_name")
            or die("Select from note_and_submission_count failed with error:  " . mysql_error());
         if ($num_rows = mysql_num_rows($result))
            {
            while ($row = mysql_fetch_array($result))
               {
               extract($row);
               $last_name = stripslashes($last_name);
               $first_name = stripslashes($first_name);
               $report .= "<a href=detail.phtml?a="
                  .  base64_encode($last_name)
                  .  "&b="
                  .  base64_encode($first_name)
                  .  "&c="
                  .  base64_encode($month_abbrev)
                  .  "&d="
                  .  base64_encode($be_authority)
                  .  ">$last_name, $first_name</a>&nbsp; [-";
               if ($be_on_team_5) $report .= "5"; else $report .= "-";
               $report .= "-";
               if ($be_on_team_30) $report .= "30"; else $report .= "--";
               $report .= "- ";
               if ($squad != "ERS") $squad = sprintf("R%02s",$squad);
               $report .= "$squad]\n";
               $report .= "<blockquote>\n";
               if ($num_submissions > 1)
                  {
                  $report .= "   <p><b>*** WARNING: SUBMISSION COUNT = $num_submissions, VERIFICATION RECOMMENDED ***</b></p>\n";
                  }
               $report .= "   <p><i>" . stripslashes($note) . "</i></p>\n";
               $report .= "</blockquote>\n<br>\n";
               $last_name = $first_name = $squad = $be_on_team_30 = $be_on_team_5 = $note = $num_submissions = "";
               }
            }
         else
            {
            $report .= "None\n";
            }
         //
         mysql_query("drop table note_and_submission_count")
            or die("Drop of note_and_submission_count failed with error:  " . mysql_error());
         }
      //
      $report .= "<pre>--- END ---</pre><br>\n";
      $report .= "<small><i><pre>\$Id$</pre></i></small>\n";
      $report .= "</td></tr></table>\n";
      $report .= "</body>\n";
      $report .= "</html>\n";
      //
      // Calculate the expiration date for this report.  For the mktime() function, the 0th day of the month+1 resolves
      // to the last day of month.
      //
      $expiration_date = date("Y-m-d",mktime(0,0,0,($applicable_month_num + 1),0));
      //
      // Store the report in the cache.
      //
      $report = addslashes($report);
      $result = mysql_query("insert into report_cache set digest='$digest'"
         . ", report='$report'"
         . ", expiration='$expiration_date'")
         or die("Report insertion failed with this error:  " . mysql_error());
      }
   }
else
   {
   //
   // Filtered report
   //
   //
   // Convert sequence of day/night scalars into 1-based arrays for easier looping later.
   //
   $d = array(1 => $d1,$d2,$d3,$d4,$d5,$d6,$d7,$d8,$d9,$d10,$d11,$d12,$d13,$d14,$d15,$d16,$d17,$d18,$d19,$d20,$d21,$d22,$d23,$d24,$d25,$d26,$d27,$d28,$d29,$d30,$d31);
   $n = array(1 => $n1,$n2,$n3,$n4,$n5,$n6,$n7,$n8,$n9,$n10,$n11,$n12,$n13,$n14,$n15,$n16,$n17,$n18,$n19,$n20,$n21,$n22,$n23,$n24,$n25,$n26,$n27,$n28,$n29,$n30,$n31);
   //
   // Maybe the required report has already been run under these same conditions, and cached in the database.  If so, just
   // retrieve it.
   //
   $condition_descriptor .= "type=FILTERED\n";
   $condition_descriptor .= "team_filter=$team_filter\n";
   $condition_descriptor .= "days=";
   for ($i=1; $i<=$days_in_applicable_month; $i++)
      {
      if ($d[$i])
         {
         $condition_descriptor .= "1";
         $expiration_day = $i;
         }
      else
         {
         $condition_descriptor .= "0";
         }
      }
   $condition_descriptor .= "\n";
   $condition_descriptor .= "nights=";
   for ($i=1; $i<=$days_in_applicable_month; $i++)
      {
      if ($n[$i])
         {
         $condition_descriptor .= "1";
         if ($i > $expiration_day) $expiration_day = $i;
         }
      else
         {
         $condition_descriptor .= "0";
         }
      }
   $condition_descriptor .= "\n";
   $result = mysql_query("select md5(\"$condition_descriptor\") as digest")
      or die("The digest calculation failed with this error:  " . mysql_error());
   $row = mysql_fetch_object($result);
   $digest = $row->digest;
   $result = mysql_query("select report from report_cache where digest = '$digest'")
      or die("The cache check failed with error:  " . mysql_error());
   if (mysql_num_rows($result))
      {
      $row = mysql_fetch_object($result);
      $report = $row->report;
      }
   else
      {
      $base_sql_statement = "select distinct last_name, first_name, squad, be_on_team_30, be_on_team_5 from avail_sheet ";
      switch ($team_filter)
         {
         case "team_5_only":
            $where_clause .= "and be_on_team_5 = 'TRUE' ";
            $info_message = "As requested, this report ONLY includes EMS-5 team members.";
            break;
         case "team_30_only":
            $where_clause .= "and be_on_team_30 = 'TRUE' ";
            $info_message = "As requested, this report ONLY includes SQUAD TRUCK team members.";
            break;
         }
      //
      $report .= "<pre>\n";
      $report .= "Filtered availability report for $month_word <a href=gen-date.phtml>generated " . date("l Y-M-d H:i:s T") . "</a>\n\n";
      $report .= "   +-----------------------------------+\n";
      $report .= "   | Legend:                           |\n";
      $report .= "   |    -5-30- Rxx Lastname, Firstname |\n";
      $report .= "   |     ^  ^   ^                      |\n";
      $report .= "   |     |  |   |                      |\n";
      $report .= "   |     |  |   +- Home rescue squad   |\n";
      $report .= "   |     |  |      (ERS for VBFD)      |\n";
      $report .= "   |     |  |                          |\n";
      $report .= "   |     |  +- Squad truck team member |\n";
      $report .= "   |     |                             |\n";
      $report .= "   |     +- EMS-5 team member          |\n";
      $report .= "   +-----------------------------------+\n\n\n";
      if ($info_message) $report .= "$info_message\n\n";
      for ($day_index = 1; $day_index <= $days_in_applicable_month; $day_index++)
         {
         if ($d[$day_index])
            {
            $day_description = date("jS \d\a\y (l):",mktime(9,0,0,$applicable_month_num,$day_index));
            $where_clause_2 = "and d$day_index='AVAILABLE' ";
            $sql_statement = stripslashes($base_sql_statement . "where " . $where_clause . $where_clause_2 . $presentation_clause);
            $result = mysql_query($sql_statement) or die("Query failed with error:  " . mysql_error());
            if ($num_rows = mysql_num_rows($result))
               {
               $report .= $day_description . "\n";
               while ($row = mysql_fetch_array($result))
                  {
                  extract($row);
                  $report .= "   -";
                  if ($be_on_team_5) $report .= "5"; else $report .= "-";
                  $report .= "-";
                  if ($be_on_team_30) $report .= "30"; else $report .= "--";
                  $report .= "- ";
                  if ($squad != "ERS") $squad = sprintf("R%02s",$squad);
                  $report .= sprintf("%3s ",$squad);
                  $last_name = stripslashes($last_name);
                  $first_name = stripslashes($first_name);
                  $report .= "<a href=detail.phtml?a="
                     .  base64_encode($last_name)
                     .  "&b="
                     .  base64_encode($first_name)
                     .  "&c="
                     .  base64_encode($month_abbrev)
                     .  ">$last_name, $first_name</a>"
                     .  "\n";
                  $last_name = $first_name = $squad = $be_on_team_30 = $be_on_team_5 = "";
                  }
               }
            else
               {
               $report .= $day_description . " None\n";
               }
            $report .= "\n";
            }
         }
      for ($night_index = 1; $night_index <= $days_in_applicable_month; $night_index++)
         {
         if ($n[$night_index])
            {
            $night_description = date("jS \\n\i\g\h\\t (l):",mktime(9,0,0,$applicable_month_num,$night_index));
            $where_clause_2 = "and n$night_index='AVAILABLE' ";
            $sql_statement = stripslashes($base_sql_statement . "where " . $where_clause . $where_clause_2 . $presentation_clause);
            $result = mysql_query($sql_statement) or die("Query failed with error:  " . mysql_error());
            if ($num_rows = mysql_num_rows($result))
               {
               $report .= $night_description . "\n";
               while ($row = mysql_fetch_array($result))
                  {
                  extract($row);
                  $report .= "   -";
                  if ($be_on_team_5) $report .= "5"; else $report .= "-";
                  $report .= "-";
                  if ($be_on_team_30) $report .= "30"; else $report .= "--";
                  $report .= "- ";
                  if ($squad != "ERS") $squad = sprintf("R%02s",$squad);
                  $report .= sprintf("%3s ",$squad);
                  $last_name = stripslashes($last_name);
                  $first_name = stripslashes($first_name);
                  $report .= "<a href=detail.phtml?a="
                     .  base64_encode($last_name)
                     .  "&b="
                     .  base64_encode($first_name)
                     .  "&c="
                     .  base64_encode($month_abbrev)
                     .  ">$last_name, $first_name</a>"
                     .  "\n";
                  $last_name = $first_name = $squad = $be_on_team_30 = $be_on_team_5 = "";
                  }
               }
            else
               {
               $report .= $night_description . " None\n";
               }
            $report .= "\n";
            }
         }
      $report .= "</pre>\n";
      $report .= "<pre>--- END ---</pre><br>\n";
      $report .= "<small><i><pre>\$Id$</pre></i></small>\n";
      $report .= "</td></tr></table>\n";
      $report .= "</body>\n";
      $report .= "</html>\n";
      //
      // Calculate the expiration date for this report.  For the mktime() function, the 0th day of the month+1 resolves
      // to the last day of month.
      //
      $expiration_date = date("Y-m-d",mktime(0,0,0,$applicable_month_num,$expiration_day));
      //
      // Store the report in the cache.
      //
      $report = addslashes($report);
      $result = mysql_query("insert into report_cache set digest='$digest', report='$report', expiration='$expiration_date'")
         or die("Report insertion failed with this error:  " . mysql_error());
      }
   }
//
// Create the notice.
//
$result = mysql_query("select 1 from trusted_user where email_address='$email_addr'")
   or die("Trust check failed with error:  " . mysql_error());
if (mysql_num_rows($result) or ($email_addr == RoleEmailAddress("schedule-coordinator")))
   {
   //
   // Then send an approval notice to the requestor directly.
   //
   $result = SendApprovalNotice($email_addr,$digest);
   }
else
   {
   //
   // Someone else requested the report.  Notify the schedule coordinator.
   //
   $screen_notice_recipient = RoleEmailAddress("schedule-coordinator");
   $screen_notice_subject = "-> OSCAR request ->";
   //
   // Give the schedule coordinator a chance to approve (weakly or strongly) or disapprove of the request.
   //
   //          0        1         2         3         4         5         6         7
   //          123456789012345678901234567890123456789012345678901234567890123456789012
   $screen_notice =  "The OSCAR system has received a request for an Availability Report from\n";
   $screen_notice .= "a user who identified him or herself as:\n\n";
   $screen_notice .= "   Name:           $name\n";
   $screen_notice .= "   Email address:  $email_addr\n\n";
   $screen_notice .= "Please take one of the following actions:\n\n\n";
   $screen_notice .= "1. To MARK THIS USER AS TRUSTED (ie, approve this\n";
   $screen_notice .= "   and subsequent OSCAR requests from this user),\n";
   $screen_notice .= "   click here:\n";
   $screen_notice .= OscarRootUrl() . "/approve-and-trust.phtml?digest=$digest&email_addr=$email_addr\n\n\n";
   $screen_notice .= "2. To approve JUST THIS ONE request without\n";
   $screen_notice .= "   marking the user as trusted, click here:\n";
   $screen_notice .= OscarRootUrl() . "/approve.phtml?digest=$digest&email_addr=$email_addr\n\n\n";
   $screen_notice .= "3. To DISAPPROVE the request, DO NOTHING.\n\n\n";
   $screen_notice .= "The report is available for review at:\n";
   $screen_notice .= OscarRootUrl() . "/get-report.phtml?digest=$digest\n\n\n";
   //
   // Add sig lines.
   //
   $screen_notice .= "-- OSCAR\n";
   $screen_notice .= "-- Home page: " . OscarHomePageUrl() . "\n";
   $screen_notice .= "-- Sysadmin: " . RoleEmailAddress("") . "\n";
   //
   // Then send a claim ticket to the requestor directly.
   //
   $claim_ticket_recipient = $email_addr;
   $claim_ticket_subject = "OSCAR claim ticket";
   //
   //                0        1         2         3         4         5         6         7
   //                123456789012345678901234567890123456789012345678901234567890123456789012
   $claim_ticket =  "Your request for an OSCAR Availability Report has been submitted to the\n";
   $claim_ticket .= "VBDEMS Central Schedule Coordinator for screening.  Check your email\n";
   $claim_ticket .= "periodically for approval.\n\n";
   $claim_ticket .= "Save this message.  It's the CLAIM TICKET for your report.\n\n";
   $claim_ticket .= "If excessive time goes by and you wish to escalate your request to a\n";
   $claim_ticket .= "higher authority, you can do so by clicking the link near the bottom of\n";
   $claim_ticket .= "this message.\n\n";
   $claim_ticket .= "   WARNING\n";
   $claim_ticket .= "   -------\n";
   $claim_ticket .= "   Do not escalate your request without due cause.  To do so is to\n";
   $claim_ticket .= "   'jump the chain of command', which is poor discipline and may be\n";
   $claim_ticket .= "   punishable.  The option to escalate is provided for cases where the\n";
   $claim_ticket .= "   primary schedule coordinator is unable to respond in a timely manner.\n";
   $claim_ticket .= "   Generally, it is better to wait for the regular approval notice.\n\n";
   $claim_ticket .= "The next authority in the chain is:\n\n";
   $claim_ticket .= "   " . RoleEmailAddress("escalation-level-1-recipient") . "\n\n";
   $claim_ticket .= "To escalate your request to the above\n";
   $claim_ticket .= "authority, click here:\n\n";
   $claim_ticket .= OscarRootUrl() . "/escalate.phtml?level=1&digest=$digest&name=" . urlencode($name) . "&email_addr=$email_addr\n\n";
   //
   // Add sig lines.
   //
   $claim_ticket .= "-- OSCAR\n";
   $claim_ticket .= "-- Home page: " . OscarHomePageUrl() . "\n";
   $claim_ticket .= "-- Sysadmin: " . RoleEmailAddress("") . "\n";
   //
   // Send the mail.
   //
   $result = mail($screen_notice_recipient, $screen_notice_subject, $screen_notice, OscarMailHeaders())
      and mail($claim_ticket_recipient, $claim_ticket_subject, $claim_ticket, OscarMailHeaders());
   }
if ($result)
   {
   PutLibPhotoRandomPlaced("sasquatch",1,"right");
   echo "<p>The OSCAR system has successfully generated your report.&nbsp;  Because the report contains personal information, a screening notice has been sent to the <a href=mailto:\"" . RoleEmailAddress("schedule-coordinator") . "\">VBDEMS Central Schedule Coordinator</a>.&nbsp; The coordinator will forward the report to you once screening is complete.</p>";
   echo "<p><b>Check your email periodically for the report.</b></p>";
   echo "<p>If you have feedback about the technical aspects of this process, please contact the <a href=mailto:" . RoleEmailAddress("") . ">OSCAR System Administrator</a>.</p>";
   }
else
   {
   //
   // Fill the page out with a warning and instructions.
   //
   ?>
   <h2><i>Error!</i></h2>
   <b>
   <blockquote>
      <p>The OSCAR system encountered an internal error while processing your request.  Please do the following:</p>
      <ul>
         <?
         echo "<li><p>Use another method (like email or telephone) to ask the <a href=mailto:\"" . RoleEmailAddress("schedule-coordinator") . "\">VBDEMS Central Schedule Coordinator</a> for the information you need.</p>";
         echo "<li><p>Let the <a href=mailto:" . RoleEmailAddress("") . "?subj=\"OSCAR Bug Report\">OSCAR System Administrator</a> know this error occurred.</p>";
         ?>
      </ul>
   </blockquote>            
   </b>
   <?
   }
?>
<hr>
<p><small><small><em><pre>$Id$</pre></em></small></small>
</td>
</tr>
</table>
</body>
</html>
