<?
//
// $Id$
//
require_once("f_runmode.phtml");
$mode = RunMode($PHP_SELF);
//
// Assign incoming argument to itself to avoid "uninitialized variable" error later.
//
$digest = $digest;
//
if ($mode) error_reporting(E_ALL);
//
require_once("f_password.phtml");
require_once("f_oscarhomepageurl.phtml");
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
//
// Connect to the database.
//
mysql_connect("localhost","kalipso",Password());
mysql_select_db("oscar");
//
$result = mysql_query("select report from " . $mode . "report_cache where digest = '$digest'")
   or die("The query failed with error:  " . mysql_error());
if (mysql_num_rows($result))
   {
   $row = mysql_fetch_object($result);
   echo $row->report;
   }
else
   {
   ?>
   <html>
      <head><title>OSCAR - Get Report Failure</title></head>
      <? BodyOpen(); ?>
         <table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
            <tr>
               <td>
                  <h6 align="center">
                     KVEO-IT-PROJECT<br>
                     <a href="<? echo OscarHomePageUrl(); ?>">OSCAR SYSTEM</a><br>
                     <a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></h6>
                  <H1 ALIGN="CENTER">Get Report Failure</H1>
                  <hr>
                  <h2><i>Sorry...</i></h2>
                  <blockquote>
                     <p>The OSCAR system could not locate the requested report.&nbsp; It has probably expired.</p>
                     <?
                     echo "<p>If you have feedback about the technical aspects of this process, please contact the <a href=mailto:" . RoleEmailAddress("") . ">OSCAR System Administrator</a>.</p>";
                     ?>
                  </blockquote>            
                  <br clear=both>
                  <hr>
                  <p><small><small><em><pre>$Id$</pre></em></small></small>
               </td>
            </tr>
         </table>
      </body>
   </html>
   <?
   }
?>