<?
//
// $Id$
//
error_reporting(E_ALL);
require_once("f_oscarhomepageurl.phtml");
require_once("x-f_putlibphotorandomplaced.phtml");
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
?>
<html>

<head><title>OSCAR System</title></head>

<? BodyOpen(); ?>

<div align="center">
   <center>
   <table border="0" width="80%">
      <tr>
         <td width="100%">
            <div align="left">
               <table border="0" cellspacing="0" cellpadding="0">
                  <tr>
                     <td rowspan="5"><? PutLibPhotoRandomPlaced("sasquatch",1); ?></td>
                     <td rowspan="5" width="20">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                     <td width="22">
                        <h5></h5>
                     </td>
                     <td align="center" width="25" bgcolor="#D0D0D0">
                        <h1>O</h1>
                     </td>
                     <td width="110">
                        <h2>nline</h2>
                     </td>
                     <td rowspan="5" width="20">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                     <td rowspan="5">
                        <p align="center"><small>
                        An open-source system for organizations that need to schedule autonomous people who have highly variable availabilities.</small></p>
                     </td>
                  </tr>
                  <tr>
                     <td width="22">
                        <h5></h5>
                     </td>
                     <td align="center" width="25" bgcolor="#D0D0D0">
                        <h1>S</h1>
                     </td>
                     <td width="110">
                        <h2>ubmission</h2>
                     </td>
                  </tr>
                  <tr>
                     <td width="22">
                        <h5>and&nbsp;</h5>
                     </td>
                     <td align="center" width="25" bgcolor="#D0D0D0">
                        <h1>C</h1>
                     </td>
                     <td width="110">
                        <h2>ompilation</h2>
                     </td>
                  </tr>
                  <tr>
                     <td width="22">
                        <h5>of&nbsp;</h5>
                     </td>
                     <td align="center" width="25" bgcolor="#D0D0D0">
                        <h1>A</h1>
                     </td>
                     <td width="110">
                        <h2>vailability</h2>
                     </td>
                  </tr>
                  <tr>
                     <td width="22">
                        <h5></h5>
                     </td>
                     <td align="center" width="25" bgcolor="#D0D0D0">
                        <h1>R</h1>
                     </td>
                     <td width="110">
                        <h2>ecords</h2>
                     </td>
                  </tr>
               </table>
               <hr>
               <table cellspacing=10>
                  <tr><td colspan=3><h3>Actions</h3></td></tr>
                  <tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td align=right><b><a href=als-avail-sub-form.phtml>Submit</a></b></td><td>an availability sheet.&nbsp;&nbsp;&nbsp;<small><i>(BCs, enter TDAs <a href=ers-tda-input-form.phtml>here</a>.)</i></small></td></tr>
                  <tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td align=right><b><a href=request-compiled-avails.phtml>Request</a></b></td><td>a compiled availability report.</td></tr>
                  <tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td align=right><b><a href=request-retraction.phtml>Retract</a></b></td><td>previous submissions.</td></tr>
                  <tr><td colspan=3><h3><br>Administrivia</h3></td></tr>
                  <tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td align=right><b><a href=whats-new.phtml>See</a></b></td><td>what's new.</td></tr>
                  <tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td align=right><b><a href=privacy.phtml>Read</a></b></td><td>the privacy policy.</td></tr>
                  <tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td align=right><b><font color=888888>Subscribe</font></b></td><td>your organization to this service.</td></tr>
                  <tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td align=right><b><a href=develop.phtml>Become</a></b></td><td>a <b>kveo-it-project</b> open-source developer.</td></tr>
                  <tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td align=right><b><a href=mailto:"<? echo RoleEmailAddress(""); ?>">Contact</a></b></td><td>the OSCAR System Administrator.</td></tr>
               </table>
               <hr>
               <p><small><i>Built with<a href="http://www.mysql.com"> MySQL </a>and<a href="http://www.php.net"> PHP </a>.</i></small></p>
               <p><small><small><em><pre>$Id$</pre></em></small></small>
            </div>
         </td>
      </tr>
   </table>
   </center>
</div>

</body>

</html>
