<?
//
// $Id$
//
require_once("f_oscarhomepageurl.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
?>
<html>

<head><title>OSCAR - Meaning of VORP</title></head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
           <h6 align="center">
              KVEO-IT-PROJECT - <a href="<? echo OscarHomePageUrl(); ?>">OSCAR SYSTEM</a></h6>
           <h1 align="center">What is a "VORP"?</h1>
        <hr>
        <? PutLibPhotoRandomPlaced("sasquatch",1,"right"); ?>
        <p><b>VORP</b> stands for <b>V</b>olunteer <b>O</b>perations <b>R</b>esponse <b>P</b>ersonnel.&nbsp; VORPs
        include ambulance, squad truck, EMS-6, Support 9, and Dive Team members.&nbsp; Tracking of VORPs is important
        because the numbers are strong indicators of the ability of the volunteer component of our system to
        autonomously staff front-line response units.</p>
        <hr>
        <p><small><small><em><pre>$Id$</pre></em></small></small></center></td>
    </tr>
  </table>
</body>

</html>

