<?
//
// $Id$
//
require_once("f_oscarhomepageurl.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("f_bodyopen.phtml");
require_once("f_password.phtml");
?>
<html>
<head><title>Report generation</title></head>
<? BodyOpen(); ?>
<table align=center width="80%"><tr><td>
<H6 ALIGN="CENTER">KVEO-IT-PROJECT<br><a href="<? echo OscarHomePageUrl(); ?>">OSCAR</a><br><a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></H6>
<H1 ALIGN="CENTER">Report generation</H1>
<hr>
<?
mysql_connect(localhost,kalipso,Password());
mysql_select_db(oscar);
//
$base_sql_statement = "select cad_num, last_name, first_name, squad, be_on_team_30, be_on_team_5, note from avail_sheet ";
$presentation_clause = "order by be_on_team_5 desc, be_on_team_30 desc, squad";
$where_clause = "";
$month_num = date("n");
$year_num = date("Y");
if ($relative_month == "NEXT")
   {
   if ($month_num < 12)
      {
      $month_num++;
      }
   else
      {
      $month_num = 1;
      $year_num++;
      }
   }
switch ($month_num)
   {
   case 1: $month_word = "JANUARY"; break;
   case 2: $month_word = "FEBRUARY"; break;
   case 3: $month_word = "MARCH"; break;
   case 4: $month_word = "APRIL"; break;
   case 5: $month_word = "MAY"; break;
   case 6: $month_word = "JUNE"; break;
   case 7: $month_word = "JULY"; break;
   case 8: $month_word = "AUGUST"; break;
   case 9: $month_word = "SEPTEMBER"; break;
   case 10: $month_word = "OCTOBER"; break;
   case 11: $month_word = "NOVEMBER"; break;
   case 12: $month_word = "DECEMBER"; break;
   }
if ($report_type == "FULL")
   {
   $where_clause = "month='" . strstr($month_word,0,3) ."' ";
   echo "<pre>\n";
   echo "Full availability report for $month_word generated " . date("l Y-M-d H:i:s T") . "\n\n";
   echo "   +--------------------------------------------+\n";
   echo "   | Legend:                                    |\n";
   echo "   |    -5-30- Rxx 8xxxxx Lastname, Firstname * |\n";
   echo "   |     ^  ^   ^    ^                        ^ |\n";
   echo "   |     |  |   |    |                        | |\n";
   echo "   |     |  |   |    +- Officer code          | |\n";
   echo "   |     |  |   |       (also 7xxxxx)         | |\n";
   echo "   |     |  |   |                             | |\n";
   echo "   |     |  |   +- Home rescue squad          | |\n";
   echo "   |     |  |      (ERS for VBFD)             | |\n";
   echo "   |     |  |                                 | |\n";
   echo "   |     |  +- Squad truck team member        | |\n";
   echo "   |     |                                    | |\n";
   echo "   |     +- EMS-5 team member                 | |\n";
   echo "   |                                          | |\n";
   echo "   |    See special request in Notes section -+ |\n";
   echo "   +--------------------------------------------+\n\n\n";
   for ($day_index = 1; $day_index <= 31; $day_index++)
      {
      $day_description = date("jS (l) \D\A\Y\:",mktime(9,0,0,$month_num,day_$index,$year_num));
      $where_clause_2 = "and d$day_index='AVAILABLE' ";
      $sql_statement = stripslashes($base_sql_statement . "where " . $where_clause . $where_clause_2 . $presentation_clause);
      $result = mysql_query($sql_statement) or die("Query failed with error:  " . mysql_error());
      if ($num_rows = mysql_num_rows($result))
         {
         echo $day_description . "\n";
         while ($row = mysql_fetch_array($result))
            {
            extract($row);
            echo "   -";
            if ($be_on_team_5) echo "5"; else echo "-";
            echo "-";
            if ($be_on_team_30) echo "30"; else echo "--";
            echo "- ";
            if ($squad != "ERS") $squad = sprintf("R%02s",$squad);
            printf("%3s %6s %s, %s ",$squad,$cad_num,$last_name,$first_name);
            if ($note != "") echo "*";
            echo "\n";
            $cad_num = $last_name = $first_name = $squad = $be_on_team_30 = $be_on_team_5 = $note = "";
            }
         }
      else
         {
         echo $day_description . " None\n";
         }
      echo "\n";
      }
   for ($night_index = 1; $night_index <= 31; $night_index++)
      {
      $night_description = date("jS (l) \N\I\G\H\T\:",mktime(21,0,0,$month_num,day_$index,$year_num));
      $where_clause_2 = "and n$night_index='AVAILABLE' ";
      $sql_statement = stripslashes($base_sql_statement . "where " . $where_clause . $where_clause_2 . $presentation_clause);
      $result = mysql_query($sql_statement) or die("Query failed with error:  " . mysql_error());
      if ($num_rows = mysql_num_rows($result))
         {
         echo $night_description . "\n";
         while ($row = mysql_fetch_array($result))
            {
            extract($row);
            echo "   -";
            if ($be_on_team_5) echo "5"; else echo "-";
            echo "-";
            if ($be_on_team_30) echo "30"; else echo "--";
            echo "- ";
            if ($squad != "ERS") $squad = sprintf("R%02s",$squad);
            printf("%3s %6s %s, %s ",$squad,$cad_num,$last_name,$first_name);
            if ($note != "") echo "*";
            echo "\n";
            $cad_num = $last_name = $first_name = $squad = $be_on_team_30 = $be_on_team_5 = $note = "";
            }
         }
      else
         {
         echo $night_description . " None\n";
         }
      echo "\n";
      }
   ?>
   </pre>
   <h3><u>Notes</u></h3>
   <?
   $result = mysql_query("select cad_num, last_name, first_name, squad, be_on_team_30, be_on_team_5, note from avail_sheet where month=\"$month\" and note != \"\" order by last_name, first_name") or die("Query failed with error:  " . mysql_error());
   if ($num_rows = mysql_num_rows($result))
      {
      while ($row = mysql_fetch_array($result))
         {
         extract($row);
         echo "$last_name, $first_name&nbsp; [-";
         if ($be_on_team_5) echo "5"; else echo "-";
         echo "-";
         if ($be_on_team_30) echo "30"; else echo "--";
         echo "- ";
         if ($squad != "ERS") $squad = sprintf("R%02s",$squad);
         echo "$squad $cad_num]\n";
         echo "<blockquote><i>" . stripslashes($note) . "</i></blockquote>\n<br>";
         $cad_num = $last_name = $first_name = $squad = $be_on_team_30 = $be_on_team_5 = $note = "";
         }
      }
   else
      {
      echo "None\n";
      }
   echo "<pre>END.</pre>\n\n";
   echo "<small><i><pre>\$Id$</pre></i></small>\n";
   }
else
   {
//   if ($div_spec_criteria != "")
//      {
//      $where_clause = $where_clause . "div_spec $div_spec_criteria ";
//      }
//   if ($frame_num_criteria != "")
//      {
//      if ($where_clause != "")
//         {
//         $where_clause = $where_clause . "and ";
//         }
//      $where_clause = $where_clause . "frame_num $frame_num_criteria ";
//      }
//   if ($be_avail_as_huge_criteria != "")
//      {
//      if ($where_clause != "")
//         {
//         $where_clause = $where_clause . "and ";
//         }
//      $where_clause = $where_clause . "be_avail_as_huge $be_avail_as_huge_criteria ";
//      }
//   if ($caption_criteria != "")
//      {
//      if ($where_clause != "")
//         {
//         $where_clause = $where_clause . "and ";
//         }
//      $where_clause = $where_clause . "caption $caption_criteria ";
//      }
//   if ($tech_details_criteria != "")
//      {
//      if ($where_clause != "")
//         {
//         $where_clause = $where_clause . "and ";
//         }
//      $where_clause = $where_clause . "tech_details $tech_details_criteria ";
//      }
//   if ($era_criteria != "")
//      {
//      if ($where_clause != "")
//         {
//         $where_clause = $where_clause . "and ";
//         }
//      $where_clause = $where_clause . "era $era_criteria ";
//      }
//   if ($copyright_year_criteria != "")
//      {
//      if ($where_clause != "")
//         {
//         $where_clause = $where_clause . "and ";
//         }
//      $where_clause = $where_clause . "copyright_year $copyright_year_criteria ";
//      }
//   if ($hits_criteria != "")
//      {
//      if ($where_clause != "")
//         {
//         $where_clause = $where_clause . "and ";
//         }
//      $where_clause = $where_clause . "hits $hits_criteria ";
//      }
//   if ($keywords_criteria != "")
//      {
//      if ($where_clause != "")
//         {
//         $where_clause = $where_clause . "and ";
//         }
//      $where_clause = $where_clause . "keywords $keywords_criteria ";
//      }
//   if ($placement_criteria != "")
//      {
//      if ($where_clause != "")
//         {
//         $where_clause = $where_clause . "and ";
//         }
//      $where_clause = $where_clause . "placement $placement_criteria ";
//      }
   }
//
?>
</td></tr></table>
</body>
</html>
