<?
//
// $Id$
//
$mode="";
   //
   // Set to "" for production, "x_" to debug.
   //
//
// Assign passed-in arguments to themselves to prevent 'undefined var' warnings later.
//
$a = $a;
$b = $b;
$c = $c;
//
if ($mode) error_reporting(E_ALL);
//
require_once("f_oscarhomepageurl.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("f_bodyopen.phtml");
require_once("f_password.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_sendapprovalnotice.phtml");
//
?>
<html>
<head><title>Retraction Confirmation</title></head>
<? BodyOpen(); ?>
<table align=center width=80%><tr><td>
<H6 ALIGN=CENTER>KVEO-IT-PROJECT<br><a href=<? OscarHomePageUrl() ?>>OSCAR</a><br><a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></H6>
<H1 ALIGN=CENTER>Retraction Confirmation</H1>
<hr>
<?
//
// Decode the arguments.
//
$first_name = base64_decode($a);
$last_name = base64_decode($b);
$applicable_month_abbrev = base64_decode($c);
//
// Connect to the database.
//
mysql_connect("localhost","kalipso",Password());
mysql_select_db("oscar");
//
// Delete the appropriate records from the avail_sheet table.
//
mysql_query
   (
   "update ignore " . $mode . "avail_sheet"
   .  " set d1=NULL, d2=NULL, d3=NULL, d4=NULL, d5=NULL, d6=NULL, d7=NULL, d8=NULL, d9=NULL, d10=NULL, d11=NULL, d12=NULL, d13=NULL, d14=NULL, d15=NULL, d16=NULL, d17=NULL, d18=NULL, d19=NULL, d20=NULL, d21=NULL, d22=NULL, d23=NULL, d24=NULL, d25=NULL, d26=NULL, d27=NULL, d28=NULL, d29=NULL, d30=NULL, d31=NULL"
   .  "    , n1=NULL, n2=NULL, n3=NULL, n4=NULL, n5=NULL, n6=NULL, n7=NULL, n8=NULL, n9=NULL, n10=NULL, n11=NULL, n12=NULL, n13=NULL, n14=NULL, n15=NULL, n16=NULL, n17=NULL, n18=NULL, n19=NULL, n20=NULL, n21=NULL, n22=NULL, n23=NULL, n24=NULL, n25=NULL, n26=NULL, n27=NULL, n28=NULL, n29=NULL, n30=NULL, n31=NULL"
   .  "    , num_extras=NULL"
   .  "    , note='%OSCAR: User at IP address $REMOTE_ADDR retracted all availabilities on " . date("l Y-M-d H:i:s T") . ".'"
   .  " where last_name = \"" . addslashes(addslashes($last_name)) . "\""
   .  "    and first_name = \"" . addslashes(addslashes($first_name)) . "\""
   .  "    and month = '$applicable_month_abbrev'"
   )
   or die("Update failed with error:  " . mysql_error());
$num_rows_affected = mysql_affected_rows();
//
PutLibPhotoRandomPlaced("sasquatch",1,"right");
echo "<p>The OSCAR system has retracted $num_rows_affected record";
if ($num_rows_affected != 1) echo "s";
echo " from its database.</p>\n";
if ($num_rows_affected == 0)
   {
   echo "<i>\n"
      . "A <u>zero</u> result can be caused by:\n"
      . "   <ul>\n"
      . "      <li>an attempt to retract records from months gone by;</li>\n"
      . "      <li>an OSCAR bug.</li>\n"
      . "   </ul>\n"
      . "If you suspect a bug, please report the problem to the following people:\n"
      . "   <ul>\n"
      . "      <li><a href=mailto:\"" . RoleEmailAddress("schedule-coordinator") . "\">the Schedule Coordinator</a></li>\n"
      . "      <li><a href=mailto:\"" . RoleEmailAddress("") . "\">the OSCAR System Administrator</a></li>\n"
      . "   </ul>\n"
      . "</i>\n";
   }
echo "<p><b>Don't forget to <a href="
   . OscarRootUrl()
   . "/" . $mode . "als-avail-sub-form.phtml>submit an accurate availability sheet</a> by the deadline.</b></p>\n"
   . "<p>If you have feedback about the technical aspects of this process, please contact the <a href=mailto:\""
   . RoleEmailAddress("")
   . "\">OSCAR System Administrator</a>.</p>";

?>
<hr>
<p><small><small><em><pre>$Id$</pre></em></small></small>
</td>
</tr>
</table>
</body>
</html>
