<?
//
// $Id$
//
require_once("f_oscarhomepageurl.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("f_bodyopen.phtml");
?>
<html>

<head><title>OSCAR - What's New</title></head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
           <h6 align="center">
              KVEO-IT-PROJECT - <a href="<? echo OscarHomePageUrl(); ?>">OSCAR SYSTEM</a></h6>
           <h1 align="center">What's New</h1>
        <hr>
        <? PutLibPhotoRandomPlaced("sasquatch",1,"right"); ?>
        <p><b>2001-12-31:&nbsp; </b>Added traceability to the squad participation toggle operation, and warning verbage to
           the Set Squad Participation page.</p>
        <p><b>2001-12-28:&nbsp; </b>Added capability for the Master OSCAR Authority to change squad participation statuses
           on his or her own.&nbsp; Previously, such a change could only be performed by the OSCAR System
           Administrator.</p>
        <p><b>2001-12-26:&nbsp; </b>Fixed bug 496823, which was causing day-of-week indications to be off by a day on
           January reports generated during December.</p>
        <p><b>2001-12-13:&nbsp; </b>Added a table to the <a href=stats.phtml>Detailed Statistics</a> page to show number
           of distinct users per month.</p>
        <p><b>2001-12-01:&nbsp; </b>Calendar subform generation is now modular and dynamic.&nbsp; Calendar subforms now look
           like conventional month-at-a-glance calendars.</p>
        <p><b>2001-11-21:&nbsp; </b>Revised verbage in a few sections to indicate that the first part of the retraction
           process may also be used to simply reconfirm prior submissions.</p>
        <p><b>2001-11-16:&nbsp; </b>Major enhancements to support availability coordination at both the department and 
           squad/team levels.&nbsp; Features will be activated on per-agency basis via database updates at direction of 
           EMS-2.&nbsp; Added availability summaries to the full reports that authorities get.&nbsp; Added failsafe
           submission recovery mechanism in case database becomes unavailable at any critical time after a
           submission.&nbsp; Added much more robust handling of database-down conditions.</p>
        <p><b>2001-11-13:&nbsp; </b>Revised report generator so that OSCAR authorities will be able to see the "# extras 
           will run" values at first glance in their versions of the full reports, rather than making them drill down per
           person.</p>
        <p><b>2001-11-12:&nbsp; </b>Revised report generator to report the latest submitted note (versus first or arbitrary) for 
           each person.&nbsp; Added the <a href=stats.phtml>Detailed stats</a> page.</p>
        <p><b>2001-11-08:&nbsp; </b>Revised main page to handle database-down condition gracefully.</p>
        <p><b>2001-11-05:&nbsp; </b>Improved retraction handling.</p>
        <p><b>2001-11-04:&nbsp; </b>Added the "Server status" indication on the main page.&nbsp; This feature forces a hit
           on the database, thereby assuring that both PHP and MySQL are up, and provides a keyword ("A-OK") that some
           site monitoring services will check for.&nbsp; Added clarifications for "surrogate" submitters.&nbsp; Added
           Zone Car ALS handling.</p>
        <p><b>2001-11-03:&nbsp; </b>Fixed a bug noticed during a demo that was preventing legitimate OSCAR authorities from
           gaining access to special request comments.&nbsp; Made authority and role tracking more robust.</p>
        <p><b>2001-11-01:&nbsp; </b>Fixed bug 477171, which had been causing the dates shown on the standard submission 
           confirmation page to be off (earlier) by one day than the dates the user actually submitted.&nbsp; This bug had
           been introduced when TDA handling was added.</p>
        <p><b>2001-10-31:&nbsp; </b>Went live as www.Oscarsystem.com.</p>
        <p><b>2001-10-29:&nbsp; </b>Began round-the-clock site response monitoring, with pager notification to the OSCAR
           Sysadmin.</p>
        <p><b>2001-10-27:&nbsp; </b>Added ERS TDA handling.</p>
        <p><b>2001-10-25:&nbsp; </b>Demonstrated the system to VBDEMS.</p>
        <p><b>2001-10-23:&nbsp; </b>Added the <a href=privacy.phtml>Privacy Policy</a> and <a href=develop.phtml>How to 
           contribute</a> pages.</p>
        <p><b>2001-10-21:&nbsp; </b>Achieved Initial Operating Capability (IOC).</p>
        <hr>
        <p><small><small><em><pre>$Id$</pre></em></small></small></center></td>
    </tr>
  </table>
</body>

</html>

