<?
//
// $Id$
//
require_once("f_runmode.phtml");
$mode = RunMode($PHP_SELF);
if ($mode) error_reporting(E_ALL);
//
require_once("f_oscarhomepageurl.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("f_bodyopen.phtml");
require_once("f_connectselectdb.phtml");
require_once("f_password.phtml");
require_once("f_agencyselectionlist.phtml");
?>
<html>

<head>
<title>OSCAR - Retraction Request Form</title>
</head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
        <table><tr><td>
           <h6 align="center">
              KVEO-IT-PROJECT<br>
              <a href="<? echo OscarHomePageUrl(); ?>">OSCAR SYSTEM</a><br>
              <a href=http://www.vabeachems.com>VIRGINIA BEACH DEPARTMENT OF EMS</a></h6>
           <h1 align="center">Retraction Request Form</h1>
        </td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>
           <? PutLibPhotoRandomPlaced("sasquatch",1); ?>
        </td></tr></table>
        <hr>
        <?
        if (ConnectSelectDb("localhost","kalipso",Password(),"oscar") != "TRUE")
           {
           ?>
           <h2><i>Sorry...</i></h2>
           <b>
           <blockquote>
              <? echo "<p>OSCAR's database is temporarily offline.&nbsp; Please try your retraction operation later.</p>"; ?>
           </blockquote>            
           </b>
           <?
           }
        else
        {
        ?>
        <p>This form allows you to "take back" what you already submitted to the OSCAR system.</p>
        <blockquote>
           <table align=center bgcolor=#E8E8E8>
              <tr>
                 <td align=center valign=middle>
                    <small><i>To guard against misuse, the OSCAR system authenticates each retraction request by sending a
                       "challenge message" to the email address <u>originally specified</u> on a person's availability 
                       sheet.&nbsp; The retraction only takes effect once OSCAR receives a proper response to the 
                       challenge.</i></small>
                 </td>
              </tr>
           </table>
        </blockquote>
        <p>This process allows you to retract <b>all</b> of the availability information that you've submitted for the
           specified month.&nbsp; Once you trigger the retraction process, you should <b>wait for further instructions</b>
           that will arrive with the email challenge message.</p>
        <p>In practice, the retraction process is easy, safe, and secure.  To begin the retraction process, complete the
           following form:</p>
        <br>
        <blockquote>
           <form action=<? echo $mode; ?>perform-gen-challenge.phtml method=post>
              <table>
                 <tr>
                    <td>First name:</td>
                    <td><input type=text name=first_name size=32></td>
                    <td valign=middle rowspan=2><small>(of EMS/ERS provider)</small></td>
                 </tr>
                 <tr>
                    <td>Last name:</td>
                    <td><input type=text name=last_name size=32></td>
                 </tr>
                 <tr>
                    <td>Applicable month:</td>
                    <td><select size=1 name=applicable_month_num>
                       <option value="">Select</option>
                       <?
                       $next_month_num = date("n") + 1;
                       echo "<option value=" . $next_month_num . ">" . date("F",mktime(12,0,0,$next_month_num,1)) . "</option>\n";
                       echo "<option value=" . ($next_month_num + 1) . ">" . date("F",mktime(12,0,0,($next_month_num + 1),1)) . "</option>\n";
                       ?>
                    </select></td>
                 </tr>
                 <tr>
                    <td>Retract availabilities from which agency?</td>
                    <td><? AgencySelectionList($mode); ?></td>
                 </tr>
              </table>
              <p>Please double check your entries before completing your request.&nbsp; They must match what you
                 supplied on your availability sheet (although uppercase & lowercase do not matter).</p>
              <input type=submit value="Request retraction"><input type=reset>
           </form>
        </blockquote>
        <?
        }
        ?>
        <hr>
        <p><small><small><em><pre>$Id$</pre></em></small></small>
       </td>
    </tr>
  </table>
</body>

</html>

